Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2023-07, with the labels that each got.

#1564 Update google provider -> 4.73.0
  pkg/modulewriter/tfversions.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
Labels: chore

#1576 Deprecate `DeploymentGroup.Kind`
  cmd/deploy.go
  cmd/destroy.go
  cmd/export.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/path.go
  pkg/config/path_test.go
  pkg/config/yaml_test.go
  pkg/modulewriter/modulewriter.go
  pkg/modulewriter/modulewriter_test.go
  pkg/shell/terraform.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/text_escape/.ghpc/artifacts/expanded_blueprint.yaml
Labels: chore

#1578 Use PR labels to auto-generate release notes
  .github/release.yml
  .github/workflows/pr-label-validation.yml
Labels: chore

#1605 Fix links in image building docs
  docs/image-building.md
Labels: chore

#1610 Check for container api when using GKE modules
  pkg/modulereader/resreader.go
Labels: chore

#1614 HTCondor formatting fixes
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/files/htcondor_configure.yml
  community/modules/scheduler/htcondor-access-point/main.tf
  docs/tutorials/htcondor.md
Labels: chore

#1616 Disambiguate deployment_name for Packer/Slurm test
  tools/cloud-build/daily-tests/tests/packer.yml
Labels: chore

#1618 Fix provider to 4.74.0
  community/modules/compute/gke-node-pool/README.md
  community/modules/compute/gke-node-pool/versions.tf
  pkg/modulewriter/tfversions.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
Labels: chore

#1617 Add MIG ID as output/input in HTCondor modules
  community/examples/htc-htcondor.yaml
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/outputs.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-access-point/templates/condor_config.tftpl
  community/modules/scheduler/htcondor-access-point/variables.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
Labels: key-new-features

#1608 Add G2 family support to GPU-normalizing code
  community/modules/compute/htcondor-execute-point/gpu_definition.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/gpu_definition.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/gpu_definition.tf
  modules/compute/vm-instance/variables.tf
  modules/compute/vm-instance/versions.tf
Labels: module-improvements

#1609 Deprecate var.gpu in Slurm v5 modules
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
Labels: deprecations

#1619 Run the "label" check on more PR events
  .github/workflows/pr-label-validation.yml
Labels: chore

#1606 Update DDN EXAscaler to 6.2
  community/modules/file-system/DDN-EXAScaler/README.md
  community/modules/file-system/DDN-EXAScaler/main.tf
  community/modules/file-system/DDN-EXAScaler/variables.tf
Labels: version-updates

#1624 Remove lingering usage of htcondor-configure in favor of htcondor-setup
  community/modules/scheduler/htcondor-setup/README.md
  community/modules/scripts/htcondor-install/README.md
  docs/gpu-support.md
  docs/vm-images.md
Labels: chore

#1623 Update DDN-EXAscaler module reference
  community/modules/file-system/DDN-EXAScaler/README.md
  community/modules/file-system/DDN-EXAScaler/main.tf
  community/modules/file-system/DDN-EXAScaler/variables.tf
Labels: chore

#1627 Increase default Packer VM scopes to cloud-platform
  modules/packer/custom-image/README.md
  modules/packer/custom-image/variables.pkr.hcl
  tools/validate_configs/golden_copies/expectations/igc_pkr/one/image/variables.pkr.hcl
  tools/validate_configs/golden_copies/expectations/text_escape/zero/lime/variables.pkr.hcl
Labels: module-improvements

#1626 Support N>2 groups of HTCondor execute points
  community/examples/htc-htcondor.yaml
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/htcondor-execute-point/variables.tf
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-access-point/templates/condor_config.tftpl
  community/modules/scripts/htcondor-install/files/autoscaler.py
Labels: key-new-features

#1639 Merge v1.21.0 release into develop
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-login-node/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: chore

#1625 Make the "Apply Changes" prompt clearer
  pkg/shell/common.go
Labels: improvements
