Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2023-10, with the labels that each got.

#1804 Pin htcondor pool secrets tf version
  community/modules/scheduler/htcondor-pool-secrets/README.md
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
Labels: release-chore

#1800 Attach a (free) license to every built VM image
  modules/packer/custom-image/image.pkr.hcl
  tools/validate_configs/golden_copies/expectations/igc_pkr/one/image/image.pkr.hcl
  tools/validate_configs/golden_copies/expectations/text_escape/zero/lime/image.pkr.hcl
Labels: release-chore

#1811 Added release-bugfix to labels in validation yml
  .github/workflows/pr-label-validation.yml
Labels: release-chore

#1789 Update documentation to disable gcloudignore and create PR trigger for ofe-deployment-integration test
  tools/cloud-build/daily-tests/README.md
  tools/cloud-build/provision/README.md
  tools/cloud-build/provision/list_tests.py
  tools/cloud-build/provision/pr-ofe-test.tf
Labels: release-chore

#1812 Removing automatic group write permission to mitigate regression tests
  community/modules/scripts/spack-setup/main.tf
  tools/cloud-build/daily-tests/tests/batch-mpi.yml
Labels: release-chore

#1810 HCLS Integration Test
  docs/videos/healthcare-and-life-sciences/hcls-blueprint.yaml
  tools/cloud-build/daily-tests/ansible_playbooks/base-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/rescue_ghpc_failure.yml
  tools/cloud-build/daily-tests/builds/hcls.yaml
  tools/cloud-build/daily-tests/tests/hcls.yml
Labels: release-improvements

#1816 Prevent infra from being left behind; only run when var is populated
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
Labels: release-chore

#1817 Fix: error on second run when mirror is already defined
  community/examples/hpc-slurm-gromacs.yaml
  community/examples/hpc-slurm-ramble-gromacs.yaml
  docs/tutorials/gromacs/spack-gromacs.yaml
  docs/tutorials/openfoam/spack-openfoam.yaml
  docs/tutorials/wrfv3/spack-wrfv3.yaml
  examples/serverless-batch-mpi.yaml
  tools/cloud-build/daily-tests/builds/batch-mpi.yaml
  tools/cloud-build/daily-tests/builds/spack-gromacs.yaml
Labels: release-chore

#1809 Simplified Script Warning
  modules/scripts/startup-script/files/running-script-warning.sh
  modules/scripts/startup-script/files/startup-script-stdlib-head.sh
  modules/scripts/startup-script/main.tf
  modules/scripts/startup-script/templates/startup-script-custom.tpl
Labels: release-module-improvements

#1818 Bump urllib3 from 1.26.16 to 1.26.17 in /community/front-end/ofe
  community/front-end/ofe/requirements.txt
Labels: release-chore

#1824 Move integration test region to try to improve obtainability
  tools/cloud-build/daily-tests/tests/slurm-v5-hpc-centos7.yml
Labels: release-chore

#1825 Adding deployment name to prefix to avoid collisions in multiple deployments
  tools/cloud-build/daily-tests/blueprints/lustre-vm.yaml
  tools/cloud-build/daily-tests/tests/lustre-vm.yml
Labels: release-chore

#1813 Add instance image name to VM-Instance Module
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/main.tf
  modules/compute/vm-instance/variables.tf
Labels: release-module-improvements

#1822 Update Slurm modules to 5.9.1 release from SchedMD
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
  docs/hybrid-slurm-cluster/demo-with-cloud-controller-instructions.md
  docs/hybrid-slurm-cluster/deploy-instructions.md
  docs/hybrid-slurm-cluster/on-prem-instructions.md
  docs/image-building.md
  docs/vm-images.md
  examples/README.md
  modules/README.md
  tools/cloud-build/Dockerfile
Labels: release-module-improvements

#1823 Rename tests
  tools/cloud-build/daily-tests/tests/batch-mpi.yml
  tools/cloud-build/daily-tests/tests/chrome-remote-desktop.yml
  tools/cloud-build/daily-tests/tests/cloud-batch.yml
  tools/cloud-build/daily-tests/tests/high-io-slurm-gcp-v5.yml
  tools/cloud-build/daily-tests/tests/hpc-high-io.yml
  tools/cloud-build/daily-tests/tests/hpc-slurm-chromedesktop.yml
  tools/cloud-build/daily-tests/tests/htcondor.yml
  tools/cloud-build/daily-tests/tests/lustre-slurm.yml
  tools/cloud-build/daily-tests/tests/lustre-vm.yml
  tools/cloud-build/daily-tests/tests/monitoring.yml
  tools/cloud-build/daily-tests/tests/omnia.yml
  tools/cloud-build/daily-tests/tests/packer.yml
  tools/cloud-build/daily-tests/tests/pbspro.yml
  tools/cloud-build/daily-tests/tests/qsim.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-hpc-centos7.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-startup-scripts.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-ubuntu.yml
  tools/cloud-build/daily-tests/tests/spack-gromacs.yml
Labels: release-chore

#1821 Update the install ramble deps runner based on the spack module
  community/modules/scripts/ramble-setup/main.tf
  community/modules/scripts/ramble-setup/templates/install_ramble_deps.yml.tpl
Labels: bug, release-bugfix

#1831 Fix install script in ml-slurm example
  examples/ml-slurm.yaml
Labels: release-bugfix

#1834 Include #1831 on develop branch
  examples/ml-slurm.yaml
Labels: release-chore

#1835 Upgrade golang.org/x/net to v0.17.0
  go.mod
  go.sum
Labels: release-chore

#1839 Ignore exit code when collecting partition info in Slurm integration test
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
Labels: release-chore

#1841 Add support for reading `metadata.yaml` in CFT-format, fallack to har…
  pkg/modulereader/metadata.go
  pkg/modulereader/metadata_legacy.go
  pkg/modulereader/modules/imaginarium/zebra/main.pkr.hcl
  pkg/modulereader/modules/imaginarium/zebra/variables.pkr.hcl
  pkg/modulereader/modules/test_role/test_module/metadata.yaml
  pkg/modulereader/resreader.go
  pkg/modulereader/resreader_test.go
  pkg/sourcereader/embedded.go
  pkg/validators/validators.go
Labels: release-improvements

#1845 Fix HCLS and gcs fuse installation
  community/modules/file-system/cloud-storage-bucket/scripts/install-gcs-fuse.sh
  docs/videos/healthcare-and-life-sciences/hcls-blueprint.yaml
  modules/file-system/pre-existing-network-storage/scripts/install-gcs-fuse.sh
Labels: release-bugfix

#1851 Warn user that Spack setup takes a few seconds
  community/modules/scripts/spack-setup/main.tf
Labels: release-chore

#1852 Bumping version to 1.24.0
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-login-node/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/htcondor-setup/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-version-updates

#1855 Merging v1.24.0 into develop
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-login-node/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/htcondor-setup/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#1837 Update ramble modules to have data file management
  community/modules/scripts/ramble-execute/README.md
  community/modules/scripts/ramble-execute/main.tf
  community/modules/scripts/ramble-execute/outputs.tf
  community/modules/scripts/ramble-execute/variables.tf
  community/modules/scripts/ramble-execute/versions.tf
  community/modules/scripts/ramble-setup/README.md
  community/modules/scripts/ramble-setup/main.tf
  community/modules/scripts/ramble-setup/outputs.tf
  community/modules/scripts/ramble-setup/templates/ramble_setup.yml.tftpl
  community/modules/scripts/ramble-setup/variables.tf
  community/modules/scripts/ramble-setup/versions.tf
  community/modules/scripts/spack-execute/README.md
  community/modules/scripts/spack-execute/main.tf
  community/modules/scripts/spack-execute/outputs.tf
  community/modules/scripts/spack-execute/variables.tf
  community/modules/scripts/spack-execute/versions.tf
  community/modules/scripts/spack-setup/README.md
  community/modules/scripts/spack-setup/main.tf
  community/modules/scripts/spack-setup/outputs.tf
  community/modules/scripts/spack-setup/templates/spack_setup.yml.tftpl
  community/modules/scripts/spack-setup/variables.tf
  tools/duplicate-diff.py
Labels: release-module-improvements

#1847 Fix HTCondor Windows download URI
  community/modules/scripts/htcondor-install/files/install-htcondor.yaml
  community/modules/scripts/htcondor-install/templates/install-htcondor.ps1.tftpl
  community/modules/scripts/htcondor-install/variables.tf
Labels: release-bugfix

#1850 Update vm-instance placement documentation
  modules/compute/vm-instance/README.md
Labels: release-chore

#1856 Updating terraform provider to 4.84.0
  pkg/modulewriter/tfversions.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
Labels: release-chore, release-version-updates

#1862 Upgrade HTCondor to LTS Release 23.0
  community/modules/scripts/htcondor-install/README.md
  community/modules/scripts/htcondor-install/files/install-htcondor.yaml
  community/modules/scripts/htcondor-install/templates/install-htcondor.ps1.tftpl
  community/modules/scripts/htcondor-install/variables.tf
Labels: release-version-updates

#1859 Add integration test for Slurm and Debian image
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/create_deployment_directory.yml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-debian.yaml
  tools/cloud-build/daily-tests/tests/slurm-v5-debian.yml
Labels: release-chore

#1805 Move to using replication.auto to avoid deprecated variable
  community/modules/scheduler/htcondor-pool-secrets/README.md
  community/modules/scheduler/htcondor-pool-secrets/main.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
Labels: release-chore

#1836 Origin/caesolution
  examples/README.md
  examples/cae/README.md
  examples/cae/cae-slurm.yaml
Labels: release-key-new-features

#1860 Update install_ansible.sh to install python3-venv and be compatible with Debian 12
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/pbspro-execution/README.md
  community/modules/compute/pbspro-execution/main.tf
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/main.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/pbspro-client/README.md
  community/modules/scheduler/pbspro-client/main.tf
  community/modules/scheduler/pbspro-server/README.md
  community/modules/scheduler/pbspro-server/main.tf
  community/modules/scripts/spack-execute/README.md
  community/modules/scripts/spack-execute/main.tf
  community/modules/scripts/spack-setup/README.md
  community/modules/scripts/spack-setup/main.tf
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/startup_from_network_storage.tf
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/startup_from_network_storage.tf
  modules/scheduler/batch-login-node/README.md
  modules/scheduler/batch-login-node/main.tf
  modules/scripts/startup-script/files/install_ansible.sh
Labels: release-chore

#1868 Fix HCLS collisions
  docs/videos/healthcare-and-life-sciences/hcls-blueprint.yaml
Labels: release-chore

#1869 Revert "Bump google.golang.org/api from 0.147.0 to 0.148.0"
  go.mod
  go.sum
Labels: release-chore

#1864 Add integration test for slurm and rocky 8
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-rocky8.yaml
  tools/cloud-build/daily-tests/tests/slurm-v5-rocky8.yml
Labels: release-chore

#1863 Render YAML-parsing errors in "rich" way
  cmd/create.go
  cmd/create_test.go
  pkg/config/config.go
  pkg/config/path.go
  pkg/config/path_test.go
  pkg/config/yaml.go
  pkg/config/yaml_test.go
Labels: release-chore

#1858 Integration task for bulk insert stockout errors
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/check_stockout.yml
Labels: release-chore

#1873 Bump minimum Golang version 1.18 -> 1.20
  go.mod
  tools/cloud-build/build-test-go.yaml
  tools/cloud-build/provision/README.md
  tools/cloud-build/provision/pr-go-build-test.tf
Labels: release-version-updates

#1877 Update ansible's usage of virtualenv to venv
  community/modules/scripts/ramble-setup/templates/install_ramble_deps.yml.tpl
  community/modules/scripts/spack-setup/scripts/install_spack_deps.yml
Labels: release-bugfix

#1523 Enable usage of GCS URL as `Module.Source`
  modules/README.md
  pkg/modulereader/resreader.go
  pkg/modulereader/resreader_test.go
  pkg/modulewriter/modulewriter.go
  pkg/sourcereader/git.go
  pkg/sourcereader/goget.go
  pkg/sourcereader/goget_test.go
  pkg/sourcereader/local.go
  pkg/sourcereader/local_test.go
  pkg/sourcereader/sourcereader.go
  pkg/sourcereader/sourcereader_test.go
Labels: release-improvements

#1870 Point path of mapping item to key instead of value position
  cmd/create_test.go
  pkg/config/yaml.go
  pkg/config/yaml_test.go
Labels: release-chore

#1883 Revert "Integration task for bulk insert stockout errors"
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/check_stockout.yml
Labels: release-chore

#1879 Move set module settings validation into separate function
  pkg/config/expand.go
  pkg/config/expand_test.go
Labels: release-chore

#1880 Check for stockouts during bulkInsert in integration tests.
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/check_stockout.yml
Labels: release-bugfix

#1840 Organize test files
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-batch-submission.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-crd.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-hello-world.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-htcondor-access-point.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-lustre-slurm.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-lustre-vm.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-monitoring.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-mounts.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-ofe-deployment.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-partitions.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-pbspro.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-spack.yml
  tools/cloud-build/daily-tests/tests/batch-mpi.yml
  tools/cloud-build/daily-tests/tests/cloud-batch.yml
  tools/cloud-build/daily-tests/tests/hcls.yml
  tools/cloud-build/daily-tests/tests/hello-world-vars.yml
  tools/cloud-build/daily-tests/tests/high-io-slurm-gcp-v5.yml
  tools/cloud-build/daily-tests/tests/hpc-enterprise-slurm.yml
  tools/cloud-build/daily-tests/tests/hpc-high-io.yml
  tools/cloud-build/daily-tests/tests/hpc-slurm-chromedesktop.yml
  tools/cloud-build/daily-tests/tests/htcondor.yml
  tools/cloud-build/daily-tests/tests/lustre-new-vpc.yml
  tools/cloud-build/daily-tests/tests/lustre-slurm.yml
  tools/cloud-build/daily-tests/tests/lustre-vm.yml
  tools/cloud-build/daily-tests/tests/monitoring.yml
  tools/cloud-build/daily-tests/tests/ofe-deployment.yml
  tools/cloud-build/daily-tests/tests/pbspro.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-hpc-centos7.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-startup-scripts.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-ubuntu.yml
  tools/cloud-build/daily-tests/tests/spack-gromacs.yml
Labels: release-chore

#1871 Add Slurm V6 controller, partition & nodeset modules
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/gpu_definition.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/outputs.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/outputs.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  tools/duplicate-diff.py
Labels: release-new-modules

#1872 Cleanup Slurm Metadata Nightly
  tools/clean-metadata.sh
  tools/cloud-build/project-cleanup.yaml
Labels: release-chore

#1894 Bake build config into trigger for Golang build tests
  tools/cloud-build/build-test-go.yaml
  tools/cloud-build/provision/pr-go-build-test.tf
Labels: release-chore

#1886 Git-ignore `expanded.yaml`
  .gitignore
Labels: release-chore

#1882 Improve Spack and Ramble Refs
  community/modules/scripts/ramble-setup/templates/ramble_setup.yml.tftpl
  community/modules/scripts/spack-setup/templates/spack_setup.yml.tftpl
Labels: release-module-improvements

#1889 Update default CRD image to Debian 11
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/scripts/configure-grid-drivers.yml
  community/modules/remote-desktop/chrome-remote-desktop/variables.tf
  community/modules/scripts/ramble-execute/README.md
  community/modules/scripts/ramble-execute/main.tf
  community/modules/scripts/ramble-setup/README.md
  community/modules/scripts/ramble-setup/main.tf
  docs/vm-images.md
  tools/validate_configs/test_configs/remote-desktop.yaml
Labels: release-chore

#1890 Slurm V6. Add login module
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/outputs.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  tools/duplicate-diff.py
Labels: release-new-modules

#1885 Add tool for checking quota minimums across multiple regions
  tools/cloud-build/quota-check/README.md
  tools/cloud-build/quota-check/bp.yaml
  tools/cloud-build/quota-check/check.py
Labels: release-chore

#1875 Validate runtime dependencies before doing `deploy`
  cmd/deploy.go
  pkg/shell/packer.go
  pkg/shell/terraform.go
Labels: release-chore

#1903 Revert "Organize test files"
  tools/cloud-build/daily-tests/ansible_playbooks/test-batch-submission.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-crd.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-hello-world.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-htcondor-access-point.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-lustre-slurm.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-lustre-vm.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-monitoring.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-mounts.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-ofe-deployment.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-partitions.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-pbspro.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-spack.yml
  tools/cloud-build/daily-tests/tests/batch-mpi.yml
  tools/cloud-build/daily-tests/tests/cloud-batch.yml
  tools/cloud-build/daily-tests/tests/hcls.yml
  tools/cloud-build/daily-tests/tests/hello-world-vars.yml
  tools/cloud-build/daily-tests/tests/high-io-slurm-gcp-v5.yml
  tools/cloud-build/daily-tests/tests/hpc-enterprise-slurm.yml
  tools/cloud-build/daily-tests/tests/hpc-high-io.yml
  tools/cloud-build/daily-tests/tests/hpc-slurm-chromedesktop.yml
  tools/cloud-build/daily-tests/tests/htcondor.yml
  tools/cloud-build/daily-tests/tests/lustre-new-vpc.yml
  tools/cloud-build/daily-tests/tests/lustre-slurm.yml
  tools/cloud-build/daily-tests/tests/lustre-vm.yml
  tools/cloud-build/daily-tests/tests/monitoring.yml
  tools/cloud-build/daily-tests/tests/ofe-deployment.yml
  tools/cloud-build/daily-tests/tests/pbspro.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-hpc-centos7.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-startup-scripts.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-ubuntu.yml
  tools/cloud-build/daily-tests/tests/spack-gromacs.yml
Labels: release-chore

#1896 Slurm6. Add basic example and integration test
  community/examples/hpc-slurm6.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-rocky8.yaml
  tools/cloud-build/daily-tests/tests/slurm-v6-rocky8.yml
Labels: release-chore

#1902 Re-raise error in rescue block of slurm integration test
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
Labels: release-chore
