Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2023-08, with the labels that each got.

#1641 Update to latest tf provider and resolve GKE conflict
  community/modules/compute/gke-node-pool/README.md
  community/modules/compute/gke-node-pool/variables.tf
  community/modules/compute/gke-node-pool/versions.tf
  pkg/modulewriter/tfversions.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
Labels: version-updates

#1646 Change description of instance image variable in CRD module to use ubuntu 2204 as default
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/variables.tf
Labels: chore

#1653 Fix "Apply" prompt so user input is separated
  pkg/shell/common.go
Labels: chore

#1652 Add labels automatically to dependabot PRs
  .github/dependabot.yml
Labels: chore

#1654 Support specification of MIG target shape in HTCondor modules
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/htcondor-execute-point/variables.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-access-point/variables.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/htcondor-central-manager/variables.tf
Labels: module-improvements

#1651 Add H3 to disk_type validation in vm-instance and slurm modules
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/outputs.tf
  modules/compute/vm-instance/main.tf
Labels: chore

#1657 Add H3 to `examples/hpc-enterprise-slurm`
  examples/README.md
  examples/hpc-enterprise-slurm.yaml
Labels: documentation, key-new-features

#1660 Remove basic tutorial for HPC toolkit cluster deployment
  docs/tutorials/README.md
  docs/tutorials/basic.md
Labels: chore

#1656 Update DDN EXAScaler image to 6.2
  community/modules/file-system/DDN-EXAScaler/README.md
  community/modules/file-system/DDN-EXAScaler/variables.tf
  docs/vm-images.md
Labels: version-updates

#1662 Replace "module" with "deployment group" in prompt
  pkg/shell/terraform.go
Labels: chore

#1661 Bump slurm-gcp to 5.7.5 (from 5.7.4)
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
  docs/hybrid-slurm-cluster/demo-with-cloud-controller-instructions.md
  docs/hybrid-slurm-cluster/deploy-instructions.md
  docs/hybrid-slurm-cluster/on-prem-instructions.md
  docs/image-building.md
  examples/README.md
  tools/cloud-build/Dockerfile
Labels: version-updates

#1592 Implement quota validation logic
  pkg/validators/quota.go
  pkg/validators/quota_test.go
  tools/enforce_coverage.pl
Labels: chore

#1668 Add a prefix to release labels
  .github/dependabot.yml
  .github/release.yml
  .github/workflows/pr-label-validation.yml
Labels: release-chore

#1669 Add logic to retrieve current resource usage
  pkg/validators/quota.go
  pkg/validators/quota_test.go
Labels: release-chore

#1667 Add H3 partition to the hpc-slurm example
  examples/README.md
  examples/hpc-slurm.yaml
Labels: release-key-new-features

#1665 Simplify H3 enterprise example
  examples/hpc-enterprise-slurm.yaml
Labels: release-chore

#1672 Fix zone in test-slurm-gcp-v5-hpc-centos7
  tools/cloud-build/daily-tests/tests/slurm-v5-hpc-centos7.yml
Labels: release-chore

#1673 Bump slurm-gcp to 5.7.6 (from 5.7.5)
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
  docs/hybrid-slurm-cluster/demo-with-cloud-controller-instructions.md
  docs/hybrid-slurm-cluster/deploy-instructions.md
  docs/hybrid-slurm-cluster/on-prem-instructions.md
  docs/image-building.md
  examples/README.md
  tools/cloud-build/Dockerfile
Labels: release-version-updates

#1676 Add blueprint used for Slurm static node testing
  tools/validate_configs/test_configs/slurm-static-test.yaml
Labels: release-chore

#1675 Add check for invalid module id
  pkg/config/validate.go
  pkg/config/validator_test.go
Labels: release-chore

#1680 Improve makefile to avoid build fail if git describe fails
  Makefile
Labels: release-chore

#1683 OFE: fixing syntax mistake in the images template and updating machine type API client
  community/front-end/ofe/website/ghpcfe/cluster_manager/cloud_info.py
  community/front-end/ofe/website/ghpcfe/templates/image/list.html
Labels: release-chore

#1670 Cloud Workstation Improvements
  tools/cloud-workstations/030_configure-hpc-toolkit.sh
  tools/cloud-workstations/Dockerfile
  tools/cloud-workstations/README.md
  tools/cloud-workstations/configure-hpc-toolkit.sh
Labels: release-chore

#1682 Add Shielded VM support to Packer module
  modules/packer/custom-image/README.md
  modules/packer/custom-image/image.pkr.hcl
  modules/packer/custom-image/variables.pkr.hcl
  tools/validate_configs/golden_copies/expectations/igc_pkr/one/image/image.pkr.hcl
  tools/validate_configs/golden_copies/expectations/igc_pkr/one/image/variables.pkr.hcl
  tools/validate_configs/golden_copies/expectations/text_escape/zero/lime/image.pkr.hcl
  tools/validate_configs/golden_copies/expectations/text_escape/zero/lime/variables.pkr.hcl
Labels: release-module-improvements

#1685 Bump version to v1.22.0
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-login-node/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/htcondor-setup/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#1689 Update pre-commit hooks
  .pre-commit-config.yaml
  community/front-end/ofe/infrastructure_files/vpc_tf/GCP/versions.tf
  community/front-end/ofe/infrastructure_files/workbench_tf/google/versions.tf
Labels: release-chore

#1679 Slurm tests. Wait for all partitions to became "UP"
  tools/cloud-build/daily-tests/ansible_playbooks/test-partitions.yml
Labels: release-chore

#1695 Updates to version numbers for release candidate commit to develop
  pkg/modulewriter/tfversions.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
Labels: release-chore

#1697 Add "release-bugfix" PR label
  .github/release.yml
Labels: release-chore

#1696 Support network_storage runners in HTCondor modules
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-central-manager/main.tf
Labels: release-improvements

#1691 hpc-enterprise-slurm gpu fix
  examples/hpc-enterprise-slurm.yaml
Labels: release-improvements, release-bugfix

#1671 Add Integration test for hpc-slurm-chromedesktop
  tools/cloud-build/babysit_tests.py
  tools/cloud-build/daily-tests/ansible_playbooks/test-crd.yml
  tools/cloud-build/daily-tests/builds/hpc-slurm-chromedesktop.yaml
  tools/cloud-build/daily-tests/tests/hpc-slurm-chromedesktop.yml
Labels: release-chore

#1678 Add hint to error message `invalid module reference: var`
  go.mod
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/errors.go
  pkg/config/expand.go
  pkg/config/expand_test.go
Labels: release-chore

#1644 Star ccm update to include Slurm
  community/examples/tutorial-starccm-slurm.yaml
  community/examples/tutorial-starccm.yaml
  examples/README.md
Labels: release-key-new-features

#1699 Remove unused `errorMessages`
  pkg/config/config.go
Labels: release-chore

#1702 Added precondition to check if a vm instance block has valid IPs.
  modules/compute/vm-instance/main.tf
Labels: release-chore

#1704 Add Shielded VM features to HTCondor modules
  community/examples/htc-htcondor.yaml
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/htcondor-execute-point/variables.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-access-point/variables.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/htcondor-central-manager/variables.tf
Labels: release-module-improvements

#1698 Update to hpc-enterprise-slurm blueprint with SuspendTime example
  examples/hpc-enterprise-slurm.yaml
Labels: release-chore

#1690 Refactor `cfg/validators` package
  cmd/create.go
  cmd/create_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/errors.go
  pkg/config/expand.go
  pkg/config/validate.go
  pkg/config/validator_test.go
  pkg/validators/validators.go
  pkg/validators/validators_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/text_escape/.ghpc/artifacts/expanded_blueprint.yaml
Labels: release-chore

#1705 Add resource requirements validator
  cmd/create.go
  cmd/create_test.go
  pkg/validators/quota.go
  pkg/validators/quota_test.go
  pkg/validators/validators.go
Labels: release-key-new-features

#1706 Fix type for deployment variable description in filestore module
  modules/file-system/filestore/README.md
  modules/file-system/filestore/variables.tf
Labels: release-chore

#1710 Fix broken link for compatibility matrix in Filestore documentation
  modules/file-system/filestore/README.md
Labels: release-chore

#1711 Closes stale issues
  .github/workflows/close-inactive-issues.yml
Labels: release-chore

#1709 Incorporate usage into resource requirements validation
  pkg/validators/quota.go
  pkg/validators/quota_test.go
Labels: release-key-new-features

#1713 Fill in default values for quota validation inputs
  pkg/config/config.go
  pkg/validators/quota.go
  pkg/validators/quota_test.go
  pkg/validators/validators.go
Labels: release-chore

#1707 Fix label for dependabot go updates (release-chore)
  .github/dependabot.yml
Labels: release-chore

#1712 Improvements to hpc-enterprise blueprint
  examples/hpc-enterprise-slurm.yaml
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-partitions.yml
Labels: release-chore

#1720 Add a blueprint that is compatible with Qwiklabs tutorials
  docs/tutorials/README.md
  docs/tutorials/hpc-slurm-qwiklabs.yaml
Labels: release-chore

#1719 Update ml-slurm base image
  examples/README.md
  examples/ml-slurm.yaml
Labels: release-chore

#1721 Refactor quota validation logic
  pkg/validators/quota.go
  pkg/validators/quota_test.go
Labels: release-chore

#1723 Added h3_partition quota information to hpc-slurm.yaml
  examples/README.md
Labels: release-chore

#1724 Use smaller machines for Omnia integration tests
  tools/cloud-build/daily-tests/tests/omnia.yml
Labels: release-chore

#1725 Create simple command line tool to summarize topology of VMs
  tools/topo-lookup.py
Labels: release-improvements
