Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2023-12, with the labels that each got.

#2009 Update slurm modules to point to fork
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
Labels: release-improvements

#1993 Refactor `pkg/sourcereader` tests.
  cmd/export_test.go
  pkg/config/config_test.go
  pkg/modulereader/resreader_test.go
  pkg/modulewriter/modulewriter_test.go
  pkg/shell/common_test.go
  pkg/sourcereader/embedded.go
  pkg/sourcereader/embedded_test.go
  pkg/sourcereader/goget_test.go
  pkg/sourcereader/local_test.go
  pkg/sourcereader/modules/network/vpc/main.tf
  pkg/sourcereader/modules/network/vpc/output.tf
  pkg/sourcereader/modules/network/vpc/variables.tf
  pkg/sourcereader/sourcereader_test.go
Labels: release-chore

#2015 Document permissions around manual usage of Spack installation
  community/modules/scripts/spack-setup/README.md
Labels: release-improvements

#2014 Adding snippet of commonly used images to make it easy to modify a blueprint
  docs/vm-images.md
Labels: release-chore

#2023 Slurm flag for maintenance API script
  tests/test_maintenance.py
  tools/maintenance/maintenance.py
Labels: release-chore

#2026 Fix local SSD example
  community/examples/hpc-slurm-local-ssd.yaml
Labels: release-bugfix

#2025 Eliminate local SSD warning
  .tflint.hcl
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
Labels: release-chore

#2029 Disable `go-critic` hook
  .pre-commit-config.yaml
Labels: release-chore

#2004 OFE: Spack upgrade to v0.21.0
  community/front-end/ofe/infrastructure_files/gcs_bucket/clusters/ansible_setup/roles/spack_install/tasks/main.yaml
  community/front-end/ofe/infrastructure_files/gcs_bucket/webserver/startup.sh
  community/front-end/ofe/requirements.txt
  community/front-end/ofe/website/ghpcfe/cluster_manager/spack.py
Labels: release-version-updates

#1895 Front End Deployment Changes
  community/front-end/ofe/deploy.sh
  community/front-end/ofe/docs/admin_guide.md
  community/front-end/ofe/infrastructure_files/gcs_bucket/webserver/startup.sh
  community/front-end/ofe/website/nginx.conf
  community/front-end/ofe/website/website/settings.py
Labels: release-improvements

#2007 Update `checkOverwriteAllowed`
  cmd/create.go
  cmd/create_test.go
  cmd/deploy.go
  cmd/destroy.go
  cmd/export.go
  cmd/import.go
  pkg/modulewriter/modulewriter.go
  pkg/modulewriter/modulewriter_test.go
  pkg/modulewriter/tfwriter.go
Labels: release-chore

#2034 Fail `terraform_docs` hook if any error occurs.
  tools/autodoc/terraform_docs.sh
Labels: release-chore

#2033 Update documentation for Slurm V6 TPU module
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/README.md
Labels: release-chore

#2041 update TFLint to 0.49 & latest plugin in precommit
  .tflint.hcl
  community/modules/compute/gke-node-pool/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/file-system/DDN-EXAScaler/variables.tf
  community/modules/project/service-account/variables.tf
  community/modules/scheduler/gke-cluster/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
  community/modules/scripts/spack-setup/variables.tf
  modules/network/vpc/variables.tf
  modules/scheduler/batch-login-node/variables.tf
  modules/scripts/startup-script/variables.tf
  tools/cloud-build/hpc-toolkit-builder.yaml
  tools/cloud-workstations/workstation-image.yaml
Labels: release-chore

#2013 Refactor `WriteDeployment`
  .pre-commit-config.yaml
  pkg/modulewriter/modulewriter.go
  pkg/modulewriter/modulewriter_test.go
  pkg/modulewriter/packerwriter.go
  pkg/modulewriter/tfwriter.go
Labels: release-chore

#2042 Fix broken golang, add tests to meet coverage threshold
  pkg/modulewriter/modulewriter.go
  pkg/modulewriter/modulewriter_test.go
  pkg/modulewriter/tfwriter.go
Labels: release-chore

#2035 Use CFT-metadata struct directly instead of mimicing it.
  go.mod
  go.sum
  pkg/modulereader/metadata.go
  pkg/modulereader/metadata_legacy.go
  pkg/modulereader/resreader.go
  pkg/modulereader/resreader_test.go
  pkg/modulewriter/tfwriter.go
Labels: release-chore

#2040 OFE: Various new features and fixes.
  community/front-end/ofe/deploy.sh
  community/front-end/ofe/infrastructure_files/gcs_bucket/webserver/startup.sh
  community/front-end/ofe/script/service_account.sh
  community/front-end/ofe/website/ghpcfe/cluster_manager/cloud_info.py
  community/front-end/ofe/website/ghpcfe/cluster_manager/clusterinfo.py
  community/front-end/ofe/website/ghpcfe/cluster_manager/filesystem.py
  community/front-end/ofe/website/ghpcfe/cluster_manager/image.py
  community/front-end/ofe/website/ghpcfe/forms.py
  community/front-end/ofe/website/ghpcfe/models.py
  community/front-end/ofe/website/ghpcfe/signals.py
  community/front-end/ofe/website/ghpcfe/static/css/jquery-ui.css
  community/front-end/ofe/website/ghpcfe/static/js/jquery-ui.js
  community/front-end/ofe/website/ghpcfe/templates/cluster/check_destroy.html
  community/front-end/ofe/website/ghpcfe/templates/cluster/create_form.html
  community/front-end/ofe/website/ghpcfe/templates/cluster/detail.html
  community/front-end/ofe/website/ghpcfe/templates/cluster/list.html
  community/front-end/ofe/website/ghpcfe/templates/cluster/update_form.html
  community/front-end/ofe/website/ghpcfe/templates/image/image-create.html
  community/front-end/ofe/website/ghpcfe/templates/job/create_form.html
  community/front-end/ofe/website/ghpcfe/templates/job/rerun_form.html
  community/front-end/ofe/website/ghpcfe/templates/vpc/import_form.html
  community/front-end/ofe/website/ghpcfe/urls.py
  community/front-end/ofe/website/ghpcfe/views/applications.py
  community/front-end/ofe/website/ghpcfe/views/clusters.py
  community/front-end/ofe/website/ghpcfe/views/credentials.py
  community/front-end/ofe/website/ghpcfe/views/grafana.py
Labels: release-module-improvements

#2043 Use protobuf getters to avoid nil-pointer panics
  pkg/inspect/modules_test.go
  pkg/validators/cloud.go
Labels: release-chore

#1874 Tutorial for FSI VaR MonteCarlo
  community/examples/fsi-montecarlo-on-batch.yaml
  community/modules/compute/notebook/README.md
  community/modules/compute/notebook/main.tf
  community/modules/compute/notebook/metadata.yaml
  community/modules/compute/notebook/variables.tf
  community/modules/compute/notebook/versions.tf
  community/modules/database/bigquery-dataset/README.md
  community/modules/database/bigquery-dataset/main.tf
  community/modules/database/bigquery-dataset/metadata.yaml
  community/modules/database/bigquery-dataset/outputs.tf
  community/modules/database/bigquery-dataset/variables.tf
  community/modules/database/bigquery-dataset/versions.tf
  community/modules/database/bigquery-table/README.md
  community/modules/database/bigquery-table/main.tf
  community/modules/database/bigquery-table/metadata.yaml
  community/modules/database/bigquery-table/outputs.tf
  community/modules/database/bigquery-table/variables.tf
  community/modules/database/bigquery-table/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/FSI_MonteCarlo.ipynb
  community/modules/files/fsi-montecarlo-on-batch/README.md
  community/modules/files/fsi-montecarlo-on-batch/iteration.sh
  community/modules/files/fsi-montecarlo-on-batch/main.tf
  community/modules/files/fsi-montecarlo-on-batch/mc_run.tpl.py
  community/modules/files/fsi-montecarlo-on-batch/mc_run.tpl.yaml
  community/modules/files/fsi-montecarlo-on-batch/mc_run_reqs.txt
  community/modules/files/fsi-montecarlo-on-batch/metadata.yaml
  community/modules/files/fsi-montecarlo-on-batch/variables.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/pubsub/bigquery-sub/README.md
  community/modules/pubsub/bigquery-sub/main.tf
  community/modules/pubsub/bigquery-sub/metadata.yaml
  community/modules/pubsub/bigquery-sub/outputs.tf
  community/modules/pubsub/bigquery-sub/variables.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/README.md
  community/modules/pubsub/topic/main.tf
  community/modules/pubsub/topic/metadata.yaml
  community/modules/pubsub/topic/outputs.tf
  community/modules/pubsub/topic/variables.tf
  community/modules/pubsub/topic/versions.tf
  docs/tutorials/fsi-montecarlo-on-batch/README.md
  examples/README.md
  modules/README.md
Labels: release-new-modules

#1965 Inject Blueprint ModuleID as specified variable
  docs/module-guidelines.md
  go.mod
  go.sum
  pkg/config/expand.go
  pkg/inspect/modules_test.go
  pkg/modulereader/metadata.go
  pkg/modulereader/metadata_legacy.go
  pkg/modulereader/modules/test_role/test_module/metadata.yaml
  pkg/modulereader/resreader.go
  pkg/modulereader/resreader_test.go
  pkg/validators/cloud.go
Labels: release-chore

#2045 Hotfix wait for startup update
  .tflint.hcl
  cmd/root.go
  community/modules/compute/gke-node-pool/variables.tf
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/DDN-EXAScaler/variables.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/project/service-account/variables.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-login-node/versions.tf
  community/modules/scheduler/gke-cluster/variables.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/htcondor-setup/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/spack-setup/variables.tf
  community/modules/scripts/wait-for-startup/scripts/wait-for-startup-status.sh
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/network/vpc/variables.tf
  modules/scheduler/batch-login-node/variables.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/variables.tf
  modules/scripts/startup-script/versions.tf
  tools/cloud-build/hpc-toolkit-builder.yaml
  tools/cloud-workstations/workstation-image.yaml
Labels: release-bugfix

#2046 Point builder-image Dockerfile to Slurm-gcp fork repo.
  tools/cloud-build/Dockerfile
Labels: release-chore

#2049 Fix wrong link to enable "Compute Engine API"
  pkg/validators/cloud.go
  pkg/validators/validators.go
Labels: release-chore

#2050 Allow usage of expression for `vars.deployment_name`
  cmd/create.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/expand.go
  pkg/config/validate.go
  pkg/config/validator_test.go
Labels: release-chore

#2056 Add label for blocking merges of PRs
  .github/workflows/pr-label-validation.yml
Labels: release-chore

#2057 Disable firewall rule logging by default
  modules/network/vpc/README.md
  modules/network/vpc/main.tf
  modules/network/vpc/variables.tf
Labels: release-module-improvements

#2061 Ignore go.sum for codespell hook
  .pre-commit-config.yaml
Labels: release-chore

#2063 Slurm6. Add required services to metadata
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/metadata.yaml
Labels: release-chore

#2064 Slurm6. Add tracking labels to GCS bucket.
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
Labels: release-chore

#2051 `vm-instance` is now able to `use` a service account
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/main.tf
  modules/compute/vm-instance/variables.tf
  tools/validate_configs/test_configs/complex-data.yaml
  tools/validate_configs/test_configs/spack-buildcache.yaml
  tools/validate_configs/test_configs/spack-environments.yaml
Labels: release-improvements

#2065 Bump golang.org/x/crypto to 0.17.0
  go.mod
  go.sum
Labels: dependencies, go, release-chore

#2052 Perform spack and ramble actions with system user
  community/examples/hpc-slurm-ramble-gromacs.yaml
  community/modules/scripts/ramble-execute/README.md
  community/modules/scripts/ramble-execute/main.tf
  community/modules/scripts/ramble-execute/outputs.tf
  community/modules/scripts/ramble-execute/templates/ramble_execute.yml.tpl
  community/modules/scripts/ramble-execute/variables.tf
  community/modules/scripts/ramble-setup/README.md
  community/modules/scripts/ramble-setup/main.tf
  community/modules/scripts/ramble-setup/outputs.tf
  community/modules/scripts/ramble-setup/templates/ramble_setup.yml.tftpl
  community/modules/scripts/ramble-setup/variables.tf
  community/modules/scripts/spack-execute/README.md
  community/modules/scripts/spack-execute/main.tf
  community/modules/scripts/spack-execute/outputs.tf
  community/modules/scripts/spack-execute/templates/execute_commands.yml.tpl
  community/modules/scripts/spack-execute/variables.tf
  community/modules/scripts/spack-setup/README.md
  community/modules/scripts/spack-setup/main.tf
  community/modules/scripts/spack-setup/outputs.tf
  community/modules/scripts/spack-setup/templates/spack_setup.yml.tftpl
  community/modules/scripts/spack-setup/variables.tf
Labels: release-key-new-features

#2066 Slurm6. Add support for `enable_slurm_gcp_plugins`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-module-improvements

#2069 Update Rocky image to older version for lustre compatibility
  tools/cloud-build/daily-tests/blueprints/lustre-vm.yaml
Labels: release-chore

#2071 Disable user interactive prompt in start-up script in quantum circuit simulator
  community/examples/quantum-circuit-simulator.yaml
Labels: release-chore

#2072 Support explicit reserved_ip_range for Filestore instances
  modules/file-system/filestore/README.md
  modules/file-system/filestore/main.tf
  modules/file-system/filestore/variables.tf
Labels: release-module-improvements

#2075 Adopt gcloud storage over gsutil by default
  modules/scripts/startup-script/files/get_from_bucket.sh
Labels: release-module-improvements

#2077 Simplify yaml marshalling for expressions
  pkg/config/expression.go
  pkg/config/yaml.go
Labels: release-chore

#2074 Skip upgrade of wheel/setuptools if already installed
  modules/scripts/startup-script/files/install_ansible.sh
Labels: release-module-improvements
