Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2023-11, with the labels that each got.

#1893 Add Path specialization that can be extended with cty.Path
  pkg/config/path.go
  pkg/config/path_test.go
  pkg/config/validate.go
Labels: release-chore

#1912 Create bucket inside Slurm cluster wrapper to control default name
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/main.tf
  pkg/config/path.go
  pkg/config/path_test.go
  pkg/config/validate.go
Labels: release-chore

#1915 Daily-cleanup updates
  tools/cloud-build/project-cleanup.yaml
  tools/cloud-build/provision/daily-cleanup.tf
Labels: release-chore

#1913 Fix missing `custom_var.mount` issue
  tools/cloud-build/daily-tests/tests/slurm-v6-rocky8.yml
Labels: release-chore

#1919 Bump Slurm `6.1.2 -> 6.2.0`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
Labels: release-chore

#1911 Rename test files roll forward
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-batch-submission.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-crd.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-hello-world.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-htcondor-access-point.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-lustre-slurm.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-lustre-vm.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-monitoring.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-mounts.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-ofe-deployment.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-partitions.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-pbspro.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-spack.yml
  tools/cloud-build/daily-tests/tests/batch-mpi.yml
  tools/cloud-build/daily-tests/tests/cloud-batch.yml
  tools/cloud-build/daily-tests/tests/hcls.yml
  tools/cloud-build/daily-tests/tests/hello-world-vars.yml
  tools/cloud-build/daily-tests/tests/high-io-slurm-gcp-v5.yml
  tools/cloud-build/daily-tests/tests/hpc-enterprise-slurm.yml
  tools/cloud-build/daily-tests/tests/hpc-high-io.yml
  tools/cloud-build/daily-tests/tests/hpc-slurm-chromedesktop.yml
  tools/cloud-build/daily-tests/tests/htcondor.yml
  tools/cloud-build/daily-tests/tests/lustre-new-vpc.yml
  tools/cloud-build/daily-tests/tests/lustre-slurm.yml
  tools/cloud-build/daily-tests/tests/lustre-vm.yml
  tools/cloud-build/daily-tests/tests/monitoring.yml
  tools/cloud-build/daily-tests/tests/ofe-deployment.yml
  tools/cloud-build/daily-tests/tests/pbspro.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-debian.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-hpc-centos7.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-rocky8.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-startup-scripts.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-ubuntu.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-rocky8.yml
  tools/cloud-build/daily-tests/tests/spack-gromacs.yml
Labels: release-chore

#1920 Test for tty before echo in /etc/profile.d scripts
  community/modules/scripts/ramble-setup/main.tf
  community/modules/scripts/spack-setup/main.tf
Labels: release-chore

#1923 Add name to triggers for vm-instance because that can be specified now
  modules/compute/vm-instance/main.tf
Labels: release-chore

#1924 Revert "Add name to triggers for vm-instance because that can be specified now"
  modules/compute/vm-instance/main.tf
Labels: release-chore

#1892 Add path to `test_module_not_used` errors
  pkg/validators/validators.go
Labels: release-chore

#1916 Add Integration test for Slurm V6 TPU nodeset
  community/examples/hpc-slurm6-tpu.yaml
  tools/cloud-build/daily-tests/ansible_playbooks/test-slurm-v6-tpu.yml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-tpu.yaml
  tools/cloud-build/daily-tests/tests/slurm-v6-tpu.yml
Labels: release-chore

#1904 Do not set role-label in expand, rely on module embedded labels
  modules/packer/custom-image/image.pkr.hcl
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/one/image/defaults.auto.pkrvars.hcl
  tools/validate_configs/golden_copies/expectations/igc_pkr/one/image/image.pkr.hcl
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/main.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/main.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/main.tf
  tools/validate_configs/golden_copies/expectations/text_escape/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/text_escape/zero/lime/defaults.auto.pkrvars.hcl
  tools/validate_configs/golden_copies/expectations/text_escape/zero/lime/image.pkr.hcl
Labels: release-deprecations

#1921 Add Dockerfile and build config for GHPC image
  tools/cloud-build/ghpc-docker/Dockerfile
  tools/cloud-build/ghpc-docker/cloudbuild.yaml
Labels: release-chore

#1930 Hotfix for vm-instance to allow image names to be used correctly
  modules/compute/vm-instance/main.tf
  tools/validate_configs/test_configs/vm.yaml
Labels: release-bugfix

#1928 Filestore clean up - ignore active builds
  tools/clean-filestore-limit.sh
Labels: release-chore

#1908 Update stockout check to account for logging delay
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/check_stockout.yml
Labels: release-chore

#1931 Disable RELEASE-tests
  tools/cloud-build/provision/release-tests.tf
Labels: release-chore

#1938 Bump version 1.24.0 -> 1.25.0
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-login-node/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/htcondor-setup/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#1941 Fix bug in `tools/topo-lookup.py`
  tools/topo-lookup.py
Labels: release-chore

#1897 Improve pre existing vpc failure mechanism
  modules/network/pre-existing-vpc/main.tf
Labels: release-chore

#1943 Fix name of HTCondor yum repository Ansible task
  community/modules/scripts/htcondor-install/files/install-htcondor.yaml
Labels: release-chore

#1944 Remove RELEASE tests
  tools/cloud-build/provision/README.md
  tools/cloud-build/provision/list-tests.tf
  tools/cloud-build/provision/main.tf
  tools/cloud-build/provision/release-tests.tf
Labels: release-chore

#1948 Merge `1.25.0` back into `develop`
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-login-node/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/htcondor-setup/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/README.md
  modules/compute/vm-instance/main.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
  tools/validate_configs/test_configs/vm.yaml
Labels: release-chore

#1927 Allow ramble module to point at forked repositories
  community/modules/scripts/ramble-execute/main.tf
  community/modules/scripts/ramble-setup/main.tf
  community/modules/scripts/ramble-setup/scripts/install_ramble_deps.yml
  community/modules/scripts/ramble-setup/templates/install_ramble_python_deps.yml.tftpl
  community/modules/scripts/spack-setup/main.tf
  community/modules/scripts/spack-setup/scripts/install_spack_deps.yml
  tools/duplicate-diff.py
Labels: release-improvements

#1937 Add reservations for test infra
  tools/cloud-build/provision/README.md
  tools/cloud-build/provision/reservations.tf
Labels: release-chore

#1949 🌈 Add colorization to the output
  cmd/color.go
  cmd/create.go
  cmd/root.go
  go.mod
  go.sum
Labels: release-improvements

#1940 Update zones and N2 quota requirements
  tools/cloud-build/quota-check/bp.yaml
  tools/cloud-build/quota-check/check.py
Labels: release-chore

#1950 Prevent ramble python venv from modifing PS1
  community/modules/scripts/ramble-setup/main.tf
Labels: release-chore

#1914 Unify image variable under `instance_image` across most modules
  community/front-end/ofe/infrastructure_files/workbench_tf/google/README.md
  community/front-end/ofe/infrastructure_files/workbench_tf/google/main.tf
  community/front-end/ofe/infrastructure_files/workbench_tf/google/variables.tf
  community/modules/compute/SchedMD-slurm-on-gcp-partition/variables.tf
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/htcondor-execute-point/variables.tf
  community/modules/compute/pbspro-execution/README.md
  community/modules/compute/pbspro-execution/main.tf
  community/modules/compute/pbspro-execution/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/file-system/DDN-EXAScaler/README.md
  community/modules/file-system/DDN-EXAScaler/main.tf
  community/modules/file-system/DDN-EXAScaler/variables.tf
  community/modules/file-system/nfs-server/README.md
  community/modules/file-system/nfs-server/main.tf
  community/modules/file-system/nfs-server/variables.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/main.tf
  community/modules/remote-desktop/chrome-remote-desktop/variables.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/README.md
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/variables.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-login-node/README.md
  community/modules/scheduler/SchedMD-slurm-on-gcp-login-node/variables.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-access-point/variables.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/htcondor-central-manager/variables.tf
  community/modules/scheduler/pbspro-client/README.md
  community/modules/scheduler/pbspro-client/main.tf
  community/modules/scheduler/pbspro-client/variables.tf
  community/modules/scheduler/pbspro-server/README.md
  community/modules/scheduler/pbspro-server/main.tf
  community/modules/scheduler/pbspro-server/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
  docs/videos/build-your-own-blueprint/batch-high-io.yaml
  examples/serverless-batch.yaml
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/variables.tf
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/main.tf
  modules/scheduler/batch-job-template/variables.tf
  tools/validate_configs/os_compatibility_tests/batch-filestore.yaml
  tools/validate_configs/os_compatibility_tests/batch-lustre.yaml
  tools/validate_configs/os_compatibility_tests/batch-startup.yaml
  tools/validate_configs/test_configs/multiple-batch-jobs.yaml
  tools/validate_configs/test_configs/rocky-ss.yaml
Labels: release-chore

#1952 Add colors flags to all commands (by adding it to the root)
  cmd/color.go
  cmd/create.go
  cmd/root.go
  go.mod
Labels: release-chore

#1953 Improve visibility of failed validators by adding color
  cmd/color.go
  cmd/create.go
Labels: release-chore

#1932 Slurm6. Fix race condition between GCS config files and instances
  community/examples/hpc-slurm6.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  tools/cloud-build/daily-tests/tests/slurm-v6-rocky8.yml
Labels: release-module-improvements

#1958 Slurm6. Fix race condition between GCS config files and instances
  community/examples/hpc-slurm6.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  tools/cloud-build/daily-tests/tests/slurm-v6-rocky8.yml
Labels: release-chore

#1959 Front End Teardown Success Bug Fix
  community/front-end/ofe/teardown.sh
Labels: release-chore

#1954 Colorize cobra errors
  cmd/color.go
  cmd/create.go
  cmd/deploy.go
  cmd/expand.go
  cmd/root.go
Labels: release-chore

#1960 Improve `instance_image` usage in example blueprints
  community/examples/htc-htcondor.yaml
  community/examples/intel/hpc-intel-select-slurm.yaml
  examples/hpc-enterprise-slurm.yaml
  examples/image-builder.yaml
  examples/ml-slurm.yaml
  tools/cloud-build/daily-tests/blueprints/lustre-slurm.yaml
Labels: release-chore

#1961 staticcheck. Fix errors
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/deploymentio/deploymentio_test.go
  pkg/deploymentio/local.go
  pkg/deploymentio/local_test.go
  pkg/inspect/modules_test.go
  pkg/modulereader/hcl_utils.go
  pkg/modulereader/metareader.go
  pkg/modulereader/packerreader.go
  pkg/modulereader/resreader.go
  pkg/modulereader/resreader_test.go
  pkg/modulewriter/modulewriter.go
  pkg/modulewriter/modulewriter_test.go
  pkg/modulewriter/tfwriter.go
  pkg/sourcereader/embedded.go
  pkg/sourcereader/embedded_test.go
  pkg/sourcereader/goget.go
  pkg/sourcereader/local_test.go
  pkg/sourcereader/sourcereader_test.go
  pkg/validators/quota_test.go
Labels: release-chore

#1946 Remove error-prone `errorMessage` map, remove deprecated `go-lint`
  .pre-commit-config.yaml
  pkg/config/config.go
  pkg/config/errors.go
  pkg/config/expand.go
  pkg/config/expand_test.go
  pkg/config/expression.go
  pkg/config/validate.go
  pkg/config/yaml.go
Labels: release-chore

#1963 Install `staticcheck`, prerequisite for #1962
  Makefile
  tools/cloud-build/Dockerfile
  tools/cloud-build/dependency-checks/Dockerfile.precommit
Labels: release-chore

#1962 Add `staticcheck` in place of deprecated `go-lint`
  .pre-commit-config.yaml
Labels: release-chore

#1942 Update slurm examples to turn GVNIC on by default
  community/examples/AMD/hpc-amd-slurm.yaml
  community/examples/hpc-slurm-chromedesktop.yaml
  community/examples/hpc-slurm-gromacs.yaml
  community/examples/hpc-slurm-legacy-sharedvpc.yaml
  community/examples/hpc-slurm-legacy.yaml
  community/examples/hpc-slurm-ramble-gromacs.yaml
  community/examples/hpc-slurm-ubuntu2004.yaml
  community/examples/hpc-slurm6.yaml
  community/examples/htc-slurm.yaml
  community/examples/intel/hpc-intel-select-slurm.yaml
  community/examples/intel/hpc-slurm-daos.yaml
  community/examples/quantum-circuit-simulator.yaml
  examples/cae/cae-slurm.yaml
  examples/hpc-slurm.yaml
  examples/image-builder.yaml
Labels: release-chore

#1967 Add the SC23 tutorial blueprint
  docs/tutorials/README.md
  docs/tutorials/sc23-tutorial/hcls-blueprint.yaml
Labels: documentation

#1956 Script run warning stage 2
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/pbspro-execution/README.md
  community/modules/compute/pbspro-execution/main.tf
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/main.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/pbspro-client/README.md
  community/modules/scheduler/pbspro-client/main.tf
  community/modules/scheduler/pbspro-server/README.md
  community/modules/scheduler/pbspro-server/main.tf
  community/modules/scripts/ramble-execute/README.md
  community/modules/scripts/ramble-execute/main.tf
  community/modules/scripts/ramble-setup/README.md
  community/modules/scripts/ramble-setup/main.tf
  community/modules/scripts/spack-execute/README.md
  community/modules/scripts/spack-execute/main.tf
  community/modules/scripts/spack-setup/README.md
  community/modules/scripts/spack-setup/main.tf
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/startup_from_network_storage.tf
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/startup_from_network_storage.tf
  modules/scheduler/batch-login-node/README.md
  modules/scheduler/batch-login-node/main.tf
  modules/scripts/startup-script/files/running-script-warning.sh
  modules/scripts/startup-script/files/startup-script-stdlib-head.sh
Labels: release-module-improvements

#1968 Add the SC23 tutorial blueprint
  docs/tutorials/README.md
  docs/tutorials/sc23-tutorial/hcls-blueprint.yaml
Labels: documentation, release-chore

#1933 Slurm6. Deprecate `enable_login`, only consider presence of `login_nodes`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-chore

#1972 Add native support for Google Cloud Storage with GKE
  community/examples/storage-gke.yaml
  community/modules/compute/gke-job-template/README.md
  community/modules/compute/gke-job-template/main.tf
  community/modules/compute/gke-job-template/templates/gke-job-base.yaml.tftpl
  community/modules/compute/gke-job-template/variables.tf
  community/modules/file-system/cloud-storage-bucket/README.md
  community/modules/file-system/cloud-storage-bucket/outputs.tf
  community/modules/file-system/gke-persistent-volume/README.md
  community/modules/file-system/gke-persistent-volume/main.tf
  community/modules/file-system/gke-persistent-volume/outputs.tf
  community/modules/file-system/gke-persistent-volume/templates/gcs-pv.yaml.tftpl
  community/modules/file-system/gke-persistent-volume/templates/gcs-pvc.yaml.tftpl
  community/modules/file-system/gke-persistent-volume/variables.tf
  community/modules/scheduler/gke-cluster/README.md
  community/modules/scheduler/gke-cluster/main.tf
  community/modules/scheduler/gke-cluster/outputs.tf
  community/modules/scheduler/gke-cluster/variables.tf
  community/modules/scheduler/gke-cluster/versions.tf
  examples/README.md
Labels: release-key-new-features

#1975 Slurm6. Surface `login_network_storage`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-chore

#1964 Selectevly suggest to run `ghpc export-outputs`
  pkg/shell/terraform.go
Labels: release-chore

#1974 Rename misleading `login group_name -> name_prefix`
  community/examples/hpc-slurm6-tpu.yaml
  community/examples/hpc-slurm6.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
Labels: release-chore

#1945 Slurm6. Enable support for CloudSQL
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
Labels: release-chore

#1849 Forces VMs to be replaced when placement policy is destroyed
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/main.tf
Labels: release-chore

#1977 Creation of script to check upcoming maintenance on nodes
  tools/maintenance/maintenance.py
Labels: release-improvements

#1984 Fix: variable takes structured data when set
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
Labels: release-chore

#1983 Add documentation how to use max_hops plugin
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
Labels: release-improvements

#1982 Add Zonal with lower capacity band support for filestore instance
  modules/file-system/filestore/README.md
  modules/file-system/filestore/variables.tf
Labels: release-improvements

#1985 Reduce usage of `log.Fatal` in tests, use `c.Fatal` instead
  pkg/deploymentio/local_test.go
  pkg/modulereader/resreader_test.go
  pkg/modulewriter/modulewriter_test.go
  pkg/sourcereader/embedded_test.go
  pkg/sourcereader/goget_test.go
Labels: release-chore

#1979 Implement Custom Logging
  cmd/create.go
  cmd/deploy.go
  cmd/expand.go
  cmd/root.go
  pkg/logging/logging.go
  pkg/modulereader/hcl_utils.go
  pkg/modulereader/packerreader.go
  pkg/modulereader/resreader.go
  pkg/shell/common.go
  pkg/shell/terraform.go
Labels: release-chore

#1987 Refactor `pkg/config` tests
  pkg/config/config_test.go
  pkg/config/expand_test.go
  pkg/config/validator_test.go
Labels: release-chore

#1990 Refactor `pkg/modulewriter` tests
  pkg/modulereader/hcl_utils_test.go
  pkg/modulereader/resreader_test.go
  pkg/modulewriter/modulewriter_test.go
Labels: release-chore

#1989 Remove usage of `log.Fatal` from non-tests files
  cmd/create.go
  cmd/root.go
  pkg/shell/common.go
  pkg/shell/terraform.go
Labels: release-chore

#1978 Front End Deployment Unique Bucket Name
  community/front-end/ofe/tf/main.tf
Labels: release-chore

#1981 Initial testing scripts with new folder for unittests
  .gitignore
  tests/__init__.py
  tests/test_maintenance.py
  tools/maintenance/maintenance.py
Labels: release-chore

#1988 Refactor `pkg/deploymentio` tests
  pkg/deploymentio/deploymentio_test.go
  pkg/deploymentio/local_test.go
Labels: release-chore

#1992 Front End go Version Updated
  community/front-end/ofe/infrastructure_files/gcs_bucket/webserver/startup.sh
Labels: release-chore, release-bugfix

#1994 Add `addlicense` pre-commit hook
  .pre-commit-config.yaml
  Makefile
  docs/module-guidelines.md
  tools/autodoc/addlicense.sh
  tools/cloud-build/hpc-toolkit-builder.yaml
  tools/cloud-build/hpc-toolkit-pr-validation.yaml
Labels: release-chore

#1991 Replace `Equals`-checker with more appropriate
  pkg/modulereader/resreader_test.go
  pkg/modulewriter/modulewriter_test.go
  pkg/sourcereader/sourcereader_test.go
Labels: release-chore

#1996 Add test to ensure that all modules have metada.yaml set
  modules/network/vpc/metadata.yaml
  pkg/inspect/modules_test.go
  pkg/modulereader/metadata.go
  pkg/modulereader/metadata_legacy.go
Labels: release-chore

#2002 Split `pkg/validators/validators.go` on multiple files.
  pkg/validators/cloud.go
  pkg/validators/semantic.go
  pkg/validators/validators.go
Labels: release-chore

#1997 Add modules metadata. Part 1 of 4
  community/modules/compute/SchedMD-slurm-on-gcp-partition/metadata.yaml
  community/modules/compute/htcondor-execute-point/metadata.yaml
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/metadata.yaml
  community/modules/compute/schedmd-slurm-gcp-v5-partition/metadata.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-partition/metadata.yaml
  community/modules/database/slurm-cloudsql-federation/metadata.yaml
  community/modules/file-system/nfs-server/metadata.yaml
  community/modules/project/service-enablement/metadata.yaml
  community/modules/scheduler/htcondor-central-manager/metadata.yaml
  community/modules/scripts/pbspro-install/metadata.yaml
  community/modules/scripts/ramble-execute/metadata.yaml
  community/modules/scripts/windows-startup-script/metadata.yaml
  modules/file-system/pre-existing-network-storage/metadata.yaml
  modules/monitoring/dashboard/metadata.yaml
  modules/network/pre-existing-vpc/metadata.yaml
  modules/scheduler/batch-job-template/metadata.yaml
  pkg/inspect/modules_test.go
Labels: release-chore

#1998 Add modules metadata. Part 2 of 4
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/metadata.yaml
  community/modules/project/new-project/metadata.yaml
  community/modules/project/service-account/metadata.yaml
  community/modules/scheduler/htcondor-access-point/metadata.yaml
  community/modules/scheduler/htcondor-pool-secrets/metadata.yaml
  community/modules/scheduler/pbspro-client/metadata.yaml
  community/modules/scheduler/pbspro-server/metadata.yaml
  community/modules/scripts/pbspro-qmgr/metadata.yaml
  community/modules/scripts/spack-setup/metadata.yaml
  modules/file-system/filestore/metadata.yaml
  pkg/inspect/modules_test.go
Labels: release-chore

#1999 Add modules metadata. Part 3 of 4
  community/modules/compute/gke-job-template/metadata.yaml
  community/modules/compute/pbspro-execution/metadata.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/metadata.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/metadata.yaml
  community/modules/file-system/cloud-storage-bucket/metadata.yaml
  community/modules/remote-desktop/chrome-remote-desktop/metadata.yaml
  community/modules/scheduler/htcondor-setup/metadata.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/metadata.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/metadata.yaml
  community/modules/scripts/htcondor-install/metadata.yaml
  community/modules/scripts/ramble-setup/metadata.yaml
  community/modules/scripts/wait-for-startup/metadata.yaml
  modules/scheduler/batch-login-node/metadata.yaml
  modules/scripts/startup-script/metadata.yaml
  pkg/inspect/modules_test.go
Labels: release-chore

#2000 Add modules metadata. Part 4 of 4
  community/modules/compute/gke-node-pool/metadata.yaml
  community/modules/file-system/DDN-EXAScaler/metadata.yaml
  community/modules/file-system/gke-persistent-volume/metadata.yaml
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/metadata.yaml
  community/modules/scheduler/SchedMD-slurm-on-gcp-login-node/metadata.yaml
  community/modules/scheduler/gke-cluster/metadata.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/metadata.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/metadata.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/metadata.yaml
  community/modules/scripts/omnia-install/metadata.yaml
  community/modules/scripts/pbspro-preinstall/metadata.yaml
  community/modules/scripts/spack-execute/metadata.yaml
  modules/compute/vm-instance/metadata.yaml
  modules/packer/custom-image/metadata.yaml
  pkg/inspect/modules_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/one/image/metadata.yaml
  tools/validate_configs/golden_copies/expectations/text_escape/zero/lime/metadata.yaml
Labels: release-chore

#2008 Fix qsim version in example to avoid new CMake changes
  community/examples/quantum-circuit-simulator.yaml
Labels: release-chore

#2006 `ghpc import-inputs`. Fix panic; refactor to meet `gocyclo` requirements
  pkg/config/expand.go
  pkg/config/expand_test.go
  pkg/shell/common.go
  pkg/shell/common_test.go
  pkg/shell/terraform.go
Labels: release-chore
