Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2023-09, with the labels that each got.

#1728 Bump slurm-gcp to 5.8.0 (from 5.7.6)
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/outputs.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
  docs/hybrid-slurm-cluster/demo-with-cloud-controller-instructions.md
  docs/hybrid-slurm-cluster/deploy-instructions.md
  docs/hybrid-slurm-cluster/on-prem-instructions.md
  docs/image-building.md
  examples/README.md
  tools/cloud-build/Dockerfile
  tools/validate_configs/test_configs/node-groups.yaml
Labels: release-module-improvements, release-version-updates

#1735 Update number of partitions
  examples/README.md
Labels: release-chore

#1736 Bump Slurm image version `5.7 -> 5.8`
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
Labels: release-chore

#1738 Static nodes in cluster partition via OFE
  community/front-end/ofe/infrastructure_files/gcs_bucket/webserver/startup.sh
  community/front-end/ofe/script/service_account.sh
  community/front-end/ofe/website/ghpcfe/cluster_manager/clusterinfo.py
  community/front-end/ofe/website/ghpcfe/forms.py
  community/front-end/ofe/website/ghpcfe/models.py
  community/front-end/ofe/website/ghpcfe/templates/cluster/detail.html
  community/front-end/ofe/website/ghpcfe/views/clusters.py
Labels: release-improvements

#1739 Update develop with release v1.22.1
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/remote-desktop/chrome-remote-desktop/scripts/configure-grid-drivers.yml
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-login-node/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/htcondor-setup/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#1740 Update release-candidate with release v1.22.1
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/remote-desktop/chrome-remote-desktop/scripts/configure-grid-drivers.yml
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-login-node/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/htcondor-setup/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#1742 Enable release integration test
  tools/cloud-build/provision/release-tests.tf
Labels: release-chore

#1732 Documenting Image Mechanics
  docs/vm-images.md
Labels: release-chore

#1734 Fix spack reference in HCLS blueprint.
  docs/videos/healthcare-and-life-sciences/hcls-blueprint.yaml
Labels: release-chore

#1745 Remove duplicate blueprint; See community/examples/hpc-slurm-chromedesktop.yaml
  docs/vm-images.md
  tools/validate_configs/os_compatibility_tests/slurm-crd.yaml
Labels: release-chore

#1741 Add check for `ghpc_role` label defintion
  community/modules/compute/SchedMD-slurm-on-gcp-partition/outputs.tf
  community/modules/compute/gke-job-template/main.tf
  community/modules/compute/gke-node-pool/main.tf
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/pbspro-execution/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/main.tf
  community/modules/database/slurm-cloudsql-federation/main.tf
  community/modules/file-system/DDN-EXAScaler/main.tf
  community/modules/file-system/cloud-storage-bucket/main.tf
  community/modules/file-system/gke-persistent-volume/main.tf
  community/modules/file-system/nfs-server/main.tf
  community/modules/project/new-project/main.tf
  community/modules/remote-desktop/chrome-remote-desktop/main.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/main.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-login-node/main.tf
  community/modules/scheduler/gke-cluster/main.tf
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/htcondor-pool-secrets/main.tf
  community/modules/scheduler/htcondor-setup/main.tf
  community/modules/scheduler/pbspro-client/main.tf
  community/modules/scheduler/pbspro-server/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
  community/modules/scripts/pbspro-preinstall/main.tf
  community/modules/scripts/spack-execute/main.tf
  community/modules/scripts/spack-setup/main.tf
  modules/compute/vm-instance/main.tf
  modules/file-system/filestore/main.tf
  modules/monitoring/dashboard/main.tf
  modules/scheduler/batch-job-template/main.tf
  modules/scheduler/batch-login-node/main.tf
  modules/scripts/startup-script/main.tf
  tools/label-check.py
Labels: release-chore

#1744 Refine Slurm CRD blueprint and rename deployment_name in test
  community/examples/hpc-slurm-chromedesktop.yaml
  tools/cloud-build/daily-tests/tests/hpc-slurm-chromedesktop.yml
Labels: release-chore

#1718 Slurm image checks and Documentation Updates
  README.md
  community/examples/AMD/hpc-amd-slurm.yaml
  community/examples/hpc-slurm-chromedesktop.yaml
  community/examples/hpc-slurm-ubuntu2004.yaml
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
  docs/hybrid-slurm-cluster/on-prem-instructions.md
  docs/vm-images.md
  examples/hpc-enterprise-slurm.yaml
  examples/image-builder.yaml
  examples/ml-slurm.yaml
  tools/cloud-build/daily-tests/blueprints/lustre-slurm.yaml
  tools/validate_configs/os_compatibility_tests/slurm-filestore.yaml
  tools/validate_configs/os_compatibility_tests/slurm-lustre.yaml
  tools/validate_configs/os_compatibility_tests/slurm-startup.yaml
  tools/validate_configs/test_configs/node-groups.yaml
  tools/validate_configs/test_configs/slurm-static-test.yaml
Labels: release-chore

#1752 Update instance image family to slurm-gcp-5-8 version
  community/examples/AMD/hpc-amd-slurm.yaml
  community/examples/hpc-slurm-ubuntu2004.yaml
  examples/hpc-enterprise-slurm.yaml
  examples/image-builder.yaml
  examples/ml-slurm.yaml
  tools/cloud-build/daily-tests/blueprints/lustre-slurm.yaml
  tools/validate_configs/os_compatibility_tests/slurm-filestore.yaml
  tools/validate_configs/os_compatibility_tests/slurm-lustre.yaml
  tools/validate_configs/os_compatibility_tests/slurm-startup.yaml
  tools/validate_configs/test_configs/node-groups.yaml
  tools/validate_configs/test_configs/slurm-static-test.yaml
Labels: release-chore

#1743 Create a helper tool to automate some of the steps of cleaning up a failed build
  tools/cleanup-build.py
Labels: release-chore

#1758 Exposed force_destroy to blueprints for cloud buckets
  community/modules/file-system/cloud-storage-bucket/README.md
  community/modules/file-system/cloud-storage-bucket/main.tf
  community/modules/file-system/cloud-storage-bucket/variables.tf
Labels: release-chore

#1756 Improve A3 VM family support
  community/modules/compute/htcondor-execute-point/gpu_definition.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/gpu_definition.tf
  modules/compute/vm-instance/gpu_definition.tf
Labels: release-module-improvements

#1755 HCLS IGC Update
  docs/videos/healthcare-and-life-sciences/README.md
  docs/videos/healthcare-and-life-sciences/hcls-blueprint.yaml
  docs/videos/healthcare-and-life-sciences/lysozyme-example/README.md
Labels: release-chore

#1764 Improve VPC documentation
  modules/network/vpc/README.md
  modules/network/vpc/outputs.tf
Labels: release-module-improvements

#1763 Improve pre-existing-vpc documentation
  modules/network/pre-existing-vpc/README.md
  modules/network/pre-existing-vpc/outputs.tf
  modules/network/pre-existing-vpc/variables.tf
Labels: release-module-improvements

#1766 Added bucket force_destroy variable to HCLS blueprint
  docs/videos/healthcare-and-life-sciences/README.md
  docs/videos/healthcare-and-life-sciences/hcls-blueprint.yaml
Labels: release-chore

#1759 Add native support for ephemeral storage to GKE modules
  community/examples/storage-gke.yaml
  community/modules/compute/gke-job-template/README.md
  community/modules/compute/gke-job-template/main.tf
  community/modules/compute/gke-job-template/templates/gke-job-base.yaml.tftpl
  community/modules/compute/gke-job-template/variables.tf
  examples/README.md
Labels: release-key-new-features

#1765 Add test for chrome-remote-desktop with Debian
  .gitignore
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/main.tf
  community/modules/remote-desktop/chrome-remote-desktop/variables.tf
  tools/cloud-build/babysit_tests.py
  tools/cloud-build/daily-tests/tests/chrome-remote-desktop.yml
  tools/validate_configs/test_configs/remote-desktop.yaml
Labels: release-chore

#1780 Merge v1.23.0 back to 'develop' as part of release process
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-login-node/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/htcondor-setup/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#1779 Add build test for Go 1.18
  tools/cloud-build/build-test-go1-18.yaml
  tools/cloud-build/provision/README.md
  tools/cloud-build/provision/pr-go1-18-build-test.tf
Labels: release-chore

#1781 Fix reference and name in Go1.18 build test provisioning.
  tools/cloud-build/provision/pr-go1-18-build-test.tf
Labels: release-chore

#1782 Update terraform provider version to v4.83.0
  pkg/modulewriter/tfversions.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
Labels: release-chore

#1783 Add support to update mount options for file store instance
  modules/file-system/filestore/README.md
  modules/file-system/filestore/main.tf
  modules/file-system/filestore/variables.tf
Labels: release-improvements

#1767 Move task Ensure all nodes are powered down to slurm integration test from partition test
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-partitions.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-hpc-centos7.yml
Labels: release-chore

#1784 Add validation `enable_placement -> !has(reservation_name)`
  community/modules/compute/schedmd-slurm-gcp-v5-partition/outputs.tf
Labels: release-chore

#1786 Do not allow null values for reservation names
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  tools/validate_configs/test_configs/node-groups.yaml
Labels: release-chore

#1768 Pin Spack version as tutorials were designed with previous version of Spack
  docs/tutorials/gromacs/spack-gromacs.yaml
  docs/tutorials/openfoam/spack-openfoam.yaml
  docs/tutorials/wrfv3/spack-wrfv3.yaml
Labels: release-chore

#1760 Guide user to solution when long family format
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
Labels: release-chore

#1793 Bumps cryptography from 41.0.3 to 41.0.4.
  community/front-end/ofe/requirements.txt
Labels: dependencies, python, release-chore

#1794 Additional changes for Slurm 5.9 release
  community/examples/AMD/hpc-amd-slurm.yaml
  community/examples/hpc-slurm-chromedesktop.yaml
  community/examples/hpc-slurm-ubuntu2004.yaml
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
  docs/hybrid-slurm-cluster/demo-with-cloud-controller-instructions.md
  docs/hybrid-slurm-cluster/deploy-instructions.md
  docs/hybrid-slurm-cluster/on-prem-instructions.md
  docs/image-building.md
  examples/README.md
  examples/hpc-enterprise-slurm.yaml
  examples/image-builder.yaml
  examples/ml-slurm.yaml
  tools/cloud-build/Dockerfile
  tools/cloud-build/daily-tests/blueprints/lustre-slurm.yaml
  tools/validate_configs/os_compatibility_tests/slurm-filestore.yaml
  tools/validate_configs/os_compatibility_tests/slurm-lustre.yaml
  tools/validate_configs/os_compatibility_tests/slurm-startup.yaml
  tools/validate_configs/test_configs/node-groups.yaml
  tools/validate_configs/test_configs/slurm-static-test.yaml
Labels: release-version-updates

#1796 Update hybrid instructions after manual testing
  docs/hybrid-slurm-cluster/blueprints/hybrid-configuration.yaml
  docs/hybrid-slurm-cluster/deploy-instructions.md
Labels: release-chore

#1797 Do not chmod spack installation unless user specifies mode
  community/modules/scripts/ramble-setup/templates/ramble_setup.yml.tftpl
  community/modules/scripts/spack-setup/README.md
  community/modules/scripts/spack-setup/main.tf
  community/modules/scripts/spack-setup/templates/spack_setup.yml.tftpl
  community/modules/scripts/spack-setup/variables.tf
Labels: release-chore

#1717 OFE Deployment test
  tools/cloud-build/daily-tests/ansible_playbooks/ofe-deployment-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-ofe-deployment.yml
  tools/cloud-build/daily-tests/builds/ofe-deployment.yaml
  tools/cloud-build/daily-tests/tests/ofe-deployment.yml
Labels: release-chore

#1798 Revert new settings for Slurm v5 login/controller
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
Labels: release-module-improvements
