Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2024-10, with the labels that each got.

#3082 Add clean up for TPUs
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/cleanup_tpu/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/cleanup_tpu/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/cleanup_tpu/scripts/cleanup_tpu.sh
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/cleanup_tpu/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/cleanup_tpu/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
Labels: release-chore

#3067 Extract `cty.Value` YAML logic from `Dict`.
  pkg/config/yaml.go
  pkg/config/yaml_test.go
Labels: release-chore

#3088 A3 High blueprint prolog solution updates
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-2-cluster.yaml
  examples/machine-learning/a3-highgpu-8g/v5-legacy/ml-slurm-a3-2-cluster-v5-legacy.yaml
Labels: release-bugfix

#3077 Update Toolkit release to v1.40.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3090 Update NeMo 23.11 to 24.07
  examples/machine-learning/a3-highgpu-8g/nemo-framework/README.md
  examples/machine-learning/a3-megagpu-8g/nemo-framework/Dockerfile
  examples/machine-learning/a3-megagpu-8g/nemo-framework/README.md
  examples/machine-learning/a3-megagpu-8g/nemo-framework/setup_nemo.sh
Labels: release-version-updates

#3054 Update Slurm 23.11.8 -> 24.05.3
  community/examples/AMD/hpc-amd-slurm.yaml
  community/examples/hpc-slurm-ubuntu2004.yaml
  community/examples/hpc-slurm6-apptainer.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
  examples/cae/cae-slurm.yaml
  examples/hpc-enterprise-slurm.yaml
  examples/hpc-slurm-static.yaml
  examples/image-builder.yaml
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
  examples/ml-slurm.yaml
  tools/cloud-build/daily-tests/blueprints/lustre-slurm.yaml
  tools/cloud-build/daily-tests/tests/slurm-v6-debian.yml
  tools/validate_configs/golden_copies/configs/versioned_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/terraform.tfvars
  tools/validate_configs/test_configs/node-groups.yaml
Labels: release-key-new-features

#3094 Increase resume-timeout for TPU partition in blueprint
  community/examples/hpc-slurm6-tpu.yaml
Labels: release-chore

#3079 Added compatibility check for GPUDirect and GKE version
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/gpu_direct.tf
  modules/compute/gke-node-pool/variables.tf
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/outputs.tf
  modules/scheduler/pre-existing-gke-cluster/README.md
  modules/scheduler/pre-existing-gke-cluster/outputs.tf
Labels: release-module-improvements

#3080 gke-topology-scheduler module implemented
  community/modules/compute/gke-topology-scheduler/README.md
  community/modules/compute/gke-topology-scheduler/main.tf
  community/modules/compute/gke-topology-scheduler/manifests/label-nodes-daemon.yaml
  community/modules/compute/gke-topology-scheduler/manifests/schedule-daemon.yaml
  community/modules/compute/gke-topology-scheduler/manifests/service-account.yaml
  community/modules/compute/gke-topology-scheduler/manifests/topology-scheduler-scripts.yaml
  community/modules/compute/gke-topology-scheduler/metadata.yaml
  community/modules/compute/gke-topology-scheduler/variables.tf
  community/modules/compute/gke-topology-scheduler/versions.tf
Labels: release-new-modules

#3092 Improve GitHub workflows configuration
  .github/workflows/pr-label-validation.yml
  .github/workflows/pr-precommit.yml
Labels: release-chore

#3098 Merge v1.40.0 release into develop branch
  cmd/root.go
  community/examples/hpc-slurm6-tpu.yaml
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-2-cluster.yaml
  examples/machine-learning/a3-highgpu-8g/nemo-framework/README.md
  examples/machine-learning/a3-highgpu-8g/v5-legacy/ml-slurm-a3-2-cluster-v5-legacy.yaml
  examples/machine-learning/a3-megagpu-8g/nemo-framework/Dockerfile
  examples/machine-learning/a3-megagpu-8g/nemo-framework/README.md
  examples/machine-learning/a3-megagpu-8g/nemo-framework/setup_nemo.sh
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3099 Adopt Google terraform provider plugin 5.44.*
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: release-chore

#3103 Do not trigger label validation on draft pull requests
  .github/workflows/pr-label-validation.yml
Labels: release-chore

#3101 SlurmGCP. Do not put job_submit script into config.
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/etc/job_submit.lua.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/job_submit.lua.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
Labels: release-chore

#3060 Provide explicit project information
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/network/private-service-access/README.md
  community/modules/network/private-service-access/main.tf
  community/modules/network/private-service-access/variables.tf
  modules/file-system/parallelstore/main.tf
Labels: release-bugfix

#3100 Batch BigQuery load of sacct data
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/load_bq.py
Labels: release-chore

#3093 Chrome Remote Desktop: increase resilience of apt operations
  community/modules/remote-desktop/chrome-remote-desktop/scripts/configure-chrome-desktop.yml
Labels: release-bugfix

#3096 Add preconditions for multi-host TPU deployments
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/outputs.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/variables.tf
Labels: release-chore

#3109 SlurmGCP `6.8.0 -> 6.8.1`
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
Labels: release-chore

#3106 Added warning for v5 Slurm deployments
  cmd/create.go
Labels: release-chore

#3112 Fix static-check.
  pkg/config/config.go
  pkg/config/errors.go
  pkg/config/expression.go
Labels: release-chore

#3104 Retry `wait-for-startup` script on internal error
  community/modules/scripts/wait-for-startup/scripts/wait-for-startup-status.sh
Labels: release-chore

#3117 Freeze slurm-gcp v5 hybrid blueprints with the latest cluster toolkit version support
  community/examples/tutorial-starccm-slurm.yaml
  docs/hybrid-slurm-cluster/blueprints/hybrid-configuration.yaml
Labels: release-deprecations

#3119 updating docs for v_blueprint feature
  examples/README.md
Labels: release-chore

#3121 Merge v1.40.1 fix from main to develop (fix issue that affected GKE blueprints from being provisioned)
  modules/network/multivpc/main.tf
Labels: release-chore

#3111 Support template file for kueue configuration in kubectl-apply module
  modules/management/kubectl-apply/README.md
  modules/management/kubectl-apply/main.tf
  modules/management/kubectl-apply/variables.tf
Labels: release-module-improvements

#3025 GKE A3 Mega Integration Test
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-job.yml
  tools/cloud-build/daily-tests/builds/gke-a3-megagpu.yaml
  tools/cloud-build/daily-tests/tests/gke-a3-megagpu.yml
Labels: release-chore

#3108 Implement xpk-gke-a3-megagpu blueprint
  community/examples/xpk-gke-a3-megagpu-files/config-map.yaml.tftpl
  community/examples/xpk-gke-a3-megagpu-files/kueue-xpk-configuration.yaml.tftpl
  community/examples/xpk-gke-a3-megagpu.yaml
  community/modules/compute/gke-topology-scheduler/manifests/schedule-daemon.yaml
  modules/compute/gke-node-pool/outputs.tf
  modules/compute/resource-policy/README.md
  modules/compute/resource-policy/main.tf
  modules/compute/resource-policy/metadata.yaml
  modules/compute/resource-policy/outputs.tf
  modules/compute/resource-policy/variables.tf
  modules/compute/resource-policy/versions.tf
Labels: release-module-improvements, release-improvements

#3126 Use sackd for the login nodes
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
Labels: release-module-improvements

#3085 inlude nccl test instruction in output for sample workload
  modules/compute/gke-node-pool/outputs.tf
Labels: release-chore

#3118 Update Slurm-gcp v5 deprecation details
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  examples/README.md
Labels: release-deprecations

#3130 Update A3-High NeMo to 24.07 and NCCL solution to latest recommended values
  examples/machine-learning/a3-highgpu-8g/nccl-tests/build-nccl-tests.sh
  examples/machine-learning/a3-highgpu-8g/nccl-tests/run-nccl-tests.sh
  examples/machine-learning/a3-highgpu-8g/nccl-tests/run-topological-nccl-tests.sh
  examples/machine-learning/a3-highgpu-8g/nemo-framework/Dockerfile
  examples/machine-learning/a3-highgpu-8g/nemo-framework/README.md
  examples/machine-learning/a3-highgpu-8g/nemo-framework/setup_nemo.sh
Labels: release-version-updates

#3123 Create and use non-default service accounts in GKE
  examples/gke-a3-highgpu.yaml
  examples/gke-a3-megagpu.yaml
  examples/hpc-gke.yaml
  examples/ml-gke.yaml
  examples/storage-gke.yaml
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  tools/cloud-build/daily-tests/blueprints/ml-gke-e2e.yaml
  tools/cloud-build/daily-tests/builds/gke-a3-megagpu.yaml
  tools/cloud-build/daily-tests/builds/gke-storage.yaml
  tools/cloud-build/daily-tests/builds/gke.yaml
  tools/cloud-build/daily-tests/builds/ml-gke-e2e.yaml
  tools/cloud-build/daily-tests/builds/ml-gke.yaml
Labels: release-improvements

#3029 Added documentation on cloud-ops-agent installation and stackdriver removal
  modules/scripts/startup-script/README.md
Labels: release-improvements

#3128 Remove mention of `./[community/]modules` from docs and examples
  community/examples/hpc-slurm-ramble-gromacs.yaml
  community/examples/hpc-slurm-ubuntu2004-v5-legacy.yaml
  community/examples/hpc-slurm-ubuntu2004.yaml
  community/examples/htc-slurm-v5-legacy.yaml
  community/examples/htc-slurm.yaml
  community/examples/tutorial-starccm-slurm.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  docs/hybrid-slurm-cluster/blueprints/create-networks.yaml
  docs/network_storage.md
  docs/tutorials/hpc-slurm-qwiklabs.yaml
  examples/README.md
  examples/hpc-enterprise-slurm-v5-legacy.yaml
  examples/hpc-enterprise-slurm.yaml
  examples/hpc-slurm-v5-legacy.yaml
  examples/hpc-slurm.yaml
  modules/README.md
  modules/scheduler/batch-job-template/README.md
  modules/scripts/startup-script/README.md
  pkg/config/config_test.go
  tools/cloud-build/daily-tests/validate_tests_metadata.py
  tools/validate_configs/golden_copies/configs/versioned_blueprint.yaml
  tools/validate_configs/test_configs/2-network-interfaces.yaml
  tools/validate_configs/test_configs/2filestore-4instances.yaml
  tools/validate_configs/test_configs/apt-collision.yaml
  tools/validate_configs/test_configs/centos8-ss.yaml
  tools/validate_configs/test_configs/cloud-batch-cft-instance-template.yaml
  tools/validate_configs/test_configs/debian-ss.yaml
  tools/validate_configs/test_configs/exascaler-existing-vpc.yaml
  tools/validate_configs/test_configs/exascaler-new-vpc.yaml
  tools/validate_configs/test_configs/gpu-v5-legacy.yaml
  tools/validate_configs/test_configs/gpu.yaml
  tools/validate_configs/test_configs/hpc-centos-ss.yaml
  tools/validate_configs/test_configs/instance-with-startup.yaml
  tools/validate_configs/test_configs/new_project.yaml
  tools/validate_configs/test_configs/nfs-servers.yaml
  tools/validate_configs/test_configs/rocky-ss.yaml
  tools/validate_configs/test_configs/simple-startup.yaml
  tools/validate_configs/test_configs/spack-buildcache.yaml
  tools/validate_configs/test_configs/spack-environments.yaml
  tools/validate_configs/test_configs/startup-options.yaml
  tools/validate_configs/test_configs/test_outputs.yaml
  tools/validate_configs/test_configs/threads_per_core.yaml
  tools/validate_configs/test_configs/timeout_test.yaml
  tools/validate_configs/test_configs/ubuntu-ss.yaml
  tools/validate_configs/test_configs/vm-instance-local-ssd.yaml
  tools/validate_configs/test_configs/vm.yaml
Labels: documentation, release-chore

#3122 improve dws_flex ux
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/outputs.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  docs/slurm-dws-flex.md
Labels: release-module-improvements

#3116 Update badge for slurm-gcp v5 and slurm-gcp v6
  examples/README.md
  modules/README.md
Labels: release-deprecations

#3133 Fix deprecation link and add deprecation notice in v5 compute modules
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
Labels: release-chore

#3132 Update Slurm-GCP to 6.8.2
  community/examples/hpc-build-slurm-image.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
  modules/README.md
Labels: release-version-updates

#3125 Add mount parallelstore service to mount parallelstore for every reboot
  modules/file-system/parallelstore/scripts/mount-daos.sh
  modules/file-system/pre-existing-network-storage/scripts/mount-daos.sh
Labels: release-bugfix

#3141 SlurmGCP. Improve reservation_name parsing logic + tests
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/common.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3136 Include deployment name in Spack and Ramble bucket names (like startup-script)
  community/modules/scripts/ramble-setup/main.tf
  community/modules/scripts/spack-setup/main.tf
Labels: release-module-improvements

#3124 GKE A3 high integration test
  tools/cloud-build/daily-tests/builds/gke-a3-highgpu.yaml
  tools/cloud-build/daily-tests/tests/gke-a3-highgpu.yml
Labels: release-chore

#3138 Share SA across node pools
  examples/storage-gke.yaml
  tools/cloud-build/daily-tests/blueprints/ml-gke-e2e.yaml
Labels: release-chore

#3143 SlurmGCP. Slurm reservation handling simplification
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3129 Ensure local SSD filesystem is assembled into a RAID even upon power off/on cycles
  modules/scripts/startup-script/files/setup-raid.yml
Labels: release-improvements

#3102 Use local paths to embedded modules throughout Toolkit
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/pbspro-execution/README.md
  community/modules/compute/pbspro-execution/main.tf
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/main.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/htcondor-service-accounts/README.md
  community/modules/scheduler/htcondor-service-accounts/main.tf
  community/modules/scheduler/htcondor-setup/README.md
  community/modules/scheduler/htcondor-setup/main.tf
  community/modules/scheduler/pbspro-client/README.md
  community/modules/scheduler/pbspro-client/main.tf
  community/modules/scheduler/pbspro-server/README.md
  community/modules/scheduler/pbspro-server/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scripts/ramble-execute/README.md
  community/modules/scripts/ramble-execute/main.tf
  community/modules/scripts/ramble-setup/README.md
  community/modules/scripts/ramble-setup/main.tf
  community/modules/scripts/spack-execute/README.md
  community/modules/scripts/spack-execute/main.tf
  community/modules/scripts/spack-setup/README.md
  community/modules/scripts/spack-setup/main.tf
  modules/network/multivpc/README.md
  modules/network/multivpc/main.tf
  modules/scheduler/batch-login-node/README.md
  modules/scheduler/batch-login-node/main.tf
  pkg/modulereader/resreader.go
  pkg/sourcereader/embedded.go
  pkg/sourcereader/embedded_test.go
Labels: release-improvements

#3139 Updating notebook module to use workbench_instance
  community/modules/compute/notebook/README.md
  community/modules/compute/notebook/main.tf
  community/modules/compute/notebook/variables.tf
Labels: release-module-improvements

#3154 Bump integration test to support Go 1.23
  tools/cloud-build/provision/pr-go-build-test.tf
Labels: release-version-updates

#3155 Update to Slurm images 6-8
  community/examples/AMD/hpc-amd-slurm.yaml
  community/examples/hpc-slurm-ubuntu2004.yaml
  community/examples/hpc-slurm6-apptainer.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
  examples/cae/cae-slurm.yaml
  examples/hpc-enterprise-slurm.yaml
  examples/hpc-slurm-static.yaml
  examples/image-builder.yaml
  examples/ml-slurm.yaml
  tools/cloud-build/daily-tests/blueprints/lustre-slurm.yaml
  tools/cloud-build/daily-tests/tests/slurm-v6-debian.yml
  tools/validate_configs/golden_copies/configs/versioned_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/terraform.tfvars
  tools/validate_configs/test_configs/node-groups.yaml
Labels: release-chore

#3150 Initial commit for new logging output
  modules/packer/custom-image/image.pkr.hcl
  tools/validate_configs/golden_copies/expectations/igc_pkr/one/image/image.pkr.hcl
  tools/validate_configs/golden_copies/expectations/text_escape/zero/lime/image.pkr.hcl
Labels: release-module-improvements

#3156 Bump go version 1.21 -> 1.22
  go.mod
Labels: release-version-updates

#3157 SlurmGCP. "All or nothing" bulk insert on requests with placements
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
Labels: release-module-improvements

#3162 Update version number to v1.41.0 as part of release process
  cmd/root.go
  community/examples/tutorial-starccm-slurm.yaml
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  docs/hybrid-slurm-cluster/blueprints/hybrid-configuration.yaml
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3151 Remove redundant provisioner for printing image name
  modules/packer/custom-image/image.pkr.hcl
  tools/validate_configs/golden_copies/expectations/igc_pkr/one/image/image.pkr.hcl
  tools/validate_configs/golden_copies/expectations/text_escape/zero/lime/image.pkr.hcl
Labels: release-module-improvements

#3164 Add direct Terraform support for Slurm SchedulerParameters and PrivateData
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-module-improvements

#3169 Merge main back to develop as part of release process
  cmd/root.go
  community/examples/tutorial-starccm-slurm.yaml
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  docs/hybrid-slurm-cluster/blueprints/hybrid-configuration.yaml
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3142 Add `use_job_duration` option
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/outputs.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/outputs.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  docs/slurm-dws-flex.md
Labels: release-chore

#3166 update vm-instance module to support TPG v6
  community/modules/compute/htcondor-execute-point/gpu_definition.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/gpu_definition.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/gpu_definition.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/gpu_definition.tf
  modules/compute/gke-node-pool/gpu_definition.tf
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/reservation_definitions.tf
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/gpu_definition.tf
  modules/compute/vm-instance/main.tf
  modules/compute/vm-instance/versions.tf
Labels: release-version-updates

#3171 Delete the new-project module to support adoption of TPG v6
  community/modules/project/new-project/README.md
  community/modules/project/new-project/main.tf
  community/modules/project/new-project/metadata.yaml
  community/modules/project/new-project/outputs.tf
  community/modules/project/new-project/variables.tf
  community/modules/project/new-project/versions.tf
  modules/README.md
  pkg/inspect/modules_test.go
  pkg/modulereader/metadata_legacy.go
  tools/validate_configs/test_configs/new_project.yaml
  tools/validate_configs/test_configs/test_outputs.yaml
Labels: release-deprecations

#3170 SlurmGCP. Relax `reservation_name` match, allow for suffix
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
Labels: release-chore

#3178 Revert "SlurmGCP. Relax `reservation_name` match, allow for suffix"
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
Labels: release-chore

#3172 Delete Daos Example Blueprints to support adoption of TPG v6
  community/examples/intel/README.md
  community/examples/intel/hpc-slurm-daos.yaml
  community/examples/intel/pfs-daos.yaml
  community/modules/file-system/Intel-DAOS/README.md
  docs/image-building.md
  examples/README.md
  examples/cae/cae-slurm-v5-legacy.yaml
  examples/cae/cae-slurm.yaml
  modules/README.md
  pkg/modulereader/metadata_legacy.go
Labels: release-deprecations, release-version-updates

#3160 Update IP address module within VPC module
  modules/network/vpc/README.md
  modules/network/vpc/main.tf
  modules/network/vpc/variables.tf
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/main.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/main.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/main.tf
Labels: release-version-updates

#3180 Revert "Revert "SlurmGCP. Relax reservation_name match, allow for suffix""
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
Labels: release-chore

#3140 increasing the tpg min version constraint to 5.44.2
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
  tools/validate_configs/test_configs/cloud-batch-cft-instance-template.yaml
Labels: release-chore

#3176 Update documentation on how to use shared vpc network using toolkit
  examples/README.md
  modules/network/pre-existing-vpc/README.md
Labels: release-chore

#3177 Refactor docker support in startup-script module
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/machine-learning/a3-highgpu-8g/v5-legacy/ml-slurm-a3-1-image-v5-legacy.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
  modules/scripts/startup-script/README.md
  modules/scripts/startup-script/main.tf
  modules/scripts/startup-script/variables.tf
Labels: release-chore

#3187 update Batch module to be compatible with TPG v6
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/main.tf
Labels: release-version-updates

#3186 update HTCondor modules to be compatible with TPG v6
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
Labels: release-version-updates

#3185 Update Slurm-GCP v5 to 5.12.1
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
  docs/hybrid-slurm-cluster/demo-with-cloud-controller-instructions.md
  docs/hybrid-slurm-cluster/deploy-instructions.md
  docs/hybrid-slurm-cluster/on-prem-instructions.md
  docs/image-building.md
  examples/README.md
  examples/machine-learning/a3-highgpu-8g/v5-legacy/README.md
  examples/machine-learning/a3-highgpu-8g/v5-legacy/ml-slurm-a3-1-image-v5-legacy.yaml
  modules/README.md
Labels: release-version-updates

#3198 Packer module README fix
  modules/packer/custom-image/README.md
Labels: release-chore

#3167 Packer Logging README update
  modules/packer/custom-image/README.md
Labels: release-chore

#3196 Update workload-identity submodule from v29 to v34
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
Labels: release-version-updates

#3193 Update default value for subnetwork_project to null
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
Labels: release-improvements
