Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2024-07, with the labels that each got.

#2731 Expose login and controller instance
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/outputs.tf
Labels: release-chore

#2728 Move GCESysPrep to provisioner in Windows scripts
  modules/packer/custom-image/image.pkr.hcl
  tools/validate_configs/golden_copies/expectations/igc_pkr/one/image/image.pkr.hcl
  tools/validate_configs/golden_copies/expectations/text_escape/zero/lime/image.pkr.hcl
Labels: release-bugfix

#2701 Add support for parallelstore in pre-existing-network-storage
  modules/file-system/pre-existing-network-storage/outputs.tf
  modules/file-system/pre-existing-network-storage/scripts/install-daos-client.sh
  modules/file-system/pre-existing-network-storage/scripts/mount-daos.sh
Labels: release-key-new-features

#2695 Add parallelstore module and support for rocky 8, ubuntu 22.04 and debian 12
  examples/README.md
  modules/README.md
  modules/file-system/parallelstore/README.md
  modules/file-system/parallelstore/main.tf
  modules/file-system/parallelstore/metadata.yaml
  modules/file-system/parallelstore/outputs.tf
  modules/file-system/parallelstore/scripts/install-daos-client.sh
  modules/file-system/parallelstore/scripts/mount-daos.sh
  modules/file-system/parallelstore/variables.tf
  modules/file-system/parallelstore/versions.tf
  tools/duplicate-diff.py
Labels: release-new-modules

#2696 Add `schedmd-slurm-gcp-v6-nodeset-dynamic` module
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/gpu_definition.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/metadata.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/outputs.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  modules/README.md
  tools/duplicate-diff.py
Labels: release-new-modules

#2734 Packer gcesysprep timeout fix
  modules/packer/custom-image/image.pkr.hcl
  tools/validate_configs/golden_copies/expectations/igc_pkr/one/image/image.pkr.hcl
  tools/validate_configs/golden_copies/expectations/text_escape/zero/lime/image.pkr.hcl
Labels: release-chore

#2737 Disable PBS Pro test
  tools/cloud-build/daily-tests/builds/pbspro.yaml
Labels: release-chore

#2738 Develop and adopt boot-time fix for EOL CentOS 7 repositories
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/startup_from_network_storage.tf
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/startup_from_network_storage.tf
  modules/scripts/startup-script/files/early_run_hotfixes.sh
  modules/scripts/startup-script/main.tf
  tools/cloud-build/daily-tests/blueprints/lustre-vm.yaml
  tools/validate_configs/os_compatibility_tests/vm-filestore.yaml
  tools/validate_configs/os_compatibility_tests/vm-lustre.yaml
Labels: release-key-new-features

#2719 Update network-storage interface to support runners and pass daos scripts during startup
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-chore

#2745 Fix hydration from GCS bucket if name is not provided
  modules/file-system/parallelstore/main.tf
Labels: release-chore

#2746 Remove `enable_devel` from examples
  community/examples/hpc-build-slurm-image.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-cluster.yaml
Labels: release-chore

#2744 Modify a3-highgpu-8g image-building blueprint network
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
Labels: release-bugfix

#2653 Update slurm-gcp module to use custom endpoints.
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-key-new-features

#2747 Update parameters for parallelstore module as per feedback
  modules/file-system/parallelstore/README.md
  modules/file-system/parallelstore/main.tf
  modules/file-system/parallelstore/outputs.tf
  modules/file-system/parallelstore/scripts/mount-daos.sh
  modules/file-system/parallelstore/variables.tf
  modules/file-system/pre-existing-network-storage/scripts/mount-daos.sh
Labels: release-chore

#2736 Gke optional accelerator
  community/modules/compute/gke-node-pool/README.md
  community/modules/compute/gke-node-pool/main.tf
  community/modules/compute/gke-node-pool/variables.tf
  examples/README.md
Labels: release-improvements

#2758 Move GKE Modules to Core
  examples/README.md
  examples/hpc-gke.yaml
  examples/ml-gke.yaml
  examples/storage-gke.yaml
  modules/README.md
  modules/compute/gke-job-template/README.md
  modules/compute/gke-job-template/main.tf
  modules/compute/gke-job-template/metadata.yaml
  modules/compute/gke-job-template/outputs.tf
  modules/compute/gke-job-template/templates/gke-job-base.yaml.tftpl
  modules/compute/gke-job-template/variables.tf
  modules/compute/gke-job-template/versions.tf
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/gpu_definition.tf
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/metadata.yaml
  modules/compute/gke-node-pool/outputs.tf
  modules/compute/gke-node-pool/threads_per_core_calc.tf
  modules/compute/gke-node-pool/variables.tf
  modules/compute/gke-node-pool/versions.tf
  modules/file-system/gke-persistent-volume/README.md
  modules/file-system/gke-persistent-volume/main.tf
  modules/file-system/gke-persistent-volume/metadata.yaml
  modules/file-system/gke-persistent-volume/outputs.tf
  modules/file-system/gke-persistent-volume/templates/filestore-pv.yaml.tftpl
  modules/file-system/gke-persistent-volume/templates/filestore-pvc.yaml.tftpl
  modules/file-system/gke-persistent-volume/templates/gcs-pv.yaml.tftpl
  modules/file-system/gke-persistent-volume/templates/gcs-pvc.yaml.tftpl
  modules/file-system/gke-persistent-volume/variables.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/metadata.yaml
  modules/scheduler/gke-cluster/outputs.tf
  modules/scheduler/gke-cluster/variables.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/README.md
  modules/scheduler/pre-existing-gke-cluster/main.tf
  modules/scheduler/pre-existing-gke-cluster/metadata.yaml
  modules/scheduler/pre-existing-gke-cluster/outputs.tf
  modules/scheduler/pre-existing-gke-cluster/variables.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  pkg/modulereader/metadata_legacy.go
  tools/cloud-build/daily-tests/builds/gke-storage.yaml
  tools/cloud-build/daily-tests/builds/gke.yaml
  tools/cloud-build/daily-tests/builds/ml-gke.yaml
  tools/cloud-build/daily-tests/tests/gke-storage.yml
  tools/cloud-build/daily-tests/tests/gke.yml
  tools/cloud-build/daily-tests/tests/ml-gke.yml
  tools/duplicate-diff.py
Labels: release-new-modules

#2759 Add terraform version to `ghpc --version`
  cmd/root.go
  pkg/shell/terraform.go
Labels: release-chore

#2739 Move `slurm_files` to the repo.
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/etc/cgroup.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/etc/job_submit.lua.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/etc/slurm.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/etc/slurmdbd.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/files/external_epilog.sh
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/files/external_prolog.sh
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/files/setup_external.sh
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/outputs.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/load_bq.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup_network_storage.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurm_gcp_plugins/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurm_gcp_plugins/__init__.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurm_gcp_plugins/max_hops/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurm_gcp_plugins/max_hops/__init__.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurm_gcp_plugins/test_plugin/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurm_gcp_plugins/test_plugin/__init__.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurm_gcp_plugins/utils/__init__.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/suspend.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_topology.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
Labels: release-module-improvements

#2765 Minor clean up of `slurm_files.bucket_dir`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
Labels: release-chore

#2761 Fix 'spot' and 'termination_action' variable passing in schedmd-slurm-gcp-v6-controller
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
Labels: release-chore

#2767 Revert "Minor clean up of `slurm_files.bucket_dir`"
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
Labels: release-chore

#2766 Fix slurm script tests
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/suspend.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#2769 Update test image to workaround CentOS end of life issues
  examples/serverless-batch-mpi.yaml
Labels: release-chore

#2763 Update A3 mega blueprint to use Slurm-GCP 6.5.12
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
Labels: release-improvements

#2770 Improve `pytest` flow
  .pytest.ini
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/common.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_topology.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_util.py
Labels: release-chore

#2772 Add validator for Terraform version and SlurmGCP6
  pkg/validators/adhoc.go
  pkg/validators/validators.go
  pkg/validators/validators_test.go
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/create_deployment_directory.yml
  tools/enforce_coverage.pl
  tools/validate_configs/validate_configs.sh
Labels: do-not-merge

#2773 Add `pytest` to pre-commit
  .github/workflows/pr-precommit.yml
  .pre-commit-config.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/requirements.txt
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/requirements.txt
Labels: release-chore

#2780 Update image to new centos image for both login and builder nodes
  examples/serverless-batch-mpi.yaml
Labels: release-bugfix

#2786 Merge `main` into `develop`
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
  examples/serverless-batch-mpi.yaml
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/parallelstore/README.md
  modules/file-system/parallelstore/main.tf
  modules/file-system/parallelstore/outputs.tf
  modules/file-system/parallelstore/scripts/mount-daos.sh
  modules/file-system/parallelstore/variables.tf
  modules/file-system/pre-existing-network-storage/scripts/mount-daos.sh
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
  pkg/validators/adhoc.go
  pkg/validators/validators.go
  pkg/validators/validators_test.go
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/create_deployment_directory.yml
  tools/enforce_coverage.pl
  tools/validate_configs/validate_configs.sh
Labels: release-chore

#2776 Stop using `DEFAULT` node definition
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/common.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_conf.py
Labels: release-chore

#2740 Add parallelstore slurm blueprint and documentation
  examples/README.md
  examples/pfs-parallelstore.yaml
  examples/ps-slurm.yaml
  modules/file-system/parallelstore/README.md
  modules/file-system/pre-existing-network-storage/README.md
  tools/cloud-build/daily-tests/builds/ps-slurm.yaml
  tools/cloud-build/daily-tests/tests/ps-slurm.yml
Labels: release-chore

#2787 Update internal usage of toolkit modules on develop to v1.36.0
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/pbspro-execution/README.md
  community/modules/compute/pbspro-execution/main.tf
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/main.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/htcondor-service-accounts/README.md
  community/modules/scheduler/htcondor-service-accounts/main.tf
  community/modules/scheduler/pbspro-client/README.md
  community/modules/scheduler/pbspro-client/main.tf
  community/modules/scheduler/pbspro-server/README.md
  community/modules/scheduler/pbspro-server/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scripts/ramble-execute/README.md
  community/modules/scripts/ramble-execute/main.tf
  community/modules/scripts/ramble-setup/README.md
  community/modules/scripts/ramble-setup/main.tf
  community/modules/scripts/spack-execute/README.md
  community/modules/scripts/spack-execute/main.tf
  community/modules/scripts/spack-setup/README.md
  community/modules/scripts/spack-setup/main.tf
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/startup_from_network_storage.tf
  modules/network/multivpc/README.md
  modules/network/multivpc/main.tf
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/startup_from_network_storage.tf
  modules/scheduler/batch-login-node/README.md
  modules/scheduler/batch-login-node/main.tf
Labels: release-chore

#2777 Simplify SlurmGCP logging
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/suspend.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#2793 Add "pretty" mode to babysitter
  tools/cloud-build/babysit/cli_ui.py
  tools/cloud-build/babysit/runner.py
Labels: release-chore

#2792 Limit `pytest` search space
  .pytest.ini
Labels: release-chore

#2798 Add more integration test for gke ml nodepool
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-ml-gke-e2e-validation.yml
  tools/cloud-build/daily-tests/blueprints/ml-gke-e2e.yaml
  tools/cloud-build/daily-tests/builds/ml-gke-e2e.yaml
  tools/cloud-build/daily-tests/tests/ml-gke-e2e.yml
Labels: release-chore, test-enhancement

#2790 Simplify SlurmGCP logging
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#2788 Compress `topology.conf`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_topology.py
Labels: release-chore

#2794 Fix cleanup compute for different versions of gcloud
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/cleanup.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/scripts/cleanup_compute.sh
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-module-improvements

#2789 Clean up SlurmGCP python importing
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/requirements.txt
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup_network_storage.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#2803 Update hpc-slurm6-apptainer.yaml
  community/examples/hpc-slurm6-apptainer.yaml
Labels: release-chore

#2800 Minor. Add test for `dict_to_conf`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_conf.py
Labels: release-chore

#2799 Update provider version to 5.38
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
Labels: release-chore

#2809 Remove `hyperdisk-extreme` from list of allowed boot disk_type
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
Labels: release-chore

#2764 Deprecate `enable_devel`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/common.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-deprecations

#2810 Fix construction of `cloud.conf`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/common.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-bugfix

#2811 add test for gke n2 pool with default driver
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-ml-gke-e2e-validation.yml
  tools/cloud-build/daily-tests/blueprints/ml-gke-e2e.yaml
Labels: release-improvements, test-enhancement

#2804 Tidy up Slurm config generation
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#2805 Update `topology.conf` during `slurmsync`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup_network_storage.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#2812 Hot fix to add defaults to cloud params
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/pre-existing-gke-cluster/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-bugfix

#2815 Fix computing md5 for devel tarball
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
Labels: release-chore

#2816 Update develop with v1.36.1 (and resolve conflict)
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2824 Update a3-highgpu-8g integration test
  tools/cloud-build/daily-tests/tests/ml-a3-highgpu-slurm-image.yml
Labels: release-chore

#2817 SlurmGCP. Fix broken `--trace-api` flag.
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-bugfix

#2818 change default disk_type for GKE nodepool to null
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/variables.tf
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-ml-gke-e2e-validation.yml
  tools/cloud-build/daily-tests/blueprints/ml-gke-e2e.yaml
Labels: release-module-improvements

#2819 SlurmGCP.setup don't take a `slurmd_feature` as an argument
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
Labels: release-chore

#2833 Babysit. Colorize output
  tools/cloud-build/babysit/cli_ui.py
  tools/cloud-build/babysit/runner.py
Labels: release-chore

#2831 Babysit. Use short URL if using `hpc-toolkit-dev`
  tools/cloud-build/babysit/cli_ui.py
  tools/cloud-build/babysit/runner.py
Labels: release-chore

#2791 SlurmGCP. Reduce `instanceProperties` overrides
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
Labels: release-chore

#2838 Also install the ghpc symlink to maintain parity
  Makefile
Labels: release-chore

#2720 Add local ssd RAID0 startup script
  modules/scripts/startup-script/README.md
  modules/scripts/startup-script/files/setup-raid.yml
  modules/scripts/startup-script/main.tf
  modules/scripts/startup-script/variables.tf
  modules/scripts/startup-script/versions.tf
Labels: release-key-new-features

#2834 Remove `tests` from devel archive
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
Labels: release-chore

#2825 Move `get_tpu_vmcount` into separate script
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/etc/job_submit.lua.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/get_tpu_vmcount.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#2847 Update workflows to reference cluster-toolkit
  .github/workflows/dependency-review.yml
  .github/workflows/pr-label-validation.yml
Labels: release-chore

#2849 Update documentation to reflect rebrand to Cluster Toolkit
  README.md
  community/front-end/ofe/docs/admin_guide.md
  docs/tutorials/fsi-montecarlo-on-batch/README.md
  docs/videos/healthcare-and-life-sciences/README.md
  docs/videos/healthcare-and-life-sciences/lysozyme-example/README.md
  examples/cae/README.md
  examples/machine-learning/a3-highgpu-8g/README.md
Labels: release-chore
