Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2024-05, with the labels that each got.

#2538 Revert #2351
  community/examples/AMD/hpc-amd-slurm-v6.yaml
  community/examples/hpc-slurm-gromacs.yaml
  community/examples/hpc-slurm-local-ssd-v6.yaml
  community/examples/hpc-slurm-ramble-gromacs-v6.yaml
  community/examples/hpc-slurm-sharedvpc.yaml
  community/examples/hpc-slurm-ubuntu2004-v6.yaml
  community/examples/hpc-slurm6-tpu-maxtext.yaml
  community/examples/hpc-slurm6-tpu.yaml
  community/examples/htc-slurm-v6.yaml
  community/examples/intel/hpc-slurm-daos.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/metadata.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
  docs/tutorials/gromacs/spack-gromacs.yaml
  docs/tutorials/hpc-slurm-qwiklabs.yaml
  docs/tutorials/openfoam/spack-openfoam.yaml
  docs/tutorials/wrfv3/spack-wrfv3.yaml
  examples/cae/cae-slurm-v6.yaml
  examples/hcls-blueprint-v6.yaml
  examples/hpc-enterprise-slurm-v6.yaml
  examples/hpc-slurm-static-v6.yaml
  examples/hpc-slurm-v6.yaml
  examples/image-builder-v6.yaml
  examples/ml-slurm-v6.yaml
  tools/cloud-build/daily-tests/blueprints/lustre-slurm-v6.yaml
  tools/validate_configs/test_configs/config-ssh.yaml
  tools/validate_configs/test_configs/gpu-v6.yaml
  tools/validate_configs/test_configs/hpc-cluster-simple-nfs-sql.yaml
  tools/validate_configs/test_configs/node-groups-v6.yaml
  tools/validate_configs/test_configs/slurm-gcp-v6-startup-scripts.yaml
  tools/validate_configs/test_configs/zone-policies-slurm-v6.yaml
Labels: release-chore

#2536 Add several missing APIs to HTCondor tutorial
  docs/tutorials/htcondor.md
Labels: release-chore

#2541 Slurm6. Fix order of clean up.
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/scripts/cleanup_compute.sh
Labels: release-chore

#2511 Adopt Slurm-GCP 6.4.6
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-module-improvements

#2530 Tests that use Filestore and VPC have a static name for the created VPC
  tools/cloud-build/daily-tests/tests/gke-storage.yml
  tools/cloud-build/daily-tests/tests/hcls-v6.yml
  tools/cloud-build/daily-tests/tests/hcls.yml
  tools/cloud-build/daily-tests/tests/hpc-enterprise-slurm-v6.yml
  tools/cloud-build/daily-tests/tests/hpc-slurm-chromedesktop.yml
  tools/cloud-build/daily-tests/tests/htc-slurm-v6.yml
  tools/cloud-build/daily-tests/tests/ml-slurm-v6.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-debian.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-hpc-centos7.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-rocky8.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-ubuntu.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-centos7.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-debian.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-rocky8.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-ssd.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-ubuntu.yml
  tools/cloud-build/daily-tests/tests/spack-gromacs.yml
Labels: release-chore

#2521 Update mentions of SlurmGCP-v6 `enable_cleanup_compute`.
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  examples/README.md
Labels: release-chore

#2542 Slurm6. Wait for controller destruction before doing clean up.
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-chore

#2522 Slurm6. Add support for nodeset `network_storage`
  community/examples/hpc-build-slurm-image.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  modules/README.md
  pkg/inspect/modules_test.go
Labels: release-module-improvements

#2524 Slurm tests. Don't "ensure all nodes are powered down" by default
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
  tools/cloud-build/daily-tests/tests/hcls.yml
  tools/cloud-build/daily-tests/tests/hpc-enterprise-slurm.yml
  tools/cloud-build/daily-tests/tests/hpc-slurm-chromedesktop.yml
  tools/cloud-build/daily-tests/tests/lustre-slurm.yml
  tools/cloud-build/daily-tests/tests/ml-slurm.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-debian.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-hpc-centos7.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-rocky8.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-startup-scripts.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-ubuntu.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-debian.yml
Labels: release-chore

#2551 Add documentation about how to use max-distance with Slurm v6
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
Labels: release-module-improvements

#2552 Prevent multiple instances of these tests because will fail due to static network name & multi-group fails to cleanup
  tools/cloud-build/daily-tests/builds/hcls-v6.yaml
  tools/cloud-build/daily-tests/builds/hcls.yaml
  tools/cloud-build/daily-tests/builds/ml-slurm-v6.yaml
Labels: release-chore

#2547 Babysit. Randomly choose next test to run.
  tools/cloud-build/babysit/core.py
Labels: release-chore

#2540 Remove `login` infix from instance name
  community/examples/AMD/hpc-amd-slurm-v6.yaml
  community/examples/hpc-slurm-gromacs.yaml
  community/examples/hpc-slurm-local-ssd-v6.yaml
  community/examples/hpc-slurm-ramble-gromacs-v6.yaml
  community/examples/hpc-slurm-sharedvpc.yaml
  community/examples/hpc-slurm-ubuntu2004-v6.yaml
  community/examples/hpc-slurm6-tpu-maxtext.yaml
  community/examples/hpc-slurm6-tpu.yaml
  community/examples/htc-slurm-v6.yaml
  community/examples/intel/hpc-slurm-daos.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/metadata.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
  docs/tutorials/gromacs/spack-gromacs.yaml
  docs/tutorials/hpc-slurm-qwiklabs.yaml
  docs/tutorials/openfoam/spack-openfoam.yaml
  docs/tutorials/wrfv3/spack-wrfv3.yaml
  examples/cae/cae-slurm-v6.yaml
  examples/hcls-blueprint-v6.yaml
  examples/hpc-enterprise-slurm-v6.yaml
  examples/hpc-slurm-static-v6.yaml
  examples/hpc-slurm-v6.yaml
  examples/image-builder-v6.yaml
  examples/ml-slurm-v6.yaml
  tools/cloud-build/daily-tests/blueprints/lustre-slurm-v6.yaml
  tools/cloud-build/daily-tests/tests/hcls-v6.yml
  tools/cloud-build/daily-tests/tests/hpc-enterprise-slurm-v6.yml
  tools/cloud-build/daily-tests/tests/htc-slurm-v6.yml
  tools/cloud-build/daily-tests/tests/lustre-slurm-v6.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-centos7.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-debian.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-rocky8.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-ssd.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-startup-scripts.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-tpu.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-ubuntu.yml
  tools/cloud-build/daily-tests/tests/spack-gromacs.yml
  tools/validate_configs/test_configs/config-ssh.yaml
  tools/validate_configs/test_configs/gpu-v6.yaml
  tools/validate_configs/test_configs/hpc-cluster-simple-nfs-sql.yaml
  tools/validate_configs/test_configs/node-groups-v6.yaml
  tools/validate_configs/test_configs/slurm-gcp-v6-startup-scripts.yaml
  tools/validate_configs/test_configs/zone-policies-slurm-v6.yaml
Labels: release-module-improvements

#2553 Remove `hpc-toolkit-builder` and its usage
  tools/cloud-build/Dockerfile
  tools/cloud-build/README.md
  tools/cloud-build/daily-tests/README.md
  tools/cloud-build/daily-tests/builds/hcls-v6.yaml
  tools/cloud-build/daily-tests/builds/ofe-deployment.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-static.yaml
  tools/cloud-build/hpc-toolkit-builder.yaml
  tools/cloud-build/images/ghpc-docker/Dockerfile
  tools/cloud-build/images/ghpc-docker/cloudbuild.yaml
  tools/cloud-build/pr-ofe.yaml
  tools/cloud-build/provision/README.md
  tools/cloud-build/provision/weekly_builder_image.tf
Labels: release-chore

#2545 Perfrom import of inputs during `destroy`
  cmd/destroy.go
Labels: release-chore

#2512 OFE: new features and fixes.
  community/front-end/ofe/deploy.sh
  community/front-end/ofe/infrastructure_files/gcs_bucket/webserver/startup.sh
  community/front-end/ofe/script/service_account.sh
  community/front-end/ofe/website/ghpcfe/cluster_manager/clusterinfo.py
  community/front-end/ofe/website/ghpcfe/cluster_manager/image.py
  community/front-end/ofe/website/ghpcfe/cluster_manager/image_import.py
  community/front-end/ofe/website/ghpcfe/forms.py
  community/front-end/ofe/website/ghpcfe/templates/cluster/update_form.html
  community/front-end/ofe/website/ghpcfe/templates/image/image-import.html
  community/front-end/ofe/website/ghpcfe/templates/image/list.html
  community/front-end/ofe/website/ghpcfe/urls.py
  community/front-end/ofe/website/ghpcfe/views/images.py
  community/front-end/ofe/website/nginx.conf
Labels: release-improvements

#2560 Fix `slurm-gcp-v6-static` test build config
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-static.yaml
Labels: release-chore

#2564 Explicitly set default emails for login/nodeset service account
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
Labels: release-chore

#2562 New output for private-service-access
  modules/file-system/filestore/README.md
  modules/file-system/filestore/main.tf
  modules/file-system/filestore/variables.tf
Labels: release-module-improvements

#2570 Syncing develop with changes on release candidate
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2569 Update to show example of the private-service-access in hpc-enterprise-slurm
  examples/hpc-enterprise-slurm-v6.yaml
  examples/hpc-enterprise-slurm.yaml
  tools/cloud-build/daily-tests/builds/hpc-enterprise-slurm-v6.yaml
  tools/cloud-build/daily-tests/builds/hpc-enterprise-slurm.yaml
Labels: release-chore

#2535 Roll TGP to v5.28.0
  community/modules/compute/gke-node-pool/README.md
  community/modules/compute/gke-node-pool/main.tf
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition/main.tf
  community/modules/scheduler/gke-cluster/README.md
  community/modules/scheduler/gke-cluster/main.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scripts/pbspro-preinstall/README.md
  community/modules/scripts/pbspro-preinstall/main.tf
  docs/image-building.md
  modules/file-system/filestore/README.md
  modules/file-system/filestore/versions.tf
  modules/network/vpc/README.md
  modules/network/vpc/main.tf
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/main.tf
  pkg/modulewriter/modulewriter_test.go
  pkg/modulewriter/tfwriter.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
Labels: release-key-new-features

#2571 Add integration test to build A3 image
  tools/cloud-build/daily-tests/builds/ml-a3-highgpu-slurm.yaml
  tools/cloud-build/daily-tests/tests/ml-a3-highgpu-slurm.yml
Labels: release-chore

#2563 OFE: fixing broken partitions update logic.
  community/front-end/ofe/website/ghpcfe/cluster_manager/clusterinfo.py
  community/front-end/ofe/website/ghpcfe/templates/blueprint/cloudsql_config.yaml.j2
  community/front-end/ofe/website/ghpcfe/templates/blueprint/cluster_config.yaml.j2
  community/front-end/ofe/website/ghpcfe/templates/blueprint/filesystem_config.yaml.j2
  community/front-end/ofe/website/ghpcfe/templates/blueprint/partition_config.yaml.j2
  community/front-end/ofe/website/ghpcfe/templates/cluster/update_form.html
  community/front-end/ofe/website/ghpcfe/urls.py
  community/front-end/ofe/website/ghpcfe/views/clusters.py
Labels: release-bugfix

#2516 Make batch job runnables a list instead of single string
  examples/serverless-batch-mpi.yaml
  examples/serverless-batch.yaml
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/main.tf
  modules/scheduler/batch-job-template/templates/batch-job-base.yaml.tftpl
  modules/scheduler/batch-job-template/variables.tf
Labels: release-module-improvements

#2500 Implement recovery of HTCondor spool (job queue)
  community/examples/htc-htcondor.yaml
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/files/htcondor_configure.yml
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-access-point/variables.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/htcondor-central-manager/variables.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
Labels: release-module-improvements

#2573 Update A3 blueprint guidance for reservations
  examples/machine-learning/README.md
  examples/machine-learning/ml-slurm-a3-2-cluster.yaml
Labels: release-improvements

#2579 Bump jinja2 from 3.1.3 to 3.1.4 in /community/front-end/ofe
  community/front-end/ofe/requirements.txt
Labels: release-chore

#2581 Eliminate resource naming collision in PBS Pro integration test
  tools/validate_configs/test_configs/pbs-unwrapped.yaml
Labels: release-chore

#2580 Revert private-service-access usage in Filestore examples
  examples/hpc-enterprise-slurm-v6.yaml
  examples/hpc-enterprise-slurm.yaml
  tools/cloud-build/daily-tests/builds/hpc-enterprise-slurm-v6.yaml
  tools/cloud-build/daily-tests/builds/hpc-enterprise-slurm.yaml
Labels: release-chore

#2558 Slurm6. Stop using SlurmGCP remote modules for partition and nodeset_dyn
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/outputs.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-module-improvements

#2567 Make Slurm-GCP v5 examples and references as legacy
  community/examples/AMD/hpc-amd-slurm-v5-legacy.yaml
  community/examples/hpc-slurm-chromedesktop-v5-legacy.yaml
  community/examples/hpc-slurm-local-ssd-v5-legacy.yaml
  community/examples/hpc-slurm-ubuntu2004-v5-legacy.yaml
  community/examples/htc-slurm-v5-legacy.yaml
  docs/videos/healthcare-and-life-sciences/README.md
  docs/videos/healthcare-and-life-sciences/hcls-blueprint-v5-legacy.yaml
  docs/vm-images.md
  examples/README.md
  examples/cae/cae-slurm-v5-legacy.yaml
  examples/hpc-enterprise-slurm-v5-legacy.yaml
  examples/hpc-slurm-v5-legacy.yaml
  examples/image-builder-v5-legacy.yaml
  examples/ml-slurm-v5-legacy.yaml
  tools/cloud-build/daily-tests/blueprints/lustre-slurm-v5-legacy.yaml
  tools/cloud-build/daily-tests/builds/hcls-v5-legacy.yaml
  tools/cloud-build/daily-tests/builds/hpc-enterprise-slurm-v5-legacy.yaml
  tools/cloud-build/daily-tests/builds/hpc-slurm-chromedesktop-v5-legacy.yaml
  tools/cloud-build/daily-tests/builds/lustre-slurm-v5-legacy.yaml
  tools/cloud-build/daily-tests/builds/ml-slurm-v5-legacy.yaml
  tools/cloud-build/daily-tests/builds/packer-v5-legacy.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-startup-scripts-v5-legacy.yaml
  tools/cloud-build/daily-tests/tests/hcls-v5-legacy.yml
  tools/cloud-build/daily-tests/tests/hpc-enterprise-slurm-v5-legacy.yml
  tools/cloud-build/daily-tests/tests/hpc-slurm-chromedesktop.yml
  tools/cloud-build/daily-tests/tests/lustre-slurm-v5-legacy.yml
  tools/cloud-build/daily-tests/tests/ml-slurm-v5-legacy.yml
  tools/cloud-build/daily-tests/tests/packer-v5-legacy.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-debian.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-hpc-centos7.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-rocky8.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-startup-scripts.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-ubuntu.yml
  tools/validate_configs/test_configs/README.md
  tools/validate_configs/test_configs/config-ssh-v5-legacy.yaml
  tools/validate_configs/test_configs/gpu-v5-legacy.yaml
  tools/validate_configs/test_configs/node-groups-v5-legacy.yaml
  tools/validate_configs/test_configs/slurm-gcp-v5-startup-scripts-v5-legacy.yaml
  tools/validate_configs/test_configs/slurm-static-test-v5-legacy.yaml
  tools/validate_configs/test_configs/zone-policies-slurm-v5-legacy.yaml
Labels: release-deprecations

#2557 Update documentation to recommend Slurm-GCP v6
  examples/README.md
Labels: release-chore

#2574 Fix: allow tasks_per_node to pass through as null
  modules/scheduler/batch-job-template/main.tf
Labels: release-chore

#2582 Private service access doc update
  community/modules/network/private-service-access/README.md
  modules/README.md
Labels: release-chore

#2586 `multivpc`. fix "NPE" in `replace`
  modules/network/multivpc/README.md
  modules/network/multivpc/variables.tf
Labels: release-chore

#2583 Add input type test for `additional_networks`
  pkg/inspect/modules_test.go
Labels: release-chore

#2543 Fix deployment of multiple Batch jobs
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/main.tf
  modules/scheduler/batch-job-template/metadata.yaml
  modules/scheduler/batch-job-template/variables.tf
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-batch-submission.yml
  tools/cloud-build/daily-tests/tests/batch-mpi.yml
  tools/cloud-build/daily-tests/tests/cloud-batch.yml
Labels: release-module-improvements

#2575 Proceed with destruction of other groups even if current failed
  cmd/destroy.go
Labels: release-improvements

#2585 Make slurm gcp v6 default
  community/examples/AMD/README.md
  community/examples/AMD/hpc-amd-slurm.yaml
  community/examples/hpc-slurm-local-ssd.yaml
  community/examples/hpc-slurm-ramble-gromacs.yaml
  community/examples/hpc-slurm-ubuntu2004.yaml
  community/examples/htc-slurm.yaml
  docs/videos/healthcare-and-life-sciences/README.md
  docs/vm-images.md
  examples/README.md
  examples/cae/cae-slurm.yaml
  examples/hcls-blueprint.yaml
  examples/hpc-enterprise-slurm.yaml
  examples/hpc-slurm-static.yaml
  examples/hpc-slurm.yaml
  examples/image-builder.yaml
  examples/ml-slurm.yaml
  tools/cloud-build/daily-tests/blueprints/lustre-slurm.yaml
  tools/cloud-build/daily-tests/builds/hcls.yaml
  tools/cloud-build/daily-tests/builds/hpc-enterprise-slurm.yaml
  tools/cloud-build/daily-tests/builds/htc-slurm.yaml
  tools/cloud-build/daily-tests/builds/lustre-slurm.yaml
  tools/cloud-build/daily-tests/builds/ml-slurm.yaml
  tools/cloud-build/daily-tests/builds/packer.yaml
  tools/cloud-build/daily-tests/tests/hcls.yml
  tools/cloud-build/daily-tests/tests/hpc-enterprise-slurm.yml
  tools/cloud-build/daily-tests/tests/htc-slurm.yml
  tools/cloud-build/daily-tests/tests/lustre-slurm.yml
  tools/cloud-build/daily-tests/tests/ml-slurm.yml
  tools/cloud-build/daily-tests/tests/packer.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-centos7.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-debian.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-rocky8.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-ssd.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-static.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-ubuntu.yml
  tools/validate_configs/test_configs/config-ssh.yaml
  tools/validate_configs/test_configs/gpu.yaml
  tools/validate_configs/test_configs/node-groups.yaml
  tools/validate_configs/test_configs/zone-policies-slurm.yaml
Labels: release-chore

#2590 Unify type of `additional_networks`
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  pkg/inspect/modules_test.go
  pkg/inspect/walk.go
Labels: release-chore

#2568 Add debugging output to spack and ramble installations
  community/modules/scripts/ramble-setup/templates/ramble_setup.yml.tftpl
  community/modules/scripts/spack-setup/templates/spack_setup.yml.tftpl
Labels: release-module-improvements

#2593 Babysit. Better interraption
  tools/cloud-build/babysit/runner.py
Labels: release-chore

#2589 Update default image in chrome-remote-desktop
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/scripts/configure-grid-drivers.yml
  community/modules/remote-desktop/chrome-remote-desktop/variables.tf
Labels: release-module-improvements

#2592 Dynamic nodeset fix broken input to `slurm_files`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
Labels: release-chore

#2565 Add blueprint to support Apptainer
  community/examples/hpc-slurm6-apptainer.yaml
  examples/README.md
Labels: documentation, release-improvements

#2601 Merge release v1.33.0 back onto development branch
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/scripts/configure-grid-drivers.yml
  community/modules/remote-desktop/chrome-remote-desktop/variables.tf
Labels: release-chore

#2595 Update Slurm-GCP v5 modules and examples to 5.11.1
  community/examples/AMD/hpc-amd-slurm-v5-legacy.yaml
  community/examples/hpc-slurm-chromedesktop-v5-legacy.yaml
  community/examples/hpc-slurm-ubuntu2004-v5-legacy.yaml
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
  docs/hybrid-slurm-cluster/demo-with-cloud-controller-instructions.md
  docs/hybrid-slurm-cluster/deploy-instructions.md
  docs/hybrid-slurm-cluster/on-prem-instructions.md
  docs/image-building.md
  examples/README.md
  examples/cae/cae-slurm-v5-legacy.yaml
  examples/hpc-enterprise-slurm-v5-legacy.yaml
  examples/image-builder-v5-legacy.yaml
  examples/machine-learning/README.md
  examples/machine-learning/ml-slurm-a3-1-image.yaml
  examples/ml-slurm-v5-legacy.yaml
  modules/README.md
  tools/cloud-build/daily-tests/blueprints/lustre-slurm-v5-legacy.yaml
  tools/cloud-build/daily-tests/tests/slurm-v5-debian.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-rocky8.yml
  tools/validate_configs/test_configs/node-groups-v5-legacy.yaml
  tools/validate_configs/test_configs/slurm-static-test-v5-legacy.yaml
Labels: release-version-updates

#2602 Adopt latest releases of internal modules
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/pbspro-execution/README.md
  community/modules/compute/pbspro-execution/main.tf
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/main.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/htcondor-service-accounts/README.md
  community/modules/scheduler/htcondor-service-accounts/main.tf
  community/modules/scheduler/pbspro-client/README.md
  community/modules/scheduler/pbspro-client/main.tf
  community/modules/scheduler/pbspro-server/README.md
  community/modules/scheduler/pbspro-server/main.tf
  community/modules/scripts/ramble-execute/README.md
  community/modules/scripts/ramble-execute/main.tf
  community/modules/scripts/ramble-setup/README.md
  community/modules/scripts/ramble-setup/main.tf
  community/modules/scripts/spack-execute/README.md
  community/modules/scripts/spack-execute/main.tf
  community/modules/scripts/spack-setup/README.md
  community/modules/scripts/spack-setup/main.tf
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/startup_from_network_storage.tf
  modules/network/multivpc/README.md
  modules/network/multivpc/main.tf
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/startup_from_network_storage.tf
  modules/scheduler/batch-login-node/README.md
  modules/scheduler/batch-login-node/main.tf
Labels: release-chore

#2594 Update Slurm-GCP v6 modules and examples to 6.5.2
  community/examples/AMD/hpc-amd-slurm.yaml
  community/examples/hpc-slurm-ubuntu2004.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
  examples/cae/cae-slurm.yaml
  examples/hpc-enterprise-slurm.yaml
  examples/hpc-slurm-static.yaml
  examples/image-builder.yaml
  examples/ml-slurm.yaml
  tools/cloud-build/daily-tests/blueprints/lustre-slurm.yaml
  tools/cloud-build/daily-tests/tests/slurm-v6-centos7.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-debian.yml
  tools/validate_configs/test_configs/node-groups.yaml
Labels: release-version-updates

#2588 Update Batch modules to use default gcloud version
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/variables.tf
  modules/scheduler/batch-login-node/README.md
  modules/scheduler/batch-login-node/variables.tf
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-batch-submission.yml
Labels: release-chore

#2584 Improve Private Service Access experience
  community/modules/network/private-service-access/README.md
  community/modules/network/private-service-access/outputs.tf
  modules/file-system/filestore/README.md
  modules/file-system/filestore/main.tf
  modules/file-system/filestore/variables.tf
Labels: release-chore

#2603 Adopt latest release of google Terraform providers
  pkg/modulewriter/modulewriter_test.go
  pkg/modulewriter/tfwriter.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
Labels: release-chore

#2604 Add instructions output to Slurm controller for SSH command
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/outputs.tf
Labels: release-chore

#2611 Better formatting for "deployment already exists" error
  cmd/create.go
  cmd/create_test.go
Labels: release-chore

#2607 Allow multiple static IPs for login nodes
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
Labels: release-chore

#2606 feat: Update database version variable in slurm-cloudsql-federation module
  community/modules/database/slurm-cloudsql-federation/README.md
  community/modules/database/slurm-cloudsql-federation/main.tf
  community/modules/database/slurm-cloudsql-federation/variables.tf
Labels: release-module-improvements

#2587 Don't destroy VPCs before `cleanup_compute` is done
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/cleanup.tf
Labels: release-chore

#2612 Allow only specific reservation for nodeset in slurm-gcp v6 nodeset
  community/examples/intel/README.md
  community/examples/intel/hpc-slurm-daos.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
Labels: release-bugfix

#2614 Allow specific reservation for node-group in slurm-gcp v5
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
Labels: release-bugfix

#2620 Document high level changes in Slurm GCP v6
  examples/README.md
Labels: release-version-updates

#2618 Update Slurm-GCP modules to v6.5.4
  community/examples/hpc-build-slurm-image.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  modules/README.md
Labels: release-version-updates

#2624 [dependabot] Update `requests` requirements for front-end
  community/front-end/ofe/requirements.txt
Labels: release-chore

#2627 Silence project-cleanup-slurm failure alert
  tools/cloud-build/provision/daily-cleanup.tf
Labels: release-chore

#2626 Update version number to v1.34.0 as part of release process
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2629 Use SocketsPerBoard instead of Socket in enterprise blueprint
  examples/hpc-enterprise-slurm.yaml
Labels: release-bugfix

#2636 Update develop with 1.34.0
  cmd/root.go
  community/examples/intel/README.md
  community/examples/intel/hpc-slurm-daos.yaml
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  examples/README.md
  examples/hpc-enterprise-slurm.yaml
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2638 Update internal usage of Toolkit modules to v1.34.0
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/pbspro-execution/README.md
  community/modules/compute/pbspro-execution/main.tf
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/main.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/htcondor-service-accounts/README.md
  community/modules/scheduler/htcondor-service-accounts/main.tf
  community/modules/scheduler/pbspro-client/README.md
  community/modules/scheduler/pbspro-client/main.tf
  community/modules/scheduler/pbspro-server/README.md
  community/modules/scheduler/pbspro-server/main.tf
  community/modules/scripts/ramble-execute/README.md
  community/modules/scripts/ramble-execute/main.tf
  community/modules/scripts/ramble-setup/README.md
  community/modules/scripts/ramble-setup/main.tf
  community/modules/scripts/spack-execute/README.md
  community/modules/scripts/spack-execute/main.tf
  community/modules/scripts/spack-setup/README.md
  community/modules/scripts/spack-setup/main.tf
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/startup_from_network_storage.tf
  modules/network/multivpc/README.md
  modules/network/multivpc/main.tf
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/startup_from_network_storage.tf
  modules/scheduler/batch-login-node/README.md
  modules/scheduler/batch-login-node/main.tf
Labels: release-chore

#2628 Simplify a3-highgpu-8g blueprint by adopting new Toolkit and Slurm-GCP features
  examples/machine-learning/ml-slurm-a3-1-image.yaml
Labels: release-chore

#2643 Add release-chore to initial release-candidate creation PR
  tools/create-release-candidate.sh
Labels: release-chore

#2639 Run pre-commit to validate PR in release-candidate branch
  .github/workflows/pr-precommit.yml
Labels: release-chore

#2642 Update Toolkit release to v1.34.1
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2648 Modify a3-highgpu-8g blueprint cluster blueprint network
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-2-cluster.yaml
Labels: release-bugfix

#2637 Initial commit of a3-megagpu-8g Slurm blueprint
  examples/machine-learning/a3-megagpu-8g/README.md
  examples/machine-learning/a3-megagpu-8g/deployment-base.yaml
  examples/machine-learning/a3-megagpu-8g/deployment-image-cluster.yaml
  examples/machine-learning/a3-megagpu-8g/nccl-tests/README
  examples/machine-learning/a3-megagpu-8g/nccl-tests/build-nccl-tests.sh
  examples/machine-learning/a3-megagpu-8g/nccl-tests/import_pytorch_container.sh
  examples/machine-learning/a3-megagpu-8g/nccl-tests/run-nccl-tests.sh
  examples/machine-learning/a3-megagpu-8g/nemo-framework/Dockerfile
  examples/machine-learning/a3-megagpu-8g/nemo-framework/README.md
  examples/machine-learning/a3-megagpu-8g/nemo-framework/setup_nemo.sh
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-base.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-cluster.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
  tools/cloud-build/daily-tests/builds/ml-a3-megagpu-slurm.yaml
  tools/cloud-build/daily-tests/tests/ml-a3-megagpu-slurm-image.yml
  tools/validate_configs/validate_configs.sh
Labels: release-key-new-features

#2651 Bump max Terraform google/google-beta providers to 5.31.x
  pkg/modulewriter/modulewriter_test.go
  pkg/modulewriter/tfwriter.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
Labels: release-chore

#2652 Fix a3-highgpu-8g blueprint in integration test
  tools/cloud-build/daily-tests/tests/ml-a3-highgpu-slurm-image.yml
Labels: release-chore

#2615 NFS export options for Filestore
  modules/file-system/filestore/README.md
  modules/file-system/filestore/main.tf
  modules/file-system/filestore/variables.tf
Labels: release-module-improvements

#2654 Fix a3-highgpu-8g blueprint in cluster integration test.
  tools/cloud-build/daily-tests/tests/ml-a3-highgpu-slurm-cluster.yml
Labels: release-chore

#2633 Add option to specify address range for psa
  community/modules/network/private-service-access/README.md
  community/modules/network/private-service-access/main.tf
  community/modules/network/private-service-access/variables.tf
Labels: release-module-improvements

#2656 Update develop branch with change to A3 Mega documentation
  examples/machine-learning/a3-megagpu-8g/README.md
Labels: release-chore
