Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2024-12, with the labels that each got.

#3319 Add dynamic setup of gpu_limit in gke-job-template module
  modules/compute/gke-job-template/README.md
  modules/compute/gke-job-template/main.tf
  modules/compute/gke-job-template/variables.tf
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/outputs.tf
  tools/cloud-build/daily-tests/blueprints/ml-gke-e2e.yaml
Labels: release-module-improvements

#3295 Update custom TAS scripts to support A3U
  community/modules/compute/gke-topology-scheduler/manifests/label-nodes-daemon.yaml
  community/modules/compute/gke-topology-scheduler/manifests/schedule-daemon.yaml
  community/modules/compute/gke-topology-scheduler/manifests/topology-scheduler-scripts.yaml
Labels: release-improvements

#3303 Simplify providing additional_networks for Slurm nodesets
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
Labels: release-chore

#3331 Refactor Python Integration Test Script
  tools/python-integration-tests/blueprints/slurm-simple-reconfig.yaml
  tools/python-integration-tests/blueprints/slurm-simple.yaml
  tools/python-integration-tests/blueprints/topology-test.yaml
  tools/python-integration-tests/deployment.py
  tools/python-integration-tests/slurm_reconfig_size.py
  tools/python-integration-tests/slurm_simple_job_completion.py
  tools/python-integration-tests/slurm_topology.py
  tools/python-integration-tests/ssh.py
  tools/python-integration-tests/test.py
Labels: release-chore

#3336 Updating Slurm-GCP to 6.8.6
  community/examples/hpc-build-slurm-image.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
  modules/README.md
Labels: release-chore

#3332 SlurmGCP. Refactor instance grouping
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/get_tpu_vmcount.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurm_gcp_plugins/__init__.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurm_gcp_plugins/test_plugin/__init__.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/common.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3339 integrate tas plugin bug fixes
  community/modules/compute/gke-topology-scheduler/manifests/topology-scheduler-scripts.yaml
Labels: release-improvements

#3335 Add Python Integration Test Build Files
  tools/python-integration-tests/builds/slurm_reconfig_size.yaml
  tools/python-integration-tests/builds/slurm_simple_job_completion.yaml
  tools/python-integration-tests/builds/slurm_topology.yaml
  tools/python-integration-tests/ssh.py
  tools/python-integration-tests/test.py
Labels: release-chore

#3344 Revert "integrate tas plugin bug fixes"
  community/modules/compute/gke-topology-scheduler/manifests/topology-scheduler-scripts.yaml
Labels: release-module-improvements

#3346 Add python test build files to daily-tests
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-reconfig-size.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-simple-job-completion.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-topology.yaml
  tools/cloud-build/daily-tests/validate_tests_metadata.py
  tools/cloud-build/images/test-runner/Dockerfile
Labels: release-chore

#3340 SlurmGCP. Improve `resume.py` performance for job arrays.
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/common.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_resume.py
Labels: release-chore

#3338 Add NodeAction classes to subsitute NodeStatus Enum
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3345 Update A3 High integration test with new base image
  tools/cloud-build/daily-tests/tests/ml-a3-highgpu-slurm-image-legacy.yml
  tools/cloud-build/daily-tests/tests/ml-a3-highgpu-slurm-image.yml
Labels: release-chore

#3347 SlurmGCP. Use generated placement policies with dense reservations.
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3256 Add multi-mount parallelstore support
  modules/file-system/parallelstore/scripts/mount-daos.sh
  modules/file-system/pre-existing-network-storage/scripts/mount-daos.sh
Labels: release-improvements

#3341 Add change to conditionally perform pip install based on gke_node_pool machine_type
  modules/compute/gke-node-pool/main.tf
Labels: release-module-improvements

#3356 update terraform provider to 6.12.0
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: release-key-new-features

#3360 Use relative path for remaining use of startup-script module
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/startup_from_network_storage.tf
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/startup_from_network_storage.tf
Labels: release-chore

#3227 Add future reservation support
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/outputs.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-module-improvements

#3354 SlurmGCP. Improve non-exclusive placement alloaction
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/common.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3363 Add TTL to SSH key
  tools/python-integration-tests/ssh.py
Labels: release-chore

#3357 Update gke-cluster module addon-config for enabling parallelstrore csi driver
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/versions.tf
Labels: release-module-improvements

#3367 Update terraform provider to 6.13.0
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: release-key-new-features

#3368 Update pinned provider in A3 Ultra preview Slurm blueprint
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
Labels: release-chore

#3369 Fix node_is_fr to handle empty string instead
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3373 Update image-builder.yaml link in README
  examples/README.md
Labels: release-improvements

#3359 make upgrade settings configurable
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/variables.tf
Labels: release-module-improvements

#3188 Standardizing the network naming for the integration tests
  tools/cloud-build/daily-tests/tests/gke-a3-highgpu.yml
  tools/cloud-build/daily-tests/tests/gke-a3-megagpu.yml
  tools/cloud-build/daily-tests/tests/gke-storage.yml
  tools/cloud-build/daily-tests/tests/hcls-v5-legacy.yml
  tools/cloud-build/daily-tests/tests/hpc-enterprise-slurm.yml
  tools/cloud-build/daily-tests/tests/hpc-slurm-chromedesktop.yml
  tools/cloud-build/daily-tests/tests/htc-slurm.yml
  tools/cloud-build/daily-tests/tests/ml-slurm.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-debian.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-hpc-centos7.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-rocky8.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-ubuntu.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-debian.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-rocky8.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-ssd.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-ubuntu.yml
  tools/cloud-build/daily-tests/tests/spack-gromacs.yml
Labels: release-chore

#3370 Add NCCL plugin installation to A3 Ultra Slurm blueprint
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
Labels: release-chore

#3288 Promote the new nic-types in vm-instance
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/variables.tf
  modules/compute/vm-instance/versions.tf
Labels: release-version-updates

#3348 Address Parallelstore feature gaps
  modules/file-system/parallelstore/scripts/install-daos-client.sh
  modules/file-system/parallelstore/scripts/mount-daos.sh
  modules/file-system/pre-existing-network-storage/scripts/install-daos-client.sh
  modules/file-system/pre-existing-network-storage/scripts/mount-daos.sh
Labels: release-chore

#3380 Migrate `instance_template` modules from `slurm-gcp` repo
  .pre-commit-config.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/main.tf
  community/modules/internal/slurm-gcp-v6/instance_template/README.md
  community/modules/internal/slurm-gcp-v6/instance_template/files/startup_sh_unlinted
  community/modules/internal/slurm-gcp-v6/instance_template/main.tf
  community/modules/internal/slurm-gcp-v6/instance_template/outputs.tf
  community/modules/internal/slurm-gcp-v6/instance_template/variables.tf
  community/modules/internal/slurm-gcp-v6/instance_template/versions.tf
  community/modules/internal/slurm-gcp-v6/internal_instance_template/README.md
  community/modules/internal/slurm-gcp-v6/internal_instance_template/main.tf
  community/modules/internal/slurm-gcp-v6/internal_instance_template/outputs.tf
  community/modules/internal/slurm-gcp-v6/internal_instance_template/variables.tf
  community/modules/internal/slurm-gcp-v6/internal_instance_template/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  pkg/inspect/modules_test.go
Labels: release-chore

#3383 skip setting disk_labels if disk_type is local-ssd
  community/modules/internal/slurm-gcp-v6/internal_instance_template/main.tf
Labels: release-chore

#3365 Add Future Reservation guide
  docs/slurm-dws-calendar.md
Labels: documentation, release-chore

#3381 Update to ensure that gpu-test is compatible with H200 and H100s
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tools/gpu-test
Labels: release-chore

#3364 Set 'enable_private_endpoint' to false
  community/examples/xpk-gke-a3-megagpu.yaml
Labels: release-bugfix

#3322 GKE clusters can now be duplicated by changing only the deployment name
  community/examples/xpk-gke-a3-megagpu.yaml
  examples/gke-a3-highgpu.yaml
  examples/gke-a3-megagpu.yaml
  examples/gke-storage-parallelstore.yaml
  examples/hpc-gke.yaml
  examples/ml-gke.yaml
  examples/storage-gke.yaml
  modules/network/vpc/README.md
  modules/network/vpc/main.tf
  modules/network/vpc/variables.tf
  tools/cloud-build/daily-tests/blueprints/gke-a2-highgpu.yaml
  tools/cloud-build/daily-tests/blueprints/ml-gke-e2e.yaml
Labels: release-key-new-features

#3342 Update OpenFOAM tutorial
  docs/tutorials/openfoam/README.md
  docs/tutorials/openfoam/spack-openfoam.md
  docs/tutorials/openfoam/spack-openfoam.yaml
Labels: release-improvements

#3388 gke v1.31 added to acceptable list for a3-mega
  modules/compute/gke-node-pool/gpu_direct.tf
Labels: release-module-improvements

#3372 Add example NCCL tests for a3-ultra Slurm via pyxis/enroot
  examples/machine-learning/a3-ultragpu-8g/nccl-tests/README.md
  examples/machine-learning/a3-ultragpu-8g/nccl-tests/build-nccl-tests.sh
  examples/machine-learning/a3-ultragpu-8g/nccl-tests/import_pytorch_container.sh
  examples/machine-learning/a3-ultragpu-8g/nccl-tests/run-nccl-tests.sh
Labels: release-chore

#3361 Update python tests to throw errors
  tools/python-integration-tests/slurm_reconfig_size.py
  tools/python-integration-tests/slurm_simple_job_completion.py
  tools/python-integration-tests/slurm_topology.py
  tools/python-integration-tests/ssh.py
  tools/python-integration-tests/test.py
Labels: release-chore

#3387 Adding network_profile to the VPC modules
  modules/network/multivpc/README.md
  modules/network/multivpc/main.tf
  modules/network/multivpc/variables.tf
  modules/network/vpc/README.md
  modules/network/vpc/main.tf
  modules/network/vpc/variables.tf
Labels: release-module-improvements

#3394 Merge main back to develop
  community/front-end/ofe/requirements.txt
Labels: release-chore

#3396 TopologyAwareScheduling enabled by default for Kueue v0.9.1
  modules/management/kubectl-apply/manifests/kueue-v0.9.1.yaml
Labels: release-module-improvements

#3390 Migrate `_slurm_instance` and `slurm_tpu_nodeset` modules from `slurm-gcp` repo
  community/modules/internal/slurm-gcp-v6/instance/README.md
  community/modules/internal/slurm-gcp-v6/instance/main.tf
  community/modules/internal/slurm-gcp-v6/instance/outputs.tf
  community/modules/internal/slurm-gcp-v6/instance/variables.tf
  community/modules/internal/slurm-gcp-v6/instance/versions.tf
  community/modules/internal/slurm-gcp-v6/nodeset_tpu/README.md
  community/modules/internal/slurm-gcp-v6/nodeset_tpu/main.tf
  community/modules/internal/slurm-gcp-v6/nodeset_tpu/outputs.tf
  community/modules/internal/slurm-gcp-v6/nodeset_tpu/variables.tf
  community/modules/internal/slurm-gcp-v6/nodeset_tpu/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
Labels: release-chore

#3398 SlurmGCP. Fix warning around `file_cache`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3397 SlurmGCP. Replace `to_hostlist` with `to_hostlist_fast`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/suspend.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3384 Slurmsync. Safeguard against nodes missing from Slurm state.
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/common.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3392 Expose cluster deletion protection
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/variables.tf
Labels: release-module-improvements

#3399 Update Toolkit release to v1.44.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3404 Fix misusage of `groupby_unsorted`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/suspend.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3400 SlurmGCP. Remove redundant terraform from newly migrated modules
  community/modules/internal/slurm-gcp-v6/instance/README.md
  community/modules/internal/slurm-gcp-v6/instance/main.tf
  community/modules/internal/slurm-gcp-v6/instance/variables.tf
  community/modules/internal/slurm-gcp-v6/instance/versions.tf
  community/modules/internal/slurm-gcp-v6/instance_template/README.md
  community/modules/internal/slurm-gcp-v6/instance_template/main.tf
  community/modules/internal/slurm-gcp-v6/instance_template/variables.tf
  community/modules/internal/slurm-gcp-v6/internal_instance_template/README.md
  community/modules/internal/slurm-gcp-v6/internal_instance_template/main.tf
  community/modules/internal/slurm-gcp-v6/internal_instance_template/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
Labels: release-chore

#3408 SlurmGCP. Reduce usage of `NSDict`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
Labels: release-chore

#3420 Fix clean_up placement policy bug
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
Labels: release-chore

#3417 Integrating kueue v0.10.0 to enable TAS with rank ordering support
  modules/management/kubectl-apply/manifests/kueue-v0.10.0.yaml
  modules/management/kubectl-apply/variables.tf
  tools/cloud-build/daily-tests/blueprints/gke-a2-highgpu.yaml
Labels: release-key-new-features

#3377 a test PR
  modules/README.md
Labels: release-chore

#3424 Enable reservations support for kueue integration tests
  tools/cloud-build/daily-tests/blueprints/gke-a2-highgpu.yaml
  tools/cloud-build/daily-tests/tests/gke-a2-highgpu-kueue.yml
Labels: release-improvements

#3416 Adding integration test for ansible OS coverage
  modules/scripts/startup-script/files/install_ansible.sh
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-ansible-vm.yml
  tools/cloud-build/daily-tests/blueprints/ansible-vm.yaml
  tools/cloud-build/daily-tests/builds/ansible-vm.yaml
  tools/cloud-build/daily-tests/tests/ansible-vm.yml
Labels: release-chore

#3421 Update terraform provider from google-beta to google for parallelstore
  modules/file-system/parallelstore/README.md
  modules/file-system/parallelstore/main.tf
  modules/file-system/parallelstore/versions.tf
Labels: release-chore

#3402 SlurmGCP. Move TPU code into separate file + refactoring
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/get_tpu_vmcount.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/suspend.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_topology.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tpu.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3414 Move a3u blueprints to develop branch
  examples/gke-a3-ultragpu/README.md
  examples/gke-a3-ultragpu/gke-a3-ultragpu-deployment.yaml
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  examples/gke-a3-ultragpu/mglru-disable.yaml
  examples/gke-a3-ultragpu/nccl-installer.yaml
  examples/gke-a3-ultragpu/nccl-jobset-example.yaml
  examples/gke-a3-ultragpu/nccl-test-32-node.yaml
  examples/gke-a3-ultragpu/nccl-test.yaml
  tools/validate_configs/validate_configs.sh
Labels: release-chore

#3407 Use dataclass to represent machine type
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/common.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3405 SlurmGCP. Don't query insert-ops if builkInsert-op is totally successful
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
Labels: release-chore

#3429 Add terraform setup to github workflow config
  .github/workflows/pr-precommit.yml
Labels: bug, release-chore

#3426 Add validation to prevent creation of empty nodesets
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/outputs.tf
Labels: release-chore

#3425 Update Kueue TAS Test Definition and add Kueue v0.10.0 toleration
  modules/management/kubectl-apply/manifests/kueue-v0.10.0.yaml
  tools/cloud-build/daily-tests/blueprints/kueue-config-files/tas-queues.yaml
Labels: release-improvements, release-bugfix

#3409 Update README with GKE parallelstore related example blueprint details
  examples/README.md
  examples/gke-storage-managed-parallelstore.yaml
  modules/file-system/gke-storage/README.md
  tools/cloud-build/daily-tests/builds/gke-storage-managed-parallelstore.yaml
  tools/cloud-build/daily-tests/tests/gke-storage-managed-parallelstore.yml
Labels: documentation, release-improvements

#3432 Fix GKE parallelstore blueprint name going beyond network char limit
  examples/README.md
  examples/gke-managed-parallelstore.yaml
  modules/file-system/gke-storage/README.md
  tools/cloud-build/daily-tests/builds/gke-managed-parallelstore.yaml
  tools/cloud-build/daily-tests/tests/gke-managed-parallelstore.yml
Labels: release-bugfix

#3433 Updated ansible playbook test file name
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-managed-parallelstore.yml
Labels: release-bugfix

#3434 [Cherry Pick] Making upgrade settings configurable
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/variables.tf
Labels: release-chore

#3436 [Cherry Pick] Add terraform setup to github workflow config
  .github/workflows/pr-precommit.yml
Labels: release-bugfix

#3431 [Cherry Pick] add reservations for kueue integration tests
  tools/cloud-build/daily-tests/blueprints/gke-a2-highgpu.yaml
  tools/cloud-build/daily-tests/tests/gke-a2-highgpu-kueue.yml
Labels: release-improvements

#3438 Upgrade a3-ultra to use kueue v0.10.0
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
Labels: release-improvements

#3437 [Cherry Pick] Update README and related test setup for GKE managed parallelstore blueprint
  examples/README.md
  examples/gke-managed-parallelstore.yaml
  modules/file-system/gke-storage/README.md
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-managed-parallelstore.yml
  tools/cloud-build/daily-tests/builds/gke-managed-parallelstore.yaml
  tools/cloud-build/daily-tests/tests/gke-managed-parallelstore.yml
Labels: documentation, release-improvements

#3442 Fix wrong API field name
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
Labels: release-chore

#3440 Rename `/community/module/internal/slurm-gcp-v6` to `slurm-gcp`
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/main.tf
  community/modules/internal/slurm-gcp/instance/README.md
  community/modules/internal/slurm-gcp/instance/main.tf
  community/modules/internal/slurm-gcp/instance/outputs.tf
  community/modules/internal/slurm-gcp/instance/variables.tf
  community/modules/internal/slurm-gcp/instance/versions.tf
  community/modules/internal/slurm-gcp/instance_template/README.md
  community/modules/internal/slurm-gcp/instance_template/files/startup_sh_unlinted
  community/modules/internal/slurm-gcp/instance_template/main.tf
  community/modules/internal/slurm-gcp/instance_template/outputs.tf
  community/modules/internal/slurm-gcp/instance_template/variables.tf
  community/modules/internal/slurm-gcp/instance_template/versions.tf
  community/modules/internal/slurm-gcp/internal_instance_template/README.md
  community/modules/internal/slurm-gcp/internal_instance_template/main.tf
  community/modules/internal/slurm-gcp/internal_instance_template/outputs.tf
  community/modules/internal/slurm-gcp/internal_instance_template/variables.tf
  community/modules/internal/slurm-gcp/internal_instance_template/versions.tf
  community/modules/internal/slurm-gcp/nodeset_tpu/README.md
  community/modules/internal/slurm-gcp/nodeset_tpu/main.tf
  community/modules/internal/slurm-gcp/nodeset_tpu/outputs.tf
  community/modules/internal/slurm-gcp/nodeset_tpu/variables.tf
  community/modules/internal/slurm-gcp/nodeset_tpu/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
Labels: release-chore

#3333 Parallelstore striping config
  modules/file-system/parallelstore/README.md
  modules/file-system/parallelstore/main.tf
  modules/file-system/parallelstore/variables.tf
Labels: release-module-improvements

#3451 Fix non-constant format string errors
  cmd/create.go
  cmd/root.go
  pkg/modulereader/hcl_utils.go
Labels: release-chore

#3449 TAS Plugin Bug fix
  community/modules/compute/gke-topology-scheduler/manifests/topology-scheduler-scripts.yaml
Labels: release-bugfix

#3453 A3 Ultra Integration tests
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  tools/cloud-build/daily-tests/builds/gke-a3-ultragpu.yaml
  tools/cloud-build/daily-tests/tests/gke-a3-ultragpu.yml
Labels: release-improvements

#3447 Update google tf provider version ceiling
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: release-chore

#3456 Update A3U blueprint to remove commit refs and remove hardcoded network names
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  tools/cloud-build/daily-tests/builds/gke-a3-ultragpu.yaml
  tools/cloud-build/daily-tests/tests/gke-a3-ultragpu.yml
Labels: release-improvements

#3439 Add compact placement validations
  modules/compute/gke-node-pool/main.tf
Labels: release-improvements

#3457 Update mount-daos.sh
  modules/file-system/parallelstore/scripts/mount-daos.sh
  modules/file-system/pre-existing-network-storage/scripts/mount-daos.sh
Labels: release-bugfix

#3458 Add full defintion of `nodeset` to partition module
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
  tools/validate_configs/test_configs/node-groups.yaml
Labels: release-chore

#3144 Allow customization of Parallelstore mounts
  modules/file-system/parallelstore/README.md
  modules/file-system/parallelstore/main.tf
  modules/file-system/parallelstore/scripts/install-daos-client.sh
  modules/file-system/parallelstore/templates/mount-daos.sh.tftpl
  modules/file-system/parallelstore/variables.tf
  modules/file-system/pre-existing-network-storage/README.md
  modules/file-system/pre-existing-network-storage/outputs.tf
  modules/file-system/pre-existing-network-storage/scripts/install-daos-client.sh
  modules/file-system/pre-existing-network-storage/templates/mount-daos.sh.tftpl
  modules/file-system/pre-existing-network-storage/variables.tf
  modules/scripts/startup-script/templates/startup-script-custom.tftpl
  tools/duplicate-diff.py
Labels: release-improvements

#3459 Placement policy null condition checks added
  modules/compute/gke-node-pool/main.tf
Labels: release-bugfix

#3462 Make upgrade settings configurable for gke-cluster
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/variables.tf
Labels: release-module-improvements

#3450 Add lifecycle rule to ignore local SSDs
  modules/compute/gke-node-pool/main.tf
Labels: release-improvements

#3463 make upgrade settings configurable
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/variables.tf
Labels: release-improvements

#3466 update a3mega nccl plugin to 1.0.7 and rxdm to 1.0.13_1
  modules/compute/gke-node-pool/gpu_direct.tf
Labels: release-improvements

#3406 Add kubectl provider in root module for blueprint with GKE cluster module setup
  community/modules/compute/gke-topology-scheduler/README.md
  community/modules/compute/gke-topology-scheduler/main.tf
  community/modules/compute/gke-topology-scheduler/variables.tf
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/variables.tf
  modules/file-system/gke-persistent-volume/README.md
  modules/file-system/gke-persistent-volume/main.tf
  modules/file-system/gke-persistent-volume/variables.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/README.md
  modules/file-system/gke-storage/main.tf
  modules/file-system/gke-storage/variables.tf
  modules/management/kubectl-apply/README.md
  modules/management/kubectl-apply/main.tf
  modules/management/kubectl-apply/providers.tf
  modules/management/kubectl-apply/variables.tf
  modules/management/kubectl-apply/versions.tf
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/outputs.tf
  modules/scheduler/pre-existing-gke-cluster/README.md
  modules/scheduler/pre-existing-gke-cluster/main.tf
  modules/scheduler/pre-existing-gke-cluster/outputs.tf
  pkg/config/expand.go
  pkg/config/expand_test.go
Labels: release-module-improvements

#3452 Add integration test for A3U / A3U blueprint updates
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  tools/cloud-build/daily-tests/ansible_playbooks/post-destroy-tasks/delete-image.yml
  tools/cloud-build/daily-tests/builds/ml-a3-ultragpu-slurm.yaml
  tools/cloud-build/daily-tests/tests/ml-a3-ultragpu-slurm.yml
Labels: release-chore

#3435 Add a3u-slurm-ubuntu-gcs blueprint
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/README.md
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/a3u-slurm-ubuntu-gcs.yaml
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/deployment.yaml
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/run-nccl-tests-via-ramble.sh
  tools/validate_configs/validate_configs.sh
Labels: release-key-new-features

#3475 Release v1.44.1: A3 Ultra (a3-ultragpu-8g) blueprints
  examples/gke-a3-ultragpu/README.md
  examples/gke-a3-ultragpu/gke-a3-ultragpu-deployment.yaml
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  examples/gke-a3-ultragpu/mglru-disable.yaml
  examples/gke-a3-ultragpu/nccl-installer.yaml
  examples/gke-a3-ultragpu/nccl-jobset-example.yaml
  examples/gke-a3-ultragpu/nccl-test-32-node.yaml
  examples/gke-a3-ultragpu/nccl-test.yaml
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/README.md
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/a3u-slurm-ubuntu-gcs.yaml
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/deployment.yaml
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/run-nccl-tests-via-ramble.sh
  examples/machine-learning/a3-ultragpu-8g/README.md
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-deployment.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-vm.yaml
  examples/machine-learning/a3-ultragpu-8g/nccl-tests/README.md
  examples/machine-learning/a3-ultragpu-8g/nccl-tests/build-nccl-tests.sh
  examples/machine-learning/a3-ultragpu-8g/nccl-tests/import_pytorch_container.sh
  examples/machine-learning/a3-ultragpu-8g/nccl-tests/run-nccl-tests.sh
  modules/compute/vm-instance/variables.tf
  tools/cloud-build/daily-tests/ansible_playbooks/post-destroy-tasks/delete-image.yml
  tools/cloud-build/daily-tests/builds/ml-a3-ultragpu-slurm.yaml
  tools/cloud-build/daily-tests/tests/ml-a3-ultragpu-slurm.yml
  tools/cloud-build/daily-tests/validate_tests_metadata.py
  tools/validate_configs/validate_configs.sh
Labels: release-chore

#3481 Update Stackdrier typo in README.md
  modules/scripts/startup-script/README.md
Labels: release-chore

#3483 Fix failures if not specifying stripe sizes for parallelstore
  modules/file-system/parallelstore/README.md
  modules/file-system/parallelstore/variables.tf
Labels: release-chore
