Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2024-03, with the labels that each got.

#2304 Add pre-commit to validate integration tests metadata (tags)
  .pre-commit-config.yaml
  tools/cloud-build/daily-tests/builds/batch-mpi.yaml
  tools/cloud-build/daily-tests/builds/chrome-remote-desktop-ubuntu.yaml
  tools/cloud-build/daily-tests/builds/chrome-remote-desktop.yaml
  tools/cloud-build/daily-tests/builds/cloud-batch.yaml
  tools/cloud-build/daily-tests/builds/gke-storage.yaml
  tools/cloud-build/daily-tests/builds/gke.yaml
  tools/cloud-build/daily-tests/builds/hcls.yaml
  tools/cloud-build/daily-tests/builds/hpc-build-slurm-image.yaml
  tools/cloud-build/daily-tests/builds/hpc-enterprise-slurm.yaml
  tools/cloud-build/daily-tests/builds/hpc-high-io-v5.yaml
  tools/cloud-build/daily-tests/builds/hpc-slurm-chromedesktop.yaml
  tools/cloud-build/daily-tests/builds/htcondor.yaml
  tools/cloud-build/daily-tests/builds/lustre-slurm.yaml
  tools/cloud-build/daily-tests/builds/lustre-vm.yaml
  tools/cloud-build/daily-tests/builds/ml-slurm.yaml
  tools/cloud-build/daily-tests/builds/monitoring.yaml
  tools/cloud-build/daily-tests/builds/ofe-deployment.yaml
  tools/cloud-build/daily-tests/builds/packer.yaml
  tools/cloud-build/daily-tests/builds/pbspro.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-debian.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-hpc-centos7.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-rocky8.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-startup-scripts.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-ubuntu2004.yaml
  tools/cloud-build/daily-tests/builds/spack-gromacs.yaml
  tools/cloud-build/daily-tests/validate_tests_metadata.py
  tools/cloud-build/requirements.txt
Labels: release-chore

#2294 Slurm v6: add extended prolog/epilog configuration template
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/etc/long-prolog-slurm.conf.tpl
  tools/duplicate-diff.py
Labels: release-chore

#2308 Babysit. Add option to use build tags as selector
  tools/cloud-build/babysit_tests.py
Labels: release-chore

#2303 Add E2E integration test
  tools/cloud-build/daily-tests/blueprints/e2e.yaml
  tools/cloud-build/daily-tests/builds/e2e.yaml
  tools/cloud-build/daily-tests/e2e.sh
Labels: release-chore

#2293 Update parameters for TPU nodeset module and add precondition checks and bump TPU to v3
  community/examples/hpc-slurm6-tpu.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/outputs.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-improvements

#2316 Fix typo in TPU example and documentation from maxtest to maxtext
  community/examples/hpc-slurm6-tpu-v4.md
  community/examples/hpc-slurm6-tpu-v4.yaml
Labels: release-chore

#2297 Add Slurm v6 version for image builder blueprint
  examples/README.md
  examples/image-builder-v6.yaml
  tools/cloud-build/daily-tests/builds/packer-v6.yaml
  tools/cloud-build/daily-tests/tests/packer-v6.yml
Labels: release-improvements

#2312 Remove `simpleTokens`
  pkg/modulewriter/tfwriter.go
Labels: release-chore

#2276 Reduce duplication of yaml-parsing code
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/errors.go
  pkg/config/yaml.go
Labels: release-chore

#2311 Babysit. Allow to use PR number instead of SHA
  tools/cloud-build/babysit_tests.py
Labels: release-chore

#2305 Test tags: set a tag for each module used in tested blueprint.
  tools/cloud-build/daily-tests/builds/batch-mpi.yaml
  tools/cloud-build/daily-tests/builds/chrome-remote-desktop-ubuntu.yaml
  tools/cloud-build/daily-tests/builds/chrome-remote-desktop.yaml
  tools/cloud-build/daily-tests/builds/cloud-batch.yaml
  tools/cloud-build/daily-tests/builds/e2e.yaml
  tools/cloud-build/daily-tests/builds/gke-storage.yaml
  tools/cloud-build/daily-tests/builds/gke.yaml
  tools/cloud-build/daily-tests/builds/hcls.yaml
  tools/cloud-build/daily-tests/builds/hpc-build-slurm-image.yaml
  tools/cloud-build/daily-tests/builds/hpc-enterprise-slurm.yaml
  tools/cloud-build/daily-tests/builds/hpc-high-io-v5.yaml
  tools/cloud-build/daily-tests/builds/hpc-slurm-chromedesktop.yaml
  tools/cloud-build/daily-tests/builds/htcondor.yaml
  tools/cloud-build/daily-tests/builds/lustre-slurm.yaml
  tools/cloud-build/daily-tests/builds/lustre-vm.yaml
  tools/cloud-build/daily-tests/builds/ml-slurm.yaml
  tools/cloud-build/daily-tests/builds/monitoring.yaml
  tools/cloud-build/daily-tests/builds/packer-v6.yaml
  tools/cloud-build/daily-tests/builds/packer.yaml
  tools/cloud-build/daily-tests/builds/pbspro.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-debian.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-hpc-centos7.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-rocky8.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-startup-scripts.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-ubuntu2004.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-rocky8.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-tpu.yaml
  tools/cloud-build/daily-tests/builds/spack-gromacs.yaml
  tools/cloud-build/daily-tests/validate_tests_metadata.py
Labels: release-chore

#2313 Populate tags for all tests, based on babysitter selectors + new
  tools/cloud-build/babysit_tests.py
  tools/cloud-build/daily-tests/builds/batch-mpi.yaml
  tools/cloud-build/daily-tests/builds/chrome-remote-desktop-ubuntu.yaml
  tools/cloud-build/daily-tests/builds/chrome-remote-desktop.yaml
  tools/cloud-build/daily-tests/builds/cloud-batch.yaml
  tools/cloud-build/daily-tests/builds/e2e.yaml
  tools/cloud-build/daily-tests/builds/gke-storage.yaml
  tools/cloud-build/daily-tests/builds/gke.yaml
  tools/cloud-build/daily-tests/builds/hcls.yaml
  tools/cloud-build/daily-tests/builds/hpc-build-slurm-image.yaml
  tools/cloud-build/daily-tests/builds/hpc-enterprise-slurm.yaml
  tools/cloud-build/daily-tests/builds/hpc-high-io-v5.yaml
  tools/cloud-build/daily-tests/builds/hpc-slurm-chromedesktop.yaml
  tools/cloud-build/daily-tests/builds/htcondor.yaml
  tools/cloud-build/daily-tests/builds/lustre-slurm.yaml
  tools/cloud-build/daily-tests/builds/lustre-vm.yaml
  tools/cloud-build/daily-tests/builds/ml-slurm.yaml
  tools/cloud-build/daily-tests/builds/monitoring.yaml
  tools/cloud-build/daily-tests/builds/ofe-deployment.yaml
  tools/cloud-build/daily-tests/builds/packer-v6.yaml
  tools/cloud-build/daily-tests/builds/packer.yaml
  tools/cloud-build/daily-tests/builds/pbspro.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-debian.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-hpc-centos7.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-rocky8.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-startup-scripts.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-ubuntu2004.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-rocky8.yaml
  tools/cloud-build/daily-tests/builds/spack-gromacs.yaml
  tools/cloud-build/daily-tests/validate_tests_metadata.py
Labels: release-chore

#2268 Refactor `cmd`
  cmd/create.go
  cmd/deploy.go
  cmd/deploy_test.go
  cmd/destroy.go
  cmd/expand.go
  cmd/export.go
  cmd/export_test.go
  cmd/import.go
  cmd/utils.go
Labels: release-chore

#2318 Add `google-cloud-build` Python SDK to builder image
  tools/cloud-build/requirements.txt
Labels: release-chore

#2317 Version/1.29.0
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2324 Increase MessageTimeout to 600 in long prolog Slurm configuration
  .pre-commit-config.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/etc/long-prolog-slurm.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/etc/long-prolog-slurm.conf.tpl
Labels: release-chore

#2272 Make `config.Dict` immutable
  cmd/create.go
  cmd/create_test.go
  pkg/config/config_test.go
  pkg/config/dict.go
  pkg/config/dict_test.go
  pkg/config/expand.go
  pkg/config/expand_test.go
  pkg/config/validator_test.go
  pkg/config/yaml.go
  pkg/config/yaml_test.go
  pkg/modulewriter/modulewriter_test.go
  pkg/modulewriter/packerwriter.go
  pkg/modulewriter/tfwriter.go
  pkg/shell/terraform.go
  pkg/validators/quota_test.go
  pkg/validators/validators_test.go
Labels: release-chore

#2296 Add support for startup script per nodeset
  community/examples/hpc-build-slurm-image.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-module-improvements

#2289 Migrate hpc slurm ubuntu2004 to v6
  community/examples/hpc-slurm-ubuntu2004-v6.yaml
  examples/README.md
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-centos7.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-debian.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-ubuntu.yaml
  tools/cloud-build/daily-tests/tests/slurm-v6-centos7.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-debian.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-ubuntu.yml
Labels: release-chore

#2321 Babysit. Add `--auto` mode to discover tests based on files changed
  tools/cloud-build/babysit_tests.py
Labels: release-chore

#2219 Allocate IP for vm-instance
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/main.tf
  modules/compute/vm-instance/variables.tf
Labels: release-module-improvements, pre-commit-autofix

#2326 Refactor `pkg/config` tests
  pkg/config/config_test.go
  pkg/config/expand_test.go
  pkg/modulewriter/modulewriter_test.go
Labels: release-chore

#2335 Merge main back to develop
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  examples/README.md
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2159 Use ghpc binary to deploy tests
  tools/cloud-build/daily-tests/ansible_playbooks/base-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
Labels: release-chore

#2331 Improve documentation and default values from #2219
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/variables.tf
  modules/compute/vm-instance/versions.tf
Labels: release-chore

#2338 Update internal usage of Toolkit modules to v1.29.0
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/pbspro-execution/README.md
  community/modules/compute/pbspro-execution/main.tf
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/main.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/htcondor-service-accounts/README.md
  community/modules/scheduler/htcondor-service-accounts/main.tf
  community/modules/scheduler/pbspro-client/README.md
  community/modules/scheduler/pbspro-client/main.tf
  community/modules/scheduler/pbspro-server/README.md
  community/modules/scheduler/pbspro-server/main.tf
  community/modules/scripts/ramble-execute/README.md
  community/modules/scripts/ramble-execute/main.tf
  community/modules/scripts/ramble-setup/README.md
  community/modules/scripts/ramble-setup/main.tf
  community/modules/scripts/spack-execute/README.md
  community/modules/scripts/spack-execute/main.tf
  community/modules/scripts/spack-setup/README.md
  community/modules/scripts/spack-setup/main.tf
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/startup_from_network_storage.tf
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/startup_from_network_storage.tf
  modules/scheduler/batch-login-node/README.md
  modules/scheduler/batch-login-node/main.tf
Labels: release-chore

#2336 Update babysit usage command
  tools/cloud-build/babysit_tests.py
Labels: release-chore

#2340 HTCondor: support user-managed secret replication
  community/modules/scheduler/htcondor-pool-secrets/README.md
  community/modules/scheduler/htcondor-pool-secrets/main.tf
  community/modules/scheduler/htcondor-pool-secrets/variables.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
Labels: release-module-improvements

#2334 Added enable_devel for packer build to fix issue with bp
  community/examples/hpc-build-slurm-image.yaml
Labels: release-bugfix

#2323 Allow `ghpc deploy blueprint.yaml`
  cmd/create.go
  cmd/deploy.go
  cmd/utils.go
  tools/cloud-build/daily-tests/e2e.sh
Labels: release-improvements

#2332 `pkg/config` tests. Use Module builder to minimize side effects
  pkg/config/config_test.go
  pkg/config/expand_test.go
Labels: release-chore

#2322 Slurm GCP version update; will cooldown before deleting orphan nodes
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
  docs/hybrid-slurm-cluster/demo-with-cloud-controller-instructions.md
  docs/hybrid-slurm-cluster/deploy-instructions.md
  docs/hybrid-slurm-cluster/on-prem-instructions.md
  docs/image-building.md
  examples/README.md
  modules/README.md
  tools/cloud-build/daily-tests/tests/hpc-enterprise-slurm.yml
Labels: release-improvements, release-version-updates

#2327 Remove slurm-lustre v5 example and references
  docs/vm-images.md
  tools/validate_configs/os_compatibility_tests/slurm-lustre.yaml
Labels: release-chore

#2328 Remove slurm-startup script v5 example and references
  docs/vm-images.md
  tools/validate_configs/os_compatibility_tests/slurm-startup.yaml
Labels: release-chore

#2345 Fix `ghpc deploy <FOLDER>` reseting `--auto-approve` flag
  cmd/deploy.go
Labels: release-chore

#2344 Update terraform_backend_defaults documentation
  examples/README.md
Labels: documentation, release-chore

#2351 Support setting system default web proxy in Windows startup
  community/modules/scripts/windows-startup-script/README.md
  community/modules/scripts/windows-startup-script/files/install_gpu_driver.ps1
  community/modules/scripts/windows-startup-script/main.tf
  community/modules/scripts/windows-startup-script/templates/install_gpu_driver.ps1.tftpl
  community/modules/scripts/windows-startup-script/variables.tf
Labels: release-module-improvements

#2343 Babysit. Add `--name` and `--all` flags, remove `test_selectors` args
  tools/cloud-build/babysit_tests.py
Labels: release-chore

#2346 Add SlurmGCP v6 example of slurm compatible with startup scripts and integration test
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-startup-scripts.yaml
  tools/cloud-build/daily-tests/tests/slurm-v6-startup-scripts.yml
  tools/validate_configs/test_configs/slurm-gcp-v6-startup-scripts.yaml
Labels: release-improvements

#2352 Adopt Slurm-GCP release 5.10.6
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
  docs/hybrid-slurm-cluster/demo-with-cloud-controller-instructions.md
  docs/hybrid-slurm-cluster/deploy-instructions.md
  docs/hybrid-slurm-cluster/on-prem-instructions.md
  docs/image-building.md
  examples/README.md
  modules/README.md
  tools/cloud-build/daily-tests/tests/hpc-enterprise-slurm.yml
Labels: release-version-updates

#2354 Rename `DeploymentGroup` -> `Group`
  cmd/create.go
  cmd/create_test.go
  cmd/deploy.go
  cmd/destroy.go
  cmd/export.go
  cmd/import.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/expand.go
  pkg/config/expand_test.go
  pkg/modulewriter/modulewriter.go
  pkg/modulewriter/modulewriter_test.go
  pkg/modulewriter/packerwriter.go
  pkg/modulewriter/tfwriter.go
  pkg/shell/common.go
  pkg/shell/common_test.go
  pkg/shell/terraform.go
Labels: release-chore

#2357 Update TPU v4 blueprint maxtext script to point to the working reference
  community/examples/hpc-slurm6-tpu-v4.yaml
Labels: release-chore

#2355 Kill `MySuite` in `modulewriter_test`
  pkg/modulewriter/modulewriter_test.go
Labels: release-chore

#2353 Update zone to us-central1-a for TPU blueprint and test and increase retries
  community/examples/hpc-slurm6-tpu.yaml
  tools/cloud-build/daily-tests/ansible_playbooks/test-slurm-v6-tpu.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-tpu.yml
Labels: release-chore

#2359 Initial commit of A3 blueprint and documentation
  examples/machine-learning/README.md
  examples/machine-learning/ml-slurm-a3-0-base.yaml
  examples/machine-learning/ml-slurm-a3-1-image.yaml
  examples/machine-learning/ml-slurm-a3-2-cluster.yaml
Labels: release-key-new-features

#2360 Add example for running the NeMo Framework
  examples/machine-learning/nemo-framework/Dockerfile
  examples/machine-learning/nemo-framework/README.md
  examples/machine-learning/nemo-framework/setup_nemo.sh
Labels: release-key-new-features, pre-commit-autofix

#2361 Add NCCL benchmark to machine-learning solution
  examples/machine-learning/README.md
  examples/machine-learning/nccl-tests/README.md
  examples/machine-learning/nccl-tests/build-nccl-tests.sh
  examples/machine-learning/nccl-tests/import_pytorch_container.sh
  examples/machine-learning/nccl-tests/run-nccl-tests.sh
  examples/machine-learning/nccl-tests/run-topological-nccl-tests.sh
Labels: release-key-new-features

#2358 Migrate config-ssh.yaml to Slurm-GCP v6
  tools/validate_configs/test_configs/config-ssh.yaml
Labels: release-improvements

#2356 Remove pre-commit.ci action
  .github/workflows/pr-precommit.yml
Labels: release-chore

#2368 Support http_proxy in HTCondor Windows installation
  community/modules/scripts/htcondor-install/README.md
  community/modules/scripts/htcondor-install/main.tf
  community/modules/scripts/htcondor-install/templates/install-htcondor.ps1.tftpl
  community/modules/scripts/htcondor-install/variables.tf
  community/modules/scripts/windows-startup-script/templates/install_gpu_driver.ps1.tftpl
Labels: release-module-improvements

#2367 Packer service account fix and alignment with Toolkit naming convention
  examples/image-builder-v6.yaml
  examples/image-builder.yaml
  modules/packer/custom-image/README.md
  modules/packer/custom-image/image.pkr.hcl
  modules/packer/custom-image/variables.pkr.hcl
  tools/cloud-build/daily-tests/builds/packer-v6.yaml
  tools/cloud-build/daily-tests/builds/packer.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/one/image/image.pkr.hcl
  tools/validate_configs/golden_copies/expectations/igc_pkr/one/image/variables.pkr.hcl
  tools/validate_configs/golden_copies/expectations/text_escape/zero/lime/image.pkr.hcl
  tools/validate_configs/golden_copies/expectations/text_escape/zero/lime/variables.pkr.hcl
Labels: release-bugfix

#2330 Remove slurm-gcp high io blueprint and integration test
  tools/cloud-build/daily-tests/blueprints/slurm-gcp-v5-high-io.yaml
  tools/cloud-build/daily-tests/builds/hpc-high-io-v5.yaml
  tools/cloud-build/daily-tests/tests/high-io-slurm-gcp-v5.yml
Labels: release-chore

#2347 Add SlurmGCP v6 version of node groups blueprint example
  tools/validate_configs/test_configs/node-groups-v6.yaml
Labels: release-improvements

#2365 Minor error messages refactoring
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/errors.go
  pkg/config/expand.go
  pkg/config/validate.go
Labels: release-chore

#1986 Slurm6. Add support for dynamic nodeset.
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/outputs.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/outputs.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-module-improvements

#2369 Add TPU maxtext example in example documentation
  community/examples/hpc-slurm6-tpu-maxtext.yaml
  docs/hpc-slurm6-tpu-maxtext.md
  examples/README.md
Labels: release-chore

#2374 Improved babysitter message
  tools/cloud-build/babysit_tests.py
Labels: release-chore

#2375 Merge back main to develop branch
  cmd/root.go
  community/examples/hpc-slurm6-tpu-maxtext.yaml
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  docs/hpc-slurm6-tpu-maxtext.md
  examples/README.md
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2377 Fix: use new scope variable in custom-image module
  modules/packer/custom-image/image.pkr.hcl
  tools/validate_configs/golden_copies/expectations/igc_pkr/one/image/image.pkr.hcl
  tools/validate_configs/golden_copies/expectations/text_escape/zero/lime/image.pkr.hcl
Labels: release-chore

#2376 Add Slurm-GCP v6 example for gpu.yaml
  tools/validate_configs/test_configs/gpu-v6.yaml
Labels: release-improvements

#2348 Add SlurmGCP v6 example of htc-slurm blueprint
  community/examples/htc-slurm-v6.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/etc/htc-slurm.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/etc/htc-slurmdbd.conf.tpl
  examples/README.md
  tools/cloud-build/daily-tests/builds/htc-slurm-v6.yaml
  tools/cloud-build/daily-tests/tests/htc-slurm-v6.yml
Labels: release-improvements

#2364 Remove outdated comments about "resources"
  community/examples/hpc-slurm-ramble-gromacs.yaml
  community/examples/hpc-slurm-ubuntu2004-v6.yaml
  community/examples/hpc-slurm-ubuntu2004.yaml
  community/examples/tutorial-starccm-slurm.yaml
  docs/tutorials/hpc-slurm-qwiklabs.yaml
  tools/validate_configs/os_compatibility_tests/batch-filestore.yaml
  tools/validate_configs/os_compatibility_tests/batch-lustre.yaml
  tools/validate_configs/os_compatibility_tests/batch-startup.yaml
  tools/validate_configs/os_compatibility_tests/slurm-filestore.yaml
  tools/validate_configs/os_compatibility_tests/vm-crd.yaml
  tools/validate_configs/os_compatibility_tests/vm-filestore.yaml
  tools/validate_configs/os_compatibility_tests/vm-lustre.yaml
  tools/validate_configs/os_compatibility_tests/vm-startup.yaml
  tools/validate_configs/test_configs/config-ssh.yaml
  tools/validate_configs/test_configs/node-groups.yaml
  tools/validate_configs/test_configs/slurm-gcp-v5-startup-scripts.yaml
  tools/validate_configs/test_configs/slurm-gcp-v6-startup-scripts.yaml
  tools/validate_configs/test_configs/slurm-static-test.yaml
  tools/validate_configs/test_configs/zone-policies-slurm-v5.yaml
Labels: release-chore

#2380 Script capture serial
  tools/capture_serial.sh
Labels: release-improvements

#2379 Deprecate `schedmd-slurm-gcp-v6-partition.network_storage`
  community/examples/hpc-slurm-gromacs.yaml
  community/examples/hpc-slurm-sharedvpc.yaml
  community/examples/hpc-slurm-ubuntu2004-v6.yaml
  community/examples/htc-slurm-v6.yaml
  community/examples/intel/hpc-slurm-daos.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  docs/tutorials/sc23-tutorial/hcls-blueprint.yaml
  examples/hpc-slurm-v6.yaml
  pkg/inspect/modules_test.go
  tools/validate_configs/test_configs/config-ssh.yaml
  tools/validate_configs/test_configs/hpc-cluster-simple-nfs-sql.yaml
  tools/validate_configs/test_configs/node-groups-v6.yaml
  tools/validate_configs/test_configs/slurm-gcp-v6-startup-scripts.yaml
Labels: release-deprecations

#2381 Allow nodeset to be used by multiple partitions
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-chore

#2385 Auto-inject `tpu_nodeset.name`. Improve description message
  community/examples/hpc-slurm6-tpu-maxtext.yaml
  community/examples/hpc-slurm6-tpu.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/metadata.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
Labels: release-chore

#2384 Update version for modules to use newer release
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/pbspro-execution/README.md
  community/modules/compute/pbspro-execution/main.tf
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/main.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/htcondor-service-accounts/README.md
  community/modules/scheduler/htcondor-service-accounts/main.tf
  community/modules/scheduler/pbspro-client/README.md
  community/modules/scheduler/pbspro-client/main.tf
  community/modules/scheduler/pbspro-server/README.md
  community/modules/scheduler/pbspro-server/main.tf
  community/modules/scripts/ramble-execute/README.md
  community/modules/scripts/ramble-execute/main.tf
  community/modules/scripts/ramble-setup/README.md
  community/modules/scripts/ramble-setup/main.tf
  community/modules/scripts/spack-execute/README.md
  community/modules/scripts/spack-execute/main.tf
  community/modules/scripts/spack-setup/README.md
  community/modules/scripts/spack-setup/main.tf
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/startup_from_network_storage.tf
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/startup_from_network_storage.tf
  modules/scheduler/batch-login-node/README.md
  modules/scheduler/batch-login-node/main.tf
Labels: release-chore

#2339 Implement `ghpc_stage` function to stage files into deployment
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/expression.go
  pkg/config/staging.go
  pkg/config/staging_test.go
  pkg/modulewriter/modulewriter.go
  pkg/modulewriter/modulewriter_test.go
  tools/validate_configs/golden_copies/configs/files/connect_mode.txt
  tools/validate_configs/golden_copies/configs/igc_tf.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/staged/connect_mode.txt_0a3df07f53
  tools/validate_configs/golden_copies/expectations/igc_tf/one/main.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/one/terraform.tfvars
  tools/validate_configs/golden_copies/expectations/igc_tf/one/variables.tf
  tools/validate_configs/golden_copies/validate.sh
Labels: release-key-new-features

#2395 Fix `Print Cloud Logging command` test step
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/get_instance_ids.yml
Labels: release-chore

#2396 Fixing Makefile `terraform-format` command
  Makefile
Labels: release-chore

#2383 Set default validation level to `ERROR`
  README.md
  cmd/expand.go
  docs/blueprint-validation.md
  docs/hpc-slurm6-tpu-maxtext.md
  tools/cloud-build/daily-tests/e2e.sh
Labels: release-improvements

#2393 Add example using Slurm static compute nodes
  examples/README.md
  examples/hpc-slurm-static-v6.yaml
  tools/cloud-build/daily-tests/ansible_playbooks/post-destroy-tasks/delete-reservation.yml
  tools/cloud-build/daily-tests/ansible_playbooks/pre-deploy-tasks/create-reservation.yml
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/rescue_ghpc_failure.yml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-static.yaml
  tools/cloud-build/daily-tests/tests/slurm-v6-static.yml
Labels: release-improvements

#2387 Remove slurm filestore blueprint and references
  docs/vm-images.md
  tools/validate_configs/os_compatibility_tests/slurm-filestore.yaml
Labels: release-chore

#2329 Add lustre slurm blueprint for v6 version and integration test
  tools/cloud-build/daily-tests/blueprints/lustre-slurm-v6.yaml
  tools/cloud-build/daily-tests/builds/lustre-slurm-v6.yaml
  tools/cloud-build/daily-tests/tests/lustre-slurm-v6.yml
Labels: release-improvements

#2337 Add v6 version of ml-slurm blueprint and integration test
  examples/README.md
  examples/ml-slurm-v6.yaml
  tools/cloud-build/daily-tests/builds/ml-slurm-v6.yaml
  tools/cloud-build/daily-tests/tests/ml-slurm-v6.yml
Labels: release-improvements

#2404 Revert "Add example using Slurm static compute nodes"
  examples/README.md
  examples/hpc-slurm-static-v6.yaml
  tools/cloud-build/daily-tests/ansible_playbooks/post-destroy-tasks/delete-reservation.yml
  tools/cloud-build/daily-tests/ansible_playbooks/pre-deploy-tasks/create-reservation.yml
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/rescue_ghpc_failure.yml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-static.yaml
  tools/cloud-build/daily-tests/tests/slurm-v6-static.yml
Labels: release-bugfix

#2390 Add Slurm-GCP v6 version of zone policies blueprint
  tools/validate_configs/test_configs/zone-policies-slurm-v6.yaml
Labels: release-improvements

#2388 Add `materialization` stage.
  cmd/create.go
  cmd/deploy.go
  cmd/destroy.go
  cmd/expand.go
  cmd/export.go
  cmd/import.go
  cmd/root.go
  pkg/config/config.go
  pkg/config/dict.go
  pkg/config/dict_test.go
  pkg/config/expression.go
  pkg/config/expression_test.go
  pkg/config/materialize.go
  pkg/modulewriter/modulewriter.go
  pkg/modulewriter/packerwriter.go
  pkg/modulewriter/tfwriter.go
  pkg/shell/terraform.go
  pkg/validators/validators.go
Labels: release-chore

#2386 Slurm-GCP-V6. Add local SSD example
  community/examples/hpc-slurm-local-ssd-v6.yaml
  examples/README.md
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-ssd.yaml
  tools/cloud-build/daily-tests/tests/slurm-v6-ssd.yml
Labels: release-chore

#2398 Simplify e2e test
  tools/cloud-build/daily-tests/builds/e2e.yaml
Labels: release-chore

#2410 Simplify & speed up integraion tests
  tools/cloud-build/daily-tests/builds/monitoring.yaml
  tools/cloud-build/images/test-runner/Dockerfile
  tools/cloud-build/images/test-runner/config.yaml
  tools/cloud-build/provision/README.md
  tools/cloud-build/provision/image-build-test-runner.tf
Labels: release-chore

#2418 Add hint to run `gcloud auth application-default login`
  pkg/validators/cloud.go
  pkg/validators/validators.go
Labels: release-chore

#2402 In place update hpc-slurm-qwiklab blueprint to use slurm-gcp v6
  docs/tutorials/hpc-slurm-qwiklabs.yaml
Labels: release-improvements

#2422 Move some tests to better flow
  tools/cloud-build/daily-tests/builds/batch-mpi.yaml
  tools/cloud-build/daily-tests/builds/chrome-remote-desktop-ubuntu.yaml
  tools/cloud-build/daily-tests/builds/chrome-remote-desktop.yaml
  tools/cloud-build/daily-tests/builds/cloud-batch.yaml
  tools/cloud-build/daily-tests/builds/e2e.yaml
  tools/cloud-build/daily-tests/e2e.sh
  tools/cloud-build/hpc-toolkit-pr-validation.yaml
Labels: release-chore

#2425 Merge release v1.31.0 into develop branch
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2427 Update TPU maxtext documentation for minor changes
  docs/hpc-slurm6-tpu-maxtext.md
Labels: release-chore

#2428 Add `jq` to the `test-runner` image
  tools/cloud-build/images/test-runner/Dockerfile
Labels: release-chore
