Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2024-02, with the labels that each got.

#2186 Fix test broken by removed module
  pkg/modulereader/resreader_test.go
Labels: release-chore

#2184 Update TPU v6 blueprint to use new VPC module
  community/examples/hpc-slurm6-tpu.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  tools/cloud-build/daily-tests/tests/slurm-v6-tpu.yml
Labels: release-chore

#2188 Improve test coverage of `pkg/modulewriter`
  pkg/modulewriter/modulewriter.go
  pkg/modulewriter/modulewriter_test.go
  pkg/modulewriter/packerwriter.go
  pkg/modulewriter/tfwriter.go
Labels: release-chore

#2187 Updating spack and ramble buckets to use 8 digits of hex
  community/modules/scripts/ramble-setup/main.tf
  community/modules/scripts/spack-setup/main.tf
Labels: release-chore

#2191 `tools/enforce_coverage.pl`, fix for gLinux & improve output
  tools/enforce_coverage.pl
Labels: release-chore

#2192 Remove v4 reference from network storage document
  docs/network_storage.md
Labels: release-chore

#2194 Add function `Dict.Keys` to protect code agnostic to values
  pkg/config/config.go
  pkg/config/dict.go
  pkg/config/expand.go
Labels: release-chore

#2195 Add shorthand `Reference.AsValue()`
  pkg/config/config_test.go
  pkg/config/dict_test.go
  pkg/config/expand.go
  pkg/config/expand_test.go
  pkg/config/expression.go
  pkg/config/expression_test.go
  pkg/modulewriter/modulewriter_test.go
  pkg/validators/validators.go
  pkg/validators/validators_test.go
Labels: release-chore

#2196 Deprecate Dell Omnia module and example blueprint
  community/examples/omnia-cluster.yaml
  examples/README.md
  modules/README.md
  tools/cloud-build/daily-tests/builds/omnia.yaml
  tools/cloud-build/daily-tests/tests/omnia.yml
  tools/validate_configs/test_configs/README.md
Labels: release-deprecations

#2190 Move topological ordering of vars into separate function.
  pkg/config/config.go
  pkg/config/config_test.go
Labels: release-chore

#2189 Update Slurm-GCP release to 5.10.2
  community/examples/AMD/hpc-amd-slurm.yaml
  community/examples/hpc-slurm-chromedesktop.yaml
  community/examples/hpc-slurm-local-ssd.yaml
  community/examples/hpc-slurm-ramble-gromacs.yaml
  community/examples/hpc-slurm-ubuntu2004.yaml
  community/examples/htc-slurm.yaml
  community/examples/tutorial-starccm-slurm.yaml
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  docs/gpu-support.md
  docs/hybrid-slurm-cluster/demo-with-cloud-controller-instructions.md
  docs/hybrid-slurm-cluster/deploy-instructions.md
  docs/hybrid-slurm-cluster/on-prem-instructions.md
  docs/image-building.md
  docs/vm-images.md
  examples/README.md
  examples/cae/cae-slurm.yaml
  examples/hpc-enterprise-slurm.yaml
  examples/image-builder.yaml
  examples/ml-slurm.yaml
  modules/README.md
  tools/cloud-build/daily-tests/blueprints/lustre-slurm.yaml
  tools/cloud-build/daily-tests/tests/slurm-v5-debian.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-rocky8.yml
  tools/validate_configs/os_compatibility_tests/slurm-filestore.yaml
  tools/validate_configs/os_compatibility_tests/slurm-lustre.yaml
  tools/validate_configs/os_compatibility_tests/slurm-startup.yaml
  tools/validate_configs/test_configs/node-groups.yaml
  tools/validate_configs/test_configs/slurm-static-test.yaml
Labels: release-version-updates

#2204 Updates to HTCondor autoscaler
  community/modules/compute/htcondor-execute-point/templates/download-condor-config.ps1.tftpl
  community/modules/scheduler/htcondor-central-manager/templates/condor_config.tftpl
  community/modules/scheduler/htcondor-pool-secrets/templates/fetch-idtoken.ps1.tftpl
  community/modules/scripts/htcondor-install/files/autoscaler.py
Labels: release-module-improvements

#2181 Take "first deploy only" dependency on `slurm_files`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
Labels: release-chore

#2201 Refactor `eval` functions
  pkg/config/config.go
  pkg/config/dict.go
  pkg/config/expand.go
  pkg/config/expression.go
  pkg/config/expression_test.go
Labels: release-chore

#2199 Change batch-job-base template from json to YAML
  examples/serverless-batch-mpi.yaml
  examples/serverless-batch.yaml
  modules/scheduler/batch-job-template/main.tf
  modules/scheduler/batch-job-template/templates/batch-job-base.json.tftpl
  modules/scheduler/batch-job-template/templates/batch-job-base.yaml.tftpl
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-batch-submission.yml
Labels: release-module-improvements

#2193 Remove `setGlobalLabels` as it's not needed
  pkg/config/config.go
  pkg/config/expand.go
  pkg/config/expand_test.go
Labels: release-chore

#2211 Show hint message if unsupported function is used
  pkg/config/config_test.go
  pkg/config/expression.go
Labels: release-chore

#2215 Restrict GitHub actions to operate on upstream
  .github/workflows/dependency-review.yml
  .github/workflows/pr-label-validation.yml
Labels: release-chore

#2214 Update pre-commit hooks
  .pre-commit-config.yaml
Labels: release-chore

#2217 Don't run `destroy_resource_policies` before `destroy_nodes` is done
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
Labels: release-chore

#2218 Add Slurm configuration template for long Prolog/Epilog scripts
  community/examples/htc-slurm.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/etc/htc-slurm.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/etc/htc-slurmdbd.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/etc/long-prolog-slurm.conf.tpl
Labels: release-module-improvements

#2216 Improve user experience of pre-commit usage in PR validation
  .github/workflows/pr-precommit.yml
  tools/cloud-build/hpc-toolkit-pr-validation.yaml
Labels: release-chore

#2220 Adopt empty string as default value for maintenance_interval
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  tools/validate_configs/test_configs/node-groups.yaml
Labels: release-chore

#2158 Do not cleanup if destroy failed as manual inspection is required
  tools/cleanup-build.py
Labels: release-chore

#2185 Document python dependencies for cleanup compute nodes on Slurm v6
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
Labels: release-chore

#2222 Fix endless error render loop
  cmd/render.go
Labels: release-chore

#2225 Disable enable_devel in slurm-gcp v5 examples
  community/examples/hpc-slurm-chromedesktop.yaml
  community/examples/hpc-slurm-local-ssd.yaml
  community/examples/hpc-slurm-ramble-gromacs.yaml
  community/examples/hpc-slurm-ubuntu2004.yaml
  community/examples/htc-slurm.yaml
  community/examples/tutorial-starccm-slurm.yaml
  examples/cae/cae-slurm.yaml
  examples/hpc-enterprise-slurm.yaml
  examples/image-builder.yaml
  examples/ml-slurm.yaml
Labels: release-chore

#2227 Add login node to spack gromacs tutorial example
  docs/tutorials/gromacs/spack-gromacs.md
  docs/tutorials/gromacs/spack-gromacs.yaml
Labels: release-improvements

#2226 Add note that persistent SSH connections might prevent group updates
  community/modules/scripts/spack-setup/README.md
Labels: release-chore

#2232 Version bump to 1.28.0
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/htcondor-setup/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2233 Initialize tflint with GitHub authentication token to avoid rate limiting
  .github/workflows/pr-precommit.yml
Labels: release-chore

#2234 Align local provider usage in startup-script with rest of Toolkit
  modules/scripts/startup-script/README.md
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2237 Set http_proxy, https_proxy variables for user login and during startup-script
  modules/scripts/startup-script/README.md
  modules/scripts/startup-script/main.tf
  modules/scripts/startup-script/templates/startup-script-custom.tftpl
  modules/scripts/startup-script/variables.tf
Labels: release-module-improvements

#2241 Update documentation for Packer to include minimum operational requirements
  examples/image-builder.yaml
  modules/packer/custom-image/README.md
Labels: release-module-improvements

#2207 Add login node in spack wrfv3 tutorial example
  docs/tutorials/wrfv3/spack-wrfv3.md
  docs/tutorials/wrfv3/spack-wrfv3.yaml
Labels: release-improvements

#2240 Remove stockout check as result was misleading and led to ignored tests
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/check_stockout.yml
Labels: release-chore

#2200 Change subprocess signature to be python36 compatible
  tests/test_maintenance.py
  tools/maintenance/maintenance.py
Labels: release-chore

#2235 Use `n2-2` instead of `c3-8` in lustre tests
  tools/cloud-build/daily-tests/blueprints/lustre-slurm.yaml
  tools/cloud-build/daily-tests/blueprints/lustre-vm.yaml
Labels: release-chore

#2242 Fix typo in lustre-slurm integration test blueprint
  tools/cloud-build/daily-tests/blueprints/lustre-slurm.yaml
Labels: release-chore

#2249 Merge `main` back to `develop`
  cmd/root.go
  community/examples/hpc-slurm-chromedesktop.yaml
  community/examples/hpc-slurm-local-ssd.yaml
  community/examples/hpc-slurm-ramble-gromacs.yaml
  community/examples/hpc-slurm-ubuntu2004.yaml
  community/examples/htc-slurm.yaml
  community/examples/tutorial-starccm-slurm.yaml
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/htcondor-setup/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  docs/tutorials/gromacs/spack-gromacs.md
  docs/tutorials/gromacs/spack-gromacs.yaml
  examples/cae/cae-slurm.yaml
  examples/hpc-enterprise-slurm.yaml
  examples/image-builder.yaml
  examples/ml-slurm.yaml
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2247 Modify cloud-storage-bucket to include ability to set bucket viewers
  community/modules/file-system/cloud-storage-bucket/README.md
  community/modules/file-system/cloud-storage-bucket/main.tf
  community/modules/file-system/cloud-storage-bucket/variables.tf
Labels: release-module-improvements

#2224 Initial implementation of deployment file flag
  cmd/create.go
  cmd/create_test.go
  cmd/expand.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/yaml.go
Labels: release-chore

#2210 Add "submit" option to batch-job-template module
  examples/serverless-batch.yaml
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/main.tf
  modules/scheduler/batch-job-template/templates/batch-submit.sh.tftpl
  modules/scheduler/batch-job-template/variables.tf
  modules/scheduler/batch-job-template/versions.tf
Labels: release-module-improvements

#2254 Update internal usage of Toolkit modules to most recent release
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/pbspro-execution/README.md
  community/modules/compute/pbspro-execution/main.tf
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/main.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/pbspro-client/README.md
  community/modules/scheduler/pbspro-client/main.tf
  community/modules/scheduler/pbspro-server/README.md
  community/modules/scheduler/pbspro-server/main.tf
  community/modules/scripts/ramble-execute/README.md
  community/modules/scripts/ramble-execute/main.tf
  community/modules/scripts/ramble-setup/README.md
  community/modules/scripts/ramble-setup/main.tf
  community/modules/scripts/spack-execute/README.md
  community/modules/scripts/spack-execute/main.tf
  community/modules/scripts/spack-setup/README.md
  community/modules/scripts/spack-setup/main.tf
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/startup_from_network_storage.tf
  modules/network/firewall-rules/versions.tf
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/startup_from_network_storage.tf
  modules/scheduler/batch-login-node/README.md
  modules/scheduler/batch-login-node/main.tf
Labels: release-chore

#2251 Update to Slurm-GCP 5.10.4
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
  docs/hybrid-slurm-cluster/demo-with-cloud-controller-instructions.md
  docs/hybrid-slurm-cluster/deploy-instructions.md
  docs/hybrid-slurm-cluster/on-prem-instructions.md
  docs/image-building.md
  examples/README.md
  modules/README.md
Labels: release-new-modules

#2256 Update CloudSQL v6 Documentation
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-chore

#2262 Version constrain Flux module for improved reliability
  community/examples/flux-framework/flux-cluster.yaml
Labels: release-chore

#2264 Fix broken link
  docs/tutorials/wrfv3/spack-wrfv3.md
Labels: release-chore

#2258 Refactor `validate & expand` phase to perform it "layer by layer".
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/expand.go
  pkg/config/expand_test.go
Labels: release-chore

#2252 Fix HTCondor image support
  docs/vm-images.md
Labels: release-chore

#2270 Update default values for htcondor-service-accounts
  community/modules/project/service-account/README.md
  community/modules/project/service-account/variables.tf
  community/modules/scheduler/htcondor-service-accounts/README.md
  community/modules/scheduler/htcondor-service-accounts/variables.tf
Labels: release-chore

#2230 Slurm-GCP Release 6.4.1
  community/examples/hpc-build-slurm-image.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
  examples/README.md
  modules/README.md
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-tpu.yaml
Labels: release-version-updates

#2265 Improve `tools/cloud-build/provision/list_tests.py`
  tools/cloud-build/provision/list-tests.tf
  tools/cloud-build/provision/list_tests.py
Labels: release-chore

#2275 Slurm6. Fix bug that prevents specifying `partition_conf`
  community/modules/compute/schedmd-slurm-gcp-v6-partition/main.tf
Labels: release-chore

#2209 Don't persist evaluated `Blueprint.Vars`
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/dict.go
  pkg/config/expand.go
  pkg/config/expression.go
  pkg/config/validate.go
  pkg/config/validator_test.go
  pkg/modulewriter/packerwriter.go
  pkg/modulewriter/tfwriter.go
  pkg/validators/quota.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/text_escape/.ghpc/artifacts/expanded_blueprint.yaml
Labels: release-chore

#2221 Slurm6. more validations around `static/exclusive/placement/reservation`
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/outputs.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/outputs.tf
Labels: release-chore

#2281 Add some additional slurm v6 tests to the babysitter
  tools/cloud-build/babysit_tests.py
Labels: release-chore

#2280 Updated Slurm v6 version, fix placement error
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
Labels: release-version-updates

#2278 Remove `DeploymentConfig struct`, use `Blueprint` instead.
  cmd/create.go
  cmd/create_test.go
  cmd/deploy.go
  cmd/destroy.go
  cmd/expand.go
  cmd/export.go
  cmd/import.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/expand_test.go
  pkg/modulewriter/modulewriter.go
  pkg/modulewriter/modulewriter_test.go
  pkg/modulewriter/packerwriter.go
  pkg/modulewriter/tfwriter.go
  pkg/shell/terraform.go
Labels: release-chore

#2279 Prevent usage of placement with static and auto-scale nodes in same nodeset
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/outputs.tf
Labels: release-module-improvements

#2285 Add collection of slurmctld and slurmsync to tests
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
Labels: release-chore

#2283 Fix for wait-for-startup.yml ansible task
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/wait-for-startup-script.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-batch-submission.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-monitoring.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-spack.yml
Labels: release-bugfix

#2277 Fix trailing whitespace in YAML expressions rendering
  pkg/config/expression.go
  pkg/modulewriter/hcl_utils_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
Labels: release-chore

#2291 Bump Golang version 1.20 -> 1.21
  go.mod
  go.sum
  tools/cloud-build/provision/pr-go-build-test.tf
Labels: release-version-updates

#2292 Adopt maintenance_interval throughout Slurm v6 modules
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-chore

#2290 Use fixed ubunut image by name in CRD test
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/variables.tf
  tools/cloud-build/daily-tests/blueprints/crd-ubuntu.yaml
Labels: release-chore

#2295 Add back v5 version of hpc-slurm blueprint and integration test
  examples/README.md
  examples/hpc-slurm-v5-legacy.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-hpc-centos7.yaml
  tools/cloud-build/daily-tests/tests/slurm-v5-hpc-centos7.yml
Labels: release-chore

#2286 Allow expressions in backend specs
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/expand.go
  pkg/config/expand_test.go
  pkg/modulewriter/tfwriter.go
  tools/validate_configs/golden_copies/configs/igc_tf.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/main.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/main.tf
Labels: release-chore

#2271 Use `bufio.Reader` instead of`fmt.Scanln` for user prompts
  pkg/shell/common.go
Labels: release-chore

#2282 Perform explicit cyclic dependencies check in `validateVars`
  pkg/config/config.go
  pkg/config/validate.go
  pkg/config/validator_test.go
Labels: release-chore

#2300 Add documentation in example folder about Slurm migration to v6
  examples/README.md
Labels: release-chore

#2299 Update several Slurm-GCP 6.4.1 tags to 6.4.2 to align with modules
  community/examples/hpc-build-slurm-image.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  examples/README.md
  modules/README.md
Labels: release-chore

#2301 Avoid `Error: the variable "labels" was not used in this blueprint`
  pkg/config/config.go
  pkg/config/config_test.go
Labels: release-chore

#2212 Update Slurm docs to reference auto-scaling nodes instead of dynamic
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
Labels: release-chore

#2302 Update naming convention for hpc-slurm blueprint for v5 and v6 versions
  examples/README.md
  examples/hpc-slurm-v6.yaml
  examples/hpc-slurm.yaml
  tools/cloud-build/daily-tests/tests/slurm-v5-hpc-centos7.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-rocky8.yml
Labels: release-chore

#2306 Tweak formatting on v6 migration
  examples/README.md
Labels: release-chore

#2287 Add TPU v4 blueprint and tutorial to demonstrate running TPU workload
  community/examples/hpc-slurm6-tpu-v4.md
  community/examples/hpc-slurm6-tpu-v4.yaml
  community/examples/hpc-slurm6-tpu.yaml
Labels: release-improvements

#2309 Extend timeout by 5 minutes on test
  tools/cloud-build/daily-tests/blueprints/crd-default.yaml
Labels: release-chore

#2310 Set providers config setting regardless of usage by modules
  pkg/config/config.go
  pkg/modulewriter/modulewriter_test.go
  pkg/modulewriter/tfwriter.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/providers.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/one/providers.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/providers.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/terraform.tfvars
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/variables.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/providers.tf
Labels: release-chore
