Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2024-04, with the labels that each got.

#2421 Fixes for workstation creation - new extension added for yaml
  tools/cloud-workstations/200_configure-hpc-toolkit.sh
  tools/cloud-workstations/Dockerfile
  tools/cloud-workstations/README.md
  tools/cloud-workstations/code_oss_requirements.txt
  tools/cloud-workstations/configure-hpc-toolkit.sh
Labels: release-bugfix

#2423 Move GKE tests to better flow
  tools/cloud-build/daily-tests/builds/gke-storage.yaml
  tools/cloud-build/daily-tests/builds/gke.yaml
Labels: release-chore

#2426 Move tests `{h|l|m}.*` to the better flow
  tools/cloud-build/daily-tests/builds/hcls.yaml
  tools/cloud-build/daily-tests/builds/hpc-build-slurm-image.yaml
  tools/cloud-build/daily-tests/builds/hpc-enterprise-slurm.yaml
  tools/cloud-build/daily-tests/builds/hpc-slurm-chromedesktop.yaml
  tools/cloud-build/daily-tests/builds/htc-slurm-v6.yaml
  tools/cloud-build/daily-tests/builds/htcondor.yaml
  tools/cloud-build/daily-tests/builds/lustre-slurm-v6.yaml
  tools/cloud-build/daily-tests/builds/lustre-slurm.yaml
  tools/cloud-build/daily-tests/builds/lustre-vm.yaml
  tools/cloud-build/daily-tests/builds/ml-slurm-v6.yaml
  tools/cloud-build/daily-tests/builds/ml-slurm.yaml
Labels: release-chore

#2412 Remove unused `max_nodes` from tests
  tools/cloud-build/daily-tests/tests/hcls.yml
  tools/cloud-build/daily-tests/tests/hpc-enterprise-slurm.yml
  tools/cloud-build/daily-tests/tests/hpc-slurm-chromedesktop.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-debian.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-hpc-centos7.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-rocky8.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-startup-scripts.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-ubuntu.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-centos7.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-debian.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-rocky8.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-ssd.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-startup-scripts.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-tpu.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-ubuntu.yml
  tools/cloud-build/daily-tests/tests/spack-gromacs.yml
Labels: release-chore

#2436 Merge hotfix release v1.31.1 into develop branch
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  examples/machine-learning/README.md
  examples/machine-learning/ml-slurm-a3-2-cluster.yaml
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2417 Initial commit of tool for creating new release candidate
  tools/create-release-candidate.sh
Labels: release-chore

#2438 Move Slurm6 tests to the better flow
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-centos7.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-debian.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-rocky8.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-ssd.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-startup-scripts.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-tpu.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-ubuntu.yaml
  tools/cloud-build/daily-tests/builds/spack-gromacs.yaml
Labels: release-chore

#2441 Update description of reservation_name for Slurm compute nodes
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
Labels: release-chore

#2439 Match yaml files in `ghpc deploy` autocomplete
  cmd/deploy.go
Labels: release-chore

#2433 Add Jupyter UI component to the babysiter code
  tools/cloud-build/babysit/cli_ui.py
  tools/cloud-build/babysit/notebook_ui.py
  tools/cloud-build/babysit/runner.py
Labels: release-chore

#2442 Fix output precondition for #2441
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/outputs.tf
Labels: release-chore

#2406 Add support for `ghpc_stage` in module.settings
  cmd/create.go
  cmd/deploy.go
  cmd/destroy.go
  cmd/export.go
  cmd/import.go
  pkg/config/config.go
  pkg/config/expression.go
  pkg/config/materialize.go
  pkg/config/staging.go
  pkg/config/staging_test.go
  tools/validate_configs/golden_copies/configs/files/local_mount.txt
  tools/validate_configs/golden_copies/configs/igc_tf.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/staged/local_mount.txt_76c024cd89
  tools/validate_configs/golden_copies/expectations/igc_tf/one/main.tf
  tools/validate_configs/golden_copies/validate.sh
Labels: release-chore

#2325 Add SlurmGCP v6 version of CAE blueprint
  examples/README.md
  examples/cae/README.md
  examples/cae/cae-slurm-v6.yaml
Labels: release-improvements

#2408 Roll forward "Add example using Slurm static compute nodes"
  examples/README.md
  examples/hpc-slurm-static-v6.yaml
  tools/cloud-build/daily-tests/ansible_playbooks/post-destroy-tasks/delete-reservation.yml
  tools/cloud-build/daily-tests/ansible_playbooks/pre-deploy-tasks/create-reservation.yml
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/rescue_ghpc_failure.yml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-static.yaml
  tools/cloud-build/daily-tests/tests/slurm-v6-static.yml
Labels: release-improvements

#2445 Update gcc to 13.1.0 on Rocky 8 Gromacs example
  community/examples/hpc-slurm-gromacs.yaml
Labels: release-improvements

#2447 Adopt latest versions of internal modules
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/pbspro-execution/README.md
  community/modules/compute/pbspro-execution/main.tf
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/main.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/htcondor-service-accounts/README.md
  community/modules/scheduler/htcondor-service-accounts/main.tf
  community/modules/scheduler/pbspro-client/README.md
  community/modules/scheduler/pbspro-client/main.tf
  community/modules/scheduler/pbspro-server/README.md
  community/modules/scheduler/pbspro-server/main.tf
  community/modules/scripts/ramble-execute/README.md
  community/modules/scripts/ramble-execute/main.tf
  community/modules/scripts/ramble-setup/README.md
  community/modules/scripts/ramble-setup/main.tf
  community/modules/scripts/spack-execute/README.md
  community/modules/scripts/spack-execute/main.tf
  community/modules/scripts/spack-setup/README.md
  community/modules/scripts/spack-setup/main.tf
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/startup_from_network_storage.tf
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/startup_from_network_storage.tf
  modules/scheduler/batch-login-node/README.md
  modules/scheduler/batch-login-node/main.tf
Labels: release-chore

#2448 Use "wait for startup" instead of "sleep 2min" in base tests
  tools/cloud-build/daily-tests/ansible_playbooks/base-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-batch-submission.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-monitoring.yml
Labels: release-chore

#2366 Add SlurmGCP v6 version of hcls blueprint and integration test
  docs/videos/healthcare-and-life-sciences/README.md
  examples/README.md
  examples/hcls-blueprint-v6.yaml
  tools/cloud-build/daily-tests/builds/hcls-v6.yaml
  tools/cloud-build/daily-tests/tests/hcls-v6.yml
Labels: release-improvements

#2446 Use `ghpc_stage` in slurm-htc examples
  community/examples/htc-slurm-v6.yaml
  community/examples/htc-slurm.yaml
  tools/validate_configs/validate_configs.sh
Labels: release-chore

#2443 Remove dependency between controller instance and cleanup_compute_nodes
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
Labels: release-chore

#2449 Updating garther startup script and integration test
  tools/cloud-build/daily-tests/ansible_playbooks/base-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/gather_startup_script_logs.yml
Labels: release-bugfix

#2456 Update MPI & Gromacs for cache hit and better compatibility w/ Rocky8 default image
  community/examples/hpc-slurm-gromacs.yaml
Labels: release-improvements

#2455 Advise A3 users to request DLVM image earlier and more prominently in documentation
  examples/machine-learning/README.md
Labels: release-chore

#2424 Make deployment file command line option visible
  cmd/expand.go
Labels: release-key-new-features

#2444 Add `examples/hpc-enterprise-slurm-v6.yml` + test
  examples/README.md
  examples/hpc-enterprise-slurm-v6.yaml
  tools/cloud-build/daily-tests/builds/hpc-enterprise-slurm-v6.yaml
  tools/cloud-build/daily-tests/tests/hpc-enterprise-slurm-v6.yml
Labels: release-chore

#2458 Update TPU maxtext blueprint and documentation
  community/examples/hpc-slurm6-tpu-maxtext.yaml
  docs/hpc-slurm6-tpu-maxtext.md
Labels: release-chore

#2460 Add `self_link` output to `vm-instance` module
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/outputs.tf
Labels: release-chore

#2465 Go binary downloads must include patch version
  community/front-end/ofe/infrastructure_files/gcs_bucket/webserver/startup.sh
Labels: release-bugfix

#2462 Resolve Ansible crash in Spack installation
  community/modules/scripts/ramble-setup/templates/ramble_setup.yml.tftpl
  community/modules/scripts/spack-setup/templates/spack_setup.yml.tftpl
Labels: release-bugfix

#2407 Update hpc-slurm-ramble-gromac example to use Slurm-GCP v6 modules
  community/examples/hpc-slurm-ramble-gromacs-v6.yaml
  examples/README.md
Labels: release-improvements

#2450 MultiVPC Module
  modules/README.md
  modules/network/multivpc/README.md
  modules/network/multivpc/main.tf
  modules/network/multivpc/metadata.yaml
  modules/network/multivpc/outputs.tf
  modules/network/multivpc/variables.tf
  modules/network/multivpc/versions.tf
Labels: release-new-modules

#2470 Ensure that Filestore cleanup always re-enables the Filestore API
  tools/clean-filestore-limit.sh
Labels: release-chore

#2469 Address feature requests for HTCondor functionality in Windows
  community/modules/scripts/htcondor-install/README.md
  community/modules/scripts/htcondor-install/main.tf
  community/modules/scripts/htcondor-install/templates/install-htcondor.ps1.tftpl
  community/modules/scripts/htcondor-install/variables.tf
  community/modules/scripts/windows-startup-script/README.md
  community/modules/scripts/windows-startup-script/main.tf
  community/modules/scripts/windows-startup-script/templates/setx_http_proxy.ps1
  community/modules/scripts/windows-startup-script/variables.tf
Labels: release-module-improvements

#2466 Simplify release-candidate creation script
  tools/create-release-candidate.sh
Labels: release-chore

#2437 Move packer and slurm5 tests to the better flow
  tools/cloud-build/daily-tests/builds/packer-v6.yaml
  tools/cloud-build/daily-tests/builds/packer.yaml
  tools/cloud-build/daily-tests/builds/pbspro.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-debian.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-hpc-centos7.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-rocky8.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-startup-scripts.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-ubuntu2004.yaml
Labels: release-chore

#2474 Remove validation check for boot disk type in nodeset module
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
Labels: release-chore

#2476 Update version number in OFE requirements
  community/front-end/ofe/requirements.txt
Labels: dependencies, release-chore

#2411 Add Slurm-gcp v6 example for hpc-amd-slurm blueprint and references
  community/examples/AMD/README.md
  community/examples/AMD/hpc-amd-slurm-v6.yaml
  examples/README.md
Labels: release-improvements

#2403 Fix "unused module validation" failures caused by crude deprecation
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
  pkg/inspect/modules_test.go
Labels: release-chore

#2480 Correct path for ofe deploy script
  community/front-end/ofe/README.md
Labels: release-chore

#2484 Make project cleanup more resiliant
  tools/cloud-build/project-cleanup.yaml
  tools/cloud-build/provision/daily-cleanup.tf
Labels: release-chore

#2493 Fix typo in version number to v1.32.1
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2482 Remove private cache as example is backed by public cache
  tools/cloud-build/daily-tests/builds/spack-gromacs.yaml
Labels: release-chore

#2485 Add docs about `ghpc_stage` and other functions
  examples/README.md
Labels: release-key-new-features

#2490 Merge `main` branch to `develop` branch as part of Release Process
  cmd/root.go
  community/front-end/ofe/website/ghpcfe/cluster_manager/clusterinfo.py
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2494 Project cleanup. Look only at relevant builds.
  tools/cloud-build/project-cleanup.yaml
Labels: release-chore

#2495 Slurm6. Replace `service_account` with `service_account_email|scopes`
  community/examples/intel/hpc-slurm-daos.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
  examples/hpc-enterprise-slurm-v6.yaml
  tools/validate_configs/test_configs/node-groups-v6.yaml
Labels: release-module-improvements

#2489 Add startup-script option to automatically install Docker at boot
  modules/scripts/startup-script/README.md
  modules/scripts/startup-script/files/install_docker.yml
  modules/scripts/startup-script/main.tf
  modules/scripts/startup-script/variables.tf
Labels: release-key-new-features

#2499 Update internal usage of modules on develop branch as part of Release Process
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/pbspro-execution/README.md
  community/modules/compute/pbspro-execution/main.tf
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/main.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/htcondor-service-accounts/README.md
  community/modules/scheduler/htcondor-service-accounts/main.tf
  community/modules/scheduler/pbspro-client/README.md
  community/modules/scheduler/pbspro-client/main.tf
  community/modules/scheduler/pbspro-server/README.md
  community/modules/scheduler/pbspro-server/main.tf
  community/modules/scripts/ramble-execute/README.md
  community/modules/scripts/ramble-execute/main.tf
  community/modules/scripts/ramble-setup/README.md
  community/modules/scripts/ramble-setup/main.tf
  community/modules/scripts/spack-execute/README.md
  community/modules/scripts/spack-execute/main.tf
  community/modules/scripts/spack-setup/README.md
  community/modules/scripts/spack-setup/main.tf
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/startup_from_network_storage.tf
  modules/network/multivpc/README.md
  modules/network/multivpc/main.tf
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/startup_from_network_storage.tf
  modules/scheduler/batch-login-node/README.md
  modules/scheduler/batch-login-node/main.tf
Labels: release-chore

#2501 Remove extra 'v' in versions generated by `create-release-candidate.sh`
  tools/create-release-candidate.sh
Labels: release-chore

#2503 Run project cleanup daily, including weekends
  tools/cloud-build/provision/daily-cleanup.tf
Labels: release-chore

#2472 Update Slurm troubleshooting docs to clarify behavior on stockout
  docs/slurm-troubleshooting.md
Labels: release-chore

#2492 Babysit. Set default value for `--project`
  tools/cloud-build/babysit/runner.py
Labels: release-chore

#2481 Update instructions to not assume project id is set in gcloud config
  modules/compute/vm-instance/outputs.tf
Labels: release-chore

#2505 Add sleep to Filestore command
  tools/clean-filestore-limit.sh
Labels: release-chore

#2486 Slurm6. Replace vars `disable_X -> enable_X`
  community/examples/AMD/hpc-amd-slurm-v6.yaml
  community/examples/hpc-slurm-gromacs.yaml
  community/examples/hpc-slurm-local-ssd-v6.yaml
  community/examples/hpc-slurm-ramble-gromacs-v6.yaml
  community/examples/hpc-slurm-sharedvpc.yaml
  community/examples/hpc-slurm-ubuntu2004-v6.yaml
  community/examples/hpc-slurm6-tpu-maxtext.yaml
  community/examples/hpc-slurm6-tpu.yaml
  community/examples/htc-slurm-v6.yaml
  community/examples/intel/hpc-slurm-daos.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
  docs/tutorials/gromacs/spack-gromacs.yaml
  docs/tutorials/hpc-slurm-qwiklabs.yaml
  docs/tutorials/openfoam/spack-openfoam.yaml
  docs/tutorials/sc23-tutorial/hcls-blueprint.yaml
  docs/tutorials/wrfv3/spack-wrfv3.yaml
  examples/hpc-enterprise-slurm-v6.yaml
  examples/hpc-slurm-static-v6.yaml
  examples/hpc-slurm-v6.yaml
  examples/image-builder-v6.yaml
  examples/ml-slurm-v6.yaml
  tools/cloud-build/daily-tests/blueprints/lustre-slurm-v6.yaml
  tools/validate_configs/test_configs/config-ssh.yaml
  tools/validate_configs/test_configs/gpu-v6.yaml
  tools/validate_configs/test_configs/hpc-cluster-simple-nfs-sql.yaml
  tools/validate_configs/test_configs/node-groups-v6.yaml
  tools/validate_configs/test_configs/slurm-gcp-v6-startup-scripts.yaml
  tools/validate_configs/test_configs/zone-policies-slurm-v6.yaml
Labels: release-module-improvements

#2509 Update hcls v6 test public ip deployment variables
  tools/cloud-build/daily-tests/tests/hcls-v6.yml
Labels: release-chore

#2413 Remove "hard" dependency between login instance and controller instance
  community/examples/hpc-build-slurm-image.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
Labels: release-module-improvements

#2517 Update network storage document for Slurm v6 support
  docs/network_storage.md
Labels: release-chore

#2515 Allow the `wait-for-startup` module to take a list of instance names
  community/modules/scripts/wait-for-startup/README.md
  community/modules/scripts/wait-for-startup/main.tf
  community/modules/scripts/wait-for-startup/scripts/wait-for-startup-status.sh
  community/modules/scripts/wait-for-startup/variables.tf
  community/modules/scripts/wait-for-startup/versions.tf
Labels: release-module-improvements

#2510 Split `daily_cleanup` on `filestore` and `slurm` parts
  tools/clean-filestore-limit.sh
  tools/cloud-build/project-cleanup-filestore.yaml
  tools/cloud-build/project-cleanup-slurm.yaml
  tools/cloud-build/provision/README.md
  tools/cloud-build/provision/daily-cleanup.tf
Labels: release-chore

#2518 Fix conflicting names in test infra provisioner
  tools/cloud-build/provision/README.md
  tools/cloud-build/provision/daily-cleanup.tf
  tools/cloud-build/provision/variables.tf
Labels: release-chore

#2479 Simplify "cleanup compute"
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/cleanup.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/scripts/cleanup_compute.sh
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
Labels: release-module-improvements

#2513 Fix Race condition and add validation for mount_runner in community/modules/compute/notebook/main.tf
  community/modules/compute/notebook/main.tf
  community/modules/compute/notebook/variables.tf
Labels: release-chore

#2519 Infra chores.
  tools/cloud-build/babysit_tests.py
  tools/cloud-build/provision/zebug.tf
Labels: release-chore

#2520 Add an option to skip `Ensure all nodes are powered down` in slurm tests
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
Labels: release-chore

#2514 Copy labels from the batch-job-template module to the actual Batch job spec
  modules/scheduler/batch-job-template/main.tf
  modules/scheduler/batch-job-template/templates/batch-job-base.yaml.tftpl
Labels: release-module-improvements

#2526 Replace `TfError` with `HintError`
  pkg/shell/packer.go
  pkg/shell/packer_test.go
  pkg/shell/terraform.go
  pkg/shell/terraform_test.go
Labels: release-chore

#2533 Update usage instructions for babysitter
  tools/cloud-build/babysit/run
  tools/cloud-build/babysit/runner.py
Labels: release-chore

#2531 Slurm6. Automatically set login intances name, don't put role into it
  community/examples/AMD/hpc-amd-slurm-v6.yaml
  community/examples/hpc-slurm-gromacs.yaml
  community/examples/hpc-slurm-local-ssd-v6.yaml
  community/examples/hpc-slurm-ramble-gromacs-v6.yaml
  community/examples/hpc-slurm-sharedvpc.yaml
  community/examples/hpc-slurm-ubuntu2004-v6.yaml
  community/examples/hpc-slurm6-tpu-maxtext.yaml
  community/examples/hpc-slurm6-tpu.yaml
  community/examples/htc-slurm-v6.yaml
  community/examples/intel/hpc-slurm-daos.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/metadata.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
  docs/tutorials/gromacs/spack-gromacs.yaml
  docs/tutorials/hpc-slurm-qwiklabs.yaml
  docs/tutorials/openfoam/spack-openfoam.yaml
  docs/tutorials/wrfv3/spack-wrfv3.yaml
  examples/cae/cae-slurm-v6.yaml
  examples/hcls-blueprint-v6.yaml
  examples/hpc-enterprise-slurm-v6.yaml
  examples/hpc-slurm-static-v6.yaml
  examples/hpc-slurm-v6.yaml
  examples/image-builder-v6.yaml
  examples/ml-slurm-v6.yaml
  tools/cloud-build/daily-tests/blueprints/lustre-slurm-v6.yaml
  tools/validate_configs/test_configs/config-ssh.yaml
  tools/validate_configs/test_configs/gpu-v6.yaml
  tools/validate_configs/test_configs/hpc-cluster-simple-nfs-sql.yaml
  tools/validate_configs/test_configs/node-groups-v6.yaml
  tools/validate_configs/test_configs/slurm-gcp-v6-startup-scripts.yaml
  tools/validate_configs/test_configs/zone-policies-slurm-v6.yaml
Labels: release-module-improvements
