Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2024-06, with the labels that each got.

#2577 Add additional interfaces to Slurm login nodes
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
Labels: release-chore

#2631 Add options to specify authorized networks for slurm-cloudsql
  community/modules/database/slurm-cloudsql-federation/README.md
  community/modules/database/slurm-cloudsql-federation/main.tf
  community/modules/database/slurm-cloudsql-federation/variables.tf
Labels: release-module-improvements

#2657 Add topologically-aware NCCL tests solution to A3 Mega
  examples/machine-learning/a3-highgpu-8g/README.md
  examples/machine-learning/a3-megagpu-8g/nccl-tests/run-topological-nccl-tests.sh
Labels: release-improvements

#2661 Cleanup A3 Mega images after building them in integration test
  tools/cloud-build/daily-tests/builds/ml-a3-megagpu-slurm.yaml
Labels: release-chore

#2663 SlurmGCP V5 relax `disk_type` validation
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
Labels: release-chore

#2635 Initial commit for adding in `terraform_providers` block to ghpc
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/expand.go
  pkg/config/expand_test.go
  pkg/config/materialize.go
  pkg/config/path.go
  pkg/config/path_test.go
  pkg/config/staging.go
  pkg/config/staging_test.go
  pkg/modulewriter/modulewriter_test.go
  pkg/modulewriter/tfwriter.go
  tools/enforce_coverage.pl
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
Labels: release-key-new-features

#2664 SlurmGCP V6 remove support for custom instance templates
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
Labels: release-deprecations

#2666 Revert "SlurmGCP V6 remove support for custom instance templates"
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
Labels: release-chore

#2668 Update slurm tags for `ml-a3-megagpu-slurm` test
  tools/cloud-build/daily-tests/builds/ml-a3-megagpu-slurm.yaml
Labels: release-chore

#2640 Add support for shared reservations
  community/examples/hpc-build-slurm-image.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/outputs.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
  modules/README.md
Labels: release-module-improvements

#2658 Add `--skip` and `--only` to `deploy` and `destroy` commands
  cmd/deploy.go
  cmd/destroy.go
  cmd/utils.go
  cmd/utils_test.go
  pkg/config/config.go
  pkg/config/expand.go
  pkg/config/validate.go
Labels: release-improvements

#2667 SlurmGCP V6 remove support for custom instance templates
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
Labels: release-deprecations

#2662 Update GKE ML blueprint to use native GKE driver
  community/examples/ml-gke.yaml
  community/modules/scripts/kubernetes-operations/README.md
  examples/README.md
  modules/README.md
Labels: release-module-improvements

#2669 Add tmux util to Cloud workstation image
  tools/cloud-workstations/Dockerfile
Labels: release-chore

#2672 Add reference validation to all expressions in blueprint
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/expand.go
  pkg/config/materialize.go
  pkg/config/path.go
  pkg/config/staging.go
  pkg/config/staging_test.go
Labels: release-chore

#2681 Check string literals for absence of expressions
  pkg/config/config.go
  pkg/config/config_test.go
Labels: release-chore

#2682 Add stand alone MIG module
  community/modules/compute/mig/README.md
  community/modules/compute/mig/main.tf
  community/modules/compute/mig/metadata.yaml
  community/modules/compute/mig/outputs.tf
  community/modules/compute/mig/variables.tf
  community/modules/compute/mig/versions.tf
Labels: release-new-modules

#2689 Run pre-commit to validate PR in main branch
  .github/workflows/pr-precommit.yml
Labels: release-chore

#2690 Move test to Europe region where test has reserved gpu
  tools/cloud-build/daily-tests/tests/hcls.yml
Labels: release-chore

#2597 Add `pre-existing-subnetwork` module
  modules/network/pre-existing-subnetwork/README.md
  modules/network/pre-existing-subnetwork/main.tf
  modules/network/pre-existing-subnetwork/metadata.yaml
  modules/network/pre-existing-subnetwork/outputs.tf
  modules/network/pre-existing-subnetwork/variables.tf
  modules/network/pre-existing-subnetwork/versions.tf
Labels: release-new-modules

#2688 Update to fix OFE filestore
  community/front-end/ofe/website/ghpcfe/cluster_manager/filesystem.py
Labels: release-bugfix

#2683 Exposes TreeWidth and TopologyPlugin in blueprints
  community/examples/hpc-build-slurm-image.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-2-cluster.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
  modules/README.md
Labels: release-module-improvements

#2692 Minor updates to create rc script
  tools/cloud-build/babysit/run
  tools/create-release-candidate.sh
Labels: release-chore

#2693 Prevent mixing dynamic and non-dynamic nodesets in single partition
  community/modules/compute/schedmd-slurm-gcp-v6-partition/outputs.tf
Labels: release-chore

#2694 Added GKE integration test for ml-gke yaml blueprint
  tools/cloud-build/daily-tests/builds/ml-gke.yaml
  tools/cloud-build/daily-tests/tests/ml-gke.yml
Labels: release-chore

#2691 Update Toolkit release to v1.35.0
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2700 OFE: new features - edited history
  community/front-end/ofe/deploy.sh
  community/front-end/ofe/infrastructure_files/gcs_bucket/webserver/startup.sh
  community/front-end/ofe/infrastructure_files/vpc_tf/GCP/README.md
  community/front-end/ofe/infrastructure_files/vpc_tf/GCP/main.tf
  community/front-end/ofe/infrastructure_files/vpc_tf/GCP/versions.tf
  community/front-end/ofe/website/ghpcfe/cluster_manager/cloud_info.py
  community/front-end/ofe/website/ghpcfe/forms.py
  community/front-end/ofe/website/ghpcfe/models.py
  community/front-end/ofe/website/ghpcfe/templates/blueprint/cloudsql_config.yaml.j2
  community/front-end/ofe/website/ghpcfe/templates/blueprint/cluster_config.yaml.j2
  community/front-end/ofe/website/ghpcfe/templates/blueprint/partition_config.yaml.j2
  community/front-end/ofe/website/ghpcfe/templates/cluster/update_form.html
  community/front-end/ofe/website/ghpcfe/views/clusters.py
Labels: release-improvements

#2670 Add 'source' argument for path to prolog or epilog scripts
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-module-improvements

#2687 Allow users to turn on access to cluster via GCP public IP address space
  community/modules/scheduler/gke-cluster/README.md
  community/modules/scheduler/gke-cluster/main.tf
  community/modules/scheduler/gke-cluster/variables.tf
Labels: enhancement, release-module-improvements

#2709 Merge main back to develop
  cmd/root.go
  community/front-end/ofe/deploy.sh
  community/front-end/ofe/infrastructure_files/gcs_bucket/webserver/startup.sh
  community/front-end/ofe/infrastructure_files/vpc_tf/GCP/README.md
  community/front-end/ofe/infrastructure_files/vpc_tf/GCP/main.tf
  community/front-end/ofe/infrastructure_files/vpc_tf/GCP/versions.tf
  community/front-end/ofe/website/ghpcfe/cluster_manager/cloud_info.py
  community/front-end/ofe/website/ghpcfe/forms.py
  community/front-end/ofe/website/ghpcfe/models.py
  community/front-end/ofe/website/ghpcfe/templates/blueprint/cloudsql_config.yaml.j2
  community/front-end/ofe/website/ghpcfe/templates/blueprint/cluster_config.yaml.j2
  community/front-end/ofe/website/ghpcfe/templates/blueprint/partition_config.yaml.j2
  community/front-end/ofe/website/ghpcfe/templates/cluster/update_form.html
  community/front-end/ofe/website/ghpcfe/views/clusters.py
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2707 Mention `ghpc deploy` in `cmd/README.md`
  cmd/README.md
Labels: documentation, release-chore

#2711 Update internal usage of Toolkit modules to v1.35.0
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/pbspro-execution/README.md
  community/modules/compute/pbspro-execution/main.tf
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/main.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/htcondor-service-accounts/README.md
  community/modules/scheduler/htcondor-service-accounts/main.tf
  community/modules/scheduler/pbspro-client/README.md
  community/modules/scheduler/pbspro-client/main.tf
  community/modules/scheduler/pbspro-server/README.md
  community/modules/scheduler/pbspro-server/main.tf
  community/modules/scripts/ramble-execute/README.md
  community/modules/scripts/ramble-execute/main.tf
  community/modules/scripts/ramble-setup/README.md
  community/modules/scripts/ramble-setup/main.tf
  community/modules/scripts/spack-execute/README.md
  community/modules/scripts/spack-execute/main.tf
  community/modules/scripts/spack-setup/README.md
  community/modules/scripts/spack-setup/main.tf
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/startup_from_network_storage.tf
  modules/network/multivpc/README.md
  modules/network/multivpc/main.tf
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/startup_from_network_storage.tf
  modules/scheduler/batch-login-node/README.md
  modules/scheduler/batch-login-node/main.tf
Labels: release-chore

#2710 Add mig module to the modules list
  modules/README.md
Labels: documentation, release-chore

#2712 Add a new post deploy test for gke cluster
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-job.yml
  tools/cloud-build/daily-tests/tests/ml-gke.yml
  tools/cloud-build/images/test-runner/Dockerfile
Labels: release-chore

#2680 Add known gpu types and their accelerators to gke module
  community/examples/ml-gke.yaml
  community/modules/compute/gke-node-pool/gpu_definition.tf
  community/modules/compute/gke-node-pool/main.tf
  examples/README.md
  tools/duplicate-diff.py
Labels: enhancement, release-module-improvements

#2704 Create 'pre-existing-gke-cluster' module
  community/modules/scheduler/gke-cluster/README.md
  community/modules/scheduler/gke-cluster/outputs.tf
  community/modules/scheduler/pre-existing-gke-cluster/README.md
  community/modules/scheduler/pre-existing-gke-cluster/main.tf
  community/modules/scheduler/pre-existing-gke-cluster/metadata.yaml
  community/modules/scheduler/pre-existing-gke-cluster/outputs.tf
  community/modules/scheduler/pre-existing-gke-cluster/variables.tf
  community/modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/README.md
Labels: release-new-modules

#2718 Disable force_destroy on bucket created in A3 Mega blueprint
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-cluster.yaml
Labels: release-chore

#2716 Hotfix 1.35.1
  cmd/root.go
  community/examples/hpc-build-slurm-image.yaml
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-cluster.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2722 Revert "Remove installation of enroot and pyxis from a3-highgpu-8g blueprint"
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
Labels: release-bugfix

#2727 Only enable gpu taints if guest_acclerator list is not empty
  community/modules/compute/gke-node-pool/main.tf
Labels: release-bugfix
