Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2024-11, with the labels that each got.

#3147 Improvements for CloudSQL
  community/modules/database/slurm-cloudsql-federation/README.md
  community/modules/database/slurm-cloudsql-federation/main.tf
  community/modules/database/slurm-cloudsql-federation/outputs.tf
  community/modules/database/slurm-cloudsql-federation/variables.tf
Labels: release-module-improvements

#3201 Add support for custom Docker daemon configuration
  modules/scripts/startup-script/README.md
  modules/scripts/startup-script/files/install_docker.yml
  modules/scripts/startup-script/main.tf
  modules/scripts/startup-script/variables.tf
Labels: release-key-new-features

#3190 Add example of using topology with pytorch
  examples/machine-learning/a3-megagpu-8g/topological-pytorch/README.md
  examples/machine-learning/a3-megagpu-8g/topological-pytorch/install.sh
  examples/machine-learning/a3-megagpu-8g/topological-pytorch/topological_pytorch.py
  examples/machine-learning/a3-megagpu-8g/topological-pytorch/topological_pytorch.sh
Labels: release-chore

#3200 Gke update default taints for user node pools
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/variables.tf
Labels: release-improvements

#3175 Update MTU for a3 mega for GKE based on best practices
  examples/gke-a3-highgpu.yaml
  examples/gke-a3-megagpu.yaml
Labels: release-improvements

#3181 add training example for gke parallelstore blueprint
  examples/gke-storage-parallelstore.yaml
  modules/compute/gke-job-template/README.md
  modules/compute/gke-job-template/main.tf
  modules/compute/gke-job-template/templates/gke-job-base.yaml.tftpl
  modules/compute/gke-job-template/variables.tf
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-storage-parallelstore.yml
Labels: release-improvements

#3206 Adopt local SSD storage for A3 docker images
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-2-cluster.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-cluster.yaml
  modules/scripts/startup-script/files/install_docker.yml
Labels: release-key-new-features

#3208 Update maintenance.py to support additional format
  tools/maintenance/maintenance.py
Labels: release-improvements

#3195 Bump SlurmGCP references for v6 and v5
  community/examples/hpc-build-slurm-image.yaml
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  docs/hybrid-slurm-cluster/demo-with-cloud-controller-instructions.md
  docs/hybrid-slurm-cluster/deploy-instructions.md
  docs/hybrid-slurm-cluster/on-prem-instructions.md
  docs/image-building.md
  examples/README.md
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/machine-learning/a3-highgpu-8g/v5-legacy/README.md
  examples/machine-learning/a3-highgpu-8g/v5-legacy/ml-slurm-a3-1-image-v5-legacy.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
  modules/README.md
Labels: release-chore

#3213 Allow latest Terraform google plugin
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: release-improvements

#3207 Fix docs for input_enable_default_mounts
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: documentation, release-chore

#3182 SlurmGCP. topology readme
  docs/slurm-topology.md
Labels: release-chore

#3211 Add c4a to the nosmt list
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3214 Refactor mount/mode setting for local SSD RAID
  modules/scripts/startup-script/files/setup-raid.yml
Labels: release-bugfix

#3174 Improve Error Message with Reservation Validation
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/reservation_definitions.tf
Labels: release-module-improvements

#3199 Fix SSH issues with integration tests
  tools/cloud-build/daily-tests/ansible_playbooks/base-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/htcondor-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/wait-for-host.yml
Labels: release-chore

#3212 Increasing ml-slurm test timeout to 5hr
  tools/cloud-build/daily-tests/builds/ml-slurm-v5-legacy.yaml
  tools/cloud-build/daily-tests/builds/ml-slurm.yaml
Labels: release-chore

#3226 Update ml-slurm examples to use recent copies of pytorch and tensorflow
  examples/README.md
  examples/ml-slurm-v5-legacy.yaml
  examples/ml-slurm.yaml
Labels: release-version-updates

#3216 SlurmGCP. Do not create placementPoliciy for a single VM
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
Labels: release-chore

#3228 Fix "too modern" type annotations
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
Labels: release-chore

#3222 Updates network_storage.md with Parallelstore info
  docs/network_storage.md
Labels: documentation, release-chore

#3231 Remove local_ssd warning
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
Labels: release-chore

#3217 Add in socket count info for c-series VMs
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3224 Cleanup Always when SSH Fails
  tools/cloud-build/daily-tests/ansible_playbooks/base-integration-test.yml
Labels: release-chore

#3232 update a3 machines local ssd to use nvme instead of scsi for better performance
  modules/compute/gke-node-pool/disk_definitions.tf
Labels: release-improvements

#3194 Improve fetching and caching job details
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-improvements

#3233 Fix regex for Job name in fetching job details
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3219 Adding retries to a3mega image blueprint
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
Labels: release-chore

#3235 Fix version constraint for resource-policy module
  modules/compute/resource-policy/README.md
  modules/compute/resource-policy/versions.tf
Labels: release-chore

#3239 Revert use of toolkit_modules_url in examples
  community/examples/tutorial-starccm-slurm.yaml
  docs/hybrid-slurm-cluster/blueprints/hybrid-configuration.yaml
Labels: release-chore

#3221 Update minimum Terraform release for gke-node-pool
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/versions.tf
Labels: release-chore

#3230 Make gke-node-pool compatible with TPG 6.x
  examples/README.md
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/variables.tf
  modules/compute/gke-node-pool/versions.tf
  tools/cloud-build/daily-tests/blueprints/ml-gke-e2e.yaml
Labels: release-version-updates

#3189 Adopt google Terraform plugin v6.10.0 and drop support for 5.x
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: release-key-new-features

#3244 SlurmGCP. Add workaround for #3242 to examples
  examples/hpc-enterprise-slurm-v5-legacy.yaml
  examples/hpc-enterprise-slurm.yaml
  examples/ml-slurm-v5-legacy.yaml
  examples/ml-slurm.yaml
Labels: release-chore

#3215 SlurmGCP. Add `set -e` to prolog mux
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/files/setup_external.sh
Labels: release-improvements

#3250 Fix formatting of Docker config warning
  modules/scripts/startup-script/main.tf
Labels: release-chore

#3229 Script for Python Tests
  tools/python-integration-tests/test.py
Labels: release-chore

#3251 Don't install Lustre in A3 tests
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/machine-learning/a3-highgpu-8g/v5-legacy/ml-slurm-a3-1-image-v5-legacy.yaml
Labels: release-chore

#3183 Add support for Filestore deletion protection
  modules/file-system/filestore/README.md
  modules/file-system/filestore/main.tf
  modules/file-system/filestore/variables.tf
  modules/file-system/filestore/versions.tf
Labels: release-key-new-features

#3253 Remove CentOS 7 from list of supported images
  docs/vm-images.md
Labels: release-chore

#3134 add gpu health check in prolog and epilog
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tools/gpu-test
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-cluster.yaml
Labels: release-improvements

#3257 Fix a bug where try was hiding extraction of gpu driver version
  modules/compute/gke-node-pool/main.tf
Labels: release-bugfix

#3252 SlurmGCP. Don't use remote module to create controller instance
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/outputs.tf
Labels: release-chore

#3259 Fix the gpu_installation_config default for case where no customer input
  modules/compute/gke-node-pool/main.tf
Labels: release-bugfix

#3262 add firewall to allow tcp traffic for parallelstore
  community/modules/network/private-service-access/README.md
  community/modules/network/private-service-access/outputs.tf
  examples/gke-storage-parallelstore.yaml
  tools/cloud-build/daily-tests/builds/gke-storage-parallelstore.yaml
Labels: release-improvements

#3260 add support for kueue v0.9.0 to enable TAS
  modules/management/kubectl-apply/README.md
  modules/management/kubectl-apply/manifests/kueue-v0.9.0.yaml
  modules/management/kubectl-apply/variables.tf
Labels: enhancement

#3255 Comment out pluging of `gpu-test`
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-cluster.yaml
Labels: release-chore

#3268 Allow specifying GKE's system node pool disk properties
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/variables.tf
Labels: release-improvements

#3266 SlurmGCP. Fix bug that prevents resourcePolicies clean up.
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
Labels: release-bugfix

#3272 Revert "update a3 machines local ssd to use nvme instead of scsi for better performance"
  modules/compute/gke-node-pool/disk_definitions.tf
Labels: release-bugfix

#3237 Adds Cluster Toolkit Dockerfile for backend integration with XPK
  tools/cloud-build/images/cluster-toolkit-dockerfile/Dockerfile
  tools/cloud-build/images/cluster-toolkit-dockerfile/README.md
Labels: enhancement, release-improvements

#3163 Add cluster and hostname as cloud ops labels
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/outputs.tf
Labels: release-chore

#3277 add support for kueue v0.9.0 to enable TAS
  modules/management/kubectl-apply/README.md
  modules/management/kubectl-apply/manifests/kueue-v0.9.0.yaml
  modules/management/kubectl-apply/variables.tf
Labels: release-key-new-features

#3279 add support for enable DCGM monitoring in GKE
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/variables.tf
Labels: release-module-improvements

#3280 add GKE support for node local dns
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/variables.tf
Labels: release-module-improvements

#3281 remove GKE reservation validation for local ssd NVMe/CSCI interface
  modules/compute/gke-node-pool/reservation_definitions.tf
Labels: release-bugfix

#3261 Update Toolkit release to v1.42.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3264 Print job detail for gke-storage-parallelstore integration test
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-storage-parallelstore.yml
Labels: release-improvements, test-enhancement

#3249 Enable Access to GCE Public IPs for the GKE Integration Test Clusters
  examples/gke-a3-highgpu.yaml
  examples/gke-a3-megagpu.yaml
  examples/gke-storage-parallelstore.yaml
  examples/hpc-gke.yaml
  examples/ml-gke.yaml
  examples/storage-gke.yaml
  tools/cloud-build/daily-tests/blueprints/ml-gke-e2e.yaml
  tools/cloud-build/daily-tests/tests/gke-a3-highgpu.yml
  tools/cloud-build/daily-tests/tests/gke-a3-megagpu.yml
  tools/cloud-build/daily-tests/tests/gke-storage-parallelstore.yml
  tools/cloud-build/daily-tests/tests/gke-storage.yml
  tools/cloud-build/daily-tests/tests/gke.yml
  tools/cloud-build/daily-tests/tests/ml-gke-e2e.yml
  tools/cloud-build/daily-tests/tests/ml-gke.yml
Labels: release-chore, test-enhancement

#3197 Add max_pods_per_node for GKE cluster and nodepool
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/variables.tf
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/variables.tf
Labels: enhancement, release-improvements

#3283 GPU definition changes
  community/modules/compute/htcondor-execute-point/gpu_definition.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/gpu_definition.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/gpu_definition.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/gpu_definition.tf
  modules/compute/gke-node-pool/gpu_definition.tf
  modules/compute/vm-instance/gpu_definition.tf
Labels: release-chore

#3284 NPI NIC types
  community/modules/compute/pbspro-execution/README.md
  community/modules/compute/pbspro-execution/variables.tf
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/variables.tf
Labels: release-chore

#3285 Update disk definitions
  modules/compute/gke-node-pool/disk_definitions.tf
Labels: release-chore

#3286 Update topology-scheduler-scripts.yaml
  community/modules/compute/gke-topology-scheduler/manifests/topology-scheduler-scripts.yaml
Labels: release-module-improvements

#3287 Fix image-building.md link
  docs/vm-images.md
Labels: release-improvements

#3290 Updating Cluster Toolkit Dockerfile README
  tools/cloud-build/images/cluster-toolkit-dockerfile/README.md
Labels: release-improvements

#3297 Merge `main` to `develop` (release v1.42.0)
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-cluster.yaml
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3299 Cluster changes for a3u
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/templates/gke-network-paramset.yaml.tftpl
  modules/scheduler/gke-cluster/variables.tf
  modules/scheduler/pre-existing-gke-cluster/README.md
  modules/scheduler/pre-existing-gke-cluster/main.tf
  modules/scheduler/pre-existing-gke-cluster/templates/gke-network-paramset.yaml.tftpl
  modules/scheduler/pre-existing-gke-cluster/variables.tf
Labels: release-key-new-features

#3301 Updating Go version in Cluster Toolkit Dockerfile
  tools/cloud-build/images/cluster-toolkit-dockerfile/Dockerfile
  tools/cloud-build/images/cluster-toolkit-dockerfile/README.md
Labels: release-improvements

#3298 Node pool changes a3u
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/reservation_definitions.tf
Labels: release-key-new-features

#3289 Add cloud rdma drivers into startup script module
  modules/scripts/startup-script/README.md
  modules/scripts/startup-script/files/install_cloud_rdma.sh
  modules/scripts/startup-script/main.tf
  modules/scripts/startup-script/variables.tf
Labels: release-key-new-features

#3302 Add Integration Test to Cluster Toolkit Dockerfile
  tools/cloud-build/daily-tests/builds/gcluster-dockerfile.yaml
  tools/cloud-build/daily-tests/validate_tests_metadata.py
Labels: release-improvements

#3192 XPK blueprint updates to make it more compatible with the tool
  community/examples/xpk-gke-a3-megagpu.yaml
Labels: release-improvements

#3307 Fix minor description error in cloud rdma variable
  docs/slurm-dws-flex.md
  modules/scripts/startup-script/README.md
  modules/scripts/startup-script/variables.tf
Labels: release-chore

#3304 expanding subnetwork_cidr_suffix
  examples/gke-a3-highgpu.yaml
  examples/gke-a3-megagpu.yaml
Labels: release-improvements

#3305 SlurmGCP. Don't set timeout on `scontrol reconfigure`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3311 Rename enable_cloud_rdma variable to install_cloud_rdma
  modules/scripts/startup-script/README.md
  modules/scripts/startup-script/files/install_cloud_rdma_drivers.sh
  modules/scripts/startup-script/main.tf
  modules/scripts/startup-script/variables.tf
Labels: release-chore

#3313 SlurmGCP. Specify `provisioning_model` for dense reservations.
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3306 Skip `test_apis_enabled` validator
  community/examples/fsi-montecarlo-on-batch.yaml
  docs/tutorials/sc23-tutorial/hcls-blueprint.yaml
  docs/videos/healthcare-and-life-sciences/hcls-blueprint-v5-legacy.yaml
  examples/hcls-blueprint.yaml
Labels: release-chore

#3312 Updating Slurm-GCP to 6.8.6
  community/examples/hpc-build-slurm-image.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
  modules/README.md
Labels: release-chore

#3316 SlurmGCP. Harden topology updates
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_topology.py
Labels: release-chore

#3314 Update Toolkit release to v1.43.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3315 Implemented kueue tests
  modules/management/kubectl-apply/variables.tf
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-kueue.yml
  tools/cloud-build/daily-tests/blueprints/gke-a2-highgpu.yaml
  tools/cloud-build/daily-tests/blueprints/kueue-config-files/block-topology-tas-small-job.yaml
  tools/cloud-build/daily-tests/blueprints/kueue-config-files/host-topology-tas-small-job.yaml
  tools/cloud-build/daily-tests/blueprints/kueue-config-files/kueue-configuration.yaml.tftpl
  tools/cloud-build/daily-tests/blueprints/kueue-config-files/rack-topology-tas-small-job.yaml
  tools/cloud-build/daily-tests/blueprints/kueue-config-files/sample-kueue-job.yaml
  tools/cloud-build/daily-tests/blueprints/kueue-config-files/tas-queues.yaml
  tools/cloud-build/daily-tests/builds/gke-a2-highgpu-kueue.yaml
  tools/cloud-build/daily-tests/tests/gke-a2-highgpu-kueue.yml
Labels: release-improvements
