Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2024-09, with the labels that each got.

#2970 Add integration test for Parallelstore (vm instances)
  examples/pfs-parallelstore.yaml
  modules/file-system/parallelstore/scripts/install-daos-client.sh
  modules/file-system/pre-existing-network-storage/scripts/install-daos-client.sh
  tools/cloud-build/daily-tests/builds/ps-vm-debian.yaml
  tools/cloud-build/daily-tests/tests/ps-vm-debian.yml
Labels: release-chore

#2998 Revert "SlurmGCP. Do not add empty startup scripts"
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-chore

#2997 Revisit the Reservation Interface for GKE Blueprints
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/variables.tf
Labels: release-module-improvements

#2993 Fix for cleanup script. The last input is optional
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/cleanup_compute/scripts/cleanup_compute.sh
Labels: release-bugfix

#2999 Update debian default image in chrome-remote-desktop module
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/variables.tf
Labels: release-chore

#2992 Catch "None" fields in slurm job datetime data for BigQuery
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/load_bq.py
Labels: release-bugfix

#2988 SlurmGCP. Don't skip clean up of "stopped" instances
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/cleanup_compute/scripts/cleanup_compute.sh
Labels: release-chore

#2987 Add enable-maintenance-reservation flag in slurm to control reservation for scheduled maintenance
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-key-new-features

#3002 Updating image builder for internal provider
  tools/cloud-build/images/test-runner/Dockerfile
  tools/cloud-build/images/test-runner/terraformrc
Labels: release-chore

#3009 Add cluster deployment step to a3-megagpu-8g integration test
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-cluster.yaml
  tools/cloud-build/daily-tests/builds/ml-a3-megagpu-slurm.yaml
  tools/cloud-build/daily-tests/tests/ml-a3-megagpu-slurm-cluster.yml
Labels: release-chore

#2957 Update gVNIC driver in A3 Mega solution
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
Labels: release-improvements

#2955 Implement udev-based approach to mounting aperture devices
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-cluster.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
Labels: release-improvements

#3007 Fix Slurm tag on A3 high integration test to match v6 blueprint
  tools/cloud-build/daily-tests/builds/ml-a3-highgpu-slurm.yaml
Labels: release-chore

#2958 Update Debian 12 image in A3 Mega solution
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
Labels: release-improvements

#3016 Update develop with Release Candidate
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/machine-learning/a3-highgpu-8g/v5-legacy/ml-slurm-a3-1-image-v5-legacy.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
Labels: release-chore

#3005 Default to zonal bulkInsert
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
Labels: release-module-improvements

#3014 Add documentation for reservation for scheduled maintenance
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
Labels: release-chore

#3015 Bump SlurmGCP references from 6.6.2 to 6.7.0
  community/examples/hpc-build-slurm-image.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
  modules/README.md
Labels: release-chore

#2983 Add enroot/pyxis step to a3 series integration tests
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-enroot.yml
  tools/cloud-build/daily-tests/tests/ml-a3-highgpu-slurm-cluster.yml
  tools/cloud-build/daily-tests/tests/ml-a3-megagpu-slurm-cluster.yml
Labels: release-chore

#2976 Remove default service account
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
Labels: release-chore

#3018 Ensure all example blueprints use official release of Toolkit modules
  community/examples/hpc-slurm6-tpu-maxtext.yaml
  community/examples/hpc-slurm6-tpu.yaml
  examples/hcls-blueprint.yaml
Labels: release-chore

#3003 Add machine type availability checks
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  tools/cloud-build/daily-tests/tests/hcls.yml
  tools/cloud-build/daily-tests/tests/hpc-enterprise-slurm.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-rocky8.yml
  tools/cloud-build/provision/reservations.tf
Labels: release-module-improvements

#3010 adding module cache to prevent repeated module downloads during modul…
  pkg/modulereader/resreader.go
Labels: enhancement, go, release-improvements

#3023 Update version from v1.38.0 to v1.39.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3026 Update zone for HCLS v5 (legacy) blueprint integration test
  tools/cloud-build/daily-tests/tests/hcls-v5-legacy.yml
Labels: release-chore

#3021 Update to RDMA VPC for reducing repeated code
  community/modules/network/rdma-vpc/README.md
  community/modules/network/rdma-vpc/main.tf
  community/modules/network/rdma-vpc/outputs.tf
  community/modules/network/rdma-vpc/variables.tf
Labels: release-chore

#3028 Merge v1.39.0 back into develop
  cmd/root.go
  community/examples/hpc-slurm6-tpu-maxtext.yaml
  community/examples/hpc-slurm6-tpu.yaml
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  examples/hcls-blueprint.yaml
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3012 add support for enabling tcpx/o in a3 and a3mega vm, provide script for injecting rxdm sidecar and other required components into user workload
  examples/gke-a3-highgpu.yaml
  examples/gke-a3-megagpu.yaml
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/gpu-direct-workload/sample-tcpx-workload-job.yaml
  modules/compute/gke-node-pool/gpu-direct-workload/sample-tcpxo-workload-job.yaml
  modules/compute/gke-node-pool/gpu-direct-workload/scripts/enable-tcpx-in-workload.py
  modules/compute/gke-node-pool/gpu-direct-workload/scripts/enable-tcpxo-in-workload.py
  modules/compute/gke-node-pool/gpu_direct.tf
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/outputs.tf
  modules/compute/gke-node-pool/versions.tf
Labels: release-module-improvements

#3019 Use Terraform naming conventions and TFLint rules
  examples/gke-a3-highgpu.yaml
  examples/gke-a3-megagpu.yaml
Labels: release-chore

#3022 Create default service account resource in controller only if service_account_email is null
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/main.tf
Labels: release-chore

#3030 Update module references to v1.39.0
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/pbspro-execution/README.md
  community/modules/compute/pbspro-execution/main.tf
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/main.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/htcondor-service-accounts/README.md
  community/modules/scheduler/htcondor-service-accounts/main.tf
  community/modules/scheduler/pbspro-client/README.md
  community/modules/scheduler/pbspro-client/main.tf
  community/modules/scheduler/pbspro-server/README.md
  community/modules/scheduler/pbspro-server/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scripts/ramble-execute/README.md
  community/modules/scripts/ramble-execute/main.tf
  community/modules/scripts/ramble-setup/README.md
  community/modules/scripts/ramble-setup/main.tf
  community/modules/scripts/spack-execute/README.md
  community/modules/scripts/spack-execute/main.tf
  community/modules/scripts/spack-setup/README.md
  community/modules/scripts/spack-setup/main.tf
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/startup_from_network_storage.tf
  modules/network/multivpc/README.md
  modules/network/multivpc/main.tf
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/startup_from_network_storage.tf
  modules/scheduler/batch-login-node/README.md
  modules/scheduler/batch-login-node/main.tf
Labels: release-chore

#3035 Remove references to hpc-centos-7
  community/modules/compute/pbspro-execution/README.md
  community/modules/compute/pbspro-execution/variables.tf
  community/modules/scheduler/pbspro-client/README.md
  community/modules/scheduler/pbspro-client/variables.tf
  community/modules/scheduler/pbspro-server/README.md
  community/modules/scheduler/pbspro-server/variables.tf
  docs/vm-images.md
  modules/scheduler/batch-job-template/README.md
  tools/cloud-build/daily-tests/builds/pbspro.yaml
  tools/validate_configs/os_compatibility_tests/batch-lustre.yaml
  tools/validate_configs/test_configs/cloud-batch-cft-instance-template.yaml
Labels: release-chore

#3033 Start daos-agent service in mount script
  modules/file-system/parallelstore/main.tf
  modules/file-system/parallelstore/scripts/install-daos-client.sh
  modules/file-system/parallelstore/scripts/mount-daos.sh
  modules/file-system/pre-existing-network-storage/outputs.tf
  modules/file-system/pre-existing-network-storage/scripts/install-daos-client.sh
  modules/file-system/pre-existing-network-storage/scripts/mount-daos.sh
Labels: release-chore

#3037 SlurmGCP. Remove usage of `google_compute_default_service_account`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/main.tf
Labels: release-chore

#3036 support ghpc_stage function in kubectl-apply module
  modules/management/kubectl-apply/README.md
  modules/management/kubectl-apply/kubectl/main.tf
Labels: release-module-improvements

#3042 Fix test-hpc-slurm-chromedesktop-v5-legacy to use valid reservation
  tools/cloud-build/daily-tests/tests/hpc-slurm-chromedesktop.yml
Labels: release-chore

#3038 SlurmGCP V6. Remove CentOS7 image support.
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/source_image_logic.tf
  tools/cloud-build/daily-tests/blueprints/lustre-slurm.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-centos7.yaml
  tools/cloud-build/daily-tests/tests/lustre-slurm.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-centos7.yml
  tools/validate_configs/test_configs/node-groups.yaml
Labels: release-deprecations

#2964 Add description as a hint to "missed required variable" error
  pkg/config/expand.go
Labels: release-chore

#3044 adding golden copy test for versioned blueprints feature
  tools/validate_configs/golden_copies/configs/versioned_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/DO_NOT_MODIFY_THIS_DIRECTORY
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/instructions.txt
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/main.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/outputs.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/providers.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/terraform.tfvars
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/variables.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: release-chore

#3048 Adding gcloud path override to wait-for-startup
  community/modules/scripts/wait-for-startup/README.md
  community/modules/scripts/wait-for-startup/main.tf
  community/modules/scripts/wait-for-startup/scripts/wait-for-startup-status.sh
  community/modules/scripts/wait-for-startup/variables.tf
Labels: release-chore

#3049 add additional vpc validation for a3/a3mega machine
  modules/compute/gke-node-pool/gpu_direct.tf
  modules/compute/gke-node-pool/variables.tf
Labels: release-improvements

#3017 Adds option to allow Kueue/Jobset to be installed on a GKE cluster via blueprints
  examples/gke-a3-highgpu.yaml
  examples/gke-a3-megagpu.yaml
  modules/management/kubectl-apply/README.md
  modules/management/kubectl-apply/main.tf
  modules/management/kubectl-apply/manifests/jobset-v0.5.2.yaml
  modules/management/kubectl-apply/manifests/kueue-v0.8.1.yaml
  modules/management/kubectl-apply/variables.tf
Labels: release-improvements

#3024 Validate Reservations in GKE Blueprints
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/reservation_definitions.tf
Labels: release-module-improvements

#3057 add argparse dependency to cloud build
  tools/cloud-build/requirements.txt
Labels: release-bugfix

#3055 adding documentation for versioned blueprint feature
  examples/README.md
Labels: documentation, release-key-new-features

#3059 update readme for gpudirect
  examples/README.md
  modules/compute/gke-node-pool/README.md
Labels: documentation, release-improvements

#3069 Update wording about DWS Flex
  docs/slurm-dws-flex.md
Labels: release-chore

#3052 adding unit test for version blueprint caching mechanism
  pkg/modulereader/resreader_test.go
Labels: release-key-new-features, release-improvements

#3046 Fix multivpc missing region
  modules/network/multivpc/main.tf
Labels: release-module-improvements

#3074 Fix missing argument
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
Labels: release-chore

#3073 Allow users to provide a commit hash instead of git tag for Spack and Ramble installations
  community/modules/scripts/ramble-setup/templates/ramble_setup.yml.tftpl
  community/modules/scripts/spack-setup/templates/spack_setup.yml.tftpl
Labels: release-bugfix

#3068 Add initial_node_count support to gke-node-pool
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/variables.tf
Labels: release-module-improvements

#3071 Improve `installing daos` script to be more non-interactive
  modules/file-system/parallelstore/scripts/install-daos-client.sh
  modules/file-system/parallelstore/scripts/mount-daos.sh
  modules/file-system/pre-existing-network-storage/scripts/install-daos-client.sh
  modules/file-system/pre-existing-network-storage/scripts/mount-daos.sh
Labels: release-chore

#3076 Update network_ip to use empty string
  community/modules/network/rdma-vpc/main.tf
Labels: release-chore

#3061 Fix parallelstore installation script on RHEL and Rocky Linux
  modules/file-system/parallelstore/scripts/install-daos-client.sh
  modules/file-system/pre-existing-network-storage/scripts/install-daos-client.sh
Labels: release-chore

#3040 removing deprecated spack setup variables
  community/modules/scripts/spack-setup/README.md
  community/modules/scripts/spack-setup/variables.tf
Labels: release-deprecations

#3041 removing deprecated ramble setup variables
  community/modules/scripts/ramble-setup/README.md
  community/modules/scripts/ramble-setup/variables.tf
Labels: release-deprecations

#3072 Update reservation for maintenance document to include compute alpha version support details
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  modules/compute/gke-node-pool/README.md
Labels: release-chore

#3078 Fixed the exact number constraint problem for additional vpcs in gpu_direct checks
  modules/compute/gke-node-pool/gpu_direct.tf
Labels: release-bugfix

#3081 resolving error when var.initial_node_count is null
  modules/compute/gke-node-pool/main.tf
Labels: bug, release-bugfix

#3083 Release candidate
  modules/compute/gke-node-pool/main.tf
Labels: release-chore

#3066 resource-policy module implemented
  modules/README.md
  modules/compute/resource-policy/resource-policy/README.md
  modules/compute/resource-policy/resource-policy/main.tf
  modules/compute/resource-policy/resource-policy/metadata.yaml
  modules/compute/resource-policy/resource-policy/outputs.tf
  modules/compute/resource-policy/resource-policy/variables.tf
  modules/compute/resource-policy/resource-policy/versions.tf
Labels: release-new-modules

#3031 SlurmGCP. Refactor reservation fetching logic
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3084 Ensure enough open files limit for Parallelstore
  modules/file-system/parallelstore/scripts/mount-daos.sh
  modules/file-system/pre-existing-network-storage/scripts/mount-daos.sh
Labels: release-chore

#3086 Move a3-megagpu-8g tests to us-west4-a
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-cluster.yaml
  tools/cloud-build/daily-tests/builds/ml-a3-megagpu-slurm.yaml
  tools/cloud-build/daily-tests/tests/ml-a3-megagpu-slurm-cluster.yml
  tools/cloud-build/daily-tests/tests/ml-a3-megagpu-slurm-image.yml
Labels: release-chore
