Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2024-08, with the labels that each got.

#2830 Update to SlurmGCP 6.6.0
  community/examples/AMD/hpc-amd-slurm.yaml
  community/examples/hpc-slurm-ubuntu2004.yaml
  community/examples/hpc-slurm6-apptainer.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
  examples/cae/cae-slurm.yaml
  examples/hpc-enterprise-slurm.yaml
  examples/hpc-slurm-static.yaml
  examples/image-builder.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
  examples/ml-slurm.yaml
  tools/cloud-build/daily-tests/ansible_playbooks/test-slurm-v6-tpu.yml
  tools/cloud-build/daily-tests/blueprints/lustre-slurm.yaml
  tools/cloud-build/daily-tests/tests/slurm-v6-centos7.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-debian.yml
  tools/validate_configs/test_configs/node-groups.yaml
Labels: release-version-updates

#2840 Stop using SlurmGCP `nodeset` module.
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-chore

#2848 SlurmGCP move to 5.12
  community/examples/AMD/hpc-amd-slurm-v5-legacy.yaml
  community/examples/hpc-slurm-chromedesktop-v5-legacy.yaml
  community/examples/hpc-slurm-ubuntu2004-v5-legacy.yaml
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
  docs/hybrid-slurm-cluster/demo-with-cloud-controller-instructions.md
  docs/hybrid-slurm-cluster/deploy-instructions.md
  docs/hybrid-slurm-cluster/on-prem-instructions.md
  docs/image-building.md
  examples/cae/cae-slurm-v5-legacy.yaml
  examples/hpc-enterprise-slurm-v5-legacy.yaml
  examples/image-builder-v5-legacy.yaml
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/ml-slurm-v5-legacy.yaml
  tools/cloud-build/daily-tests/blueprints/lustre-slurm-v5-legacy.yaml
  tools/cloud-build/daily-tests/tests/slurm-v5-debian.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-rocky8.yml
  tools/validate_configs/test_configs/node-groups-v5-legacy.yaml
  tools/validate_configs/test_configs/slurm-static-test-v5-legacy.yaml
Labels: release-version-updates

#2823 Move daos agent log to /var/log/daos_agent/
  modules/file-system/parallelstore/scripts/install-daos-client.sh
  modules/file-system/pre-existing-network-storage/scripts/install-daos-client.sh
Labels: release-chore

#2846 Babysit. Make CLI UI less verbose
  tools/cloud-build/babysit/cli_ui.py
  tools/cloud-build/babysit/runner.py
Labels: release-chore

#2850 Update integration tests to use gcluster
  tools/cloud-build/daily-tests/ansible_playbooks/base-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/htcondor-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/multigroup-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/rescue_gcluster_failure.yml
Labels: release-chore

#2843 Add `instance_properties` var to `nodeset`
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-module-improvements

#2857 Update Slurm-GCP 5.11.1 links to 5.12.0
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  examples/README.md
  examples/machine-learning/a3-highgpu-8g/README.md
  modules/README.md
Labels: release-chore

#2855 Fix application of `nodeset.instance_properties`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
Labels: release-chore

#2856 SlurmGCP6. Fix nodes stack in `down*` state.
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
Labels: release-bugfix

#2858 Fix references to old name of Toolkit
  README.md
  cmd/README.md
  community/examples/AMD/README.md
  community/examples/intel/README.md
  docs/network_storage.md
  modules/packer/custom-image/README.md
Labels: release-chore

#2860 Merge v1.37.1 documentation updates into develop branch
  README.md
  cmd/README.md
  community/examples/AMD/README.md
  community/examples/intel/README.md
  docs/network_storage.md
  modules/packer/custom-image/README.md
Labels: release-chore

#2842 Point cloud build trigger provisioning to new github repo name
  tools/cloud-build/provision/README.md
  tools/cloud-build/provision/pr-go-build-test.tf
  tools/cloud-build/provision/pr-ofe-test.tf
  tools/cloud-build/provision/pr-ofe.tf
  tools/cloud-build/provision/pr-tests.tf
  tools/cloud-build/provision/pr-validation.tf
  tools/cloud-build/provision/variables.tf
Labels: release-chore

#2863 Enable local SSD formatting solution to set POSIX permissions
  modules/scripts/startup-script/README.md
  modules/scripts/startup-script/main.tf
  modules/scripts/startup-script/variables.tf
Labels: release-module-improvements

#2864 SlurmGCP. Fix bugs around nodeset zones
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  tools/cloud-build/daily-tests/tests/hpc-enterprise-slurm.yml
Labels: release-bugfix

#2873 support for min_cpu_platform usage on vm-instance
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/main.tf
  modules/compute/vm-instance/variables.tf
Labels: release-key-new-features

#2874 Add doc about DWS Flex Start
  docs/slurm-dws-flex.md
Labels: release-chore

#2875 Fix typo slurm-dws-flex.md
  docs/slurm-dws-flex.md
Labels: release-chore

#2854 Provide a note about H3 availability in the Slurm example blueprints
  examples/hpc-enterprise-slurm.yaml
  examples/hpc-slurm.yaml
Labels: good first issue, release-chore

#2820 SlurmGCP. Rework logging
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/get_tpu_vmcount.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup_network_storage.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/suspend.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#2861 Add test for legacy v5 a3-highgpu-8g blueprint
  tools/cloud-build/provision/README.md
  tools/cloud-build/provision/legacy-tests.tf
Labels: release-chore

#2862 SlurmGCP. Use config-independent storage client.
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#2879 Update SlurmGCP 6.6.0 -> 6.6.1
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
Labels: release-chore

#2778 Add `allow_automatic_updates` flag
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/compute_image.tf
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/htcondor-execute-point/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-access-point/variables.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/htcondor-central-manager/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/compute_image.tf
  modules/compute/vm-instance/main.tf
  modules/compute/vm-instance/variables.tf
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/compute_image.tf
  modules/scheduler/batch-job-template/main.tf
  modules/scheduler/batch-job-template/variables.tf
  modules/scheduler/batch-job-template/versions.tf
  tools/cloud-build/daily-tests/blueprints/e2e.yaml
  tools/duplicate-diff.py
Labels: release-key-new-features

#2870 Update local ssd examples to use local ssd startup solution
  community/examples/hpc-slurm-local-ssd-v5-legacy.yaml
  community/examples/hpc-slurm-local-ssd.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-ssd.yaml
Labels: release-improvements

#2871 Update a3-megagpu-8 example to use local ssd solution
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-cluster.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
Labels: release-improvements

#2886 DWS. Add form to sing up for allowlist
  docs/slurm-dws-flex.md
Labels: release-chore

#2888 Remove `docs/slurm-dws-flex.md`
  docs/slurm-dws-flex.md
Labels: release-chore

#2853 Add `sort_nodes.py`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/sort_nodes.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_topology.py
Labels: release-improvements

#2896 Align variable name around gcluster to avoid mismatch
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/gather_startup_script_logs.yml
Labels: release-chore

#2897 Extend timeout on batch test build
  tools/cloud-build/daily-tests/builds/batch-mpi.yaml
Labels: release-chore

#2887 Add section "Standard PR Response Times" to CONTRIBUTING.md
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: release-chore

#2898 Fix link in Packer README
  modules/packer/custom-image/README.md
Labels: release-chore

#2768 Add documentation for exclusive mode
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
Labels: release-chore

#2895 Delete at most one resource policy at a time
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/scripts/cleanup_compute.sh
Labels: release-bugfix

#2828 Make CloudSQL secret replication configurable
  community/modules/database/slurm-cloudsql-federation/README.md
  community/modules/database/slurm-cloudsql-federation/main.tf
  community/modules/database/slurm-cloudsql-federation/outputs.tf
  community/modules/database/slurm-cloudsql-federation/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-module-improvements

#2883 Override machine type to reduce chance of stockout
  examples/ps-slurm.yaml
  tools/cloud-build/daily-tests/tests/ps-slurm.yml
Labels: release-chore

#2892 Add `slurmgcp-managed` infix to resource policy name
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/scripts/cleanup_compute.sh
Labels: release-bugfix

#2893 Fix bug of supplying different `instance_properties`
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-chore

#2900 replacing centos7 with rocky8 in vm-instance modules
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/variables.tf
Labels: release-improvements

#2901 replacing centos7 with rocky8 in nfs-server modules
  community/modules/file-system/nfs-server/README.md
  community/modules/file-system/nfs-server/variables.tf
Labels: release-improvements

#2899 replacing centos7 with rocky8 in packer modules
  modules/packer/custom-image/README.md
  modules/packer/custom-image/variables.pkr.hcl
  tools/validate_configs/golden_copies/expectations/igc_pkr/one/image/variables.pkr.hcl
  tools/validate_configs/golden_copies/expectations/text_escape/zero/lime/variables.pkr.hcl
Labels: release-improvements

#2902 Babysit. Show "less interesting" statuses first
  tools/cloud-build/babysit/cli_ui.py
Labels: release-chore

#2882 Add setting `allow_automatic_updates: false` to examples
  community/examples/AMD/hpc-amd-slurm.yaml
  community/examples/client-google-cloud-storage.yaml
  community/examples/hpc-build-slurm-image.yaml
  community/examples/hpc-slurm-gromacs.yaml
  community/examples/hpc-slurm-local-ssd.yaml
  community/examples/hpc-slurm-ramble-gromacs.yaml
  community/examples/hpc-slurm-sharedvpc.yaml
  community/examples/hpc-slurm6-apptainer.yaml
  community/examples/hpc-slurm6-tpu-maxtext.yaml
  community/examples/htc-htcondor.yaml
  community/examples/htc-slurm.yaml
  community/examples/omnia-cluster.yaml
  community/examples/tutorial-fluent.yaml
  community/examples/tutorial-starccm.yaml
  examples/cae/cae-slurm.yaml
  examples/hcls-blueprint.yaml
  examples/hpc-enterprise-slurm.yaml
  examples/hpc-slurm-static.yaml
  examples/hpc-slurm.yaml
  examples/image-builder.yaml
  examples/pfs-lustre.yaml
  examples/ps-slurm.yaml
  examples/serverless-batch-mpi.yaml
  examples/serverless-batch.yaml
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/variables.tf
  tools/cloud-build/daily-tests/tests/slurm-v6-centos7.yml
Labels: release-chore

#2906 cleanup-build. Minor improvements
  tools/cleanup-build.py
Labels: release-chore

#2905 Merge `main` into `develop`
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/scripts/cleanup_compute.sh
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2907 fix passing additional networks to login nodes
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
Labels: release-chore

#2909 SlurmGCP. Remove global `cfg`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/load_bq.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup_network_storage.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#2913 Merge 'main' (hotfix release v1.37.2) into 'release-candidate'
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/scripts/cleanup_compute.sh
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2914 Install `script_nodes.py` along slurm binaries (`/usr/local/bin`)
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/sort_nodes.py
Labels: release-key-new-features

#2916 Add setting `allow_automatic_updates: false` to examples
  community/examples/AMD/hpc-amd-slurm.yaml
  community/examples/client-google-cloud-storage.yaml
  community/examples/hpc-build-slurm-image.yaml
  community/examples/hpc-slurm-gromacs.yaml
  community/examples/hpc-slurm-local-ssd.yaml
  community/examples/hpc-slurm-ramble-gromacs.yaml
  community/examples/hpc-slurm-sharedvpc.yaml
  community/examples/hpc-slurm6-apptainer.yaml
  community/examples/hpc-slurm6-tpu-maxtext.yaml
  community/examples/htc-htcondor.yaml
  community/examples/htc-slurm.yaml
  community/examples/omnia-cluster.yaml
  community/examples/tutorial-fluent.yaml
  community/examples/tutorial-starccm.yaml
  examples/cae/cae-slurm.yaml
  examples/hcls-blueprint.yaml
  examples/hpc-enterprise-slurm.yaml
  examples/hpc-slurm-static.yaml
  examples/hpc-slurm.yaml
  examples/image-builder.yaml
  examples/pfs-lustre.yaml
  examples/ps-slurm.yaml
  examples/serverless-batch-mpi.yaml
  examples/serverless-batch.yaml
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/variables.tf
  tools/cloud-build/daily-tests/tests/slurm-v6-centos7.yml
Labels: release-chore

#2917 SlurmGCP. Stop using global mutable `lkp`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/get_tpu_vmcount.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/load_bq.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup_network_storage.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/suspend.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#2920 Build is taking longer, extend timeout so test will pass while investigate
  tools/cloud-build/daily-tests/builds/batch-mpi.yaml
Labels: release-chore

#2884 Update batch image to hpc-rocky-linux-8
  examples/serverless-batch.yaml
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/variables.tf
Labels: release-improvements

#2915 Bump version from v1.37.2 to v1.38.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2926 Fix bug of suppliying different `instance_properties`
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-chore

#2928 SlurmGCP. Fix typo-bug `lookup -> lookup()`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/suspend.py
Labels: release-chore

#2908 Fix misuse of `log.exception`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
Labels: release-chore

#2921 OFE - various updates and fixes
  community/front-end/ofe/README.md
  community/front-end/ofe/deploy.sh
  community/front-end/ofe/docs/developer_guide.md
  community/front-end/ofe/infrastructure_files/gcs_bucket/clusters/ansible_setup/roles/c2_daemon/files/ghpcfe_c2daemon.py
  community/front-end/ofe/infrastructure_files/gcs_bucket/clusters/ansible_setup/roles/c2_daemon/tasks/main.yaml
  community/front-end/ofe/infrastructure_files/gcs_bucket/webserver/startup.sh
  community/front-end/ofe/tf/README.md
  community/front-end/ofe/tf/variables.tf
  community/front-end/ofe/website/ghpcfe/cluster_manager/cloud_info.py
  community/front-end/ofe/website/ghpcfe/cluster_manager/clusterinfo.py
  community/front-end/ofe/website/ghpcfe/cluster_manager/filesystem.py
  community/front-end/ofe/website/ghpcfe/cluster_manager/image.py
  community/front-end/ofe/website/ghpcfe/forms.py
  community/front-end/ofe/website/ghpcfe/models.py
  community/front-end/ofe/website/ghpcfe/templates/blueprint/cluster_config.yaml.j2
  community/front-end/ofe/website/ghpcfe/templates/blueprint/partition_config.yaml.j2
  community/front-end/ofe/website/ghpcfe/templates/cluster/update_form.html
  community/front-end/ofe/website/ghpcfe/views/clusters.py
  community/front-end/ofe/website/nginx.conf
  community/front-end/ofe/website/website/settings.py
Labels: release-improvements

#2927 Bump django from 4.2.11 to 4.2.15 (Cherrypick #2885)
  community/front-end/ofe/requirements.txt
Labels: release-chore

#2930 In Slurm v6 controller, update `grpcio` to 1.56.2 and `requests` to 2.32.0
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/requirements.txt
Labels: release-chore

#2922 SlurmGCP. Minor refactoring.
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#2931 Add dependabot scanning for Slurm v6 Controller module
  .github/dependabot.yml
Labels: release-chore

#2880 Add reservation support in slurm sync for scheduled maintenance
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-key-new-features

#2934 Roll back changes in go.mod to release v1.37.2
  go.mod
  go.sum
Labels: release-bugfix

#2919 SlurmGCP. Don't fetch config in `util.py`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#2881 SlurmGCP. Store nodeset and partition configs in separate files
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup_network_storage.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#2938 SlurmGCP. Fix `datetime` usage.
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
Labels: release-chore

#2932 OFE - Go download url change.
  community/front-end/ofe/infrastructure_files/gcs_bucket/webserver/startup.sh
Labels: release-chore

#2891 GKE Blueprints to support reservations
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/variables.tf
Labels: release-module-improvements

#2937 Merge v1.38.0 back to develop
  cmd/root.go
  community/examples/hpc-slurm-local-ssd-v5-legacy.yaml
  community/examples/hpc-slurm-local-ssd.yaml
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/requirements.txt
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-2-cluster.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-cluster.yaml
  go.mod
  go.sum
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2942 Change dependabot Golang package version update to monthly
  .github/dependabot.yml
Labels: release-chore

#2943 Update parallelstore documentation to add section for supported operating systems
  modules/file-system/parallelstore/README.md
Labels: release-chore

#2939 SlurmGCP. Store TPU and dynamic nodesets configs in separate files
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#2925 Revert "Remove `docs/slurm-dws-flex.md`"
  docs/slurm-dws-flex.md
Labels: release-chore

#2944 Update A3H instructions: Python dependencies are no longer needed for v6
  examples/machine-learning/a3-highgpu-8g/README.md
Labels: release-chore

#2946 SlurmGCP. Clean up `get_nodes_status`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
Labels: release-chore

#2807 Add `TopologySummary` to track changes to topology
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/requirements.txt
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_topology.py
Labels: release-chore

#2947 Add physical topo. Update rules to trigger reconfiguration
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/common.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_topology.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#2948 Add `cloud_parameters.topology_param`, defaults to `SwitchAsNodeRank`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-chore

#2894 renaming ghpc to gcluster in the locations where ghpc is called
  community/examples/AMD/README.md
  community/examples/flux-framework/README.md
  community/examples/intel/README.md
  community/front-end/ofe/website/ghpcfe/cluster_manager/image.py
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  docs/blueprint-validation.md
  docs/hpc-slurm6-tpu-maxtext.md
  docs/hybrid-slurm-cluster/demo-with-cloud-controller-instructions.md
  docs/hybrid-slurm-cluster/deploy-instructions.md
  docs/hybrid-slurm-cluster/on-prem-instructions.md
  docs/tutorials/gromacs/spack-gromacs.md
  docs/tutorials/htcondor.md
  docs/tutorials/openfoam/spack-openfoam.md
  docs/tutorials/wrfv3/spack-wrfv3.md
  examples/README.md
  modules/README.md
  modules/compute/vm-instance/README.md
  tools/cloud-build/README.md
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/create_deployment_directory.yml
  tools/cloud-build/daily-tests/builds/ml-a3-highgpu-slurm.yaml
  tools/cloud-build/daily-tests/builds/monitoring.yaml
  tools/cloud-build/images/ghpc-docker/Dockerfile
  tools/cloud-build/images/test-runner/Dockerfile
  tools/validate_configs/golden_copies/validate.sh
  tools/validate_configs/test_configs/README.md
  tools/validate_configs/validate_configs.sh
Labels: release-chore

#2941 Upgrade to DAOS 2.6, skip installation if already installed
  modules/file-system/parallelstore/scripts/install-daos-client.sh
  modules/file-system/pre-existing-network-storage/scripts/install-daos-client.sh
Labels: release-chore

#2949 SurmGCP. Bump version `6.6.1 -> 6.6.2`
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
Labels: release-chore

#2956 Change Parallelstore installation script to not move log folder for debian/ubuntu
  modules/file-system/parallelstore/scripts/install-daos-client.sh
  modules/file-system/pre-existing-network-storage/scripts/install-daos-client.sh
Labels: release-bugfix

#2961 Remove `test_tf_version_for_slurm` validator
  pkg/validators/adhoc.go
  pkg/validators/validators.go
  pkg/validators/validators_test.go
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/create_deployment_directory.yml
  tools/validate_configs/validate_configs.sh
Labels: release-chore

#2959 Added validation block to prevent node_conf from setting Sockets
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
Labels: release-chore

#2960 SlurmGCP. Remove dependency of controller on config
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/outputs.tf
Labels: release-chore

#2797 Support multivpc with GKE
  community/modules/compute/htcondor-execute-point/gpu_definition.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/gpu_definition.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/gpu_definition.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/gpu_definition.tf
  examples/README.md
  examples/gke-a3-highgpu.yaml
  examples/gke-a3-megagpu.yaml
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/gpu_definition.tf
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/variables.tf
  modules/compute/vm-instance/gpu_definition.tf
  modules/network/multivpc/main.tf
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/variables.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/README.md
  modules/scheduler/pre-existing-gke-cluster/main.tf
  modules/scheduler/pre-existing-gke-cluster/variables.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
Labels: release-module-improvements

#2945 adding optional fields to redirect use of embedded modules to pull fr…
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/expand.go
  pkg/config/expand_test.go
  pkg/config/path.go
  pkg/config/path_test.go
Labels: release-key-new-features

#2918 SlurmGCP. Store "extra files" hash in config
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
Labels: release-chore

#2978 Prevent use of google provider 6.0 where breaking changes are in use
  community/modules/compute/pbspro-execution/README.md
  community/modules/compute/pbspro-execution/main.tf
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/main.tf
  community/modules/scheduler/pbspro-client/README.md
  community/modules/scheduler/pbspro-client/main.tf
  community/modules/scheduler/pbspro-server/README.md
  community/modules/scheduler/pbspro-server/main.tf
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/versions.tf
Labels: release-bugfix

#2975 Increate `ps-slurm.yaml` startup scripts timeout
  examples/ps-slurm.yaml
Labels: release-chore

#2971 Expose maintenance interval as a blueprint setting for node pools in GKE
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/variables.tf
  tools/cloud-build/daily-tests/builds/ml-gke.yaml
Labels: release-module-improvements

#2969 Support named placements in GKE node pools
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/variables.tf
Labels: release-module-improvements

#2982 Improved serial port collection tool
  tools/serial_port_collector.py
Labels: release-chore

#2985 kubernetes provider added to gke-cluster module
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/versions.tf
Labels: release-bugfix

#2962 Add machine type availability checks to slurm-gcp-v6-nodeset
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
Labels: release-module-improvements

#2981 Don't set `automaticRestart: false`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
Labels: release-improvements

#2986 Disable automatic updates in daos installation script
  modules/file-system/parallelstore/scripts/install-daos-client.sh
  modules/file-system/pre-existing-network-storage/scripts/install-daos-client.sh
Labels: release-chore

#2965 SlurmGCP. Do not add empty startup scripts
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-chore

#2972 SlurmGCP. Fixes & improvements around config fetching
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#2990 Revert "Add machine type availability checks to slurm-gcp-v6-nodeset"
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
Labels: release-chore
