Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2024-01, with the labels that each got.

#2067 Slurm6. Make `subnetwork_self_link` required, don't pass `subnetwork_project`
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
Labels: release-module-improvements

#2068 Slurm6. Automagicaly set `nodeset.name` from module id.
  community/examples/hpc-slurm6.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/metadata.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
Labels: release-module-improvements

#2083 VPC. Replace `s/_/-/` in `deployment_name` to avoid deploy-time error
  modules/network/vpc/main.tf
Labels: release-chore

#2084 Add `hpc-slurm6.yaml` to `examples/README`
  .pre-commit-config.yaml
  examples/README.md
Labels: release-chore

#2086 Slurm6. QuickFix broken TPU nodeset usage
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
Labels: release-chore

#2087 Slurm6. Reference TPU example in `examples/README`
  examples/README.md
Labels: release-chore

#2088 Use `cty.Type` instead of `string` to represent type of vars.
  pkg/config/config_test.go
  pkg/config/expand.go
  pkg/config/expand_test.go
  pkg/inspect/modules_test.go
  pkg/modulereader/hcl_utils.go
  pkg/modulereader/resreader.go
  pkg/modulereader/resreader_test.go
  pkg/modulewriter/modulewriter_test.go
  pkg/modulewriter/tfwriter.go
Labels: release-chore

#2093 fix: header was over-indented
  modules/README.md
Labels: release-chore

#2089 Check if supplied value matches expected module variable type
  pkg/config/expand.go
  pkg/config/expression_test.go
  pkg/config/validator_test.go
  pkg/config/yaml.go
  pkg/config/yaml_test.go
  pkg/modulereader/metadata.go
  pkg/modulewriter/modulewriter_test.go
  pkg/validators/validators_test.go
Labels: release-improvements

#2082 Add spelling hints for global vars and outputs
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/errors.go
  pkg/config/expand.go
Labels: release-chore

#2081 Point ref errors to a location within nested object
  pkg/config/config.go
  pkg/config/expand.go
  pkg/config/expression.go
Labels: release-chore

#2094 Refactor `Blueprint.WalkModules`
  pkg/config/config.go
  pkg/config/expand.go
  pkg/config/expand_test.go
  pkg/config/path.go
  pkg/config/validate.go
  pkg/validators/cloud.go
  pkg/validators/semantic.go
Labels: release-chore

#2090 Update spack openfoam example to Slurm V6
  docs/tutorials/openfoam/spack-openfoam.md
  docs/tutorials/openfoam/spack-openfoam.yaml
Labels: release-improvements

#2091 Add test that check that modules don't output forbidden names
  pkg/inspect/modules_test.go
Labels: release-chore

#2062 Slurm6. Add support for `additional_networks`, `access_config` & `reservation_name`
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-module-improvements

#2116 Merge v1.27.0 back to develop
  cmd/root.go
  community/modules/compute/gke-node-pool/versions.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/gke-persistent-volume/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-login-node/versions.tf
  community/modules/scheduler/gke-cluster/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/htcondor-setup/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  go.mod
  go.sum
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#2117 Add zone finding for cpu partitions in hpc-enterprise-slurm test
  tools/cloud-build/daily-tests/tests/hpc-enterprise-slurm.yml
Labels: release-chore

#2118 Rename GKE subnet with build id to avoid conflicts
  tools/cloud-build/daily-tests/builds/gke-storage.yaml
  tools/cloud-build/daily-tests/builds/gke.yaml
Labels: release-chore

#2104 Remove pre existing fs example and references
  tools/validate_configs/test_configs/pre-existing-fs.yaml
Labels: release-deprecations

#2106 Remove slurm-two-partitions-workstation example and references
  tools/validate_configs/test_configs/slurm-two-partitions-workstation.yaml
Labels: release-deprecations

#2107 Remove use-resources example and references
  tools/validate_configs/test_configs/use-resources.yaml
Labels: release-deprecations

#2109 Update test outputs example and remove slurm partition and controller
  tools/validate_configs/test_configs/test_outputs.yaml
Labels: release-deprecations

#2110 Remove test-gcs-fuse example and references
  tools/validate_configs/test_configs/test-gcs-fuse.yaml
Labels: release-deprecations

#2111 Remove hpc-cluster-service-acct example and references
  tools/validate_configs/test_configs/hpc-cluster-service-acct.yaml
Labels: release-deprecations

#2112 Remove hpc-cluste-slurm-with-startup example and references
  tools/validate_configs/test_configs/hpc-cluster-slurm-with-startup.yaml
Labels: release-deprecations

#2113 Remove hpc-cluster-project example and references
  tools/validate_configs/test_configs/hpc-cluster-project.yaml
Labels: release-deprecations

#2114 Remove hpc-cluster-high-io-remote-state example and references
  tools/validate_configs/test_configs/README.md
  tools/validate_configs/test_configs/hpc-cluster-high-io-remote-state.yaml
Labels: release-deprecations

#2095 Unify usage and rendering of `HintError`
  cmd/create.go
  cmd/create_test.go
  cmd/render.go
  cmd/render_test.go
  pkg/validators/cloud.go
  pkg/validators/validators.go
Labels: release-chore

#2108 Remove lustre-new-vpc example and references
  tools/cloud-build/daily-tests/blueprints/lustre-with-new-vpc.yaml
  tools/cloud-build/daily-tests/builds/lustre-new-vpc.yaml
  tools/cloud-build/daily-tests/tests/lustre-new-vpc.yml
Labels: release-deprecations

#2103 Remove hpc-slurm-legacy example and references
  community/examples/hpc-slurm-legacy.yaml
  examples/README.md
  tools/cloud-build/daily-tests/builds/hpc-high-io-v4.yaml
  tools/cloud-build/daily-tests/tests/hpc-high-io.yml
Labels: release-deprecations

#2119 Fix slurm v6 links in example README
  examples/README.md
Labels: release-chore

#2121 Rename slurm tpu test to be consistent with blueprint name
  tools/cloud-build/babysit_tests.py
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-tpu.yaml
  tools/cloud-build/daily-tests/tests/slurm-v6-tpu.yml
Labels: release-chore

#2122 yamllint. Don't show warnings
  .pre-commit-config.yaml
Labels: release-chore

#2123 Silence make error message for old versions of git
  Makefile
Labels: release-chore

#2097 Slurm6. Move `examples/hpc-slurm` to V6
  community/examples/hpc-slurm6.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  examples/README.md
  examples/hpc-slurm.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-hpc-centos7.yaml
  tools/cloud-build/daily-tests/tests/slurm-v5-hpc-centos7.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-rocky8.yml
Labels: release-chore

#2092 Add `has_to_be_used` behaviour to some of modules
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/metadata.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/metadata.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-partition/metadata.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/metadata.yaml
  docs/module-guidelines.md
  pkg/config/expand.go
  pkg/modulereader/metadata.go
Labels: release-improvements

#2124 Hint spelling for module inputs
  pkg/config/validate.go
Labels: release-chore

#2127 Reduce default maximum number of HTCondor execute points
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/variables.tf
Labels: release-module-improvements

#2125 fix typo
  community/modules/file-system/DDN-EXAScaler/README.md
Labels: release-chore

#2096 Simplify rendering of errors with Position instead of Path
  cmd/render.go
  pkg/config/errors.go
  pkg/config/path.go
  pkg/config/path_test.go
  pkg/config/yaml.go
  pkg/config/yaml_test.go
  pkg/modulereader/resreader.go
Labels: release-chore

#2130 Fix rendering of "cobra" errors
  cmd/root.go
Labels: release-chore

#2120 Startup stackdriver option
  modules/scripts/startup-script/README.md
  modules/scripts/startup-script/files/install_monitoring_agent.sh
  modules/scripts/startup-script/main.tf
  modules/scripts/startup-script/variables.tf
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-monitoring.yml
  tools/cloud-build/daily-tests/blueprints/monitoring.yaml
  tools/cloud-build/daily-tests/tests/monitoring.yml
  tools/validate_configs/test_configs/apt-collision.yaml
  tools/validate_configs/test_configs/ubuntu-ss.yaml
Labels: release-module-improvements

#2126 SlurmV6. Make `cleanup_compute_nodes` `depends_on` on network
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
Labels: release-chore

#2132 Update spack wrf example and references to use Slurm V6
  docs/tutorials/wrfv3/spack-wrfv3.md
  docs/tutorials/wrfv3/spack-wrfv3.yaml
Labels: release-improvements, release-deprecations

#2131 Update spack openfoam example to use /opt/apps directory
  docs/tutorials/openfoam/spack-openfoam.md
  docs/tutorials/openfoam/spack-openfoam.yaml
Labels: release-bugfix

#2133 Improve readability of "required setting is missing" error
  pkg/config/errors.go
  pkg/config/expand.go
Labels: release-chore

#2141 Fix HTCondow Windows URI for latest 23.0 LTS release
  community/modules/scripts/htcondor-install/templates/install-htcondor.ps1.tftpl
Labels: release-bugfix

#2140 HTCondor: variable MIG behavior
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/htcondor-execute-point/variables.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-access-point/variables.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/htcondor-central-manager/variables.tf
Labels: release-module-improvements

#2137 Extending GKE Scheduler module
  community/modules/scheduler/gke-cluster/README.md
  community/modules/scheduler/gke-cluster/main.tf
  community/modules/scheduler/gke-cluster/variables.tf
Labels: release-module-improvements

#2135 Remove intel-select blueprints and references
  community/examples/intel/README.md
  community/examples/intel/hpc-intel-select-slurm.yaml
  docs/tutorials/README.md
  docs/tutorials/intel-select/hpc-cluster-intel-select.yaml
  docs/tutorials/intel-select/intel-select.md
  examples/README.md
  modules/README.md
  modules/packer/custom-image/README.md
Labels: release-deprecations

#2076 Add support for string interpolation
  examples/README.md
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/expand.go
  pkg/config/expand_test.go
  pkg/config/expression.go
  pkg/config/expression_test.go
  pkg/config/yaml.go
  pkg/modulewriter/modulewriter_test.go
Labels: release-improvements

#2145 🌈 Enable output colorization by default
  cmd/color.go
Labels: release-key-new-features

#2138 Update spack gromacs example and references to Slurm V6
  docs/tutorials/gromacs/spack-gromacs.md
  docs/tutorials/gromacs/spack-gromacs.yaml
Labels: release-improvements

#2146 Slurm6. Advance to 6.3.1
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
Labels: release-chore

#2151 Copies python binaries instead of symlink for more isolated venv
  modules/scripts/startup-script/files/install_ansible.sh
Labels: release-module-improvements

#2156 Clarify that zone-finding isn't available for TPUs
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/variables.tf
Labels: release-chore

#2149 Update hpc slurm gromac example and references to use Slurm V6
  community/examples/hpc-slurm-gromacs.yaml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-spack.yml
  tools/cloud-build/daily-tests/tests/spack-gromacs.yml
Labels: release-improvements

#2147 Update DAOS blueprints to use google-cloud-daos v0.5.0, slurm v6
  community/examples/intel/README.md
  community/examples/intel/hpc-slurm-daos.yaml
  community/examples/intel/pfs-daos.yaml
Labels: release-improvements

#2153 Increase dynamic node count to a more reasonable default value
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
Labels: release-module-improvements

#2053 Bring `$(...)` functionality on par with `((...))`
  community/front-end/ofe/infrastructure_files/workbench_tf/google/wait-for-startup/README.md
  examples/README.md
  pkg/config/expression.go
  pkg/config/expression_test.go
  pkg/modulewriter/modulewriter_test.go
  pkg/modulewriter/tfwriter.go
  pkg/shell/terraform.go
  tools/cloud-build/daily-tests/blueprints/lustre-vm.yaml
  tools/cloud-build/daily-tests/builds/batch-mpi.yaml
Labels: release-improvements

#2157 Start legacy monitoring agent after installing
  modules/scripts/startup-script/files/install_monitoring_agent.sh
Labels: release-chore

#2164 Fix false-positive `test_deployment_variable_not_used`
  pkg/config/config.go
  pkg/config/config_test.go
Labels: release-chore

#2163 Bump test coverage for `pkg/modulewriter`
  pkg/modulewriter/hcl_utils.go
  pkg/modulewriter/modulewriter_test.go
  pkg/modulewriter/tfversions.go
  pkg/modulewriter/tfwriter.go
Labels: release-chore

#2162 Add `--force` flag to `ghpc create`
  cmd/create.go
  cmd/create_test.go
Labels: release-improvements

#2078 Improve logging for expressions errors
  pkg/config/expression.go
  pkg/config/expression_test.go
  pkg/config/yaml.go
Labels: release-chore

#2167 Remove quantum circuit simulator example
  community/examples/quantum-circuit-simulator.yaml
  examples/README.md
  tools/cloud-build/daily-tests/builds/quantum-circuit.yaml
  tools/cloud-build/daily-tests/tests/qsim.yml
Labels: release-chore

#2143 Update hpc-slurm-legacy-sharedvpc example and references to use Slurm V6
  community/examples/hpc-slurm-legacy-sharedvpc.yaml
  examples/README.md
Labels: release-improvements

#2165 Bump `cmd` test coverage
  cmd/create.go
  cmd/create_test.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: release-chore

#2169 Update Slurm image 6.1 -> 6.3
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
Labels: release-chore

#2170 Add login node in the spack openfoam tutorial example
  docs/tutorials/openfoam/spack-openfoam.md
  docs/tutorials/openfoam/spack-openfoam.yaml
Labels: release-improvements

#2171 Update Toolkit docs to point to GCP Slurm fork
  docs/vm-images.md
Labels: release-chore

#2172 Fix: added new variables to ml-slurm integration test
  tools/cloud-build/daily-tests/tests/ml-slurm.yml
Labels: release-chore

#2168 Update Slurm Cloud SQL example to V6
  community/modules/database/slurm-cloudsql-federation/metadata.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  tools/validate_configs/test_configs/hpc-cluster-simple-nfs-sql.yaml
Labels: release-version-updates

#2178 Portability fixes for Slurm v6 image building example
  community/examples/hpc-build-slurm-image.yaml
Labels: release-chore

#2175 Updated legacy-sharedvpc reference naming to sharedvpc
  community/examples/hpc-slurm-sharedvpc.yaml
  examples/README.md
Labels: release-chore

#2148 Validation added to Slurm v5 login_startup_scripts_timeout
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
Labels: release-bugfix

#2179 Patch Slurm integration test
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
Labels: release-chore

#2174 Ensure Windows VMs start HTCondor only after successful secret download
  community/modules/compute/htcondor-execute-point/templates/download-condor-config.ps1.tftpl
  community/modules/scheduler/htcondor-pool-secrets/templates/fetch-idtoken.ps1.tftpl
  community/modules/scripts/htcondor-install/templates/install-htcondor.ps1.tftpl
Labels: release-bugfix

#2160 Remove Slurm V4 modules and add note to use and reference V4 modules and examples
  community/modules/compute/SchedMD-slurm-on-gcp-partition/README.md
  community/modules/compute/SchedMD-slurm-on-gcp-partition/metadata.yaml
  community/modules/compute/SchedMD-slurm-on-gcp-partition/outputs.tf
  community/modules/compute/SchedMD-slurm-on-gcp-partition/variables.tf
  community/modules/compute/SchedMD-slurm-on-gcp-partition/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/README.md
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/main.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/metadata.yaml
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/outputs.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/variables.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-controller/versions.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-login-node/README.md
  community/modules/scheduler/SchedMD-slurm-on-gcp-login-node/main.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-login-node/metadata.yaml
  community/modules/scheduler/SchedMD-slurm-on-gcp-login-node/variables.tf
  community/modules/scheduler/SchedMD-slurm-on-gcp-login-node/versions.tf
  docs/gpu-support.md
  docs/slurm-troubleshooting.md
  modules/README.md
  modules/scripts/startup-script/README.md
  pkg/modulereader/metadata_legacy.go
Labels: release-deprecations

#2173 Make TPU non-preemptible in blueprint and add retries in JAX verification integration test
  community/examples/hpc-slurm6-tpu.yaml
  tools/cloud-build/daily-tests/ansible_playbooks/test-slurm-v6-tpu.yml
Labels: release-chore

#2180 Update Chrome Remote Desktop to Debian 12 by default
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/scripts/configure-grid-drivers.yml
  community/modules/remote-desktop/chrome-remote-desktop/variables.tf
Labels: release-module-improvements

#2183 Update startup-script module to latest release
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/pbspro-execution/README.md
  community/modules/compute/pbspro-execution/main.tf
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/main.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/pbspro-client/README.md
  community/modules/scheduler/pbspro-client/main.tf
  community/modules/scheduler/pbspro-server/README.md
  community/modules/scheduler/pbspro-server/main.tf
  community/modules/scripts/ramble-execute/README.md
  community/modules/scripts/ramble-execute/main.tf
  community/modules/scripts/ramble-setup/README.md
  community/modules/scripts/ramble-setup/main.tf
  community/modules/scripts/spack-execute/README.md
  community/modules/scripts/spack-execute/main.tf
  community/modules/scripts/spack-setup/README.md
  community/modules/scripts/spack-setup/main.tf
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/startup_from_network_storage.tf
  modules/scheduler/batch-job-template/README.md
  modules/scheduler/batch-job-template/startup_from_network_storage.tf
  modules/scheduler/batch-login-node/README.md
  modules/scheduler/batch-login-node/main.tf
Labels: release-module-improvements

#2161 Bump `pkg/modulereader` test coverage 80% -> 87%
  pkg/modulereader/hcl_utils_test.go
  pkg/modulereader/resreader_test.go
Labels: release-chore
