Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2025-08, with the labels that each got.

#4485 Merge v1.61.0 into develop
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4469 Support DWS canlendar with regular reservation
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#4488 Change log from info to debug
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: enhancement, release-chore

#4486 Ignore exclusive jobs for slices
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#4461 Add A4X blueprints and gpu definition
  examples/machine-learning/a4x-highgpu-4g/README.md
  examples/machine-learning/a4x-highgpu-4g/a4xhigh-slurm-blueprint.yaml
  examples/machine-learning/a4x-highgpu-4g/a4xhigh-slurm-deployment.yaml
  examples/machine-learning/a4x-highgpu-4g/system_benchmarks/README.md
  examples/machine-learning/a4x-highgpu-4g/system_benchmarks/run-nccl-tests-via-ramble.sh
  modules/internal/gpu-definition/main.tf
  tools/validate_configs/validate_configs.sh
Labels: release-key-new-features

#4493 Adding username to writer
  cluster-toolkit-writers.json
Labels: release-chore

#4492 Revert "Added capacity checks for reservations"
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
Labels: release-module-improvements

#3862 Create a new community scheduler module for Slinky (Slurm on Kubernetes)
  community/examples/hpc-slinky/exporter-pod-monitoring.yaml
  community/examples/hpc-slinky/hpc-slinky.yaml
  community/modules/scheduler/slinky/README.md
  community/modules/scheduler/slinky/main.tf
  community/modules/scheduler/slinky/metadata.yaml
  community/modules/scheduler/slinky/outputs.tf
  community/modules/scheduler/slinky/providers.tf
  community/modules/scheduler/slinky/variables.tf
  community/modules/scheduler/slinky/versions.tf
  examples/README.md
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-slinky.yml
  tools/cloud-build/daily-tests/builds/slinky.yml
  tools/cloud-build/daily-tests/tests/slinky.yml
  tools/validate_configs/validate_configs.sh
Labels: release-key-new-features, release-new-modules

#4502 Update Toolkit release to v1.62.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4490 Update nccl gib plugin version
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  examples/gke-a3-ultragpu/nccl-jobset-example.yaml
  examples/gke-a3-ultragpu/system_benchmarks/ramble-nccl.yaml
  examples/gke-a4/gke-a4.yaml
  examples/gke-a4/nccl-jobset-example.yaml
  examples/gke-a4x/nccl-jobset-example.yaml
  examples/gke-consumption-options/dws-flex-start-queued-provisioning/nccl-installer.yaml
  examples/gke-consumption-options/dws-flex-start-queued-provisioning/nccl-jobset-example.yaml
  examples/gke-consumption-options/dws-flex-start/nccl-installer.yaml
  examples/gke-consumption-options/dws-flex-start/nccl-jobset-example.yaml
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/a3u-slurm-ubuntu-gcs.yaml
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/system_benchmarks/run-nccl-tests-via-ramble.sh
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a3-ultragpu-8g/nemo-framework/Dockerfile
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-vm.yaml
  examples/machine-learning/a4-highgpu-8g/system_benchmarks/run-nccl-tests-via-ramble.sh
  modules/management/kubectl-apply/variables.tf
Labels: release-chore

#4512 update A3M blueprint with new slurm gcp verion.
  examples/machine-learning/a3-megagpu-8g/a3mega-slurm-blueprint.yaml
Labels: release-chore

#4495 add a4x image build recipe
  examples/machine-learning/build-service-images/README.md
  examples/machine-learning/build-service-images/a4x/blueprint.yaml
Labels: release-improvements

#4498 Fix: Slurm scripts incorrectly identifying all accelerators as GPUs
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-bugfix

#4499 Improvements applied to gke-pv-module
  modules/file-system/gke-persistent-volume/README.md
  modules/file-system/gke-persistent-volume/main.tf
  modules/file-system/gke-persistent-volume/outputs.tf
  modules/file-system/gke-persistent-volume/templates/filestore-pv.yaml.tftpl
  modules/file-system/gke-persistent-volume/templates/gcs-pvc.yaml.tftpl
  modules/file-system/gke-persistent-volume/variables.tf
Labels: release-module-improvements

#4508 Added partial Slinky install option
  community/modules/scheduler/slinky/README.md
  community/modules/scheduler/slinky/main.tf
  community/modules/scheduler/slinky/outputs.tf
  community/modules/scheduler/slinky/variables.tf
Labels: release-module-improvements

#4527 Merge v1.62.1 into develop
  cmd/root.go
  community/front-end/ofe/infrastructure_files/gcs_bucket/clusters/ansible_setup/roles/c2_daemon/templates/ghpcfe_c2.yaml.j2
  community/front-end/ofe/infrastructure_files/gcs_bucket/clusters/ansible_setup/roles/containers/templates/enroot_credentials.j2
  community/front-end/ofe/website/ghpcfe/templates/blueprint/artifact_registry_config.yaml.j2
  community/front-end/ofe/website/ghpcfe/templates/blueprint/cloudsql_config.yaml.j2
  community/front-end/ofe/website/ghpcfe/templates/blueprint/cluster_config.yaml.j2
  community/front-end/ofe/website/ghpcfe/templates/blueprint/filesystem_config.yaml.j2
  community/front-end/ofe/website/ghpcfe/templates/blueprint/partition_config.yaml.j2
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/templates/setx_http_proxy.ps1
  community/modules/scripts/windows-startup-script/versions.tf
  examples/science/af3-slurm/examples/simple_job_launcher/launch_af3_job.sh.j2
  examples/science/af3-slurm/examples/simple_service_launcher/af3config.json.j2
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4550 Hotfix: Calculate correct "assuredCount" for reservations
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-bugfix

#4556 Add SlurmdTimeout of 900 sec to avoid hitting QP limit
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  examples/hpc-slurm-h4d.yaml
Labels: release-chore

#4516 updated the storage for a3Ultra to basic ssd
  examples/machine-learning/a3-ultragpu-8g/a3ultra-vm.yaml
Labels: release-breaking-changes

#4571 Merge V1.63.0 into Develop
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4577 Revert gke-node-pool module to using google-beta provider
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/versions.tf
Labels: release-version-updates, release-bugfix

#4477 Allow alternative services for private-service-access
  community/modules/network/private-service-access/README.md
  community/modules/network/private-service-access/main.tf
  community/modules/network/private-service-access/variables.tf
  community/modules/network/private-service-access/versions.tf
Labels: release-improvements

#4572 GKE Managed Lustre integration
  examples/gke-managed-lustre.yaml
  modules/file-system/gke-persistent-volume/README.md
  modules/file-system/gke-persistent-volume/main.tf
  modules/file-system/gke-persistent-volume/templates/managed-lustre-pv.yaml.tftpl
  modules/file-system/gke-persistent-volume/templates/managed-lustre-pvc.yaml.tftpl
  modules/file-system/gke-persistent-volume/variables.tf
  modules/file-system/managed-lustre/outputs.tf
  modules/network/firewall-rules/README.md
  modules/network/firewall-rules/main.tf
  modules/network/firewall-rules/variables.tf
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/variables.tf
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-managed-lustre.yml
  tools/cloud-build/daily-tests/builds/gke-managed-lustre.yaml
  tools/cloud-build/daily-tests/tests/gke-managed-lustre.yml
Labels: release-key-new-features, release-module-improvements

#4581 Update Toolkit release to v1.64.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore
