Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2025-01, with the labels that each got.

#3476 add GKE support for managed hyperdisk
  examples/README.md
  examples/gke-managed-hyperdisk.yaml
  examples/gke-managed-parallelstore.yaml
  modules/file-system/gke-storage/README.md
  modules/file-system/gke-storage/persistent-volume-claim/hyperdisk-balanced-pvc.yaml.tftpl
  modules/file-system/gke-storage/persistent-volume-claim/hyperdisk-extreme-pvc.yaml.tftpl
  modules/file-system/gke-storage/persistent-volume-claim/hyperdisk-throughput-pvc.yaml.tftpl
  modules/file-system/gke-storage/storage-class/hyperdisk-balanced-sc.yaml.tftpl
  modules/file-system/gke-storage/storage-class/hyperdisk-extreme-sc.yaml.tftpl
  modules/file-system/gke-storage/storage-class/hyperdisk-throughput-sc.yaml.tftpl
  modules/file-system/gke-storage/variables.tf
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-managed-hyperdisk.yml
  tools/cloud-build/daily-tests/builds/gke-managed-hyperdisk.yaml
  tools/cloud-build/daily-tests/tests/gke-managed-hyperdisk.yml
Labels: release-module-improvements

#3448 Replace duplicated `gpu_definition.tf` by shared internal module
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/gpu_definition.tf
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/gpu_definition.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/gpu_definition.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/reservation_definitions.tf
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/gpu_definition.tf
  modules/compute/vm-instance/main.tf
  modules/internal/gpu-definition/README.md
  modules/internal/gpu-definition/main.tf
  tools/duplicate-diff.py
Labels: release-chore

#3489 update README for managed-hyperdiska nd managed-parallelstore example blueprint
  examples/README.md
Labels: release-chore

#3412 Document unsupported "bracket-less" collection addressing
  examples/README.md
  pkg/config/expression.go
  pkg/config/expression_test.go
Labels: release-chore

#3430 Update python test `deployment_name` to `BUILD_ID`
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-reconfig-size.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-simple-job-completion.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-topology.yaml
  tools/python-integration-tests/blueprints/slurm-simple-reconfig.yaml
  tools/python-integration-tests/blueprints/slurm-simple.yaml
  tools/python-integration-tests/blueprints/topology-test.yaml
  tools/python-integration-tests/deployment.py
Labels: release-chore

#3490 Remove provisioningModel from future reservations
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
Labels: release-chore

#3493 Remove slurm-gcp v5 tests
  tools/cloud-build/daily-tests/builds/hcls-v5-legacy.yaml
  tools/cloud-build/daily-tests/builds/hpc-enterprise-slurm-v5-legacy.yaml
  tools/cloud-build/daily-tests/builds/hpc-slurm-chromedesktop-v5-legacy.yaml
  tools/cloud-build/daily-tests/builds/lustre-slurm-v5-legacy.yaml
  tools/cloud-build/daily-tests/builds/ml-a3-highgpu-slurm-v5.yaml
  tools/cloud-build/daily-tests/builds/ml-slurm-v5-legacy.yaml
  tools/cloud-build/daily-tests/builds/packer-v5-legacy.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-debian.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-hpc-centos7.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-rocky8.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-startup-scripts-v5-legacy.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v5-ubuntu2004.yaml
  tools/cloud-build/daily-tests/tests/hcls-v5-legacy.yml
  tools/cloud-build/daily-tests/tests/hpc-enterprise-slurm-v5-legacy.yml
  tools/cloud-build/daily-tests/tests/hpc-slurm-chromedesktop.yml
  tools/cloud-build/daily-tests/tests/lustre-slurm-v5-legacy.yml
  tools/cloud-build/daily-tests/tests/ml-a3-highgpu-slurm-cluster-legacy.yml
  tools/cloud-build/daily-tests/tests/ml-slurm-v5-legacy.yml
  tools/cloud-build/daily-tests/tests/packer-v5-legacy.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-debian.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-hpc-centos7.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-rocky8.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-startup-scripts.yml
  tools/cloud-build/daily-tests/tests/slurm-v5-ubuntu.yml
Labels: release-deprecations

#3498 Revert "Revert use of toolkit_modules_url in examples"
  community/examples/tutorial-starccm-slurm.yaml
  docs/hybrid-slurm-cluster/blueprints/hybrid-configuration.yaml
Labels: release-chore

#3494 Remove slurm-gcp v5 examples and update documentation
  community/examples/AMD/README.md
  community/examples/AMD/hpc-amd-slurm-v5-legacy.yaml
  community/examples/hpc-slurm-chromedesktop-v5-legacy.yaml
  community/examples/hpc-slurm-local-ssd-v5-legacy.yaml
  community/examples/hpc-slurm-ubuntu2004-v5-legacy.yaml
  community/examples/htc-slurm-v5-legacy.yaml
  docs/videos/healthcare-and-life-sciences/README.md
  docs/videos/healthcare-and-life-sciences/hcls-blueprint-v5-legacy.yaml
  examples/README.md
  examples/cae/README.md
  examples/cae/cae-slurm-v5-legacy.yaml
  examples/hpc-enterprise-slurm-v5-legacy.yaml
  examples/hpc-slurm-v5-legacy.yaml
  examples/image-builder-v5-legacy.yaml
  examples/machine-learning/a3-highgpu-8g/v5-legacy/README.md
  examples/machine-learning/a3-highgpu-8g/v5-legacy/ml-slurm-a3-0-base-v5-legacy.yaml
  examples/machine-learning/a3-highgpu-8g/v5-legacy/ml-slurm-a3-1-image-v5-legacy.yaml
  examples/machine-learning/a3-highgpu-8g/v5-legacy/ml-slurm-a3-2-cluster-v5-legacy.yaml
  examples/ml-slurm-v5-legacy.yaml
  tools/cloud-build/daily-tests/blueprints/lustre-slurm-v5-legacy.yaml
  tools/validate_configs/test_configs/gpu-v5-legacy.yaml
  tools/validate_configs/test_configs/node-groups-v5-legacy.yaml
  tools/validate_configs/test_configs/slurm-gcp-v5-startup-scripts-v5-legacy.yaml
  tools/validate_configs/test_configs/slurm-static-test-v5-legacy.yaml
  tools/validate_configs/test_configs/zone-policies-slurm-v5-legacy.yaml
Labels: release-deprecations

#3501 Update A3U blueprint to remove MTU var
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
Labels: release-chore

#3413 Add max_distance variable
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/outputs.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/common.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-key-new-features

#3502 Remove max_hops plugin
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurm_gcp_plugins/max_hops/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurm_gcp_plugins/max_hops/__init__.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-chore

#3507 Add shielded instance config to default pool
  modules/scheduler/gke-cluster/main.tf
Labels: release-module-improvements

#3506 Add blueprint name before build ID
  tools/python-integration-tests/blueprints/slurm-simple-reconfig.yaml
  tools/python-integration-tests/blueprints/slurm-simple.yaml
  tools/python-integration-tests/blueprints/topology-test.yaml
  tools/python-integration-tests/deployment.py
Labels: release-chore

#3508 Hotfix: Slurm autoscaler support for future reservations
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
Labels: release-bugfix

#3510 Fix main->develop merge
  examples/gke-a3-ultragpu/README.md
  examples/gke-a3-ultragpu/gke-a3-ultragpu-deployment.yaml
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  examples/gke-a3-ultragpu/mglru-disable.yaml
  examples/gke-a3-ultragpu/nccl-installer.yaml
  examples/gke-a3-ultragpu/nccl-jobset-example.yaml
  examples/gke-a3-ultragpu/nccl-test-32-node.yaml
  examples/gke-a3-ultragpu/nccl-test.yaml
  tools/validate_configs/validate_configs.sh
Labels: release-chore

#3505 Update reservation used by GKE A3 Ultra integration test
  tools/cloud-build/daily-tests/tests/gke-a3-ultragpu.yml
Labels: release-chore

#3503 Freeze gcluster version for blueprints which were not migrated to slurm-gcp v6
  docs/hybrid-slurm-cluster/blueprints/static-cluster.yaml
  tools/validate_configs/test_configs/two-clusters-sql.yaml
Labels: release-chore

#3512 Python Integration Test - Support tests running concurrently
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-reconfig-size.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-simple-job-completion.yaml
  tools/cloud-build/daily-tests/validate_tests_metadata.py
  tools/python-integration-tests/blueprints/slurm-reconfig-after.yaml
  tools/python-integration-tests/blueprints/slurm-reconfig-before.yaml
  tools/python-integration-tests/slurm_reconfig_size.py
  tools/python-integration-tests/ssh.py
  tools/python-integration-tests/test.py
Labels: release-chore

#3497 Remove Slurm-gcp v5 modules and update documentation
  cmd/create.go
  community/front-end/ofe/infrastructure_files/gcs_bucket/webserver/startup.sh
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/gpu_definition.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/metadata.yaml
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/outputs.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-node-group/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/metadata.yaml
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/outputs.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v5-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/metadata.yaml
  community/modules/compute/schedmd-slurm-gcp-v5-partition/outputs.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v5-partition/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/etc/htc-slurm.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/etc/htc-slurmdbd.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/etc/long-prolog-slurm.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/metadata.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/outputs.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/metadata.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-hybrid/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/gpu_definition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/metadata.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v5-login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scripts/spack-setup/README.md
  docs/gpu-support.md
  docs/slurm-troubleshooting.md
  docs/vm-images.md
  examples/hpc-enterprise-slurm.yaml
  modules/README.md
  pkg/modulereader/metadata_legacy.go
  tools/cloud-build/project-cleanup-slurm.yaml
  tools/duplicate-diff.py
  tools/validate_configs/golden_copies/configs/versioned_blueprint.yaml
  tools/validate_configs/validate_configs.sh
Labels: release-deprecations

#3499 Enable optional creation of cloud router/nat for vpcs
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/variables.tf
  modules/network/vpc/README.md
  modules/network/vpc/main.tf
  modules/network/vpc/variables.tf
Labels: release-improvements

#3516 Update dependabot version update configuration
  .github/dependabot.yml
Labels: release-chore

#3520 Use version prefix in conjunction with release channels
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/variables.tf
Labels: release-improvements

#3519 Restore a3-ultragpu-8g Slurm blueprints and integration test
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/README.md
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/a3u-slurm-ubuntu-gcs.yaml
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/deployment.yaml
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/run-nccl-tests-via-ramble.sh
  examples/machine-learning/a3-ultragpu-8g/README.md
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-deployment.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-vm.yaml
  examples/machine-learning/a3-ultragpu-8g/nccl-tests/README.md
  examples/machine-learning/a3-ultragpu-8g/nccl-tests/build-nccl-tests.sh
  examples/machine-learning/a3-ultragpu-8g/nccl-tests/import_pytorch_container.sh
  examples/machine-learning/a3-ultragpu-8g/nccl-tests/run-nccl-tests.sh
  tools/cloud-build/daily-tests/ansible_playbooks/post-destroy-tasks/delete-image.yml
  tools/cloud-build/daily-tests/builds/ml-a3-ultragpu-slurm.yaml
  tools/cloud-build/daily-tests/tests/ml-a3-ultragpu-slurm.yml
  tools/cloud-build/daily-tests/validate_tests_metadata.py
Labels: release-chore

#3521 Update Filestore examples to use Private Service Access
  community/examples/hpc-slurm-gromacs.yaml
  community/examples/hpc-slurm-local-ssd.yaml
  community/examples/hpc-slurm-ubuntu2004.yaml
  community/examples/htc-slurm.yaml
  examples/hcls-blueprint.yaml
  examples/hpc-enterprise-slurm.yaml
  examples/hpc-slurm.yaml
  examples/ml-slurm.yaml
  tools/cloud-build/daily-tests/builds/hcls.yaml
  tools/cloud-build/daily-tests/builds/hpc-enterprise-slurm.yaml
  tools/cloud-build/daily-tests/builds/htc-slurm.yaml
  tools/cloud-build/daily-tests/builds/ml-slurm.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-debian.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-rocky8.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-ssd.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-ubuntu.yaml
  tools/cloud-build/daily-tests/builds/spack-gromacs.yaml
Labels: release-chore

#3513 Enable hierarchical namespace support in cloud-storage-bucket module
  community/modules/file-system/cloud-storage-bucket/README.md
  community/modules/file-system/cloud-storage-bucket/main.tf
  community/modules/file-system/cloud-storage-bucket/variables.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
Labels: release-key-new-features

#3517 Bump jobset version to 0.7.2 and remove v0.7.1 as valid version
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  modules/management/kubectl-apply/manifests/jobset-v0.7.2.yaml
  modules/management/kubectl-apply/variables.tf
Labels: release-improvements

#3523 Update network storage document after v5 deprecation
  docs/network_storage.md
Labels: release-chore

#3487 Add support for Redhat 7, 8 and 9 to startup-script Anisble
  modules/scripts/startup-script/files/install_ansible.sh
  tools/cloud-build/daily-tests/blueprints/ansible-vm.yaml
Labels: release-module-improvements

#3524 Enable exclusive partition in A3 Ultra Slurm standard blueprint
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
Labels: release-chore

#3300 Include MemSpecLimit when calculating defmem
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
Labels: release-improvements

#3477 Add NeMo framework example to a3-Ultra
  examples/machine-learning/a3-ultragpu-8g/nemo-framework/Dockerfile
  examples/machine-learning/a3-ultragpu-8g/nemo-framework/README.md
  examples/machine-learning/a3-ultragpu-8g/nemo-framework/setup_nemo.sh
Labels: release-key-new-features

#3418 Add option for NFSv4 to Filestore creation
  modules/file-system/filestore/README.md
  modules/file-system/filestore/main.tf
  modules/file-system/filestore/variables.tf
Labels: release-chore

#3401 Add uniqueness validation for subnetwork_ranges_list items
  modules/network/vpc/README.md
  modules/network/vpc/main.tf
  modules/network/vpc/variables.tf
Labels: release-chore

#3526 Update Minimum terraform version in Makefile from 1.2 to 1.5.7
  Makefile
Labels: release-version-updates

#3528 Fixing validation block error in Filestore module
  modules/file-system/filestore/README.md
  modules/file-system/filestore/main.tf
  modules/file-system/filestore/variables.tf
  modules/file-system/filestore/versions.tf
Labels: release-improvements

#3530 Increase version to v1.45.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3532 Update OFE virtualenv to address CVE-2024-53899
  community/front-end/ofe/requirements.txt
Labels: release-chore

#3531 Improve dependency version coverage of Toolkit pre-commit
  .github/workflows/pr-precommit.yml
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/requirements.txt
Labels: release-chore

#3525 SlurmGCP. Deprecate `enable_smt`, add `advanced_machine_features`
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
  community/modules/internal/slurm-gcp/instance_template/README.md
  community/modules/internal/slurm-gcp/instance_template/main.tf
  community/modules/internal/slurm-gcp/instance_template/variables.tf
  community/modules/internal/slurm-gcp/internal_instance_template/README.md
  community/modules/internal/slurm-gcp/internal_instance_template/main.tf
  community/modules/internal/slurm-gcp/internal_instance_template/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
  examples/hcls-blueprint.yaml
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-2-cluster.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-cluster.yaml
  tools/validate_configs/test_configs/node-groups.yaml
  tools/validate_configs/test_configs/two-clusters-sql.yaml
Labels: release-module-improvements

#3536 Updating location for gke-managed-hyperdisk test
  examples/gke-managed-hyperdisk.yaml
  tools/cloud-build/daily-tests/builds/gke-managed-hyperdisk.yaml
  tools/cloud-build/daily-tests/tests/gke-managed-hyperdisk.yml
Labels: release-improvements

#3549 Merging updates in v1.45.0 release candidate branch into develop
  cmd/root.go
  community/front-end/ofe/requirements.txt
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3537 SlurmGCP. Fix mypy errors, and found bug
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3551 Remove A3 Ultra readme inaccessible warning
  examples/gke-a3-ultragpu/README.md
Labels: release-chore

#3552 Updating A3 Ultra JBVM blueprint README documentation
  examples/machine-learning/a3-ultragpu-8g/README.md
Labels: release-improvements

#3527 Adding a note to use of Private Service Access module
  community/examples/hpc-slurm-gromacs.yaml
  community/examples/hpc-slurm-local-ssd.yaml
  community/examples/hpc-slurm-ubuntu2004.yaml
  community/examples/htc-slurm.yaml
  community/modules/network/private-service-access/README.md
  examples/gke-managed-parallelstore.yaml
  examples/hcls-blueprint.yaml
  examples/hpc-enterprise-slurm.yaml
  examples/hpc-slurm.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-base.yaml
  examples/ml-slurm.yaml
  examples/pfs-parallelstore.yaml
  examples/ps-slurm.yaml
  modules/file-system/gke-storage/README.md
  modules/file-system/parallelstore/README.md
Labels: release-module-improvements

#3553 Remove duplicative LimitNOFILE overrides
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/a3u-slurm-ubuntu-gcs.yaml
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
Labels: release-chore

#3555 Remove expanded blueprint from A3U Slurm solution
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
Labels: release-chore

#3557 Set correct go toolchain version
  Makefile
  go.mod
  tools/cloud-build/provision/pr-go-build-test.tf
Labels: release-chore

#3556 Remove netplan from A3 Ultra Slurm solution
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
Labels: release-chore

#3554 Remove terraformrc file for private provider configuration
  tools/cloud-build/images/test-runner/Dockerfile
  tools/cloud-build/images/test-runner/terraformrc
Labels: release-chore

#3535 Deprecate Slurm GCP plugins.
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurm_gcp_plugins/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurm_gcp_plugins/__init__.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurm_gcp_plugins/test_plugin/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurm_gcp_plugins/test_plugin/__init__.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurm_gcp_plugins/utils/__init__.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/suspend.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-deprecations

#3362 Untangle `exclusive` and `enable_placement`, update examples.
  community/examples/AMD/hpc-amd-slurm.yaml
  community/examples/hpc-slurm-sharedvpc.yaml
  community/examples/hpc-slurm-ubuntu2004.yaml
  community/examples/htc-slurm.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/outputs.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/outputs.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  docs/hybrid-slurm-cluster/blueprints/hybrid-configuration.yaml
  docs/tutorials/hpc-slurm-qwiklabs.yaml
  examples/hcls-blueprint.yaml
  examples/hpc-enterprise-slurm.yaml
  examples/hpc-slurm-static.yaml
  examples/hpc-slurm.yaml
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-2-cluster.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-cluster.yaml
  examples/ml-slurm.yaml
  examples/ps-slurm.yaml
  tools/cloud-build/daily-tests/blueprints/lustre-slurm.yaml
  tools/python-integration-tests/blueprints/topology-test.yaml
  tools/validate_configs/golden_copies/configs/versioned_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/main.tf
  tools/validate_configs/test_configs/config-ssh.yaml
  tools/validate_configs/test_configs/gpu.yaml
  tools/validate_configs/test_configs/slurm-gcp-v6-startup-scripts.yaml
  tools/validate_configs/test_configs/zone-policies-slurm.yaml
Labels: release-improvements

#3562 docs(DDN-EXAScaler): current links caption
  community/modules/file-system/DDN-EXAScaler/README.md
Labels: release-chore

#3454 Add a3u-gke-gcs blueprint
  examples/hypercompute_clusters/a3u-gke-gcs/README.md
  examples/hypercompute_clusters/a3u-gke-gcs/a3u-gke-gcs.yaml
  examples/hypercompute_clusters/a3u-gke-gcs/deployment.yaml
  examples/hypercompute_clusters/a3u-gke-gcs/kueue-configuration.yaml.tftpl
  examples/hypercompute_clusters/a3u-gke-gcs/nccl-rdma-installer.yaml
  examples/hypercompute_clusters/a3u-gke-gcs/system_benchmarks/README.md
  examples/hypercompute_clusters/a3u-gke-gcs/system_benchmarks/ramble-hpl.yaml
  examples/hypercompute_clusters/a3u-gke-gcs/system_benchmarks/ramble-nccl.yaml
  examples/hypercompute_clusters/a3u-gke-gcs/system_benchmarks/ramble-nemo.yaml
  modules/file-system/gke-persistent-volume/main.tf
  modules/file-system/gke-persistent-volume/templates/gcs-pv.yaml.tftpl
Labels: release-key-new-features

#3559 Remove slurm portion of dependabot config
  .github/dependabot.yml
  tools/cloud-build/images/test-runner/Dockerfile
Labels: release-chore

#3574 Remove unnecessary constraint on static+dynamic with placement
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/outputs.tf
Labels: release-module-improvements

#3573 Revert PR 3406
  community/modules/compute/gke-topology-scheduler/README.md
  community/modules/compute/gke-topology-scheduler/main.tf
  community/modules/compute/gke-topology-scheduler/variables.tf
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/variables.tf
  modules/file-system/gke-persistent-volume/README.md
  modules/file-system/gke-persistent-volume/main.tf
  modules/file-system/gke-persistent-volume/variables.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/README.md
  modules/file-system/gke-storage/main.tf
  modules/file-system/gke-storage/variables.tf
  modules/management/kubectl-apply/README.md
  modules/management/kubectl-apply/main.tf
  modules/management/kubectl-apply/providers.tf
  modules/management/kubectl-apply/variables.tf
  modules/management/kubectl-apply/versions.tf
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/outputs.tf
  modules/scheduler/pre-existing-gke-cluster/README.md
  modules/scheduler/pre-existing-gke-cluster/main.tf
  modules/scheduler/pre-existing-gke-cluster/outputs.tf
  pkg/config/expand.go
  pkg/config/expand_test.go
Labels: release-bugfix

#3576 Merge main into develop
  community/modules/compute/gke-topology-scheduler/README.md
  community/modules/compute/gke-topology-scheduler/main.tf
  community/modules/compute/gke-topology-scheduler/variables.tf
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/variables.tf
  modules/file-system/gke-persistent-volume/README.md
  modules/file-system/gke-persistent-volume/main.tf
  modules/file-system/gke-persistent-volume/variables.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/README.md
  modules/file-system/gke-storage/main.tf
  modules/file-system/gke-storage/variables.tf
  modules/management/kubectl-apply/README.md
  modules/management/kubectl-apply/main.tf
  modules/management/kubectl-apply/providers.tf
  modules/management/kubectl-apply/variables.tf
  modules/management/kubectl-apply/versions.tf
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/outputs.tf
  modules/scheduler/pre-existing-gke-cluster/README.md
  modules/scheduler/pre-existing-gke-cluster/main.tf
  modules/scheduler/pre-existing-gke-cluster/outputs.tf
  pkg/config/expand.go
  pkg/config/expand_test.go
Labels: release-chore

#3561 SlurmGCP. Refactor timestamp parsing
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3587 Change seed to update test schedule
  tools/cloud-build/provision/list_tests.py
Labels: release-chore

#3577 Added support for clean target to remove gcluster binary and the ghpc…
  Makefile
Labels: enhancement, release-improvements

#3580 Use `dataclass` for GCP instance
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/suspend.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/common.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_topology.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3585 Change cloud rdma installation script to upgrade packages
  modules/scripts/startup-script/files/install_cloud_rdma_drivers.sh
Labels: bug, release-chore

#3578 Add H4d vm blueprint
  examples/h4d-vm.yaml
Labels: release-key-new-features

#3586 Add H4d Slurm cluster example
  community/examples/hpc-slurm-h4d.yaml
Labels: release-chore

#3588 Adding var.provisioning_model to vm-instance module
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/main.tf
  modules/compute/vm-instance/variables.tf
Labels: release-module-improvements

#3564 SlurmGCP. Fix type annotations problems
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/load_bq.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup_network_storage.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/sort_nodes.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_topology.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3571 Improve GKE service account posture by aligning with GKE best practices
  examples/gke-a3-highgpu.yaml
  examples/gke-a3-megagpu.yaml
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  examples/gke-managed-hyperdisk.yaml
  examples/gke-managed-parallelstore.yaml
  examples/hpc-gke.yaml
  examples/hypercompute_clusters/a3u-gke-gcs/a3u-gke-gcs.yaml
  examples/ml-gke.yaml
  examples/storage-gke.yaml
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/outputs.tf
  tools/cloud-build/daily-tests/blueprints/gke-a2-highgpu.yaml
  tools/cloud-build/daily-tests/blueprints/ml-gke-e2e.yaml
  tools/cloud-build/daily-tests/builds/gke-a3-ultragpu.yaml
  tools/cloud-build/daily-tests/builds/gke-managed-hyperdisk.yaml
  tools/cloud-build/daily-tests/builds/gke-managed-parallelstore.yaml
  tools/cloud-build/daily-tests/tests/gke-managed-hyperdisk.yml
  tools/cloud-build/daily-tests/tests/gke-managed-parallelstore.yml
Labels: release-improvements

#3584 Adding ray operator addon support for GKE cluster creation
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/variables.tf
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-ray.yml
  tools/cloud-build/daily-tests/blueprints/ml-gke-e2e.yaml
  tools/cloud-build/daily-tests/tests/ml-gke-e2e.yml
Labels: release-improvements

#3579 Add integration test for a3ultra-vm.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-vm.yaml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-nvidia-smi.yml
  tools/cloud-build/daily-tests/builds/ml-a3-ultragpu-jbvms.yaml
  tools/cloud-build/daily-tests/tests/ml-a3-ultragpu-jbvms.yml
Labels: release-improvements

#3593 Updates to use variable provisioning_model for vm-instances
  community/modules/compute/pbspro-execution/main.tf
  community/modules/remote-desktop/chrome-remote-desktop/main.tf
  community/modules/scheduler/pbspro-client/main.tf
  community/modules/scheduler/pbspro-server/main.tf
Labels: release-chore

#3589 Replace Spack w/ Enroot/pyxis for NCCL tests
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/run-nccl-tests-via-ramble.sh
Labels: release-improvements

#3594 Update NCCL plugin to v1.0.3 in A3U
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/a3u-slurm-ubuntu-gcs.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a3-ultragpu-8g/nemo-framework/Dockerfile
Labels: release-version-updates

#3591 Fixed naming for deployment name in test to fit in size limit
  tools/cloud-build/daily-tests/tests/gke-a2-highgpu-kueue.yml
Labels: release-improvements

#3598 Fix k8s service account message issue
  modules/scheduler/gke-cluster/outputs.tf
Labels: release-chore

#3610 Update socket count and disable smt in slurm for h4d
  community/examples/hpc-slurm-h4d.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
  examples/h4d-vm.yaml
Labels: release-chore

#3601 Handle current API format for `upcomingMaintenance`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/common.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3609 SlurmGCP. More MyPy fixes
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/common.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_topology.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tpu.py
Labels: release-chore

#3607 Increase version to v1.46.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3614 Updates A3 image blueprints to set omit_external_ip to false
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
Labels: release-chore

#3612 Add in socket info for c4d
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3611 More MyPy fixes
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/load_bq.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3619 Remove explicitly stated mtu in gke-a3-ultragpu as default mtu has sa…
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
Labels: release-improvements

#3620 Support Kueue 0.10.1
  modules/management/kubectl-apply/manifests/kueue-v0.10.1.yaml
  modules/management/kubectl-apply/variables.tf
Labels: release-module-improvements

#3615 Add cuda-toolkit to a3ultra-jbvms blueprint
  examples/machine-learning/a3-ultragpu-8g/a3ultra-vm.yaml
Labels: release-improvements
