Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2025-07, with the labels that each got.

#4353 Add PayalJakhar to Cluster toolkit writers list
  cluster-toolkit-writers.json
Labels: release-chore

#4354 Update NCCL RDMA and Nvidia driver configs for a4x
  .yamllint
  examples/gke-a4x/nccl-rdma-installer.yaml
  examples/gke-a4x/nvidia-dra-driver.yaml
  modules/management/kubectl-apply/README.md
  modules/management/kubectl-apply/main.tf
  modules/management/kubectl-apply/variables.tf
Labels: release-chore

#4334 Install CHS on A3m and Common image
  examples/machine-learning/build-service-images/a3m/blueprint.yaml
  examples/machine-learning/build-service-images/common/blueprint.yaml
Labels: release-improvements

#4357 Add kadupoornima to cluster-toolkit-writers
  cluster-toolkit-writers.json
Labels: release-chore

#4358 Adding agrawalkhushi18 to cluster toolkit writer json
  cluster-toolkit-writers.json
Labels: release-chore

#4365 Don't log warning for acceptably missed instance metadata
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#4348 Add better logging for failed timeouts with google-cloud-ops-agent
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
Labels: release-chore

#4364 eliminate code duplication and move chs download to shared.yaml
  examples/machine-learning/build-service-images/a3m/blueprint.yaml
  examples/machine-learning/build-service-images/common/blueprint.yaml
  examples/machine-learning/build-service-images/shared.yaml
Labels: release-improvements

#4375 Add support for Kueue/TAS in gke-a4x
  examples/gke-a4x/kueue-configuration.yaml.tftpl
  examples/gke-a4x/nccl-jobset-example.yaml
Labels: release-improvements

#4317 feat: add script to automate nvidia-bug-report collection on GCE COS VM.
  community/gce-cos-nvidia-bug-report/Dockerfile
  community/gce-cos-nvidia-bug-report/README.md
  community/gce-cos-nvidia-bug-report/app/constants.py
  community/gce-cos-nvidia-bug-report/app/gce-cos-nvidia-bug-report.py
  community/gce-cos-nvidia-bug-report/app/requirements.txt
  community/gce-cos-nvidia-bug-report/build-and-push-gce-cos-nvidia-bug-report.sh
Labels: release-key-new-features

#4378 Update zone for DWS integration tests
  tools/cloud-build/daily-tests/tests/gke-a3u-dws-flex-start-queued-provisioning.yml
  tools/cloud-build/daily-tests/tests/gke-a3u-dws-flex-start.yml
Labels: release-chore

#4388 Update Toolkit release to v1.58.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4391 Fix bug in tensorflow example 'text input must be of type str
  examples/gke-managed-hyperdisk.yaml
Labels: release-bugfix

#4393 Fix bug in tensorflow example 'text input must be of type str
  examples/gke-managed-hyperdisk.yaml
Labels: release-chore

#4368 gke-node-pool module to use "google" instead of "google-beta" provider
  ml-01/primary/modules/embedded/community/modules/README.md
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/versions.tf
Labels: release-version-updates

#4394 Delete ml-01/primary/modules/embedded/community/modules directory
  ml-01/primary/modules/embedded/community/modules/README.md
Labels: release-chore

#4374 Symlink `/var/lib/mysql` to "state disk"
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
Labels: release-improvements

#4397 Move google_compute_image into check block
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/source_image_logic.tf
Labels: release-chore

#4398 Add retry functionality to google-cloud-ops and increase timeout
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
Labels: release-chore

#4402 update terraform-provider version to 6.43.0
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: release-chore

#4366 Adding ips_per_nat config for A family blueprints
  examples/gke-a3-highgpu.yaml
  examples/gke-a3-megagpu/gke-a3-megagpu.yaml
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  examples/gke-a4/gke-a4.yaml
  examples/gke-a4x/gke-a4x.yaml
  modules/network/vpc/README.md
  modules/network/vpc/variables.tf
Labels: release-module-improvements

#4403 Fix additional disks for login nodes
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
Labels: release-bugfix

#4395 update chs commit and fix typo in readme
  examples/machine-learning/build-service-images/README.md
  examples/machine-learning/build-service-images/shared.yaml
Labels: release-improvements

#4408 added rachit as a writer
  cluster-toolkit-writers.json
Labels: release-chore

#4404 Implement accelerator topology
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/outputs.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/common.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-improvements

#4379 Changes to Dockerfile for updating workstation image
  tools/cloud-workstations/Dockerfile
Labels: release-chore

#4409 Resolve a3u/a4h slurm nvidia version mismatch error
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
Labels: release-bugfix

#4407 Freeze accelerator image version to build service images
  examples/machine-learning/build-service-images/a3m/blueprint.yaml
  examples/machine-learning/build-service-images/common/blueprint.yaml
Labels: release-chore

#4413 Fix nvidia version mismatch for service images
  examples/machine-learning/build-service-images/common/blueprint.yaml
Labels: release-bugfix

#4435 Revert "Minimize tf drift for spot instances during re-deploy"
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
Labels: release-chore

#4434 update terraform-provider version to 6.45.0
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: release-chore

#4438 Update GKE release channel for a2 high Kueue integ. tests
  tools/cloud-build/daily-tests/blueprints/gke-a2-highgpu.yaml
Labels: release-improvements

#4445 Adding bytetwin(hanu) to writers
  cluster-toolkit-writers.json
Labels: release-chore

#4447 Updates the machine type of a4x in README.md file
  examples/gke-a4x/README.md
Labels: documentation, release-chore

#4453 Move base image forward, fixing lustre/nvidia/driver compat.
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
Labels: release-bugfix

#4455 Merge v1.59.2 to develop
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
Labels: release-chore

#4458 Hold all nvidia software to the same version
  examples/machine-learning/a3-megagpu-8g/a3mega-slurm-blueprint.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
  examples/machine-learning/build-service-images/a3m/blueprint.yaml
  examples/machine-learning/build-service-images/common/blueprint.yaml
Labels: release-bugfix

#4459 Hold all nvidia software to the same version (fix to develop)
  examples/machine-learning/a3-megagpu-8g/a3mega-slurm-blueprint.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
  examples/machine-learning/build-service-images/a3m/blueprint.yaml
  examples/machine-learning/build-service-images/common/blueprint.yaml
Labels: release-bugfix

#4436 Use setsid resume.py to reduce reconfigure time
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume_wrapper.sh
Labels: release-bugfix

#4451 namespace for gke-modules
  modules/file-system/gke-persistent-volume/README.md
  modules/file-system/gke-persistent-volume/main.tf
  modules/file-system/gke-persistent-volume/templates/filestore-pvc.yaml.tftpl
  modules/file-system/gke-persistent-volume/templates/gcs-pvc.yaml.tftpl
  modules/file-system/gke-persistent-volume/templates/namespace.yaml.tftpl
  modules/file-system/gke-persistent-volume/variables.tf
  modules/file-system/gke-storage/README.md
  modules/file-system/gke-storage/main.tf
  modules/file-system/gke-storage/persistent-volume-claim/hyperdisk-balanced-pvc.yaml.tftpl
  modules/file-system/gke-storage/persistent-volume-claim/hyperdisk-extreme-pvc.yaml.tftpl
  modules/file-system/gke-storage/persistent-volume-claim/hyperdisk-throughput-pvc.yaml.tftpl
  modules/file-system/gke-storage/persistent-volume-claim/namespace.yaml.tftpl
  modules/file-system/gke-storage/persistent-volume-claim/parallelstore-pvc.yaml.tftpl
  modules/file-system/gke-storage/variables.tf
Labels: release-module-improvements

#4372 Added capacity checks for reservations
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
Labels: release-improvements

#4464 update terraform-provider version to v6.46.0
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: release-chore

#4441 Add optimized gcsfuse configurations to A3 Ultra and A4 blueprints.
  examples/machine-learning/a3-ultragpu-8g/README.md
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/README.md
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
  tools/cloud-build/daily-tests/builds/ml-a3-ultragpu-slurm.yaml
  tools/cloud-build/daily-tests/builds/ml-a4-highgpu-slurm-flex.yaml
  tools/cloud-build/daily-tests/builds/ml-a4-highgpu-slurm.yaml
  tools/cloud-build/daily-tests/tests/ml-a3-ultragpu-slurm.yml
  tools/cloud-build/daily-tests/tests/ml-a4-highgpu-slurm.yml
Labels: release-improvements
