Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2025-09, with the labels that each got.

#4597 Merge v1.64.0 into develop
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4586 Add proxy check for verifying rank ordering [A3M]
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-kueue-config.yml
Labels: release-chore

#4537 Deprecate Debian blueprints from a3 mega gpu
  examples/machine-learning/a3-megagpu-8g/debian/README.md
  examples/machine-learning/a3-megagpu-8g/debian/deployment-base.yaml
  examples/machine-learning/a3-megagpu-8g/debian/deployment-image-cluster.yaml
  examples/machine-learning/a3-megagpu-8g/debian/slurm-a3mega-base.yaml
  examples/machine-learning/a3-megagpu-8g/debian/slurm-a3mega-cluster.yaml
  examples/machine-learning/a3-megagpu-8g/debian/slurm-a3mega-image.yaml
  tools/cloud-build/daily-tests/builds/ml-a3-megagpu-slurm.yaml
  tools/cloud-build/daily-tests/tests/ml-a3-megagpu-slurm-cluster.yml
  tools/cloud-build/daily-tests/tests/ml-a3-megagpu-slurm-image.yml
  tools/validate_configs/validate_configs.sh
Labels: release-deprecations

#4601 Adding unkillable_step_timeout (UnkillableStepTimeout) to the H4D blueprint.
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  examples/hpc-slurm-h4d.yaml
Labels: bug, release-chore

#4549 Add validation for disk compatibility
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/internal/slurm-gcp/instance_template/README.md
  community/modules/internal/slurm-gcp/instance_template/main.tf
  community/modules/internal/slurm-gcp/internal_instance_template/README.md
  community/modules/internal/slurm-gcp/internal_instance_template/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
  modules/internal/instance_validations/README.md
  modules/internal/instance_validations/main.tf
  modules/internal/instance_validations/variables.tf
  modules/internal/instance_validations/versions.tf
Labels: release-chore

#4611 Update Toolkit release to v1.65.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4614 Add sudo to systemctl restart
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#4619 Add saara-tyagi27 to writers.json
  cluster-toolkit-writers.json
Labels: release-chore

#4608 H4D enable gcsfuse and set cluster availability type to ZONAL
  examples/gke-h4d/gke-h4d.yaml
Labels: release-key-new-features

#4606 Upgrade to Slurm 25.05
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/machine-learning/a3-megagpu-8g/a3mega-slurm-blueprint.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
  examples/machine-learning/a4x-highgpu-4g/a4xhigh-slurm-blueprint.yaml
Labels: enhancement, release-improvements

#4631 revert a3 ultra integ test changes
  tools/cloud-build/daily-tests/tests/gke-a3-ultragpu.yml
Labels: release-chore

#4381 Add additional provisioning model options to H4D blueprint
  examples/hpc-slurm-h4d.yaml
Labels: release-chore

#4656 Merge V1.66.0 into Develop
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  examples/hpc-slurm-h4d.yaml
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4553 added nvidia-repositories script
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
Labels: release-module-improvements

#4663 Update the blueprints using managed_lustre vars to 36T/500MB Tier
  examples/gke-managed-lustre.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
  examples/pfs-managed-lustre-slurm.yaml
  examples/pfs-managed-lustre-vm.yaml
  modules/file-system/managed-lustre/README.md
  modules/file-system/managed-lustre/variables.tf
  tools/cloud-build/daily-tests/tests/gke-managed-lustre.yml
Labels: release-chore

#4669 Release candidate v1.67.0
  cmd/root.go
  community/examples/gke-tpu-v6/tpu-multislice.yaml
  community/gce-cos-nvidia-bug-report/Dockerfile
  community/gce-cos-nvidia-bug-report/README.md
  community/gce-cos-nvidia-bug-report/app/constants.py
  community/gce-cos-nvidia-bug-report/app/gce-cos-nvidia-bug-report.py
  community/gce-cos-nvidia-bug-report/build-and-push-gce-cos-nvidia-bug-report.sh
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  examples/machine-learning/a3-highgpu-8g/README.md
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-2-cluster.yaml
  examples/machine-learning/a3-megagpu-8g/a3mega-slurm-blueprint.yaml
  examples/machine-learning/a3-megagpu-8g/a3mega-slurm-deployment.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4618 Refactoring in gke persistent module
  modules/compute/gke-job-template/README.md
  modules/compute/gke-job-template/main.tf
  modules/compute/gke-job-template/variables.tf
  modules/file-system/gke-persistent-volume/README.md
  modules/file-system/gke-persistent-volume/main.tf
  modules/file-system/gke-persistent-volume/outputs.tf
  modules/file-system/gke-persistent-volume/versions.tf
Labels: release-module-improvements

#4675 Merge v1.67.0 into develop
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4667 Updated A3-mega and A4-high Slurm blueprints to adopt nvidia add repository scirpt.
  examples/machine-learning/a3-megagpu-8g/a3mega-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
Labels: release-improvements

#4679 Remove superfluous addition of chs logs to cloud ops config
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
Labels: release-bugfix

#4680 downloading libnccl2 and libnccl-dev for a3u and a4h
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
Labels: release-key-new-features

#4623 Adding "datacenter-gpu-manager-4-dev" as an additional installation in A* YAML files.
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/a3u-slurm-ubuntu-gcs.yaml
  examples/machine-learning/a3-megagpu-8g/a3mega-slurm-blueprint.yaml
  examples/machine-learning/a3-megagpu-8g/a3mega-slurm-gcsfuse-lssd-blueprint.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
  examples/machine-learning/a4x-highgpu-4g/a4xhigh-slurm-blueprint.yaml
  examples/machine-learning/build-service-images/common/blueprint.yaml
Labels: bug, release-bugfix

#4689 minor bug fix on MFT version comparison
  community/gce-cos-nvidia-bug-report/app/gce-cos-nvidia-bug-report.py
Labels: release-bugfix

#4694 add akiki-liang0 to writers.json
  cluster-toolkit-writers.json
Labels: release-chore

#4538 Fix inconsistent plan on Slurm cluster reconfigure
  community/modules/internal/slurm-gcp/login/README.md
  community/modules/internal/slurm-gcp/login/main.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  modules/scripts/startup-script/README.md
  modules/scripts/startup-script/main.tf
  modules/scripts/startup-script/versions.tf
Labels: release-bugfix

#4696 Allowing setting use_job_duration with non-exclusive partitions.
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/outputs.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/mig_flex.py
Labels: release-breaking-changes

#4707 Update process to filter out starting comments in a source yaml file
  modules/management/kubectl-apply/kubectl/main.tf
Labels: release-bugfix
