Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2025-05, with the labels that each got.

#4030 Fix `placement_max_distance` in slurm partitions
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
Labels: release-bugfix

#3978 Fix a typo (a Filestore mention) in the GCS Fuse variable description (GKE Cluster module)
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/variables.tf
Labels: release-chore

#4019 Add support for task-level prolog and epilog. Closes #4013
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/common.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-chore

#4022 Adding GKE support for Managed Lustre
  modules/file-system/managed-lustre/README.md
  modules/file-system/managed-lustre/main.tf
  modules/file-system/managed-lustre/scripts/install-managed-lustre-client.sh
  modules/file-system/managed-lustre/variables.tf
  modules/file-system/pre-existing-network-storage/README.md
  modules/file-system/pre-existing-network-storage/outputs.tf
  modules/file-system/pre-existing-network-storage/scripts/install-managed-lustre-client.sh
  modules/file-system/pre-existing-network-storage/variables.tf
Labels: release-module-improvements

#3945 Add dws flex and spot provisioning options to the A4 example
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
  examples/machine-learning/a4-highgpu-8g/README.md
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-deployment.yaml
Labels: release-improvements

#4038 Fix typo on DWS machine type validation
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/outputs.tf
Labels: release-chore

#4042 Add RDMA preflight script in /tools for convenience
  tools/rdma-preflight.sh
Labels: release-chore

#4043 Release machine type validation for dws flex
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/outputs.tf
Labels: release-chore

#4044 Add randomness to managed lustre integration tests
  examples/pfs-managed-lustre-slurm.yaml
  examples/pfs-managed-lustre-vm.yaml
  tools/cloud-build/daily-tests/tests/pfs-managed-lustre-slurm.yml
  tools/cloud-build/daily-tests/tests/pfs-managed-lustre-vm.yml
Labels: release-chore

#4046 Update toolkit release to v1.50.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4052 Fix logic for verifying gpu count for machine types
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/outputs.tf
Labels: release-chore

#4053 Merge #4052 into release-candidate
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/outputs.tf
Labels: release-chore

#4059 A3 Ultra Slurm: workaround temporary driver packaging issue
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
Labels: release-bugfix

#4062 Merge Main to Develop
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4048 add gpu-health-epilog check to the A3 High and A3 Mega Slurm blueprints
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-2-cluster.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-cluster.yaml
Labels: release-improvements

#4055 Explicitly define labels at `google_compute_instance_from_template`
  community/modules/internal/slurm-gcp/instance/main.tf
  community/modules/internal/slurm-gcp/instance_template/README.md
  community/modules/internal/slurm-gcp/instance_template/main.tf
  community/modules/internal/slurm-gcp/instance_template/outputs.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
Labels: release-bugfix

#4060 add GKE version_prefix support as a configurable parameter
  examples/gke-a3-megagpu/gke-a3-megagpu.yaml
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  examples/gke-a4/gke-a4.yaml
Labels: release-key-new-features

#4067 Update helm manifest for nvidia dra driver
  modules/management/kubectl-apply/main.tf
Labels: release-improvements

#4027 Add preconditions for the flex start option of GKE nodepool
  modules/compute/gke-node-pool/main.tf
Labels: release-chore

#4049 Test nvidia-smi on A* blueprints
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gpus-slurm.yml
  tools/cloud-build/daily-tests/tests/ml-a3-highgpu-slurm-cluster.yml
  tools/cloud-build/daily-tests/tests/ml-a3-megagpu-slurm-cluster.yml
  tools/cloud-build/daily-tests/tests/ml-a3-ultragpu-slurm.yml
  tools/cloud-build/daily-tests/tests/ml-a4-highgpu-slurm.yml
Labels: release-chore

#4063 Update terraform provider version to v6.33.0
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: release-chore

#4066 Remove instance image override at the top of cae.yaml example
  examples/cae/cae-slurm.yaml
Labels: release-bugfix

#4072 Update terraform provider version to v6.34.0
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: release-chore

#4023 Bring parity of functionality to both A3U and A4
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
Labels: release-improvements, release-breaking-changes

#4051 Add TPU V6 Trillium example
  community/examples/gke-tpu-v4-2x2x2/tpu-available-chips.yaml
  community/examples/gke-tpu-v6/README.md
  community/examples/gke-tpu-v6/gke-tpu-v6-deployment.yaml
  community/examples/gke-tpu-v6/gke-tpu-v6.yaml
  community/examples/gke-tpu-v6/tpu-multislice.yaml
  examples/README.md
  tools/validate_configs/validate_configs.sh
Labels: release-improvements

#4081 split kubectl installation into two parts to reduce race conditions
  modules/management/kubectl-apply/main.tf
Labels: release-bugfix

#4054 Surface other consumption options in a3u examples and update docs
  docs/slurm-dws-flex.md
  examples/machine-learning/a3-ultragpu-8g/README.md
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-deployment.yaml
  examples/machine-learning/a4-highgpu-8g/README.md
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-deployment.yaml
Labels: release-chore

#4045 Managed Lustre Data Import (Hydration)
  modules/file-system/managed-lustre/README.md
  modules/file-system/managed-lustre/main.tf
  modules/file-system/managed-lustre/variables.tf
Labels: release-module-improvements

#4082 Improve `sync_placement_groups` API consumption
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3968 GKE consumption option examples
  examples/README.md
  examples/gke-consumption-options/README.md
  examples/gke-consumption-options/dws-calendar/README.md
  examples/gke-consumption-options/dws-calendar/gke-a3-ultragpu-deployment.yaml
  examples/gke-consumption-options/dws-calendar/gke-a3-ultragpu.yaml
  examples/gke-consumption-options/dws-calendar/mglru-disable.yaml
  examples/gke-consumption-options/dws-calendar/nccl-installer.yaml
  examples/gke-consumption-options/dws-flex-start-queued-provisioning/README.md
  examples/gke-consumption-options/dws-flex-start-queued-provisioning/dws-queues.yaml.tftpl
  examples/gke-consumption-options/dws-flex-start-queued-provisioning/gke-a3-ultragpu-deployment.yaml
  examples/gke-consumption-options/dws-flex-start-queued-provisioning/gke-a3-ultragpu.yaml
  examples/gke-consumption-options/dws-flex-start-queued-provisioning/mglru-disable.yaml
  examples/gke-consumption-options/dws-flex-start-queued-provisioning/nccl-installer.yaml
  examples/gke-consumption-options/dws-flex-start-queued-provisioning/sample-job.yaml
  examples/gke-consumption-options/dws-flex-start/README.md
  examples/gke-consumption-options/dws-flex-start/dws-flex-start.yaml
  examples/gke-consumption-options/dws-flex-start/gke-a3-ultragpu-deployment.yaml
  examples/gke-consumption-options/dws-flex-start/gke-a3-ultragpu.yaml
  examples/gke-consumption-options/dws-flex-start/mglru-disable.yaml
  examples/gke-consumption-options/dws-flex-start/nccl-installer.yaml
  examples/gke-dws-flex-start/README.md
  examples/gke-dws-flex-start/gke-dws-flex-start.yaml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-dws-flex-start.yml
  tools/cloud-build/daily-tests/builds/gke-dws-flex-start.yaml
  tools/cloud-build/daily-tests/tests/gke-dws-flex-start.yml
  tools/validate_configs/validate_configs.sh
Labels: release-improvements

#4080 Adding DCGM test to gpu tests for slurm
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gpus-slurm.yml
Labels: release-chore

#4071 Add copying prolog and epilog scripts to compute nodes
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-improvements

#4078 Add gpu nodes for a3-highgpu-1,2,4g
  modules/internal/gpu-definition/main.tf
Labels: release-chore

#4084 Adding persistenced check to slurm-gpu tests
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gpus-slurm.yml
  tools/cloud-build/daily-tests/tests/ml-a3-ultragpu-slurm.yml
  tools/cloud-build/daily-tests/tests/ml-a4-highgpu-slurm.yml
Labels: release-chore

#4090 Remove DWS Calendar example until the release
  examples/gke-consumption-options/dws-calendar/README.md
  examples/gke-consumption-options/dws-calendar/gke-a3-ultragpu-deployment.yaml
  examples/gke-consumption-options/dws-calendar/gke-a3-ultragpu.yaml
  examples/gke-consumption-options/dws-calendar/mglru-disable.yaml
  examples/gke-consumption-options/dws-calendar/nccl-installer.yaml
Labels: release-chore

#4093 Fix gke a3 mega integration test
  modules/compute/gke-node-pool/gpu_direct.tf
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-a3-mega.yml
Labels: release-bugfix

#4092 Update Open Front End Django dependency and fix OFE integration test
  community/front-end/ofe/requirements.txt
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-ofe-deployment.yml
Labels: release-chore

#4094 Add developer key option for slurm
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-module-improvements

#4069 Better integrate, optimize, and control the gIB NCCL RDMA plugin installer
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  examples/gke-a3-ultragpu/nccl-installer.yaml.tftpl
  examples/gke-a4/gke-a4.yaml
  examples/gke-a4/nccl-installer.yaml.tftpl
  modules/management/kubectl-apply/README.md
  modules/management/kubectl-apply/kubectl/README.md
  modules/management/kubectl-apply/kubectl/variables.tf
  modules/management/kubectl-apply/main.tf
  modules/management/kubectl-apply/variables.tf
Labels: release-key-new-features, release-module-improvements

#4089 Update default Accelerator Image in A3 Ultra and A4 Slurm blueprints
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
Labels: release-bugfix

#4101 Update Toolkit release to v1.51.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4040 Get rid of template_cache
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/file_cache.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#4106 Improve logging details of `subprocess.run`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#4108 Set resumeTimeout to max for all flex partitions
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/outputs.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/main.tf
  docs/slurm-dws-flex.md
Labels: release-chore

#4107 Fix multiple bugs in notifying jobs during failed resume
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
Labels: release-bugfix

#4065 Relax `retry_exception` test
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-bugfix

#4105 Add support for multiple task prolog and epilog scripts. Closes #4100
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tools/task-epilog
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tools/task-prolog
Labels: release-improvements

#4116 update terraform-provider version to v6.34.1
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: release-chore

#4117 Small adjustment to README for modules to include managed-lustre
  modules/README.md
Labels: release-chore

#4031 Make delete instances status tracking "asynchronous"
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/local_pubsub.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/suspend.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/watch_delete_vm_op.py
Labels: release-chore

#4077 Fix documentation related to lustre blueprint friction
  community/modules/file-system/DDN-EXAScaler/README.md
  examples/README.md
Labels: release-chore

#4088 remove gvnic-1 from pods manifests
  examples/gke-a3-ultragpu/nccl-jobset-example.yaml
  examples/gke-a3-ultragpu/system_benchmarks/ramble-hpl.yaml
  examples/gke-a3-ultragpu/system_benchmarks/ramble-nccl.yaml
  examples/gke-a3-ultragpu/system_benchmarks/ramble-nemo.yaml
  examples/gke-a4/nccl-jobset-example.yaml
Labels: release-improvements

#4122 Remove pre-set deployment names from GKE example blueprints
  examples/gke-a3-highgpu.yaml
  examples/gke-a3-megagpu/gke-a3-megagpu-deployment.yaml
  examples/gke-a3-ultragpu/gke-a3-ultragpu-deployment.yaml
  examples/gke-a4/gke-a4-deployment.yaml
  examples/gke-consumption-options/dws-flex-start-queued-provisioning/gke-a3-ultragpu-deployment.yaml
  examples/gke-consumption-options/dws-flex-start/gke-a3-ultragpu-deployment.yaml
Labels: release-chore

#4127 Move core logic of helm install into independent helm module
  community/modules/management/helm-install/helm_install/README.md
  community/modules/management/helm-install/helm_install/main.tf
  community/modules/management/helm-install/helm_install/metadata.yaml
  community/modules/management/helm-install/helm_install/variables.tf
  community/modules/management/helm-install/helm_install/versions.tf
Labels: release-improvements

#4125 Fixes to nodeset dynamic
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/variables.tf
Labels: release-bugfix

#4113 Fix missing region
  community/modules/internal/slurm-gcp/instance_template/README.md
  community/modules/internal/slurm-gcp/instance_template/variables.tf
  community/modules/internal/slurm-gcp/internal_instance_template/README.md
  community/modules/internal/slurm-gcp/internal_instance_template/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
Labels: release-bugfix

#4123 Updating Slurm dev key logic to use static file instead of env var
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#4124 Fix script destination path concat in setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
Labels: release-chore

#4115 CloudSQL improvements: database flags, query insights, bump default version
  community/modules/database/slurm-cloudsql-federation/README.md
  community/modules/database/slurm-cloudsql-federation/main.tf
  community/modules/database/slurm-cloudsql-federation/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
Labels: release-breaking-changes

#4136 New way to timeout on dpkg during `install_ansible`
  modules/scripts/startup-script/files/install_ansible.sh
Labels: release-chore

#4133 Update Toolkit release to v1.52.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4134 deprecate old gke a3 mega blueprint
  examples/gke-a3-megagpu.yaml
Labels: release-deprecations

#4138 Drop CentOS 7 support for Ansible installation
  modules/scripts/startup-script/files/install_ansible.sh
  tools/cloud-build/daily-tests/blueprints/ansible-vm.yaml
  tools/cloud-build/daily-tests/tests/ansible-vm.yml
Labels: release-deprecations

#4139 Upgrade Ansible to maximum allowed version on oldest supported OS distributions
  modules/scripts/startup-script/files/install_ansible.sh
Labels: release-version-updates

#4140 Add Ubuntu 24.04 Ansible installation and test coverage
  modules/scripts/startup-script/files/install_ansible.sh
  tools/cloud-build/daily-tests/blueprints/ansible-vm.yaml
Labels: release-key-new-features

#4141 Do not fail `setup_controller` if `sync_instances` fails
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
Labels: release-chore

#4145 Block broken release of nvidia-container-toolkit
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
Labels: release-bugfix

#4146 Improve Slurm GPU testing
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gpus-slurm.yml
Labels: release-chore

#4152 Block broken release of nvidia-container-toolkit
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
Labels: release-bugfix

#4155 Merge v1.51.1 hotfix release into v1.52.0 candidate release branch
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
Labels: release-chore

#4156 Fix invalid import
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
Labels: release-chore

#4057 Allow deploying cluster without live reservation
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/reservation_definitions.tf
  modules/compute/gke-node-pool/variables.tf
  tools/cloud-build/daily-tests/README.md
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-cluster-provisioning.yml
  tools/cloud-build/daily-tests/builds/gke-inactive-reservation.yaml
  tools/cloud-build/daily-tests/tests/gke-inactive-reservation.yml
Labels: release-module-improvements

#4162 Updating variable documentation in blueprints
  examples/gke-a3-megagpu/gke-a3-megagpu-deployment.yaml
  examples/gke-a3-megagpu/gke-a3-megagpu.yaml
  examples/gke-a3-ultragpu/gke-a3-ultragpu-deployment.yaml
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  examples/gke-a4/gke-a4-deployment.yaml
  examples/gke-a4/gke-a4.yaml
Labels: documentation, release-improvements

#4161 Update the link for gke a3 mega example on readme
  examples/README.md
  examples/gke-a3-megagpu/README.md
Labels: release-chore

#4164 Drop CentOS 7 from integration test for DDN/WhamCloud Lustre implementation
  tools/cloud-build/daily-tests/blueprints/lustre-vm.yaml
  tools/cloud-build/daily-tests/tests/lustre-vm.yml
Labels: release-chore

#4163 Update readme for gke managed parallelstore example
  examples/README.md
  examples/gke-managed-parallelstore.yaml
Labels: release-chore

#4149 Update cluster-tool-kit-writers-json for shubpal07
  cluster-toolkit-writers.json
Labels: release-chore

#4154 Merge v1.51.1 hotfix release into develop
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
Labels: release-chore

#4171 Updated pfs-lustre deprecation message
  examples/pfs-lustre.yaml
Labels: release-chore

#4169 Improvements to `python-integration-tests`
  tools/python-integration-tests/deployment.py
  tools/python-integration-tests/test.py
Labels: release-chore

#4173 HCLS solution: Fix mistaken variable name in README
  docs/videos/healthcare-and-life-sciences/README.md
Labels: release-chore

#4165 Drop PBS Pro modules and tests
  community/modules/compute/pbspro-execution/README.md
  community/modules/compute/pbspro-execution/main.tf
  community/modules/compute/pbspro-execution/metadata.yaml
  community/modules/compute/pbspro-execution/scripts/pbs_usecp.yml
  community/modules/compute/pbspro-execution/variables.tf
  community/modules/compute/pbspro-execution/versions.tf
  community/modules/scheduler/pbspro-client/README.md
  community/modules/scheduler/pbspro-client/main.tf
  community/modules/scheduler/pbspro-client/metadata.yaml
  community/modules/scheduler/pbspro-client/variables.tf
  community/modules/scheduler/pbspro-client/versions.tf
  community/modules/scheduler/pbspro-server/README.md
  community/modules/scheduler/pbspro-server/main.tf
  community/modules/scheduler/pbspro-server/metadata.yaml
  community/modules/scheduler/pbspro-server/outputs.tf
  community/modules/scheduler/pbspro-server/variables.tf
  community/modules/scheduler/pbspro-server/versions.tf
  community/modules/scripts/pbspro-install/README.md
  community/modules/scripts/pbspro-install/main.tf
  community/modules/scripts/pbspro-install/metadata.yaml
  community/modules/scripts/pbspro-install/outputs.tf
  community/modules/scripts/pbspro-install/scripts/pbs_install.yml
  community/modules/scripts/pbspro-install/variables.tf
  community/modules/scripts/pbspro-install/versions.tf
  community/modules/scripts/pbspro-preinstall/README.md
  community/modules/scripts/pbspro-preinstall/main.tf
  community/modules/scripts/pbspro-preinstall/metadata.yaml
  community/modules/scripts/pbspro-preinstall/outputs.tf
  community/modules/scripts/pbspro-preinstall/variables.tf
  community/modules/scripts/pbspro-preinstall/versions.tf
  community/modules/scripts/pbspro-qmgr/README.md
  community/modules/scripts/pbspro-qmgr/main.tf
  community/modules/scripts/pbspro-qmgr/metadata.yaml
  community/modules/scripts/pbspro-qmgr/outputs.tf
  community/modules/scripts/pbspro-qmgr/scripts/pbs_qmgr.yml
  community/modules/scripts/pbspro-qmgr/variables.tf
  community/modules/scripts/pbspro-qmgr/versions.tf
  docs/gpu-support.md
  modules/README.md
  pkg/modulereader/metadata_legacy.go
  tools/cloud-build/daily-tests/builds/pbspro.yaml
  tools/cloud-build/daily-tests/tests/pbspro.yml
  tools/cloud-build/daily-tests/validate_tests_metadata.py
  tools/validate_configs/test_configs/pbs-unwrapped.yaml
Labels: release-deprecations

#4174 Update documentation regarding deploying parallelstore blueprints using gcluster
  examples/README.md
Labels: release-chore

#4172 Update condition for workload policy
  modules/compute/resource-policy/main.tf
  modules/compute/resource-policy/outputs.tf
Labels: release-improvements, release-bugfix

#4175 Update kubernetes provider version to >=2.36 in gke-cluster module
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/versions.tf
Labels: dependencies, release-chore

#4166 Update readme for gke managed hyperdisk example
  community/examples/gke-tpu-v6/README.md
  examples/README.md
  examples/gke-managed-hyperdisk.yaml
Labels: release-chore

#4176 A3 Mega Slurm: fix package URL after Ansible upgrade in #4167
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
Labels: release-chore

#4179 Update hpc-gke example and readme
  examples/README.md
  examples/hpc-gke.yaml
Labels: release-chore

#4185 Update variable names in the GKE A3 Ultra example to match the cloud doc
  examples/gke-a3-ultragpu/gke-a3-ultragpu-deployment.yaml
Labels: release-chore

#4178 Add recurse to condor spool directory
  community/modules/scheduler/htcondor-access-point/files/htcondor_configure.yml
Labels: release-bugfix

#4184 Crd/ubuntu
  community/modules/remote-desktop/chrome-remote-desktop/scripts/configure-grid-drivers.yml
Labels: release-chore

#4183 Add ubuntu 24.04 ARM64 check for ansible-vm test
  tools/cloud-build/daily-tests/blueprints/ansible-vm.yaml
Labels: release-chore

#4198 Deprecate imex, gpu driver and dra driver manifests
  modules/management/kubectl-apply/manifests/gpu-operator-crd-v25.3.0.yaml
  modules/management/kubectl-apply/manifests/gpu-operator-namespace-v25.3.0.yaml
  modules/management/kubectl-apply/manifests/gpu-operator-v25.3.0.yaml
  modules/management/kubectl-apply/manifests/imex.yaml
  modules/management/kubectl-apply/manifests/nvidia-dra-driver.yaml
Labels: release-deprecations

#4118 add a4H flex test
  tools/cloud-build/daily-tests/builds/ml-a4-highgpu-slurm-flex.yaml
  tools/cloud-build/daily-tests/tests/ml-a4-highgpu-slurm-flex.yml
Labels: release-chore

#4202 Several minor fixes + missing file added to AF3 solution
  examples/science/af3-slurm/README.md
  examples/science/af3-slurm/adm/apptainer_cloudbuild.yaml
  examples/science/af3-slurm/examples/simple_service_launcher/README.md
Labels: release-improvements

#4091 Improve API consumption of `_handle_bulk_insert_op`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#4180 Updating the checkpoint PV for A3U and A4 to the recommended mount options
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  examples/gke-a4/gke-a4.yaml
Labels: release-improvements

#4205 Add authorized_cidr to deployment vars in gke integration tests
  tools/cloud-build/daily-tests/tests/gke-inactive-reservation.yml
  tools/cloud-build/daily-tests/tests/gke.yml
Labels: release-chore

#4197 Replace extended_reservation variable with reservation for TPU
  community/examples/gke-tpu-v6/README.md
  community/examples/gke-tpu-v6/gke-tpu-v6-deployment.yaml
  community/examples/gke-tpu-v6/gke-tpu-v6.yaml
Labels: release-chore

#4213 Avoid "drop user" noise in setup.log
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
Labels: release-chore

#4220 Update Toolkit release to v1.53.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4212 Make controller to self-report IP address
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/etc/slurm.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore
