Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2025-04, with the labels that each got.

#3871 Fix filestore instance location var for REGIONAL tier
  modules/file-system/filestore/main.tf
Labels: release-bugfix

#3876 Merge back to develop as part of release process
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3877 Move h4d tests to europe-west4
  tools/cloud-build/daily-tests/builds/h4d-vm.yaml
  tools/cloud-build/daily-tests/tests/h4d-vm.yml
Labels: release-chore

#3801 Extend `cred_expire=120 -> 600` to accomodate for long running prologue
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/etc/long-prolog-slurm.conf.tpl
  tools/duplicate-diff.py
Labels: release-chore

#3874 Update GKE version prefix for A3 Mega to v1.32.2
  examples/gke-a3-megagpu.yaml
Labels: release-improvements

#3880 Add comment description for variables in a4 blueprint
  examples/gke-a4/gke-a4-deployment.yaml
Labels: release-improvements

#3878 Update terraform provider version to 6.27.0
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: release-chore

#3860 Add kueue configuration support to a3 mega
  examples/gke-a3-megagpu/README.md
  examples/gke-a3-megagpu/gke-a3-megagpu-deployment.yaml
  examples/gke-a3-megagpu/gke-a3-megagpu.yaml
  examples/gke-a3-megagpu/kueue-configuration.yaml.tftpl
  tools/cloud-build/daily-tests/builds/gke-a3-megagpu.yaml
  tools/cloud-build/daily-tests/tests/gke-a3-megagpu.yml
  tools/validate_configs/validate_configs.sh
Labels: release-improvements

#3736 Allow the use of user-defined service accounts in vertex notebook instances
  community/modules/compute/notebook/README.md
  community/modules/compute/notebook/main.tf
  community/modules/compute/notebook/variables.tf
Labels: release-chore

#3883 add GCS updates to A3 Ultra
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
Labels: release-bugfix

#3882 Update file path in image builder blueprint
  examples/image-builder.yaml
Labels: release-chore

#3885 add nvidia imex support
  modules/management/kubectl-apply/manifests/imex.yaml
  modules/management/kubectl-apply/manifests/nvidia-dra-driver.yaml
Labels: release-key-new-features

#3817 TPU support with GKE nodepool module and TPU v4 2x2x2 example blueprint
  community/examples/gke-tpu-v4-2x2x2/README.md
  community/examples/gke-tpu-v4-2x2x2/gke-tpu-v4-2x2x2-deployment.yaml
  community/examples/gke-tpu-v4-2x2x2/gke-tpu-v4-2x2x2.yaml
  community/examples/gke-tpu-v4-2x2x2/tpu-available-chips.yaml
  examples/README.md
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/guest_cpus.tf
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/outputs.tf
  modules/compute/gke-node-pool/reservation_definitions.tf
  modules/compute/gke-node-pool/variables.tf
  tools/validate_configs/validate_configs.sh
Labels: release-key-new-features, release-module-improvements

#3884 [GKE] Add support to enable DNS based endpoint config
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/outputs.tf
  modules/scheduler/gke-cluster/variables.tf
Labels: release-improvements

#3894 Update dra driver module
  modules/management/kubectl-apply/manifests/nvidia-dra-driver.yaml
Labels: release-improvements

#3895 Add resource quota for gpu operator
  modules/management/kubectl-apply/manifests/gpu-operator-v24.9.2.yaml
Labels: release-bugfix

#3889 Update GKE A3 megagpu blueprints with reservation, and gcsfuse & parallelstore flags
  examples/gke-a3-megagpu/gke-a3-megagpu-deployment.yaml
  examples/gke-a3-megagpu/gke-a3-megagpu.yaml
  tools/cloud-build/daily-tests/tests/gke-a3-megagpu.yml
Labels: release-chore

#3898 Update reservation example value in GKE A3 Mega example blueprint
  examples/gke-a3-megagpu/gke-a3-megagpu-deployment.yaml
  examples/gke-a3-megagpu/gke-a3-megagpu.yaml
  tools/cloud-build/daily-tests/tests/gke-a3-megagpu.yml
Labels: release-chore

#3873 Add physicalHost to topology log
  tools/python-integration-tests/slurm_topology.py
  tools/python-integration-tests/test.py
Labels: release-chore

#3901 AlphaFold 3 High Throughput Solution (af3-slurm)
  examples/README.md
  examples/science/af3-slurm/README.md
  examples/science/af3-slurm/adm/af3-htc-architecture.png
  examples/science/af3-slurm/adm/apptainer_image.yml
  examples/science/af3-slurm/adm/controller.yml
  examples/science/af3-slurm/adm/datapipeline.yml
  examples/science/af3-slurm/adm/inference.yml
  examples/science/af3-slurm/adm/onetime_prepare_databasebucket.yml
  examples/science/af3-slurm/af3-slurm-deployment.yaml
  examples/science/af3-slurm/af3-slurm.yaml
  examples/science/af3-slurm/examples/simple_job_launcher/README.md
  examples/science/af3-slurm/examples/simple_job_launcher/af3-job-launcher.yml
  examples/science/af3-slurm/examples/simple_job_launcher/launch_af3_job.sh.j2
  examples/science/af3-slurm/examples/simple_service_launcher/README.md
  examples/science/af3-slurm/examples/simple_service_launcher/af3-service.yml
  examples/science/af3-slurm/examples/simple_service_launcher/af3-user.yml
  examples/science/af3-slurm/examples/simple_service_launcher/af3config.json.j2
  examples/science/af3-slurm/examples/simple_service_launcher/requirements.txt
  examples/science/af3-slurm/examples/simple_service_launcher/simple_service_launcher.py
  tools/validate_configs/validate_configs.sh
Labels: release-key-new-features

#3900 Update filestore timeout config based on high capacity tier
  modules/file-system/filestore/README.md
  modules/file-system/filestore/main.tf
  modules/file-system/filestore/variables.tf
Labels: release-module-improvements

#3907 Updates to examples README and removal of EOL files
  docs/slurm-gcp-support.md
  examples/README.md
  modules/README.md
  tools/cloud-build/daily-tests/tests/ml-a3-highgpu-slurm-image-legacy.yml
Labels: release-chore

#3906 Update nccl installer for a4
  examples/gke-a4/nccl-installer.yaml
Labels: release-bugfix

#3912 Fix indentation in GKE A4 yaml
  examples/gke-a4/nccl-installer.yaml
Labels: release-chore

#3919 Documentation hotfix release v1.48.1
  README.md
  community/examples/README.md
  docs/slurm-gcp-support.md
  examples/README.md
  examples/gke-a3-ultragpu/README.md
  examples/gke-a4/README.md
  examples/machine-learning/README.md
  modules/README.md
  tools/cloud-build/daily-tests/tests/ml-a3-highgpu-slurm-image-legacy.yml
Labels: release-chore

#3903 Add MIG based DWS Flex support
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/outputs.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
  community/modules/internal/slurm-gcp/instance_template/README.md
  community/modules/internal/slurm-gcp/instance_template/main.tf
  community/modules/internal/slurm-gcp/instance_template/variables.tf
  community/modules/internal/slurm-gcp/internal_instance_template/README.md
  community/modules/internal/slurm-gcp/internal_instance_template/main.tf
  community/modules/internal/slurm-gcp/internal_instance_template/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/cleanup_compute/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/cleanup_compute/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/cleanup_compute/scripts/cleanup_compute.sh
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/cleanup_compute/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/mig_flex.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/suspend.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/common.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  docs/slurm-dws-flex.md
Labels: release-improvements

#3923 Bump golang versions `(1.22, 1.23) -> (1.23, 1.24)`
  .github/workflows/pr-precommit.yml
  Makefile
  go.mod
  tools/cloud-build/provision/pr-go-build-test.tf
Labels: release-version-updates

#3916 Fix GKE A4 NCCL Jobset error and update integration test
  examples/gke-a4/nccl-jobset-example.yaml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-a4.yml
  tools/cloud-build/daily-tests/tests/gke-a4.yml
Labels: release-chore

#3929 Make is_flex_node return a bool in all cases
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3932 Update A4 High Slurm Readme
  docs/slurm-dws-flex.md
  examples/machine-learning/a4-highgpu-8g/README.md
Labels: release-chore

#3930 Merge v1.48.1 release into develop branch
  README.md
  community/examples/README.md
  docs/slurm-gcp-support.md
  examples/README.md
  examples/gke-a3-ultragpu/README.md
  examples/gke-a4/README.md
  examples/machine-learning/README.md
  modules/README.md
  tools/cloud-build/daily-tests/tests/ml-a3-highgpu-slurm-image-legacy.yml
Labels: release-chore

#3933 helm_install module implemented
  modules/management/kubectl-apply/README.md
  modules/management/kubectl-apply/helm_install/README.md
  modules/management/kubectl-apply/helm_install/main.tf
  modules/management/kubectl-apply/helm_install/metadata.yaml
  modules/management/kubectl-apply/helm_install/variables.tf
  modules/management/kubectl-apply/helm_install/versions.tf
  modules/management/kubectl-apply/main.tf
  modules/management/kubectl-apply/providers.tf
  modules/management/kubectl-apply/variables.tf
  modules/management/kubectl-apply/versions.tf
Labels: release-key-new-features

#3934 integrate support for multi-arch compliant jobset v0.8.1
  modules/management/kubectl-apply/manifests/jobset-v0.8.1.yaml
  modules/management/kubectl-apply/variables.tf
Labels: release-key-new-features

#3935 Update vm-instance to support additional persistent disks
  modules/compute/vm-instance/README.md
  modules/compute/vm-instance/main.tf
  modules/compute/vm-instance/variables.tf
Labels: release-key-new-features

#3938 add support for workload policy
  modules/compute/resource-policy/README.md
  modules/compute/resource-policy/main.tf
  modules/compute/resource-policy/variables.tf
  modules/compute/resource-policy/versions.tf
Labels: release-key-new-features

#3942 Add relavent comment for variable in gke-a3u deployment file
  examples/gke-a3-ultragpu/gke-a3-ultragpu-deployment.yaml
Labels: release-chore

#3943 Update Cluster Toolkit Readme
  README.md
Labels: release-chore

#3952 Update node pool service account role to storage.objectAdmin
  examples/gke-a4/gke-a4.yaml
Labels: release-chore

#3953 Add support for filestore instance description
  modules/file-system/filestore/README.md
  modules/file-system/filestore/main.tf
  modules/file-system/filestore/variables.tf
Labels: release-module-improvements

#3954 Fix syntax errors for resource policy
  modules/compute/resource-policy/main.tf
Labels: release-bugfix

#3925 Use non-authoritative `google_storage_bucket_iam`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
Labels: release-chore

#3909 Populate partition configs outside of `slurm_files` module
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/outputs.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
Labels: release-chore

#3959 Fix invalid reservation_name validation
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
Labels: release-chore

#3960 Fix Packer documentation for minimum necessary IAM roles
  modules/packer/custom-image/README.md
Labels: release-module-improvements

#3961 A4 Slurm: enable sudo in Slurm jobs for users with OS Admin Login role
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
Labels: release-improvements

#3963 Fix workload_policy varible definition and usage.
  modules/compute/resource-policy/README.md
  modules/compute/resource-policy/main.tf
  modules/compute/resource-policy/variables.tf
Labels: release-module-improvements

#3937 Add Managed Lustre to pre-existing-filestore module
  docs/network_storage.md
  modules/file-system/pre-existing-network-storage/README.md
  modules/file-system/pre-existing-network-storage/outputs.tf
  modules/file-system/pre-existing-network-storage/scripts/install-managed-lustre-client.sh
Labels: release-module-improvements

#3962 Revert network profile URI
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
Labels: release-bugfix

#3910 Use `depends_on` instead of taking md5 of scripts.
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
Labels: release-chore

#3940 Remove dead code (XPK config files) to avoid confusion
  community/examples/xpk-gke-a3-megagpu-files/config-map.yaml.tftpl
  community/examples/xpk-gke-a3-megagpu-files/kueue-xpk-configuration.yaml.tftpl
Labels: release-chore

#3967 Add validation for workload policy in resource policy output
  modules/compute/resource-policy/outputs.tf
Labels: release-chore

#3846 Updates the go package version.
  go.mod
  go.sum
Labels: release-chore

#3964 Allow for creating clusters without partitions
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-chore

#3970 Add release notes section for "breaking changes"
  .github/release.yml
  .github/workflows/pr-label-validation.yml
Labels: release-chore

#3958 Make login nodes deployable independently of "controller"
  community/modules/internal/slurm-gcp/login/README.md
  community/modules/internal/slurm-gcp/login/main.tf
  community/modules/internal/slurm-gcp/login/outputs.tf
  community/modules/internal/slurm-gcp/login/variables.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup_network_storage.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/outputs.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
Labels: release-breaking-changes

#3972 Add bucket outputs to controller module
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/outputs.tf
Labels: release-chore

#3973 Fix broken `login_network_storage`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup_network_storage.py
Labels: release-chore

#3950 Adding Managed Lustre to Cluster Toolkit
  docs/network_storage.md
  modules/file-system/managed-lustre/README.md
  modules/file-system/managed-lustre/main.tf
  modules/file-system/managed-lustre/metadata.yaml
  modules/file-system/managed-lustre/outputs.tf
  modules/file-system/managed-lustre/scripts/install-managed-lustre-client.sh
  modules/file-system/managed-lustre/scripts/mount.sh
  modules/file-system/managed-lustre/variables.tf
  modules/file-system/managed-lustre/versions.tf
  modules/file-system/pre-existing-network-storage/README.md
  tools/duplicate-diff.py
Labels: release-new-modules

#3975 Fix name of step in A3 Mega Slurm integration test
  tools/cloud-build/daily-tests/builds/ml-a3-megagpu-slurm.yaml
Labels: release-chore

#3977 Fix typo in TPU v4 example
  community/examples/gke-tpu-v4-2x2x2/README.md
  community/examples/gke-tpu-v4-2x2x2/gke-tpu-v4-2x2x2.yaml
Labels: release-chore

#3979 Add info on TPU variables
  community/examples/gke-tpu-v4-2x2x2/README.md
Labels: release-chore

#3966 Add sudo via OS Login to all A3 Slurm solutions
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-2-cluster.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-cluster.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
Labels: release-improvements

#3965 Update examples/README.md with AI Hypercomputer link
  examples/README.md
Labels: release-chore

#3982 Remove old signup form for dws flex
  docs/slurm-dws-flex.md
Labels: release-chore

#3983 Update Toolkit release to v1.49.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3980 Add a simple XPK blueprint example
  community/examples/xpk-n2-filestore/config-map.yaml.tftpl
  community/examples/xpk-n2-filestore/kueue-xpk-configuration.yaml.tftpl
  community/examples/xpk-n2-filestore/storage-crd.yaml
  community/examples/xpk-n2-filestore/xpk-n2-filestore.yaml
  examples/README.md
  tools/validate_configs/validate_configs.sh
Labels: release-improvements

#3986 Update gpu-operator and nvidia-dra-driver
  modules/management/kubectl-apply/main.tf
  modules/management/kubectl-apply/manifests/gpu-operator-v25.3.0.yaml
  modules/management/kubectl-apply/manifests/nvidia-dra-driver.yaml
Labels: release-chore

#3976 Enable specification of system node pool zones in the GKE Cluster module
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/variables.tf
Labels: release-module-improvements

#3988 Update base image used in A3 High Slurm test
  tools/cloud-build/daily-tests/tests/ml-a3-highgpu-slurm-image.yml
Labels: release-chore

#3990 Add support for optional GCS bucket module config
  community/modules/file-system/cloud-storage-bucket/README.md
  community/modules/file-system/cloud-storage-bucket/main.tf
  community/modules/file-system/cloud-storage-bucket/variables.tf
Labels: release-module-improvements

#3989 Update A4 reservation name
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
  tools/cloud-build/daily-tests/tests/gke-a4.yml
  tools/cloud-build/daily-tests/tests/ml-a4-highgpu-slurm.yml
Labels: release-chore

#3955 Move from auth/munge to auth/slurm
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/etc/htc-slurm.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/etc/htc-slurmdbd.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/etc/long-prolog-slurm.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/etc/slurm.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/etc/slurmdbd.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup_network_storage.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-key-new-features

#3887 Remove the broken auto_delete_disk system, and replace it with a working snapshot-based alternative, in the NFS Server module
  community/modules/file-system/nfs-server/README.md
  community/modules/file-system/nfs-server/main.tf
  community/modules/file-system/nfs-server/variables.tf
  community/modules/file-system/nfs-server/versions.tf
  tools/cloud-build/daily-tests/blueprints/monitoring.yaml
  tools/validate_configs/test_configs/centos8-ss.yaml
  tools/validate_configs/test_configs/debian-ss.yaml
  tools/validate_configs/test_configs/hpc-centos-ss.yaml
  tools/validate_configs/test_configs/nfs-servers.yaml
  tools/validate_configs/test_configs/node-groups.yaml
  tools/validate_configs/test_configs/rocky-ss.yaml
  tools/validate_configs/test_configs/slurm-gcp-v6-startup-scripts.yaml
  tools/validate_configs/test_configs/ubuntu-ss.yaml
Labels: release-module-improvements

#3993 Update golang.org/x/net
  go.mod
  go.sum
Labels: release-chore

#3941 Update README.md
  community/modules/file-system/DDN-EXAScaler/README.md
Labels: release-chore

#3998 Merge main into Develop
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/DDN-EXAScaler/README.md
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
  tools/cloud-build/daily-tests/tests/gke-a4.yml
  tools/cloud-build/daily-tests/tests/ml-a4-highgpu-slurm.yml
Labels: release-chore

#4002 Add unique name for resource policy
  modules/compute/resource-policy/README.md
  modules/compute/resource-policy/main.tf
  modules/compute/resource-policy/versions.tf
Labels: release-improvements

#4001 Increase Debian 12 version for CRD module to avoid pruned header package
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/variables.tf
Labels: release-chore

#3692 Update a3-highgpu image blueprint to remove slurm_version
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
Labels: release-chore

#4000 Add guidance on setting ResumeRate for Slurm
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
Labels: release-chore

#3951 Address shelve permissions
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-bugfix

#4003 Fix cloud rdma driver script for rocky 8
  modules/scripts/startup-script/files/install_cloud_rdma_drivers.sh
Labels: release-chore

#3956 fix filestore limit
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-vm.yaml
  tools/cloud-build/check_running_build.sh
  tools/cloud-build/daily-tests/builds/gke-storage.yaml
  tools/cloud-build/daily-tests/builds/h4d-vm.yaml
  tools/cloud-build/daily-tests/builds/hcls.yaml
  tools/cloud-build/daily-tests/builds/hpc-enterprise-slurm.yaml
  tools/cloud-build/daily-tests/builds/htc-slurm.yaml
  tools/cloud-build/daily-tests/builds/ml-a3-ultragpu-jbvms.yaml
  tools/cloud-build/daily-tests/builds/ml-a3-ultragpu-slurm.yaml
  tools/cloud-build/daily-tests/builds/ml-a4-highgpu-slurm.yaml
  tools/cloud-build/daily-tests/builds/ml-slurm.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-debian.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-rocky8.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-ssd.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-ubuntu.yaml
  tools/cloud-build/daily-tests/builds/spack-gromacs.yaml
  tools/cloud-build/daily-tests/tests/gke-storage.yml
  tools/cloud-build/daily-tests/tests/hpc-enterprise-slurm.yml
  tools/cloud-build/daily-tests/tests/htc-slurm.yml
  tools/cloud-build/daily-tests/tests/ml-a3-ultragpu-jbvms.yml
  tools/cloud-build/daily-tests/tests/ml-a3-ultragpu-slurm.yml
  tools/cloud-build/daily-tests/tests/ml-slurm.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-debian.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-rocky8.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-ssd.yml
  tools/cloud-build/daily-tests/tests/slurm-v6-ubuntu.yml
  tools/cloud-build/daily-tests/tests/spack-gromacs.yml
Labels: release-chore

#3995 add non-queue flex-start support in gke
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/variables.tf
  modules/compute/gke-node-pool/versions.tf
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: release-module-improvements

#3987 Remove firewall for Mellanox VPCs
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/a3u-slurm-ubuntu-gcs.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-vm.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-vm.yaml
  modules/network/gpu-rdma-vpc/README.md
  modules/network/gpu-rdma-vpc/main.tf
  modules/network/gpu-rdma-vpc/variables.tf
  modules/network/multivpc/README.md
  modules/network/multivpc/variables.tf
  modules/network/vpc/README.md
  modules/network/vpc/main.tf
  modules/network/vpc/variables.tf
Labels: release-chore

#4014 h4d filestore naming
  examples/h4d-vm.yaml
  tools/cloud-build/daily-tests/tests/h4d-vm.yml
Labels: release-chore

#4017 update kueue configurations and reservations in a3 mega, ultra and A4
  examples/gke-a3-megagpu/gke-a3-megagpu.yaml
  examples/gke-a3-megagpu/kueue-configuration.yaml.tftpl
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  examples/gke-a3-ultragpu/kueue-configuration.yaml.tftpl
  examples/gke-a4/gke-a4.yaml
  examples/gke-a4/kueue-configuration.yaml.tftpl
  tools/cloud-build/daily-tests/blueprints/kueue-config-files/tas-queues.yaml
Labels: release-improvements

#4008 a4h filestore replace network_name with test_name
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
  tools/cloud-build/daily-tests/tests/ml-a4-highgpu-slurm.yml
Labels: release-chore

#4012 Previous network name has collision with hidden resource
  tools/cloud-build/daily-tests/tests/hpc-enterprise-slurm.yml
Labels: release-chore

#4024 Remove k8s service account var from gke-a3U blueprint
  examples/gke-a3-ultragpu/gke-a3-ultragpu-deployment.yaml
  tools/cloud-build/daily-tests/tests/gke-a3-ultragpu.yml
Labels: release-improvements

#4026 deprecate kueue v0.11.1 and use v0.11.4
  modules/management/kubectl-apply/README.md
  modules/management/kubectl-apply/manifests/kueue-v0.11.1.yaml
  modules/management/kubectl-apply/variables.tf
Labels: release-key-new-features, release-module-improvements, release-improvements

#4006 disable unattended upgrades in a3u and a4h slurm solutions
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
Labels: release-improvements

#4016 set static network name to solve the parallelstore reach limit failure
  examples/gke-managed-parallelstore.yaml
  examples/pfs-parallelstore.yaml
  examples/ps-slurm.yaml
  tools/cloud-build/daily-tests/tests/gke-managed-parallelstore.yml
  tools/cloud-build/daily-tests/tests/ps-slurm.yml
  tools/cloud-build/daily-tests/tests/ps-vm-debian.yml
Labels: release-chore

#4028 move h4d tests to us-central1
  tools/cloud-build/daily-tests/builds/h4d-vm.yaml
  tools/cloud-build/daily-tests/tests/h4d-vm.yml
Labels: release-chore

#4029 Missed setting that breaks integration test
  examples/pfs-managed-lustre-vm.yaml
Labels: release-bugfix

#3974 Update A3U and A4H Slurm examples with Lustre modules
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
Labels: release-chore
