Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2025-03, with the labels that each got.

#3688 OFE: update Python to version 3.12
  community/front-end/ofe/infrastructure_files/gcs_bucket/webserver/startup.sh
  community/front-end/ofe/website/ghpcfe/templates/blueprint/partition_config.yaml.j2
Labels: release-chore

#3697 NCCL integration tests
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-a3-high.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-a3-mega.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-a3-ultra.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-job.yml
  tools/cloud-build/daily-tests/builds/gke-a2-highgpu-kueue.yaml
  tools/cloud-build/daily-tests/builds/gke-a3-highgpu.yaml
  tools/cloud-build/daily-tests/builds/gke-a3-megagpu.yaml
  tools/cloud-build/daily-tests/builds/gke-a3-ultragpu.yaml
  tools/cloud-build/daily-tests/builds/gke-managed-hyperdisk.yaml
  tools/cloud-build/daily-tests/builds/gke-managed-parallelstore.yaml
  tools/cloud-build/daily-tests/builds/gke-storage.yaml
  tools/cloud-build/daily-tests/builds/gke.yaml
  tools/cloud-build/daily-tests/builds/ml-gke-e2e.yaml
  tools/cloud-build/daily-tests/builds/ml-gke.yaml
  tools/cloud-build/daily-tests/tests/gke-a3-highgpu.yml
  tools/cloud-build/daily-tests/tests/gke-a3-megagpu.yml
  tools/cloud-build/daily-tests/tests/gke-a3-ultragpu.yml
Labels: release-improvements

#3737 Move from `auth/munge` to `auth/slurm`
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/etc/htc-slurm.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/etc/htc-slurmdbd.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/etc/long-prolog-slurm.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/etc/slurm.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/etc/slurmdbd.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup_network_storage.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
Labels: release-key-new-features

#3739 remove chengcongdu as codeowner
  CODEOWNERS
Labels: release-chore

#3751 Add a4-high-vm blueprint
  examples/machine-learning/a4-highgpu-8g/README.md
  examples/machine-learning/a4-highgpu-8g/a4high-vm-deployment.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-vm.yaml
Labels: release-key-new-features

#3752 Cloud DNS config addition to GKE Cluster module
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/variables.tf
Labels: release-key-new-features

#3758 SlurmGCP. Fix `var/local` typo
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
Labels: release-chore

#3760 Update repo to include ib_cm.ko file and startup script reload
  examples/h4d/README.md
  examples/h4d/h4d-vm.yaml
  examples/h4d/hpc-slurm-h4d.yaml
  modules/scripts/startup-script/files/install_cloud_rdma_drivers.sh
  tools/cloud-build/daily-tests/builds/h4d-vm.yaml
  tools/cloud-build/daily-tests/tests/h4d-vm.yml
Labels: release-chore

#3763 fix GCS name prefix typo
  examples/hypercompute_clusters/a3u-gke-gcs/a3u-gke-gcs.yaml
Labels: release-chore

#3766 Rename obsolete mentions of "resource" to "module"
  tools/validate_configs/test_configs/node-groups.yaml
Labels: release-chore

#3726 Add NeMo and HPL Slurm GCS System Benchmarks with Ramble
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/README.md
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/a3u-slurm-ubuntu-gcs.yaml
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/deployment.yaml
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/system_benchmarks/README.md
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/system_benchmarks/run-hpl-via-ramble.sh
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/system_benchmarks/run-nccl-tests-via-ramble.sh
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/system_benchmarks/run-nemo-via-ramble.sh
Labels: release-improvements

#3757 Fix a4-high readme typo for vm creation
  examples/machine-learning/a4-highgpu-8g/README.md
Labels: release-chore

#3756 Change region for h4d integration test from europe-west to us-central
  tools/cloud-build/daily-tests/builds/h4d-vm.yaml
  tools/cloud-build/daily-tests/tests/h4d-vm.yml
Labels: release-chore

#3765 Fix issue 3748 (Error with stateful_ips iteration in MIG)
  community/modules/scheduler/htcondor-access-point/main.tf
Labels: release-bugfix

#3771 Add Integration test for A4 slurm blueprint
  tools/cloud-build/daily-tests/builds/ml-a4-highgpu-slurm.yaml
  tools/cloud-build/daily-tests/tests/ml-a4-highgpu-slurm.yml
Labels: release-chore

#3770 Reduce number of startup scripts.
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-deprecations

#3749 GCS update to GKE A4 High blueprint
  examples/gke-a4-highgpu/README.md
  examples/gke-a4-highgpu/gke-a4-highgpu-deployment.yaml
  examples/gke-a4-highgpu/gke-a4-highgpu.yaml
  examples/hypercompute_clusters/a3u-gke-gcs/a3u-gke-gcs.yaml
  tools/cloud-build/daily-tests/builds/gke-a4-highgpu.yaml
Labels: release-improvements

#3778 Bump py req version in `/community/front-end/ofe`
  community/front-end/ofe/requirements.txt
Labels: dependencies, python, release-chore

#3786 Update Kueue documentation
  modules/management/kubectl-apply/README.md
Labels: release-improvements

#3785 Fix GCS local mount and readme typo
  examples/gke-a4-highgpu/README.md
  examples/gke-a4-highgpu/gke-a4-highgpu.yaml
Labels: release-chore

#3793 Update urls to point to toolkit main
  modules/management/kubectl-apply/README.md
Labels: release-bugfix

#3775 Don't take md5 of storage objects to avoid provider bug
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
Labels: release-chore

#3794 add support for enablePrivateNode at nodepool level
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/variables.tf
Labels: release-module-improvements

#3795 Convert a4 integration to use future reservation instead of just reservation
  tools/cloud-build/daily-tests/builds/ml-a4-highgpu-slurm.yaml
  tools/cloud-build/daily-tests/tests/ml-a4-highgpu-slurm.yml
Labels: release-chore

#3798 Update Toolkit release to v1.48.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3800 Update htc slurm blueprint and template config
  community/examples/htc-slurm.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/etc/htc-slurm.conf.tpl
Labels: release-chore

#3740 Update Slurm image reference to new family (6-9)
  community/examples/AMD/hpc-amd-slurm.yaml
  community/examples/hpc-slurm-ubuntu2004.yaml
  community/examples/hpc-slurm6-apptainer.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/source_image_logic.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/internal/slurm-gcp/instance_template/main.tf
  community/modules/internal/slurm-gcp/nodeset_tpu/README.md
  community/modules/internal/slurm-gcp/nodeset_tpu/main.tf
  community/modules/internal/slurm-gcp/nodeset_tpu/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/get_tpu_vmcount.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/load_bq.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup_network_storage.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/sort_nodes.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/suspend.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/source_image_logic.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
  examples/cae/cae-slurm.yaml
  examples/hpc-enterprise-slurm.yaml
  examples/hpc-slurm-static.yaml
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/a3u-slurm-ubuntu-gcs.yaml
  examples/image-builder.yaml
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
  examples/ml-slurm.yaml
  tools/cloud-build/daily-tests/blueprints/lustre-slurm.yaml
  tools/cloud-build/daily-tests/tests/slurm-v6-debian.yml
  tools/validate_configs/golden_copies/configs/versioned_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/terraform.tfvars
  tools/validate_configs/test_configs/node-groups.yaml
Labels: release-version-updates

#3804 Update slurm-gcp version references to 6.9.1
  community/examples/hpc-build-slurm-image.yaml
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/a3u-slurm-ubuntu-gcs.yaml
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
  modules/README.md
Labels: release-chore

#3805 Revert "Move from `auth/munge` to `auth/slurm`"
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/etc/htc-slurm.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/etc/htc-slurmdbd.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/etc/long-prolog-slurm.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/etc/slurm.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/etc/slurmdbd.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup_network_storage.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  tools/cloud-build/daily-tests/ansible_playbooks/slurm-integration-test.yml
Labels: release-chore

#3806 Add B200 to accepted gpu test script
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tools/gpu-test
Labels: release-chore

#3783 Add comment descriptions for a3U vars
  examples/gke-a3-ultragpu/gke-a3-ultragpu-deployment.yaml
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  examples/gke-a4-highgpu/gke-a4-highgpu-deployment.yaml
  examples/gke-a4-highgpu/gke-a4-highgpu.yaml
Labels: release-improvements

#3781 Adding Automatic Prolog/Epilog Slurm GPU Health Checks
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tools/gpu-test
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  docs/CHS-Slurm.md
Labels: release-key-new-features

#3814 Created GPU Operator Manifest
  community/examples/gpu-operator-configuration-files/gpu-operator-template.yaml.tftpl
Labels: release-key-new-features

#3816 Improve job template naming
  examples/ml-gke.yaml
  modules/compute/gke-job-template/metadata.yaml
Labels: release-improvements

#3820 Update GPU Operator manifest definition
  community/examples/gpu-operator-configuration-files/gpu-operator-template.yaml.tftpl
Labels: release-improvements

#3821 Rollback name injection change in job template
  modules/compute/gke-job-template/metadata.yaml
Labels: release-bugfix

#3822 Update Toolkit release to v1.48.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3810 Add log to topology test
  tools/python-integration-tests/slurm_topology.py
Labels: release-chore

#3826 Support multiple nodepools creation in gke nodepool module
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  examples/gke-a4-highgpu/gke-a4-highgpu.yaml
  examples/hypercompute_clusters/a3u-gke-gcs/a3u-gke-gcs.yaml
  modules/compute/gke-job-template/README.md
  modules/compute/gke-job-template/main.tf
  modules/compute/gke-job-template/variables.tf
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/outputs.tf
  modules/compute/gke-node-pool/variables.tf
Labels: release-module-improvements

#3832 Bump NCCL/gIB version to 1.0.5
  examples/gke-a3-ultragpu/nccl-installer.yaml
  examples/gke-a3-ultragpu/nccl-jobset-example.yaml
  examples/gke-a4-highgpu/nccl-installer.yaml
  examples/gke-a4-highgpu/nccl-jobset-example.yaml
  examples/hypercompute_clusters/a3u-gke-gcs/nccl-rdma-installer.yaml
  examples/hypercompute_clusters/a3u-gke-gcs/system_benchmarks/ramble-nccl.yaml
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/a3u-slurm-ubuntu-gcs.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a3-ultragpu-8g/nemo-framework/Dockerfile
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-vm.yaml
  examples/machine-learning/a4-highgpu-8g/system_benchmarks/run-nccl-tests-via-ramble.sh
Labels: release-version-updates

#3833 add kueue v0.11.1 manifest
  modules/management/kubectl-apply/manifests/kueue-v0.11.1.yaml
Labels: release-key-new-features

#3829 Support resource manager tags on instance template and attached disks
  community/examples/hpc-slurm-local-ssd.yaml
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-partition/variables.tf
  community/modules/internal/slurm-gcp/instance_template/README.md
  community/modules/internal/slurm-gcp/instance_template/main.tf
  community/modules/internal/slurm-gcp/instance_template/variables.tf
  community/modules/internal/slurm-gcp/internal_instance_template/README.md
  community/modules/internal/slurm-gcp/internal_instance_template/main.tf
  community/modules/internal/slurm-gcp/internal_instance_template/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/partition.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/variables.tf
Labels: release-key-new-features

#3828 Workaround python changes to support older images
  community/modules/internal/slurm-gcp/instance_template/files/startup_sh_unlinted
Labels: release-chore

#3835 Unify gke a3 ultra blueprints
  examples/gke-a3-ultragpu/gke-a3-ultragpu-deployment.yaml
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  examples/gke-a3-ultragpu/system_benchmarks/README.md
  examples/gke-a3-ultragpu/system_benchmarks/ramble-hpl.yaml
  examples/gke-a3-ultragpu/system_benchmarks/ramble-nccl.yaml
  examples/gke-a3-ultragpu/system_benchmarks/ramble-nemo.yaml
  examples/hypercompute_clusters/a3u-gke-gcs/README.md
  examples/hypercompute_clusters/a3u-gke-gcs/a3u-gke-gcs.yaml
  examples/hypercompute_clusters/a3u-gke-gcs/deployment.yaml
  examples/hypercompute_clusters/a3u-gke-gcs/kueue-configuration.yaml.tftpl
  examples/hypercompute_clusters/a3u-gke-gcs/nccl-rdma-installer.yaml
  tools/cloud-build/daily-tests/builds/gke-a3-ultragpu.yaml
Labels: release-improvements, release-deprecations

#3671 Advanced network configuration support on notebook instance community module
  community/modules/compute/notebook/README.md
  community/modules/compute/notebook/main.tf
  community/modules/compute/notebook/variables.tf
  community/modules/compute/notebook/versions.tf
Labels: release-improvements

#3837 Add omnia deprecation warning
  community/modules/scripts/omnia-install/README.md
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
Labels: release-deprecations

#3840 introduce feature to enable k8s beta apis
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/variables.tf
Labels: release-key-new-features, release-module-improvements

#3843 updating defaults for slurm chs prolog
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  docs/CHS-Slurm.md
Labels: release-improvements

#3839 Revert "Dont take md5 of storage objects to avoid provider bug"
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
Labels: release-chore

#3813 Add Rocky 9 compatibility for NFS
  community/modules/file-system/nfs-server/scripts/install-nfs-client.sh
  modules/file-system/filestore/scripts/install-nfs-client.sh
  modules/file-system/pre-existing-network-storage/scripts/install-nfs-client.sh
Labels: release-bugfix

#3807 Enable higher performance self-managed NFS server configurations
  community/modules/file-system/nfs-server/README.md
  community/modules/file-system/nfs-server/main.tf
  community/modules/file-system/nfs-server/variables.tf
Labels: release-module-improvements

#3847 Update Toolkit release to v1.48.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3845 fix gke a3-ultra blueprint
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
Labels: release-bugfix

#3830 Add support for Kueue 0.11.1
  examples/gke-a3-ultragpu/kueue-configuration.yaml.tftpl
  examples/gke-a4-highgpu/kueue-configuration.yaml.tftpl
  modules/management/kubectl-apply/README.md
  modules/management/kubectl-apply/variables.tf
Labels: release-key-new-features

#3812 Add disk size vars in deployment file for a3U
  examples/gke-a3-ultragpu/gke-a3-ultragpu-deployment.yaml
Labels: release-improvements

#3852 Update naming of a4 gke files and variables
  examples/gke-a4/README.md
  examples/gke-a4/gke-a4-deployment.yaml
  examples/gke-a4/gke-a4.yaml
  examples/gke-a4/kueue-configuration.yaml.tftpl
  examples/gke-a4/mglru-disable.yaml
  examples/gke-a4/nccl-installer.yaml
  examples/gke-a4/nccl-jobset-example.yaml
  modules/compute/gke-node-pool/disk_definitions.tf
  tools/cloud-build/daily-tests/builds/gke-a4.yaml
  tools/cloud-build/daily-tests/tests/gke-a4.yml
  tools/validate_configs/validate_configs.sh
Labels: release-chore

#3853 Update A3U slurm threads configuration
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/a3u-slurm-ubuntu-gcs.yaml
Labels: release-improvements

#3851 Partial revert #3770
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/main.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-chore

#3855 add support for resource quota in gpu-operator namespace
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/variables.tf
Labels: release-module-improvements

#3854 Force retry use of gce service account
  community/modules/internal/slurm-gcp/instance_template/files/startup_sh_unlinted
Labels: release-bugfix

#3857 Update Toolkit release to v1.48.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3863 Alert filestore cleanup failure
  tools/cloud-build/provision/daily-cleanup.tf
Labels: release-chore
