Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2025-06, with the labels that each got.

#4233 Implement A3 High network blocking script as startup-script feature
  modules/scripts/startup-script/README.md
  modules/scripts/startup-script/files/install_gpu_network_wait_online.yml
  modules/scripts/startup-script/main.tf
  modules/scripts/startup-script/variables.tf
Labels: release-module-improvements

#4215 speed up deployment of GKE clusters
  modules/scheduler/gke-cluster/main.tf
Labels: release-improvements

#4229 Remove Docker configuration warning
  modules/scripts/startup-script/files/install_docker.yml
  modules/scripts/startup-script/main.tf
Labels: release-improvements

#4240 Move Slurm H4D Blueprint and remove firewall rules for IRDMA VPCs
  examples/README.md
  examples/h4d-vm.yaml
  examples/hpc-slurm-h4d.yaml
Labels: release-chore

#4237 Kueue config application verification Integration tests
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-kueue.yml
  tools/cloud-build/daily-tests/tests/gke-a3-megagpu.yml
  tools/cloud-build/daily-tests/tests/gke-a3-ultragpu.yml
  tools/cloud-build/daily-tests/tests/gke-a4.yml
Labels: release-chore, release-improvements

#4243 Merge V1.53.0 into Develop
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4244 update terraform-provider version to v6.38.0
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: release-chore

#4245 add integration tests for GKE A3U DWS flex-start and queued-provisioning
  examples/gke-consumption-options/dws-flex-start-queued-provisioning/gke-a3-ultragpu.yaml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-a3u-dws-flex-start-queued-provisioning.yml
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-gke-a3u-dws-flex-start.yml
  tools/cloud-build/daily-tests/builds/gke-a3u-dws-flex-start-queued-provisioning.yaml
  tools/cloud-build/daily-tests/builds/gke-a3u-dws-flex-start.yaml
  tools/cloud-build/daily-tests/tests/gke-a3u-dws-flex-start-queued-provisioning.yml
  tools/cloud-build/daily-tests/tests/gke-a3u-dws-flex-start.yml
Labels: release-chore

#4246 Revert changes to fix test GKE kueue integration test
  tools/cloud-build/daily-tests/tests/gke-a3-megagpu.yml
  tools/cloud-build/daily-tests/tests/gke-a3-ultragpu.yml
  tools/cloud-build/daily-tests/tests/gke-a4.yml
Labels: release-chore

#4249 Adjust OFI tunables and disable rndv write mode
  modules/scripts/startup-script/main.tf
Labels: release-chore

#4250 Update Toolkit release to v1.54.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4236 Allow to run slum tests on already deployed cluster
  tools/cloud-build/daily-tests/builds/slurm-flex.yaml
  tools/cloud-build/daily-tests/builds/slurm-gcp-v6-simple-job-completion.yaml
  tools/python-integration-tests/deployment.py
  tools/python-integration-tests/external_deployment.py
  tools/python-integration-tests/slurm_reconfig_size.py
  tools/python-integration-tests/slurm_simple_job_completion.py
  tools/python-integration-tests/slurm_topology.py
  tools/python-integration-tests/ssh.py
  tools/python-integration-tests/test.py
Labels: release-chore

#4231 AlphaFold 3 High Throughput Solution (af3-slurm)
  examples/README.md
  examples/science/af3-slurm/README.md
  examples/science/af3-slurm/adm/af3-htc-architecture.png
  examples/science/af3-slurm/adm/apptainer_cloudbuild.yaml
  examples/science/af3-slurm/adm/apptainer_image.yml
  examples/science/af3-slurm/adm/controller.yml
  examples/science/af3-slurm/adm/datapipeline.yml
  examples/science/af3-slurm/adm/inference.yml
  examples/science/af3-slurm/adm/onetime_prepare_databasebucket.yml
  examples/science/af3-slurm/af3-slurm-deployment.yaml
  examples/science/af3-slurm/af3-slurm.yaml
  examples/science/af3-slurm/examples/simple_job_launcher/README.md
  examples/science/af3-slurm/examples/simple_job_launcher/af3-job-launcher.yml
  examples/science/af3-slurm/examples/simple_job_launcher/launch_af3_job.sh.j2
  examples/science/af3-slurm/examples/simple_service_launcher/README.md
  examples/science/af3-slurm/examples/simple_service_launcher/af3-service.yml
  examples/science/af3-slurm/examples/simple_service_launcher/af3-user.yml
  examples/science/af3-slurm/examples/simple_service_launcher/af3config.json.j2
  examples/science/af3-slurm/examples/simple_service_launcher/requirements.txt
  examples/science/af3-slurm/examples/simple_service_launcher/simple_service_launcher.py
  tools/validate_configs/validate_configs.sh
Labels: release-key-new-features

#4255 Removing MGLRU dependency from Google cloud cluster toolkit
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  examples/gke-a3-ultragpu/mglru-disable.yaml
  examples/gke-a4/gke-a4.yaml
  examples/gke-a4/mglru-disable.yaml
  examples/gke-a4x/gke-a4x.yaml
  examples/gke-a4x/mglru-disable.yaml
  examples/gke-consumption-options/dws-flex-start-queued-provisioning/gke-a3-ultragpu.yaml
  examples/gke-consumption-options/dws-flex-start-queued-provisioning/mglru-disable.yaml
  examples/gke-consumption-options/dws-flex-start/gke-a3-ultragpu.yaml
  examples/gke-consumption-options/dws-flex-start/mglru-disable.yaml
Labels: release-improvements

#4256 Allow to supply custom startup script
  community/modules/internal/slurm-gcp/instance_template/README.md
  community/modules/internal/slurm-gcp/instance_template/main.tf
  community/modules/internal/slurm-gcp/instance_template/variables.tf
  community/modules/internal/slurm-gcp/login/README.md
  community/modules/internal/slurm-gcp/login/main.tf
  community/modules/internal/slurm-gcp/login/variables.tf
Labels: release-chore

#4253 Modify reservation variable to accommodate different reservation options
  examples/gke-a3-megagpu/gke-a3-megagpu-deployment.yaml
  examples/gke-a3-megagpu/gke-a3-megagpu.yaml
  examples/gke-a3-ultragpu/gke-a3-ultragpu-deployment.yaml
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  examples/gke-a4/gke-a4-deployment.yaml
  examples/gke-a4/gke-a4.yaml
  examples/gke-a4x/gke-a4x-deployment.yaml
  examples/gke-a4x/gke-a4x.yaml
  tools/cloud-build/daily-tests/tests/gke-a3-megagpu.yml
  tools/cloud-build/daily-tests/tests/gke-a3-ultragpu.yml
  tools/cloud-build/daily-tests/tests/gke-a4.yml
Labels: release-improvements

#4258 Fix templates to point to right AccountingStorageHost
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/etc/htc-slurm.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/etc/long-prolog-slurm.conf.tpl
Labels: release-chore

#4263 Align GCSFuse configurations with best practices
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/a3u-slurm-ubuntu-gcs.yaml
Labels: release-improvements

#4264 Add functionality to export slurm config bucket as controller NFS
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup_network_storage.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#4259 Information on DWS Calendar consumption option in GKE blueprint
  examples/gke-consumption-options/dws-calendar.md
Labels: release-improvements

#4267 Make `clean-resource-policies.sh` resilient to inevitable failures
  tools/clean-resource-policies.sh
Labels: release-chore

#4270 Remove validation around gpu instances for DWS Flex
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/outputs.tf
Labels: release-chore

#4268 update terraform-provider version to v6.39.0
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: release-chore

#4273 Update variable name as the nodepool is not of static type
  examples/gke-consumption-options/dws-flex-start-queued-provisioning/gke-a3-ultragpu.yaml
Labels: release-chore

#4274 remove the deprecated ubuntu-2004-lts image
  tools/cloud-build/daily-tests/blueprints/ansible-vm.yaml
Labels: release-chore

#4271 Allow for use of DNS + hostname for controller
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#4265 Allow setup using config/startup scripts from mounted NFS
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#4281 update debian image and kernel header in a3m and CRD
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/variables.tf
  examples/machine-learning/a3-megagpu-8g/debian/slurm-a3mega-image.yaml
Labels: release-chore

#4284 Merge V1.55.0 into Develop
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/remote-desktop/chrome-remote-desktop/README.md
  community/modules/remote-desktop/chrome-remote-desktop/variables.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  examples/machine-learning/a3-megagpu-8g/debian/slurm-a3mega-image.yaml
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4276 SlurmGCP Resume Improvements
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/etc/slurm.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume_wrapper.sh
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_conf.py
Labels: release-improvements

#4291 Merge Hotfix To Develop
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#4299 Add recipe to build specialized images
  examples/machine-learning/build-service-images/README.md
  examples/machine-learning/build-service-images/a3m/blueprint.yaml
  examples/machine-learning/build-service-images/build.sh
  examples/machine-learning/build-service-images/common/blueprint.yaml
  examples/machine-learning/build-service-images/shared.yaml
  tools/validate_configs/validate_configs.sh
Labels: release-chore

#4300 Update Toolkit release to v1.56.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4301 Release candidate: v1.56.0
  cmd/root.go
  community/front-end/ofe/requirements.txt
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/etc/slurm.conf.tpl
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/load_bq.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume_wrapper.sh
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  examples/machine-learning/build-service-images/README.md
  examples/machine-learning/build-service-images/a3m/blueprint.yaml
  examples/machine-learning/build-service-images/build.sh
  examples/machine-learning/build-service-images/common/blueprint.yaml
  examples/machine-learning/build-service-images/shared.yaml
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
  tools/validate_configs/validate_configs.sh
Labels: release-chore

#4309 Merge V1.56.0 into Develop
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  examples/machine-learning/build-service-images/a3m/blueprint.yaml
  examples/machine-learning/build-service-images/common/blueprint.yaml
  examples/machine-learning/build-service-images/shared.yaml
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4305 enable wait_for_rollout for kubectl dependencies
  modules/management/kubectl-apply/main.tf
Labels: release-improvements

#4314 update terraform-provider version to v6.41.0
  modules/file-system/managed-lustre/README.md
  modules/file-system/managed-lustre/main.tf
  modules/file-system/managed-lustre/variables.tf
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: release-chore

#4315 Bump timeout on google cloud ops agent to 90 seconds
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
Labels: release-chore

#4275 Revamp install_cloud_rdma_drivers startup script
  examples/h4d-vm.yaml
  examples/hpc-slurm-h4d.yaml
  modules/scripts/startup-script/README.md
  modules/scripts/startup-script/files/install_cloud_rdma_drivers.sh
  modules/scripts/startup-script/variables.tf
Labels: release-deprecations, release-bugfix

#4319 Fix TAS Flag in v0.11.4
  modules/management/kubectl-apply/manifests/kueue-v0.11.4.yaml
Labels: release-bugfix

#4293 created chs-cronjob manifest
  examples/gke-a3-megagpu/chs-cronjob.yaml.tftpl
  examples/gke-a3-megagpu/chs-permissions.yaml.tftpl
  examples/gke-a3-megagpu/chs-pvc.yaml.tftpl
  examples/gke-a3-megagpu/gke-a3-megagpu-deployment.yaml
  examples/gke-a3-megagpu/gke-a3-megagpu.yaml
  modules/management/kubectl-apply/README.md
  modules/management/kubectl-apply/main.tf
  modules/management/kubectl-apply/manifests/kueue-v0.11.4.yaml
  modules/management/kubectl-apply/variables.tf
Labels: release-key-new-features

#4321 CHS Integration for A3 Ultra
  examples/gke-a3-megagpu/gke-a3-megagpu-deployment.yaml
  examples/gke-a3-ultragpu/chs-cronjob.yaml.tftpl
  examples/gke-a3-ultragpu/chs-permissions.yaml.tftpl
  examples/gke-a3-ultragpu/chs-pvc.yaml.tftpl
  examples/gke-a3-ultragpu/gke-a3-ultragpu-deployment.yaml
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
Labels: release-key-new-features

#4323 CHS Integration for A4
  examples/gke-a4/chs-cronjob.yaml.tftpl
  examples/gke-a4/chs-permissions.yaml.tftpl
  examples/gke-a4/chs-pvc.yaml.tftpl
  examples/gke-a4/gke-a4-deployment.yaml
  examples/gke-a4/gke-a4.yaml
Labels: release-key-new-features

#4328 CHS for A3 Ultra
  examples/gke-a3-ultragpu/chs-cronjob.yaml.tftpl
  examples/gke-a3-ultragpu/chs-permissions.yaml.tftpl
  examples/gke-a3-ultragpu/chs-pvc.yaml.tftpl
  examples/gke-a3-ultragpu/gke-a3-ultragpu-deployment.yaml
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  examples/gke-a3-ultragpu/read-chs-logs-job.yaml
Labels: release-key-new-features

#4320 [update] new weight request form URL
  examples/science/af3-slurm/README.md
Labels: release-key-new-features

#4332 Update Toolkit release to v1.57.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/internal/slurm-gcp/login/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/file-system/managed-lustre/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#4335 Remove Kueue topology annotation as DWS does not work with TAS (yet)
  examples/gke-consumption-options/dws-flex-start-queued-provisioning/nccl-jobset-example.yaml
  examples/gke-consumption-options/dws-flex-start/nccl-jobset-example.yaml
Labels: release-bugfix

#4336 Remove Kueue topology annotation as DWS does not work with TAS (yet)
  examples/gke-consumption-options/dws-flex-start-queued-provisioning/nccl-jobset-example.yaml
  examples/gke-consumption-options/dws-flex-start/nccl-jobset-example.yaml
Labels: release-bugfix
