Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2025-02, with the labels that each got.

#3631 Fixes HPL benchmark test due to WARMUP_END_PROG environment variable.
  examples/hypercompute_clusters/a3u-gke-gcs/a3u-gke-gcs.yaml
  examples/hypercompute_clusters/a3u-gke-gcs/system_benchmarks/ramble-hpl.yaml
Labels: release-bugfix

#3582 enable queued provisioning on gke nodepool
  modules/compute/gke-node-pool/README.md
  modules/compute/gke-node-pool/main.tf
  modules/compute/gke-node-pool/variables.tf
  modules/compute/gke-node-pool/versions.tf
Labels: release-module-improvements

#3635 Increase google and google-beta provider versions for GKE cluster
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/versions.tf
Labels: release-bugfix

#3599 Add missing indexes and a3U documentation in readme for gke blueprints
  examples/README.md
Labels: release-improvements

#3634 Add variable for k8s service account and remove hardcoded value
  examples/gke-a3-ultragpu/gke-a3-ultragpu-deployment.yaml
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/variables.tf
  tools/cloud-build/daily-tests/tests/gke-a3-ultragpu.yml
Labels: release-improvements

#3460 GCSFuse cache enabled a3-mega blueprint
  examples/machine-learning/a3-megagpu-8g/README.md
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-gcsfuse-lssd-cluster.yaml
Labels: release-key-new-features

#3638 minor update on README.md for gke dws flex start
  examples/gke-dws-flex-start/README.md
Labels: release-chore

#3640 Add default value for k8s service account name in gke cluster
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/variables.tf
Labels: release-improvements

#3643 SlurmGCP. Fix TypeError: can't subtract offset-naive and offset-aware
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3642 Add startup script to set OFI env vars for Cloud RDMA workloads
  community/examples/hpc-slurm-h4d.yaml
  examples/h4d-vm.yaml
  modules/scripts/startup-script/README.md
  modules/scripts/startup-script/main.tf
  modules/scripts/startup-script/variables.tf
Labels: release-chore

#3651 Merge main back into develop
  cmd/root.go
  community/examples/hpc-slurm-h4d.yaml
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  examples/README.md
  examples/h4d-vm.yaml
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
  examples/machine-learning/a3-megagpu-8g/slurm-a3mega-image.yaml
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/README.md
  modules/scripts/startup-script/main.tf
  modules/scripts/startup-script/variables.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3621 Add H4d vm integration tests
  tools/cloud-build/daily-tests/ansible_playbooks/test-validation/test-irdma.yml
  tools/cloud-build/daily-tests/builds/h4d-vm.yaml
  tools/cloud-build/daily-tests/tests/h4d-vm.yml
Labels: release-chore

#3518 Handle startup scripts individually per login group
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/login.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup_network_storage.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/main.tf
Labels: release-chore

#3656 Fix guest accelerator (broken for GKE)
  modules/internal/gpu-definition/README.md
  modules/internal/gpu-definition/main.tf
Labels: release-bugfix

#3659 Switch ofi startup script to not run automatically
  cmd/root.go
  community/examples/hpc-slurm-h4d.yaml
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/main.tf
  modules/scripts/startup-script/versions.tf
Labels: release-bugfix

#3663 Merge main back into develop
  cmd/root.go
  community/examples/hpc-slurm-h4d.yaml
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/main.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3658 Fix minor typo with PROJECT_ID env var
  examples/hypercompute_clusters/a3u-gke-gcs/README.md
Labels: release-chore

#3655 Add internal module `vpc_peering`
  modules/internal/vpc_peering/README.md
  modules/internal/vpc_peering/main.tf
  modules/internal/vpc_peering/metadata.yaml
Labels: release-chore

#3665 Slurm-GCP MyPy fixes
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3657 update GPU and disk definitions for A4
  modules/compute/gke-node-pool/disk_definitions.tf
  modules/internal/gpu-definition/main.tf
Labels: release-module-improvements

#3667 Remove unused MD5s from config
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
Labels: release-chore

#3669 Pin to latest TPG v6.20.0 minor release
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: release-version-updates

#3670 Slurm-GCP Resolving MyPy Errors
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/conf.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/load_bq.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/slurmsync.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3673 Enable NVIDIA DCGM in A3 Ultra Slurm blueprint
  examples/hypercompute_clusters/a3u-slurm-ubuntu-gcs/a3u-slurm-ubuntu-gcs.yaml
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
Labels: release-bugfix

#3676 Add MyPy to pre-commit
  .pre-commit-config.yaml
  Makefile
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/requirements-dev.txt
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/requirements-dev.txt
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/test_util.py
Labels: release-chore

#3664 Fix htcondor config
  community/modules/compute/htcondor-execute-point/README.md
  community/modules/compute/htcondor-execute-point/main.tf
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
Labels: release-bugfix

#3668 Stable IP for HTCondor MIGs
  community/modules/scheduler/htcondor-access-point/README.md
  community/modules/scheduler/htcondor-access-point/main.tf
  community/modules/scheduler/htcondor-central-manager/README.md
  community/modules/scheduler/htcondor-central-manager/main.tf
Labels: release-chore

#3678 Deprecate gke topology scheduler
  community/examples/xpk-gke-a3-megagpu.yaml
  community/modules/compute/gke-topology-scheduler/README.md
  community/modules/compute/gke-topology-scheduler/main.tf
  community/modules/compute/gke-topology-scheduler/manifests/label-nodes-daemon.yaml
  community/modules/compute/gke-topology-scheduler/manifests/schedule-daemon.yaml
  community/modules/compute/gke-topology-scheduler/manifests/service-account.yaml
  community/modules/compute/gke-topology-scheduler/manifests/topology-scheduler-scripts.yaml
  community/modules/compute/gke-topology-scheduler/metadata.yaml
  community/modules/compute/gke-topology-scheduler/variables.tf
  community/modules/compute/gke-topology-scheduler/versions.tf
  examples/hypercompute_clusters/a3u-gke-gcs/a3u-gke-gcs.yaml
Labels: release-deprecations

#3679 Set defaults for GPU driver, disk type and Jobset version for A3U blueprints
  examples/gke-a3-ultragpu/gke-a3-ultragpu.yaml
  examples/hypercompute_clusters/a3u-gke-gcs/a3u-gke-gcs.yaml
  modules/management/kubectl-apply/README.md
  modules/management/kubectl-apply/variables.tf
Labels: release-improvements

#3681 add gke dws flex start example to examples readme
  examples/README.md
Labels: release-chore

#3677 Remove `s/tests/requirements-dev.txt`
  Makefile
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/requirements-dev.txt
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/tests/requirements-dev.txt
Labels: release-chore

#3674 Add `modules/internal/network-attachment`
  modules/internal/network-attachment/README.md
  modules/internal/network-attachment/main.tf
  modules/internal/network-attachment/metadata.yaml
Labels: release-chore

#3662 Include list of members with write permissions
  .pre-commit-config.yaml
  cluster-toolkit-writers.json
Labels: release-chore

#3660 Configure 2-Party Review on Github PRs from External Contributors
  .github/workflows/multi-approvers.yml
Labels: release-chore

#3675 Allow deploy controller & config bucket in different project
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
Labels: release-chore

#3666 Add CODEOWNERS file
  CODEOWNERS
Labels: release-chore

#3686 removing mention of centos 7 in readme
  README.md
Labels: release-chore

#3687 Revert "Remove unused MD5s from config"
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
Labels: release-chore

#3661 Add controller save state disk
  community/modules/internal/slurm-gcp/instance_template/README.md
  community/modules/internal/slurm-gcp/instance_template/main.tf
  community/modules/internal/slurm-gcp/instance_template/variables.tf
  community/modules/internal/slurm-gcp/internal_instance_template/README.md
  community/modules/internal/slurm-gcp/internal_instance_template/main.tf
  community/modules/internal/slurm-gcp/internal_instance_template/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables.tf
Labels: release-key-new-features

#3689 Reduce DWS Flex max duration 2 weeks -> 1 week.
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/README.md
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/resume.py
Labels: release-chore

#3691 Update a3-highgpu image blueprint to use install_nvidia_repo
  examples/machine-learning/a3-highgpu-8g/ml-slurm-a3-1-image.yaml
Labels: release-chore

#3693 Update Toolkit release to v1.47.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3694 Update README.md with correct cluster location
  examples/gke-dws-flex-start/README.md
Labels: documentation, release-chore

#3644 Standardize naming prefixes for kubernetes network objects
  examples/gke-a3-highgpu.yaml
  examples/gke-a3-megagpu.yaml
  examples/gke-a3-ultragpu/nccl-jobset-example.yaml
  modules/compute/gke-node-pool/gpu-direct-workload/sample-tcpxo-workload-job.yaml
  modules/compute/gke-node-pool/gpu_direct.tf
  modules/compute/gke-node-pool/outputs.tf
  modules/scheduler/gke-cluster/README.md
  modules/scheduler/gke-cluster/main.tf
  modules/scheduler/gke-cluster/variables.tf
Labels: release-improvements

#3699 SlurmGCP. Fix Debian-specific issues
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup.py
Labels: release-chore

#3702 Add machine specs for A4 PS
  modules/compute/gke-node-pool/disk_definitions.tf
  modules/internal/gpu-definition/main.tf
Labels: release-chore

#3703 Intital blueprints for A4 GKE (not intended for public use yet)
  examples/gke-a4-highgpu/README.md
  examples/gke-a4-highgpu/gke-a4-highgpu-deployment.yaml
  examples/gke-a4-highgpu/gke-a4-highgpu.yaml
  examples/gke-a4-highgpu/kueue-configuration.yaml.tftpl
  examples/gke-a4-highgpu/mglru-disable.yaml
  examples/gke-a4-highgpu/nccl-installer.yaml
  examples/gke-a4-highgpu/nccl-jobset-example.yaml
  tools/validate_configs/validate_configs.sh
Labels: release-chore

#3704 add gke a4 readme
  examples/gke-a4-highgpu/README.md
Labels: release-chore

#3705 A4 readme fixes
  examples/gke-a4-highgpu/README.md
  examples/gke-a4-highgpu/nccl-jobset-example.yaml
Labels: release-chore

#3707 Update CODEOWNERS file
  CODEOWNERS
Labels: release-chore

#3708 updating codeowners
  CODEOWNERS
Labels: release-chore

#3714 Update Toolkit release to v1.47.0
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3718 A4 GKE integration test
  tools/cloud-build/daily-tests/builds/gke-a4-highgpu.yaml
  tools/cloud-build/daily-tests/tests/gke-a4-highgpu.yml
Labels: release-improvements

#3722 Cherry-pick "A4 GKE integration test"
  tools/cloud-build/daily-tests/builds/gke-a4-highgpu.yaml
  tools/cloud-build/daily-tests/tests/gke-a4-highgpu.yml
Labels: release-chore

#3721 Cherry-pick "use public a4 nccl image"
  examples/gke-a4-highgpu/nccl-installer.yaml
  examples/gke-a4-highgpu/nccl-jobset-example.yaml
Labels: release-chore

#3723 Fix supported features table
  docs/vm-images.md
Labels: release-chore

#3685 SlurmGCP. Don't persist controller address in stored config
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/setup_network_storage.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
Labels: release-chore

#3690 set up GCS (HNS enabled) using blueprint for the ML workload
  examples/hypercompute_clusters/a3u-gke-gcs/README.md
  examples/hypercompute_clusters/a3u-gke-gcs/a3u-gke-gcs.yaml
  examples/hypercompute_clusters/a3u-gke-gcs/deployment.yaml
Labels: release-chore

#3698 A3U Slurm: enable nvidia-persistenced daemon
  examples/machine-learning/a3-ultragpu-8g/a3ultra-slurm-blueprint.yaml
Labels: release-improvements

#3709 Add A4 slurm blueprints
  examples/machine-learning/a4-highgpu-8g/README.md
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-deployment.yaml
  tools/validate_configs/validate_configs.sh
Labels: release-key-new-features

#3725 A4 nccl tests
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/system_benchmarks/README.md
  examples/machine-learning/a4-highgpu-8g/system_benchmarks/run-nccl-tests-via-ramble.sh
Labels: release-chore

#3728 Remove yuryu from CODEOWNERS
  CODEOWNERS
Labels: release-chore

#3729 nvidia compute server variants not yet available for 570
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
Labels: release-chore

#3730 Cherry-pick PR3709, PR3725, PR3729
  examples/machine-learning/a4-highgpu-8g/README.md
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-blueprint.yaml
  examples/machine-learning/a4-highgpu-8g/a4high-slurm-deployment.yaml
  examples/machine-learning/a4-highgpu-8g/system_benchmarks/README.md
  examples/machine-learning/a4-highgpu-8g/system_benchmarks/run-nccl-tests-via-ramble.sh
  tools/validate_configs/validate_configs.sh
Labels: release-chore

#3733 Merge Main back to Develop
  cmd/root.go
  community/modules/compute/htcondor-execute-point/versions.tf
  community/modules/compute/mig/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-dynamic/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset-tpu/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-nodeset/versions.tf
  community/modules/compute/schedmd-slurm-gcp-v6-partition/versions.tf
  community/modules/database/slurm-cloudsql-federation/versions.tf
  community/modules/file-system/cloud-storage-bucket/versions.tf
  community/modules/file-system/nfs-server/versions.tf
  community/modules/files/fsi-montecarlo-on-batch/versions.tf
  community/modules/network/private-service-access/versions.tf
  community/modules/project/service-enablement/versions.tf
  community/modules/pubsub/bigquery-sub/versions.tf
  community/modules/pubsub/topic/versions.tf
  community/modules/scheduler/htcondor-access-point/versions.tf
  community/modules/scheduler/htcondor-central-manager/versions.tf
  community/modules/scheduler/htcondor-pool-secrets/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-login/versions.tf
  community/modules/scripts/wait-for-startup/versions.tf
  community/modules/scripts/windows-startup-script/versions.tf
  modules/compute/gke-node-pool/versions.tf
  modules/compute/vm-instance/versions.tf
  modules/file-system/filestore/versions.tf
  modules/file-system/gke-persistent-volume/versions.tf
  modules/file-system/gke-storage/versions.tf
  modules/monitoring/dashboard/versions.tf
  modules/network/firewall-rules/versions.tf
  modules/network/pre-existing-subnetwork/versions.tf
  modules/network/pre-existing-vpc/versions.tf
  modules/scheduler/batch-login-node/versions.tf
  modules/scheduler/gke-cluster/versions.tf
  modules/scheduler/pre-existing-gke-cluster/versions.tf
  modules/scripts/startup-script/versions.tf
Labels: release-chore

#3734 Update TPG from v6.20.0 to v6.23.0
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: release-chore

#3727 Enable using network_attachment on controller machine
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/controller.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/README.md
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/main.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/scripts/util.py
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/modules/slurm_files/variables.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/slurm_files.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/variables_controller_instance.tf
  community/modules/scheduler/schedmd-slurm-gcp-v6-controller/versions.tf
Labels: release-chore

#3724 Remove experimental tag from GKE blueprints in readme
  examples/README.md
Labels: release-improvements
