Repository GoogleCloudPlatform/cluster-toolkit, pull requests merged in 2025-10, with the labels that each got.

#4709 Install mpi-operator and add a reference link to the test for GKE H4D blueprint example
  examples/gke-h4d/README.md
  examples/gke-h4d/gke-h4d.yaml
Labels: release-chore

#4725 Update machine-leaning/a3-ultragpu-8g/nemo-framework to fix segmentation fault error
  examples/machine-learning/a3-ultragpu-8g/nemo-framework/Dockerfile
  examples/machine-learning/a3-ultragpu-8g/nemo-framework/README.md
  examples/machine-learning/a3-ultragpu-8g/nemo-framework/setup_nemo.sh
Labels: release-bugfix

#4723 Add multi-network support in TPU v6e
  community/examples/gke-tpu-v6/gke-tpu-v6.yaml
Labels: release-breaking-changes

#4726 updating startup script wait message to fix build failures.
  community/modules/scripts/wait-for-startup/scripts/wait-for-startup-status.sh
  tools/cloud-build/daily-tests/ansible_playbooks/tasks/wait-for-startup-script.yml
Labels: release-chore, test-enhancement

#4732 Update vpc and cloud_router versions in VPC network module
  modules/network/vpc/README.md
  modules/network/vpc/main.tf
Labels: release-breaking-changes

#4736 Updating google provider version upper bound to 7.6.0 - latest version
  pkg/config/expand.go
  pkg/config/expand_test.go
  tools/validate_configs/golden_copies/expectations/igc_pkr/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_pkr/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/igc_tf/one/versions.tf
  tools/validate_configs/golden_copies/expectations/igc_tf/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/merge_flatten/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/merge_flatten/zero/versions.tf
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/.ghpc/artifacts/expanded_blueprint.yaml
  tools/validate_configs/golden_copies/expectations/versioned_blueprint/primary/versions.tf
Labels: dependencies, release-version-updates

#4729 Add Filestore, PV, and sample job template snippets to the GKE H4D blueprint
  examples/gke-h4d/README.md
  examples/gke-h4d/gke-h4d.yaml
  tools/cloud-build/daily-tests/builds/gke-h4d.yaml
Labels: release-chore
